### ISSUE TITLE
Practices: ALT+del conflicts with JAWS keystroke

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1]
ALT+del is used for "remove current tab" in http://www.w3.org/WAI/PF/aria-practices/#tabpanel
This conflicts with "Say Active Cursor" in JAWS. We should choose a different keystroke.

**Comment by jnurthen** [comment]
Resolved alt+del on tabs in master.

**Comment by MichielBijl** [comment]
Woohoo! Only took us 2 years :P
