### ISSUE TITLE
Structural roles for floating boxes

### ISSUE THREAD

**Issue by essepuntato** [w3c/aria#100]
Premise: RASH, the Research Article in Simplified HTML format, available on github at http://github.com/essepuntato/rash, is an HTML-based markup language for scholarly articles that has been already used in academic events (e.g., SAVE-SD 2015, http://cs.unibo.it/save-sd/2015/index.html). The new version of RASH will use the structural roles defined in the Digital Publishing WAI-ARIA Module 1.0 – W3C Editor's Draft.

In RASH there exist four different kinds of floating boxes (specified through the element "figure"), i.e.: figure box, table box, formula box, and listing box. As you can image, these are used to define referenceable boxes like it happens in other document-oriented languages such as LaTeX, ODT, etc.

In the version of RASH that will publish soon, these are specified by using the following roles (still by means of the attribute @role on "figure" elements): "picturebox", "tablebox", "formulabox" and "listingbox", e.g.:

<pre>
&lt;figure id="figure_1" role="picturebox"&gt;
    &lt;p&gt;
        &lt;img src="img/rash.png" alt="The RASH logo!"/&gt;
    &lt;/p&gt;
    &lt;figcaption&gt;Caption of the figure.&lt;/figcaption&gt;
&lt;/figure&gt;
</pre>

There is the possibility of adding some particular and official role in [DPub] that enables one to handle these specific structures?

Note that the disambiguation based on the content of "figure" can not hold sometimes, if, for instance, I want to express similar boxes with different kinds of contents. In RASH, that is the case of formulas, that can be expressed by means of either MathML or image, i.e.:

<pre>
&lt;figure id="formula_1" role="formulabox"&gt;
    &lt;p&gt;
        &lt;img src="img/formula.png" alt="[a + b]^260 + [a + b]_i"/&gt;
    &lt;/p&gt;
&lt;/figure&gt;
</pre>

and

<pre>
&lt;figure id="formula_1" role="formulabox"&gt;
    &lt;p&gt;
        &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;
            &lt;mrow&gt;
                &lt;msup&gt;
                    &lt;mfenced open="[" close="]"&gt;
                        &lt;mrow&gt;
                            &lt;mi&gt;a&lt;/mi&gt;
                            &lt;mo&gt;+&lt;/mo&gt;
                            &lt;mi&gt;b&lt;/mi&gt;
                        &lt;/mrow&gt;
                    &lt;/mfenced&gt;
                    &lt;mn&gt;260&lt;/mn&gt;
                &lt;/msup&gt;
                &lt;mo&gt;+&lt;/mo&gt;
                &lt;msub&gt;
                    &lt;mfenced open="{" close="}"&gt;
                        &lt;mrow&gt;
                            &lt;mi&gt;a&lt;/mi&gt;
                            &lt;mo&gt;+&lt;/mo&gt;
                            &lt;mi&gt;b&lt;/mi&gt;
                        &lt;/mrow&gt;
                    &lt;/mfenced&gt;
                    &lt;mi&gt;i&lt;/mi&gt;
                &lt;/msub&gt;
            &lt;/mrow&gt;
        &lt;/math&gt;
    &lt;/p&gt;
&lt;/figure&gt;
</pre>

**Comment by TzviyaSiegman** [comment]
Editors deemed this out of scope for this module. Some of the information is conveyed by the native semantics of the child elements. For example, if a `<figure>` includes `<ol>`, native semantics convey to AT that the child element is a list. You may be interested in the loosely related issue at https://discourse.wicg.io/t/proposal-list-head-caption-title/1832/33
