### ISSUE TITLE
Remove base and related concepts rows from Characteristics tables

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#1003]
If you look at https://w3c.github.io/aria/#cell (and other roles), we have a row in the role's characteristic's table which contains: `Base Concept:  HTML td`

Likewise, if you look at https://w3c.github.io/aria/#checkbox (and other roles), we have a row in the role's characteristic's table which contains: `Related Concepts: HTML input[type="checkbox"]`

I personally don't think that those rows offer anything readers of the spec don't already know. In addition, including them requires occasional maintenance (i.e. ensuring links aren't broken).

This maintenance is potentially increased in light of the new [Memorandum of Understanding](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html#referencing), which states:

> Normative references from W3C specifications to material that is in the HTML and DOM specifications shall reference the whatwg.org Living Standard both in-line and in the Normative References section. 

Because the WhatWG version is a living standard, links can break and content can be removed at any time. What happens if we're in CR and need to update a reference because the living standard changed? Do we have to exit and re-enter CR? Do we have to keep updating -- or doing errata for -- specs in TR?

On the one hand, I'm sure this will all get worked out (if it hasn't already been) so the Process associated with reference maintenance is relatively smooth. On the other hand, everyone reading our spec presumably knows that an ARIA `cell` is like an HTML `td` and an ARIA `checkbox` is like an HTML `checkbox`. So if these rows offer no significant value to the reader, and have an associated maintenance cost, is their inclusion worth it?

I propose we remove base and related concepts rows from the Characteristics tables. In the case of rows which the concept is another of our own roles, I think we can address this with a "See also:" statement in the role's definition.

**Comment by carmacleod** [comment]
I'm a bit worried that people won't easily understand what generic role is without the
> Related Concepts: HTML div, HTML span

I would be ok with collapsing the "Base concept" and "Related Concepts" rows into a single "Related Concepts" row so as to reduce the number of potential rows.

**Comment by joanmarie** [comment]
Could we instead tackle this with some narrative text in the description of the role?

> The `generic` role is bla bla bla, and similar in nature to the `div` and `span` in HTML?

Then we can still do the rowectomy while addressing your concerns (right)?

The problem, I think, in keeping the rows (even if we collapse them into one) is that it implies we need to populate them/it. :) For instance, why did we reference `div` and `span` for `generic`, but fail to mention `td` for cell?

*When* a reference is essential to understanding, I have no problem whatsoever with mentioning it. I just want to find a way to make it possible to reference only when needed.

**Comment by carmacleod** [comment]
> For instance, why did we reference div and span for generic, but fail to mention td for cell?

If we remove the "Base Concept" row, we would move `HTML td` into the "Related Concepts" row.

> I just want to find a way to make it possible to reference only when needed.

If the Related Concepts row is not populated, then the row should not show up in the table.

For background, I'd like to actually have _more_ "tie-ins" to html... please see my [request to add a "Related Concepts" section/note/whatever to the APG patterns](https://github.com/w3c/aria-practices/issues/633).  :)

**Comment by joanmarie** [comment]
I'm questioning whether or not we need `td` mentioned *at all* in the ARIA spec. Do readers of the spec really not know what a `td` is?

**Comment by carmacleod** [comment]
Might help them to understand what a `cell` is?

**Comment by joanmarie** [comment]
That's fine for authoring practices. Do readings of the ARIA spec not know what a cell is?

**Comment by carmacleod** [comment]
I'm thinking that it doesn't hurt to remind them that there's a related HTML thing, with all of the semantic goodness built in. :)

A blind colleague once told me, "You people use way too much ARIA!", and since then I've been mindful of mentioning that "there could be an easier way to do this thing" (i.e. are you _sure_ you want to use `role="button"` when there's a nice `HTML <button>` available?)

So I prefer to keep ensuring that readers of the ARIA spec are subtly reminded that there are HTML elements that may suit their needs by providing a handy link to those elements in a predictable place.

All of that said, of course, if a quorum of the group think we should remove all of the tie-in rows, I will go with that decision.

**Comment by joanmarie** [comment]
Fair enough. :)

I will admit that what's driven me from "This doesn't add much, if any, value" to "this should be removed" is the new Memorandum of Understanding (see link in opening report). We are expected to link to a living standard. That implies the potential for additional maintenance of our spec:

* Our links to living-standard content can move or break
* Living standard definitions of what we reference can change

The former is a hassle; the latter might be a problem if we base our concept/role on their concept/element, and then they change it to mean something else.

Furthermore, since the ARIA spec is not a living standard, there is Process associated with updating it from CR through TR.

So... I think for each instance we need to ask ourselves, is this reference truly needed? As you pointed out for `generic`, yeah, it probably is. But for most of our references, I don't think that's the case.

Anyhoo.... I wonder if one approach could be that the ARIA spec links informatively, on a per role/state/property attribute to authoring practices. Then authoring practices can link to the HTML spec. I *think* that updating a Note entails less Process overhead than updating a Rec. And we had already stated that when the APG was ready, we wanted to add links from our spec to it so authors can find good examples and best practices.

**Comment by jnurthen** [comment]
Can we just structure the reference like <td> in [[HTML]]
It would have no specific reference so unless <td> got removed we would have nothing to update.

**Comment by joanmarie** [comment]
That is a clever way to solve the broken link problem. :) I guess I can live with that.

**Comment by jnurthen** [comment]
I guess we can close this. Please reopen if necessary.
