### ISSUE TITLE
Should name be required on timer, log, table?

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria#1005]
ARIA requires accessible name on the `timer`, `log`, `table` roles (among others).

For `timer`, why is it required? The examples I've seen don't set an accessible name.

For `log`, why is it required?

For `table`, this is a mismatch with HTML, which doesn't require a `caption` element.

cc @mcking65

**Comment by zcorpan** [comment]
cc @spectranaut

**Comment by jnurthen** [comment]
(chair hat off - personal opinion) 

> For `timer`, why is it required? The examples I've seen don't set an accessible name.

Knowing something about the timer seems useful but I agree making it required seems a little overboard.

> For `log`, why is it required?

As timer

> For `table`, this is a mismatch with HTML, which doesn't require a `caption` element.

I agree it is a mismatch but something as complex as a table really does need an accessible name. I'd argue it is HTML that has got this wrong not ARIA.

**Comment by zcorpan** [comment]
Not all tables are complex, though.

Also, making `caption` required in HTML could have the unintended consequence of web developers adding bogus `caption` elements to their tables (whether they are data tables or layout tables), which could damage accessibility (by adding bogus cruft or by having layout tables be misidentified as data tables).

**Comment by jnurthen** [comment]
@zcorpan I am not arguing to make `caption` required on HTML tables - partly due to the layout table problem (which we don't have to deal with with the aria `table` role) and partly due to the issues laying out `caption` in a satisfactory manner.

Personally, I don't feel that HTML and ARIA have to align here.

**Comment by carmacleod** [comment]
For `timer` and `log` it might make sense to say something like, "Required if there's more than one, in order to differentiate".

**Comment by jnurthen** [comment]
> For `timer` and `log` it might make sense to say something like, "Required if there's more than one, in order to differentiate".

IMO that becomes authoring guidance and not spec language at that point and should fit better in the APG. We also don't do this for things like navigation and search which would have the same requirement.
