### ISSUE TITLE
Why can not the author use aria-labelledby if the interface can not display the label on the screen?

### ISSUE THREAD

**Issue by mpruser** [w3c/aria#1007]
Why can not the author use aria-labelledby if the interface can not display the label on the screen?

If users are using the language translation feature of their browser, there is a problem that the contents entered in 'aria-label' are not translated. So, sometimes I use 'aria-labelledby'. This is of course a problem with the language translation feature of the browser. But the clause below is too harsh.

----
>**If the interface is such that it is not possible to have a visible label on the screen, authors SHOULD use aria-label and SHOULD NOT use aria-labelledby.** As required by the accessible name and description computation, user agents give precedence to aria-labelledby over aria-label when computing the accessible name property.

[https://www.w3.org/TR/wai-aria-1.2/#aria-labelledby](https://www.w3.org/TR/wai-aria-1.2/#aria-labelledby)

**Comment by jnurthen** [comment]
@mpruser The text does not prohibit users from using aria-labelledby if the text can't be displayed on the screen . It is a SHOULD which in RFC2119 means
"SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course."

Something not working correctly would seem to me to be a valid reason for you to do something different if that is important to the functionality of your page. 

Of course google chrome page translations now takes into account aria-label so it would be hoped that other browsers would catch up soon.

Please reopen if this is not an adequate response.
