### ISSUE TITLE
`aria-details` precedence over `aria-describedby` 

### ISSUE THREAD

**Issue by jongund** [w3c/aria#1009]
In the definition of [aria-details](http://w3c.github.io/aria/#aria-details) has the following statement about the precedence of `aria-details` over `aria-describedby`:

"In some user agents, multiple reference relationships for descriptive information are not supported by the accessibility API. In such cases, if both aria-describedby and aria-details are provided on an element, aria-details takes precedence."

The [CORE AAM for `aria-details` and `aria-describedby`](https://w3c.github.io/core-aam/#details-id-105)  tells an interesting story:
1. The mappings seem to be independent of each other except for UIA, so are processing instructions needed to be included to enforce the precedence of `aria-details`? Can the mapping be updated for UIA to make them independent?
1. What is more concerning is there is no mapping for `aria-details` for AX API, which means using this property will be useless to users of macOS.  If anything shouldn't we be giving precedence to `aria-describedby` which is supported on all platforms?

**Comment by jnurthen** [comment]
@cookiecrook At TPAC you seemed amenable to getting a mapping for aria-details into AX API. Can we get a path forwards on this so we can resolve this issue particularly in regards to the ongoing work on ARIA Annotations.

**Comment by cookiecrook** [comment]
My comment was that original use cases for `aria-details` were questionable like `longdesc` or `aria-describedat`, but that the annotations use case mentioned for document suites has merit. @aleventhal is proposing using this use for Google Docs.

**Comment by jnurthen** [comment]
Correct - any chance we can get some mappings for AX API so we can resolve at least half of this issue? I can log an issue against core-aam and assign to you if that would help.

**Comment by cookiecrook** [comment]
https://bugs.webkit.org/show_bug.cgi?id=165842

**Comment by pkra** [comment]
I think this can be closed now. The problematic wording is no longer in the spec. Instead it reads

> If a user agent relies on an accessibility API that does not support exposing multiple descriptive relations, and if an element has both aria-details and aria-describedby, the user agent SHOULD expose the aria-details relation and the description string computed from the aria-describedby relationship.

For point about core-aam listing AX API as no mapped I filed https://github.com/w3c/core-aam/issues/88.
