### ISSUE TITLE
References to document objects (e.g., sections)

### ISSUE THREAD

**Issue by essepuntato** [w3c/aria#101]
Premise: RASH, the Research Article in Simplified HTML format, available on github at http://github.com/essepuntato/rash, is an HTML-based markup language for scholarly articles that has been already used in academic events (e.g., SAVE-SD 2015, http://cs.unibo.it/save-sd/2015/index.html). The new version of RASH will use the structural roles defined in the Digital Publishing WAI-ARIA Module 1.0 – W3C Editor's Draft.

While in [DPub] there are roles for referring to footnotes (doc-noteref) and bibliographic entries (doc-biblioref), I've not found any role for pointing to other meaningful document components, such as sections, figures, formulas, tables and listings. RASH is using the ad-hoc role "ref" specified on the element "a", as shown in the following excerpt:

<pre>
&lt;p&gt;In &lt;a href="#metadata" role="ref"&gt;&lt;/a&gt; we explain how to specify the metadata of the article as appropriate elements within &lt;code&gt;head&lt;/code&gt;, while the rest of the document mainly pertains elements within the element &lt;code&gt;body&lt;/code&gt;.&lt;/p&gt;

...

&lt;section id="metadata"&gt;
    &lt;h1&gt;Metadata&lt;/h1&gt;
    &lt;p&gt;...&lt;/p&gt;
&lt;/section&gt;
</pre>

What such "a" element with "ref" role creates is a specific link/reference to an existing object (a section in this case) that will be then rendered as, for instance, "Section 2" in the browser. 

This role seems to behave like the other references included in [DPub](i.e.,). What about adding a generic "ref" for dealing with references to other kinds of objects?

**Comment by TzviyaSiegman** [comment]
This is fulfilled with the [doc-backlink](https://rawgit.com/w3c/aria/dpub-cr/aria/dpub.html#doc-backlink) role. 

If you have sample files using the DPUB-ARIA roles, please submit them to one of the editors for testing purposes. Thank you
