### ISSUE TITLE
Use of group within list is unclear

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1011]
Neither the definition of the roles list, listitem and group nor the definition of aria-level in the specification contains any indication of how nested ARIA lists are created. Is the use of group sufficient or is aria-level required? If there is an element with role=group in role=list, this could be used to group or nest the list entries...? Unfortunately, the specification makes no statement about this. 
Therefore I would like to know how 
```
<ul><li>...<ul><li>...</ul></ul>
```
is marked in ARIA. I would also suggest changing the specification so that it becomes clear.

**Comment by JAWS-test** [comment]
Just to let you know what the output of JAWS 2019 (e.g. with IE 11 and in Chrome) of ARIA lists is like:

The following roles are not output as nested lists (specified in the order of their nesting in the source code)
* list - group - listitem
* list - listitem - group - listitem
* list - listitem with aria-level
* list - listitem - listitem

The following elements are output as a nested list
* list - list - listitem
* list - listitem - list - listitem
* list - listitem - group - list - listitem (with additional output of the group)

So this seems to be quite a mess, while for HTML it is clearly specified how nested lists must be marked.

**Comment by joanmarie** [comment]
Making 1.2 for now and asking APG TF to look into.

**Comment by sh0ji** [comment]
I haven't been able to find any instance where it made any meaningful difference to use `group` instead of `list` in my research and support the notion to remove it here.

**Comment by jnurthen** [comment]
See https://github.com/dequelabs/axe-core/issues/1200 for more discussion on this
