### ISSUE TITLE
Text Logos as links

### ISSUE THREAD

**Issue by 7dITS** [w3c/aria#1013]
An application that I am auditing for accessibility issues contains a logo that is a link. The logo is actually text. The link is in the header and is the text version of the logo for the website. When clicked a new tab opens a new page, the homepage for the website. What would be the best way to tell the user that they will be sent to a new page once they click the link? 

Please note the designers of this website do not want to include the opens new window icons, visual text in the link telling the user the link opens in a new window or underlining the text in the link.  I think that a pop up containing a redirect message would be the best option for them. 

What I need to know:

Will the pop up containing the redirect message fulfill WCAG 2.0 Guideline 3.2 – Predictable?
https://www.w3.org/TR/WCAG20-TECHS/G201.html

Is there any type of expections for logo text links in a header?

![image](https://user-images.githubusercontent.com/24323027/61406060-211d0480-a8a9-11e9-8a1b-980d92c29889.png)

![image](https://user-images.githubusercontent.com/24323027/61406156-427df080-a8a9-11e9-9584-6376cb275600.png) - when link receives focus

**Comment by jnurthen** [comment]
This doesn’t sound like an issue for the aria repository. While we would like to help with all accessibility issues we don’t have the bandwidth to do so. 
The https://lists.w3.org/Archives/Public/w3c-wai-ig/ mailing list sounds like a more appropriate venue for this question.
