### ISSUE TITLE
Issues with aria-expanded on tabpanel/tablist/tab

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria#1032]
I found this when researching for writing a new section in aria-practices for Controlling Widget States.

Here are the issues me and @spectranaut found:

* `tabpanel` - what is the advantage of using `aria-expanded` when `aria-selected` already indicates which tabs are selected?
* The spec is inconsistent about whether `aria-expanded` should go on `tabpanel`, `tablist`, or `tab`.

> For a multi-selectable tablist, authors SHOULD ensure each visible tabpanel has its aria-expanded attribute set to true, and that the remaining hidden tabpanel elements have their aria-expanded attributes set to false.

https://w3c.github.io/aria/#tab

> For a multi-selectable tablist, authors SHOULD ensure each visible tabpanel has its aria-expanded attribute set to true, and that the remaining hidden tabpanel elements have their aria-expanded attributes set to false.

https://w3c.github.io/aria/#tablist

...but `aria-expanded` is a supported state on `tab`, not `tabpanel` or `tablist`

_Originally posted by @zcorpan in https://github.com/w3c/aria/issues/681#issuecomment-506703445_

**Comment by carmacleod** [comment]
This issue will be fixed by PR #1403.

To answer the question:
> what is the advantage of using aria-expanded when aria-selected already indicates which tabs are selected?

please see: https://github.com/w3c/aria-practices/issues/341
