### ISSUE TITLE
discussion of aria-expanded on multi select tabpanels

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#1040]
There is a sentence in the [section on tablists](https://www.w3.org/TR/wai-aria-1.1/#tablist) that I found curious.

> For a multi-selectable tablist, authors SHOULD ensure each visible tabpanel has its aria-expanded attribute set to true, and that the remaining hidden tabpanel elements have their aria-expanded attributes set to false.

1) is it right to have aria-expanded on a tablist?
2) If so, wouldn't aria-expanded go on the trigger element not the destination element role="tab" rather than tabpanel?
3) If more than one tabpanel can be displayed at once, then why not just have aria-selected on all of them, instead of aria-expanded?

**Comment by jnurthen** [comment]
> 
>     1. is it right to have aria-expanded on a tablist?

No and I don't believe this is stated anywhere - aria-expanded is not allowed on tablist

> 
>     2. If so, wouldn't aria-expanded go on the trigger element not the destination element role="tab" rather than tabpanel?

+1

> 
>     3. If more than one tabpanel can be displayed at once, then why not just have aria-selected on all of them, instead of aria-expanded?

Seeing as this entire behaviour was driving off aria-multiselectable that would make a lot of sense. However selection and expanded are not the same thing. I think the property should really be aria-multiexpandable in this case.
I'm open for discussing this though

(note this whole thing is from the old accordion pattern which we really don't recommend people use any more. I'd be totally happy to discuss deprecating aria-multiselectable on tablists)

**Comment by accdc** [comment]
One complication is that having both attributes supports complex implementations. E.G What if multiple tabs are selectable as part of a delete or move process, yet this is separate from the expanded or collapsed state of each tab? In this case, multiple tabs may be both selected and expandable at the same time, and both states must be conveyable to assistive technologies as separate states because they represent different functions.

**Comment by accdc** [comment]
Also, aria-selected and aria-expanded should only ever be used on role="tab", and never on role="tablist" or role="tabpanel".
http://whatsock.com/training/matrices/#tablist
