### ISSUE TITLE
Specification for live region not clear enough

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1043]
Perhaps part of the explanation of live regions should not only be in the ARIA Practices, but directly in the specification? The more of them, the better I'd like it.

See proposal at: https://github.com/w3c/aria-practices/issues/78#issuecomment-524619306.

See also: https://github.com/w3c/aria/issues/712

**Comment by pkra** [comment]
It's difficult to address such a broad question. Could you point to individual points that you find especially unclear?

It might be a good idea to first pursue w3c/aria-practices#78 which could then help identify potential points of improvement within the ARIA spec. Ideally, those points would be small / manageable chunks. 

I'd personally add that spreading information across specs can also add confusion.

**Comment by JAWS-test** [comment]
I close it and insert more concrete questions about the topic (e.g. https://github.com/w3c/aria/issues/1048)

**Comment by pkra** [comment]
Thanks, @JAWS-test - much appreciated!
