### ISSUE TITLE
Does combobox require an accessible name?

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1046]
In the axe-core 3.3.0 we added a rule to check for the accessible name of non-native form fields, including combobox. Since than I've had a few people point me to this example in the ARIA practices:

https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

```html
<label id="ex2-label" class="combobox-label">
  Choice 2 Fruit or Vegetable
</label>
<div class="combobox-wrapper">
  <div role="combobox"
       aria-expanded="false"
       aria-owns="ex2-listbox"
       aria-haspopup="listbox"
       id="ex2-combobox">
    <input type="text"
           aria-autocomplete="list"
           aria-controls="ex2-listbox"
           aria-labelledby="ex2-label"
           id="ex2-input">
  </div>
  <ul aria-labelledby="ex2-label"
      role="listbox"
      id="ex2-listbox"
      class="listbox hidden">
  </ul>
</div>
```

This example has three elements with a role that, according to ARIA 1.1 require an accessible name: `combobox`, `textbox`, and `listbox`. In this example, the `textbox` and `listbox` have the same accessible name, and the `combobox` has no accessible name.

I'm guessing combobox probably doesn't need to have an accessible name, unless role=combobox is used on a native text box. Should this be changed?

**Comment by accdc** [comment]
I'm not sure that's right though, having unlabeled comboboxes makes it impossible for screen readers to jump between combobox widgets and intuitively differentiate them for non-sighted users.

**Comment by jnurthen** [comment]
I believe in the linked issue at the last F2F we decided that the combo and its child textinput should simply have the same label.

**Comment by aleventhal** [comment]
@jnurthen or why not have the browser copy one to the other when one of them is nameless. Or, my favorite, I suggest the AT is responsible for doing this. NVDA will look at the parent of an nameless input and for a combobox name and use that.

**Comment by accdc** [comment]
The issue with having browsers do it, is that I then need to add this to the AccName spec, which is annoying because it doesn't follow any form of paradigm existing elsewhere in the spec for any other widget type. I would have to make a step just for dealing with the combobox role.

**Comment by mcking65** [comment]
I am hoping we will resolve this by eliminating the combobox wrapper idea introduced in aria 1.1. Neither Bryan nor I thought this was a good idea. It seems time may have proven us right. This is on the TPAC agenda. Reviewing the presentation I will use at TPAC is on Tuesday's APG agenda.

If that proposal does not fly, then we will need to figure out how to resolve this issue and decide who is responsible for naming the wrapper. It could be author; it could be labeled by the label on the textbox in the same way that a caption labels a table. I don't think we can push it off to AT.

**Comment by zcorpan** [comment]
#1051 is merged.
