### ISSUE TITLE
Tokens for aria-autocomplete

### ISSUE THREAD

**Issue by johnfoliot** [w3c/aria#1047]
Ref: https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-autocomplete

I have some concerns about this that I'd like to either get clarification on, or request that the ARIA WG address. 

In the current [ARIA 1.1 Recommendation](https://www.w3.org/TR/wai-aria-1.1/), it states that aria-autocomplete takes as it's value **a token**, yet nowhere in the specification do I see a ___specific list of the tokens___ the attribute can take. Reading the Rec carefully, I can presume that the intended allowed token values are perhaps one of: _list_, _inline_, _both_, or _none_, but it would be useful if that was explicitly noted, and not left to inference, as it may lead to some potential author confusion.  (i.e. could this attribute also take one of the token values noted below?)

1) Is this attribute also intended to be providing parity to the HTML 5 attribute [**@autocomplete**](https://www.w3.org/TR/html52/sec-forms.html#autofill)? I'm going to guess no, however if the intent is parity with html, note that the token value of "list" is not part of the controlled taxonomy, which can be found at: [https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute](https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute)<br><br>**If this is NOT the intention**, then some additional specificity about that would be useful in the ARIA Recommendation, as it is not clear whether the WG was going for HTML parity, or attempting to fix a gap in expressing additional functionality.

2) Also confusing is the fact that currently in [WCAG 2.1, Success Criteria 1.3.5 - Identify Input Purpose](https://www.w3.org/TR/WCAG21/#identify-input-purpose), the inputs scoped for that SC are the same taxonomy list found in HTML5, but [echo'ed in the WCAG 2.1 Recommendation](https://www.w3.org/TR/WCAG21/#input-purposes). <br><br>Currently today, the only technique to meet this SC is to use the @autocomplete attribute, and I fear that some developers may begin to think that they can use this aria attribute as a second conforming technique:<br><br>`<label for="foobar">Family Name<input type="text" aria-autocomplete="family-name" id="foobar"></label>`

3) Related to the @autocomplete attribute, as well as WCAG 2.1, there is also effort underway to introduce a new attribute coming from the Personalization Task Force ([data-purpose](https://w3c.github.io/personalization-semantics/content/index.html#purpose-explanation)) which again will only accept as a token value one of the specified values found in the WCAG 2.1 Section 7 reference (which is [an echo of the token values specified in HTML5](https://w3c.github.io/personalization-semantics/content/index.html#values-1)). 

**Summary:**
It is unfortunate that this attribute invokes the term "autocomplete", when that term is being used elsewhere to describe a completely different function. Ideally this aria-attribute would be deprecated for a different term (aria-attribute) that still invoked the function envisioned for this attribute, but without using the term of art "autocomplete". (perhaps `aria-hint` ?)

Barring that, **can the explanation text more explicitly explain the difference**, and also **explicitly list the allowed token values** for this attribute (instead of simply by inference)?

**Comment by jnurthen** [comment]
The spec states the following (Secdtion 6.3)

> 6.3. Values for States and Properties
> 
> Many states and properties accept a specific set of tokens as values. The allowed values and explanation of their meaning is shown after the table of characteristics. The default value, if defined, is shown in strong type. When a value is indicated as the default, the user agent MUST follow the behavior prescribed by this value when the state or property is empty or undefined. Some roles also define what behavior to use when certain states or properties, that do not have default values, are not provided.

**Comment by jnurthen** [comment]
>     1. Is this attribute also intended to be providing parity to the HTML 5 attribute [**@autocomplete**](https://www.w3.org/TR/html52/sec-forms.html#autofill)? I'm going to guess no, however if the intent is parity with html, note that the token value of "list" is not part of the controlled taxonomy, which can be found at: https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute**If this is NOT the intention**, then some additional specificity about that would be useful in the ARIA Recommendation, as it is not clear whether the WG was going for HTML parity, or attempting to fix a gap in expressing additional functionality.

When the autocomplete attribute was introduced into HTML5 it had values of on or off. When aria-autocomplete was introduced it extended this concept to allow AT to know how the autocomplete was being provided. On and off it still an allowed usage in HTML.

When HTML extended the autocomplete attribute in the HTML51 timeframe they went a different direction and started using autocomplete as a "What"

If there is some text you think would clarify this please submit a PR.

**Comment by jnurthen** [comment]
>     2\. Also confusing is the fact that currently in [WCAG 2.1, Success Criteria 1.3.5 - Identify Input Purpose](https://www.w3.org/TR/WCAG21/#identify-input-purpose), the inputs scoped for that SC are the same taxonomy list found in HTML5, but [echo'ed in the WCAG 2.1 Recommendation](https://www.w3.org/TR/WCAG21/#input-purposes). Currently today, the only technique to meet this SC is to use the @autocomplete attribute, and I fear that some developers may begin to think that they can use this aria attribute as a second conforming technique:`<label for="foobar">Family Name<input type="text" aria-autocomplete="family-name" id="foobar"></label>`

If there is something confusing in WCAG I suggest filing an issue and perhaps a PR against WCAG

**Comment by jnurthen** [comment]
closing as no reply
