### ISSUE TITLE
Add handling author errors update for unnamed region and form landmarks?

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1083]
`region` requires a name from authors, and [`form` will require author naming](https://github.com/w3c/aria/pull/1071).

If names are not provided, should we note in the Handling Author Errors section that these landmarks should not be exposed if authors fail to provide them?

HTML AAM already notes that if names are not provided, then `section` and `form` have no corresponding role (will be updated to `role=generic`).

**Comment by JAWS-test** [comment]
I'm for that. This consistency between ARIA and HTML makes sense to me. Core AAM should then be updated for `form` as well
