### ISSUE TITLE
Removal of glossary entries failing when the only reference is within the glossary itself.

### ISSUE THREAD

**Issue by klown** [w3c/aria#109]
@halindrome:

The bug is inside restrictReferences() within the handler for the "core/link-to-dfn".  See:
https://github.com/w3c/aria/blob/master/common/script/resolveReferences.js#L119

The rationale is that $("a.internalDFN") will produce a list of all the reference links to glossary terms within the main content of the document.  The problem is that some of those links occur only within the glossary itself.

An example is the glossary entry "Ontology".  There is a reference to it ("ontology") from the glossary entry for "Taxonomy".  Because of that, the handler leaves the entry for "Ontology" in the document.  However, If "Taxonomy" is not referenced, its entry is removed.  The result is a glossary entry for "Ontology" where it is not referenced from anywhere within the document.

You can see an example by loading the rawgit url of accname-aam.html.  Both "Ontology" and "Keyboard Accessible" are listed in the important terms section, even though neither is linked to from anywhere within the document:
http://rawgit.com/w3c/aria/master/accname-aam/accname-aam.html#glossary

(note:  "Keyboard Accessible" is referenced from the glossary entry for "Operable").

I've been puzzling over this for a while, but haven't thought of an elegant way to get around it.

**Comment by halindrome** [comment]
I have a tentative solution.   Let me take a crack at it.

**Comment by klown** [comment]
> I have a tentative solution. Let me take a crack at it.

Be my guest, @halindrome.
