### ISSUE TITLE
Should aria-disabled be allowed on role=link?

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1099]
See discussion about keeping/removing aria-disabled from role=link: https://github.com/w3c/aria/pull/1023#issuecomment-540760795

This needs to be discussed in further detail in ARIA 1.3, which will focus on HTML attribute parity.

**Comment by scottaohara** [comment]
>We definitely should address also things like `<a href="[href]" aria-disabled="true">`

Does ARIA need to address this?  The mentioned code snippet already exposes a disabled state (though the likelihood of a developer actually doing everything necessary to disable said link is rather low).  A more appropriate topic for ARIA in HTML, and this _will_ be addressed there.

**Comment by stes-acc** [comment]
> A more appropriate topic for ARIA in HTML, and this will be addressed there.

This is fine 👍

**Comment by jnurthen** [comment]
lets close this. Please reopen if disagree

**Comment by stes-acc** [comment]
Disabled links are very common in Business UIs since there may be locks or people role restrictions. I want the disabled state mapping point clarified with  ARIA in HTML spec owners.

**Comment by scottaohara** [comment]
This is already noted over there
