### ISSUE TITLE
Write editorial note for each of the four no-longer-global properties for wide review spec

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#1105]
We recently changed several global attributes to no longer be global. I *think* we'll be able to get that implemented in time, but we might not. In addition, we want to be sure this change is seen by everyone as part of wide review.

Because of the issues above, the decision from today's ARIA WG meeting is that we would add a note in the definition section of each property, pointing out this change. If we don't get the implementations before we're ready to enter CR, we can update the note to mark these changes as at-risk for 1.2.

**Comment by jnurthen** [comment]
This state or property was a Global state or property in the previous version of the ARIA specification [WAI-ARIA-1.1]. This version makes this state or property only applicable on the roles listed below. <a href="#state_property_processing">State and Property Attribute Processing</a> requires that User agents MUST ignore non-global states and properties used on an element without a role supporting the state or property. At time of publishing this Working Draft this property may still be exposed on all roles as it would have been as a Global state or property.

**Comment by jnurthen** [comment]
@joanmarie @michael-n-cooper please comment on this text. If good I'll update the 4 properties with this and push to stable

**Comment by joanmarie** [comment]
That works for me. (Comma after "Working Draft")

**Comment by michael-n-cooper** [comment]
I'm a little unsure about the last sentence, trying to understand what it means to a reader who isn't us. Maybe I'd change the beginning to "However, until implementations are updated, this property might still be exposed...". I might also add another sentence at the end "Two implementations of this change are required to validate it, and if they are not found by the end of the Candidate Recommendation period this change would need to be reverted."

**Comment by jnurthen** [comment]
This state or property was a Global state or property in the previous version of the ARIA specification [WAI-ARIA-1.1]. This version makes this state or property only applicable on the roles listed below. State and Property Attribute Processing requires that User agents MUST ignore non-global states and properties used on an element without a role supporting the state or property. However, until implementations are updated, this property might still be exposed to user agents. 

Two implementations of this change are required to validate it, and if they are not found before this specification enters candidate recommendation these changes will be marked "at-risk" and, consequently, if not found before the end of candidate recommendation this change would need to be reverted.

**Comment by jnurthen** [comment]
Attempt 2 above... @joanmarie @michael-n-cooper

**Comment by michael-n-cooper** [comment]
Looks good to me.

**Comment by joanmarie** [comment]
Works for me as well. Nit-picky tweaks of the second paragraph for your consideration:

Two implementations of this change are required to validate it. If they are not found before this specification enters Candidate Recommendation, this change will be marked "at-risk." If they are not found before the end of Candidate Recommendation period, this change will be reverted.
