### ISSUE TITLE
Why is aria-current=page limited to pagination links?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1107]
[ARIA spec for aria-current](https://w3c.github.io/aria/#aria-current) says:

> A page token used to indicate a link within a set of pagination links, where the link is visually styled to represent the currently-displayed page.

According to my understanding "pagination links" are links that refer to page numbers (1, 2, 3, 4 etc.). I think it would be useful, if  `aria-current=page` can also be used within navigation links, e.g.

```
<ul>
  <li><a href=...>Code</a>
  <li><a href=... aria-current=page>Issues</a>
  <li><a href=...>PR</a>
  <li><a href=...>Actions</a>
</ul>
```

I suggest that the description be adjusted, analogous to the description in the table "Values":
> page: Represents the current page within a set of pages.

**Comment by scottaohara** [comment]
Out of context, yes I'd agree with this issue.  However, in context of the full definition, it's stated that these are examples, as this paragraph immediately precedes the text you quoted:

>The aria-current attribute is used when an element within a set of related elements is visually styled to indicate it is the current item in the set. For example:

That said, might this rewording help clarify:

>A page token used to indicate a link within a set of links, such as a general navigation or pagination pattern, where a link is visually styled to represent the currently-displayed page.

**Comment by LJWatson** [comment]
@scottaohara  is right that it's only an example, but it was included with good reason. It encourages authors away from using aria-current="page" on main navigation blocks, because that risks having pages with two things set to aria-current="page" - the main nav and a pagination block. Whilst both are technically correct within the definition of the attribute, which is scoped to the containing collection, it isn't a good result for users.

**Comment by eps1lon** [comment]
> It encourages authors away from using aria-current="page" on main navigation blocks, because that risks having pages with two things set to aria-current="page" - the main nav and a pagination block.

I cannot find any text indicating there should be only one `aria-current="page"` in the document. It only refers to "a set of related links". IMO two different `<nav />` blocks are different sets and therefore aria-current is allowed in both blocks.
