### ISSUE TITLE
Editorial: Remove parenthesis from headings

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria#1108]
A conversation on WebAIM prompted me to look at how easy it is to navigate the ARIA spec and locate content. The robust heading structure and linked table of contents are both really useful, but searching for a particular role, attribute, or property, isn't so easy.

The reason is that the table of contents doesn't drill down to the level of the individual roles and attributes, and the heading text puts the word "role" or "property" or whatever in parenthesis. For example:
>note (role)>

When searching for something, it's more likely that someone will type in "Note role", and consequently not be able to find it. Could the parenthesis be removed possibly?

**Comment by pkra** [comment]
From the same WebAIM thread (I'm guessing): the "Notes" components have the word "Note" marked up as a heading; this creates a lot of noise when navigating by heading (e.g., there are 74 such Notes in the spec right now).

**Comment by pkra** [comment]
@jnurthen I just added this because the headings was a specific problem Lucy described on the thread. Obviously, Leonie's suggestion is great (and lower hanging fruit).

**Comment by LJWatson** [comment]
>From the same WebAIM thread (I'm guessing): the "Notes" components 
have the word "Note" marked up as a heading; this creates a lot of noise 
when navigating
by heading (e.g., there are 74 such Notes in the spec right now).>

I don't really agree that these headings are a particular problem, which 
is why I didn't file an issue to that effect.
