### ISSUE TITLE
Place to collect feedback on ARIA Annotations proposal

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#1109]
Please leave feedback here on proposal at https://github.com/aleventhal/aria-annotations

Original ARIA Annotations issue = https://github.com/w3c/aria/issues/749

**Comment by aleventhal** [comment]
Relevant PRs:
https://github.com/w3c/aria/pull/1133 (aria-description)
https://github.com/w3c/aria/pull/1134 (aria-details changes)
https://github.com/w3c/aria/pull/1135 (role=comment)
https://github.com/w3c/aria/pull/1136 (role=suggestion)
https://github.com/w3c/aria/pull/1137 (role=mark)

**Comment by larscwallin** [comment]
Hi 👋
I would like to suggest the addition of a section in the explainer for cases where the annotations are not an intrinsic part of the annotated content. There are cases, especially in digital publishing scenarios, where the source document markup can not be modified and hence the annotations will be external to the document context. This is where a clarification is needed as `aria-details`, as an example, needs an id which is local with in the same document.

So what mechanism should we employ here you think? 

Pseudo markup follows as seed for discussion...

Example document somearticle.html:
```
<article>
    <p>
          So Long and Thanks for All the Fish
    </p>
</article>
```

Example annotation using standard rel attribute and a local `<a>` that points to the annotated content:
```
<div class="annotation" role="comment" aria-detail="linktoannotatedcontent">
   <a rel="external" id="linktoannotatedcontent" href="https://somesite.com/articles/somearticle.html#:~:text=Thanks%20for%20All%20the%20Fish">
        Go to the annotated content
    </a>
    This annotation is a comment on the "Thanks for All the Fish" text range.
</div>
```

What say ye wise peeps?

**Comment by aleventhal** [comment]
There's no reason that an annotation can't point to an external resource via a link. It will be an extra hop for the screen reader user, but it works.  User would navigate to the annotation that has a link, and then could activate the link.

However, the  aria-details (not aria-detail btw) should go on the thing that is being commented, and point to the comment. 

I was about to write some example code, but I'm not sure what you're looking to do. Are you looking to point from the comment back to the annotated content in the source document? ARIA Annotations work the other way, pointing from the annotated content to the annotation body.

**Comment by larscwallin** [comment]
Thanks for your reply 🙂

The reason for my previous comment was to highlight the need for annotations that are not part of the structure of the document being commented on.

As far a "directionality" goes it would seem logical that the annotated content would only rarely know about any annotations that are referencing it.

The concept of referencing a local link from an aria-details attribute to point to an external resource is taken from the ARIA docs.

Example 19
https://www.w3.org/TR/wai-aria-1.2/#aria-details

I will write a better example of my toughts on Monday when I'm back from vacation 🙂

**Comment by pkra** [comment]
I think this can be closed as resolved (all PRs have been merged).
