### ISSUE TITLE
"URI" attribute type is unused?

### ISSUE THREAD

**Issue by domenic** [w3c/aria#1111]
https://w3c.github.io/aria/#propcharacteristic_value defines a URI type, but Ctrl+Fing for "URI" in the spec does not appear to turn up any instances. It might be good to remove this.

**Comment by carmacleod** [comment]
Apparently it was used for [`aria-describedat`](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-describedat) which [never made it into a published version of the ARIA spec](https://webaim.org/discussion/mail_thread?thread=8630). I don't really know the history, but I guess some folks said that it [didn't provide anything that longdesc didn't already provide](http://www.d.umn.edu/~lcarlson/research/constriants/ariadescribedat.html). So I think it's fine to remove it.
