### ISSUE TITLE
Revisit potentially outdated Related Concepts links

### ISSUE THREAD

**Issue by smhigley** [w3c/aria#1114]
Some of the links under "Related Concepts" sections look (at least to me) like they might be outdated, or at least worth a revisit:

- `application` role links to [Device Independence Delivery Unit](https://www.w3.org/TR/di-gloss/#def-delivery-unit)
- `directory` role links to [DAISY Guide](http://www.daisy.org/z3986/2005/Z3986-2005.html#Guide)
- `document` role also links to [Device Independence Delivery Unit](https://www.w3.org/TR/di-gloss/#def-delivery-unit)
- `menu` role links to [JAPI MENU](https://docs.oracle.com/javase/10/docs/api/javax/accessibility/AccessibleRole.html#MENU) -- this isn't outdated so much as mildly confusing -- i.e. why Java, and why specifically menu and menuitem?
- `menuitem` role links to [MENU_ITEM in JAPI](https://docs.oracle.com/javase/10/docs/api/javax/accessibility/AccessibleRole.html#MENU_ITEM) -- same as above
- `roletype` abstract role links to [XHTML role](https://www.w3.org/TR/xhtml-role/#s_role_module_attributes) and [Dublin Core Type](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/)
- `tablist` role links to [DAISY Guide](http://www.daisy.org/z3986/2005/Z3986-2005.html#Guide)

Apologies if these do make sense, and I'm just missing the context :)

**Comment by scottaohara** [comment]
adding onto this, I think the related concept links to HTML's `<menuitem>` for `command` and `menuitem` should also be removed, since `<menuitem>` is obsolete in HTML.

For instance, `role=marquee` does not reference HTML's obsolete `<marquee>` as a related concept.
