### ISSUE TITLE
AriaAttributes members need [CEReactions]

### ISSUE THREAD

**Issue by annevk** [w3c/aria#1116]
Otherwise custom element callbacks aren't called for any changes they end up making, which seems wrong.

That does make the mixin that also goes on top of `ElementInternals` a bit more awkward, but maybe we can patch `[CEReactions]` to only care about nodes somehow.

cc @alice @dot-miniscule @domenic @bzbarsky

**Comment by domenic** [comment]
Eh, [CEReactions] is harmless when used in cases that won't cause CE reactions, so I don't think it's a problem.

**Comment by annevk** [comment]
Yeah, putting an early return there if the this object isn't an element seems nice, but it does not appear to be needed indeed.

**Comment by carmacleod** [comment]
Can this issue be closed?
