### ISSUE TITLE
Tab Panel keyboard interaction

### ISSUE THREAD

**Issue by StommePoes** [w3c/aria#113]
The current guidelines for tab panel keyboard interactions have this
- "Up arrow - behaves the same as left arrow in order to support vertical tabs 
- Down arrow - behaves the same as right arrow in order to support vertical tabs"

Developers (for example at jQuery UI) seem to have taken this to mean "always make up/down arrows mimic left/right arrows in tab-panels", however what this does is prevent sighted keyboarders from scrolling the page. The only option is moving by an entire page with PageUp/PageDown, which is difficult to read blocks of text with, while seemingly offering little gain.

Can either the spec clarify that up/down arrows should only be hijacked IF these are vertical tabs, or better yet, leave them alone all the time? Whether a tab-panel has horizontal or vertical tabs seems to be a pure visual-design/CSS choice and shouldn't change how the things work, nor should these widgets remove current browser functionality by accident.

**Comment by MichielBijl** [comment]
I wholeheartedly agree +1

This is however consistent with how radiobuttons work. How you escape those?

**Comment by StommePoes** [comment]
I have never, ever had radios so long that I could not read them all.

As I move down a list of radios, my screen moves with me, if somehow one did manage to make a longer-than-one-page-full of radios.

Plus anyone who does such a thing is probably evil and trying to make me cry.

**Comment by MichielBijl** [comment]
What I mean is if you reach the last radio button and you press an arrow key. Like on this page: http://dir.agosto.nl/accessibility/radios-text.html. The result in Safari 9 is that if the user reaches the last radio button and presses the down key; the page scrolls. If the user then presses the up key, it must go through all radio's again before scrolling up.

**Comment by StommePoes** [comment]
That's true for radios, and more often I'm in a form where the next or previous thing is a focusable-by-tab. If the first/last item in a form is a radio field then yeah, I'd have to get out of them or to the end of them to scroll the page.

**Comment by MichielBijl** [comment]
Not saying that is a solution, just comparing results :)

**Comment by StommePoes** [comment]
To make them more comparable, I think you'd have to change the text underneath as you arrow through the radios.

**Comment by MichielBijl** [comment]
That is a very good point. Crap.

**Comment by jnurthen** [comment]
Now tablist supports aria-orientation we should really suggest that for horizontal tabs we only use left/right to switch tabs and leave up/down to the browser and for vertical tabs use up/down and leave left/right to the browser (although I'm not sure what harm it would do to allow left/right)

**Comment by MichielBijl** [comment]
@jnurthen am I correct in saying that there is no mention of `aria-orientation` in the [tab panel design pattern](http://w3c.github.io/aria/practices/aria-practices.html#tabpanel)?

**Comment by jnurthen** [comment]
You are correct. Tablist didn't support it in aria 1.0.

**Comment by jnurthen** [comment]
> Also, what would happen if you have vertical tabs whose content is longer than the window height? You'd still need arrow keys to scroll. Should we recommend setting tabindex=0 to the active tab panel so that users can scroll using arrow keys?

This would be a hole in the design pattern. My thought is that this is a rare case but yes - I guess we could specify that. If the tab panel is a div with overflow that would automatically become tabbable in FF anyway (although not in all other browsers)

**Comment by StommePoes** [comment]
I've been setting my panes (unless there's a direct first-child focusable inside) to tabindex=0 so far. It works for me, but would like to know if that's doable for everyone else everywhere. *normally* we don't want to make non-interactives focusable...

**Comment by MichielBijl** [comment]
I offered to build the tab widget for the user testing session thing during CSUN (as proposed by Ian Pouncy). This could be a thing we can test with real people. And I think we should, given that we're writing the book on how to do it. 

I'll see if I can get the widget done somewhere this week. There is already an issue for it here on GitHub.

**Comment by StommePoes** [comment]
oooh! user testing!!  Grab some random person from the street too-- someone not working in the (dis)ability space. Hotel staff. Restaurant servers. Whatever.

**Comment by MichielBijl** [comment]
Related issue: https://github.com/w3c/aria/issues/206

**Comment by jnurthen** [comment]
I missed this when editing the tab stuff (perils of multiple issue tracking systems) but I will get to this in the near future.

**Comment by MichielBijl** [comment]
This issue was moved to w3c/aria-practices#14
