### ISSUE TITLE
WAI-ARIA: add role value image as synonym for img

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#116]
`img` is the only role value that is not a (mostly) complete word. I suggest we add `image` as a synonym.

**Comment by Joanmarie** [comment]
Do we have evidence of a significant number of authors using "image" instead of "img"?

**Comment by MichielBijl** [comment]
I don't have any numbers except for a conversation I once had where I used “image” and it didn't work. I can look it up.

In any case, the current keyword is inconsistent with all the other values like `figure`, `itemlist`, and `video`. These are not called `fig`, `il`, and `vid`. It makes sense to add `image` as a synonym if you ask me.

**Comment by stevefaulkner** [comment]
Of approx 160,000 pages (from webdevdata.org) use of 3 instances of
role=image were found. On same set of HTML files 546 instances of role=img
found.

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by MichielBijl** [comment]
Thank you Steve! So it's 546 against 3?

**Comment by MichielBijl** [comment]
If I'm the only one here that thinks that this is a good idea, we might as well close it.
