### ISSUE TITLE
Deprecate global attributes instead of removing them

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1164]
ARIA 1.2 is proposing to remove the following global attributes:

- aria-disabled
- aria-errormessage
- aria-haspopup
- aria-invalid

While I understand the need for such a change, I do not think removing them is the right way to go here. The web is a slow developing platforms. Removing features from a specification isn't going to stop anyone from using them. Browsers, assistive tech, authoring tools and validators will have to support these attributes for years to come. Taking attributes out, especially global attributes, is too abrupt a change in my opinion.

I think these attributes need to be deprecated instead or removed. Deprecating them makes for much greater transparency. I noticed this was done for the "directory" role, I think the same can be done here.

**Comment by scottaohara** [comment]
they're not being removed from the spec though.  they've been removed from being global attributes, but are still allowed on roles where these states and properties would be useful.

so `<input aria-invalid=true>` is still perfectly fine, but `<div role=banner aria-invalid=true>` will now be considered incorrect usage.

**Comment by WilcoFiers** [comment]
The one I'm especially concerned about is aria-disabled. That one inherits, so you can use it to disable a group of fields like this:

```html
<div aria-disabled="true">
  <input aria-label="given name" />
  <input aria-label="family name" />
</div>
```

**Comment by JAWS-test** [comment]
> That one inherits, so you can use it to disable a group of fields like this:

I think the change was made to be consistent with the [HTML attribute disabled](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls:-the-disabled-attribute). disabled can only be used on form elements or form field groups (fieldset). This is now also the case with ARIA. In your example, the group should be marked with role=group

**Comment by jnurthen** [comment]
@WilcoFiers I tested your example on Windows
both fields get read as "unavailable" with both Chrome and Firefox with both NVDA and JAWS
As such I think you are right and we should revisit this (at least for aria-disabled)

**Comment by WilcoFiers** [comment]
Yeah, I'd be a lot more comfortable pulling these things if there was test data showing that removing these attributes from all roles (valid and invalid) couldn't cause issues. I happen to know the aria-disabled one because I worked on it fairly recently.

**Comment by jnurthen** [comment]
https://github.com/w3c/aria-common/pull/43
