### ISSUE TITLE
Allow caption within treegrid

### ISSUE THREAD

**Issue by smhigley** [w3c/aria#1168]
Currently the `caption` role lists `figure`, `grid`, and `table` under Required Context Role. Would it make sense to include `treegrid` as well? It appears to be supported already Chrome, Firefox, and Edge on Windows (don't have access to a mac at the moment to test support there).

Is there any objection to adding `treegrid` to both the `caption` definition and the list of required context roles?

**Comment by jnurthen** [comment]
Sounds like you are volunteering to create a PR so I have assigned to you.... if not please unassign yourself and I'll take it.

**Comment by carmacleod** [comment]
Ha, @jnurthen - I had just finished typing basically the same thing when your reply appeared:

No objections here. A PR would be lovely. 😉

**Comment by smhigley** [comment]
Done! 😁
