### ISSUE TITLE
Combobox and aria-activedesendant

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1175]
The requirements for aria-activedesendant are incompatible with the new combobox pattern. `aria-activedesendant` says the following:

> Authors MUST ensure that one of the following two sets of conditions is met when setting the value of aria-activedescendant on an element with DOM focus:
> 1. The value of aria-activedescendant refers to an element that is either a descendant of the element with DOM focus or is a logical descendant as indicated by the aria-owns attribute.

Example 6 looks like this:

```html
    <label for="tag_combo">Tag</label>
  <input type="text" id="tag_combo"
      role="combobox" aria-autocomplete="list"
      aria-haspopup="listbox" aria-expanded="true"
      aria-controls="popup_listbox" aria-activedescendant="selected_option">
<ul role="listbox" id="popup_listbox">
   <li role="option">Zebra</li>
   <li role="option" id="selected_option">Zoom</li>
</ul>
```

Since `#selected_option` is neither a descendant of, nor owned by `#tag_combo`, this example seems to be invalid.

**Comment by JAWS-test** [comment]
> Authors MUST ensure that *one of the following two* sets of conditions is met
> The element with DOM focus is a combobox or textbox with aria-controls referring to an element that supports aria-activedescendant, and the value of aria-activedescendant refers to either a descendant of the controlled element or is a logical descendant of that controlled element as indicated by the aria-owns attribute. For example, in a combobox, focus may remain on the combobox while the value of aria-activedescendant on the combobox element refers to a descendant of a popup listbox that is controlled by the combobox.

**Comment by WilcoFiers** [comment]
Right you are! Apologies, not sure how I overlooked that. Thanks for the reply!

**Comment by WilcoFiers** [comment]
Also, yeah searchbox should be in there I suppose.
