### ISSUE TITLE
Add UA requirements for ARIA 1.1 under combobox

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1178]
Under combobox it says: 

> The ARIA 1.0 specification describes a combobox pattern where the input element with the combobox role references the popup element with aria-owns instead of aria-controls. User agents, assistive technologies, and conformance checkers SHOULD continue to support the ARIA 1.0 pattern so that existing implementations of the ARIA 1.0 pattern remain functional. The ARIA 1.1 specification describes a combobox pattern where the element with role combobox is a composite container instead of a focusable input. User agents and assistive technologies did not adequately support the ARIA 1.1 pattern, so the ARIA 1.2 pattern supersedes the ARIA 1.1 pattern, which authors SHOULD abandon.

In combobox, it is mentioned that UA should continue to support the ARIA 1.0 pattern. I think the same needs to happen for the ARIA 1.1 pattern. Yes, authors should move away from it, but until they have, browsers have to maintain support for this pattern. This could very easilly take a decade. I think ARIA 1.2 needs to be clear on this.

**Comment by mcking65** [comment]
@WilcoFiers wrote:

> ... it is mentioned that UA should continue to support the ARIA 1.0 pattern. I think the same needs to happen for the ARIA 1.1 pattern. Yes, authors should move away from it, but until they have, browsers have to maintain support for this pattern. This could very easilly take a decade. I think ARIA 1.2 needs to be clear on this.

Given the fact that the 1.1 pattern does not work for most assistive technology users, are there real benefits to recommending any continued support?

I am sure browser support for 1.1 implementations will not immediately break for the few people benefiting from it. However, it is guaranteed that any existing 1.1 implementation is creating more difficulties than benefits for users. So, a requirement, or even recommendation, to maintain code that is more harmful than beneficial does not seem like an optimal path. It will tend to perpetuate the problems.

Even if browser and assistive technology support for the 1.1 pattern were to remain at current levels for the next few years, which is likely even without a recommendation in the spec, it is hard to imagine that 1.1 implementations will persist for very long given that a broadly functional alternative is finally available. And, if checkers invalidate them, that will help promote their demise.

Would the following wording provide more clear and reasonable direction?

>The ARIA 1.0 specification describes a combobox pattern where the input element with the combobox role references the popup element with aria-owns instead of aria-controls. User agents and assistive technologies SHOULD continue to support the ARIA 1.0 pattern so that existing implementations of the ARIA 1.0 pattern remain functional. However, conformance checkers SHOULD recommend that authors convert to the ARIA 1.2 pattern.
>
>The ARIA 1.1 specification describes a combobox pattern where the element with role combobox is a composite container instead of a focusable input. Due to insufficient support by user agents and assistive technologies, the ARIA 1.2 pattern supersedes the ARIA 1.1 pattern. Authors SHOULD convert implementations of the ARIA 1.1 pattern to the ARIA 1.2 pattern. Conformance checkers SHOULD warn authors that the ARIA 1.1 pattern is no longer valid. User agents and assistive technologies MAY phase out support for the ARIA 1.1 pattern at their own discretion.

**Comment by carmacleod** [comment]
@mcking65 Completely agree with the words in the previous comment, except for one nit.

I think the following sentence doesn't clearly state which version was insufficiently supported:
> Due to insufficient support by user agents and assistive technologies, the ARIA 1.2 pattern supersedes the ARIA 1.1 pattern. 

The sentence that was there originally is clearer:
> User agents and assistive technologies did not adequately support the ARIA 1.1 pattern, so the ARIA 1.2 pattern supersedes the ARIA 1.1 pattern.

**Comment by mcking65** [comment]
Thank you Carolyn, then the proposal would read as follows. I'm also thinking it would be useful to incorporate more specifics for conformance checkers as proposed by @accdc in #1118.

>The ARIA 1.0 specification describes a combobox pattern where the input element with the combobox role references the popup element with aria-owns instead of aria-controls. User agents and assistive technologies SHOULD continue to support the ARIA 1.0 pattern so that existing implementations of the ARIA 1.0 pattern remain functional. However, conformance checkers SHOULD recommend that authors convert to the ARIA 1.2 pattern by replacing aria-owns with aria-controls.
>
>The ARIA 1.1 specification describes a combobox pattern where the element with role combobox is a composite container instead of a focusable input. User agents and assistive technologies did not adequately support the ARIA 1.1 pattern, so the ARIA 1.2 pattern supersedes the ARIA 1.1 pattern. Authors SHOULD convert implementations of the ARIA 1.1 pattern to the ARIA 1.2 pattern. Conformance checkers SHOULD warn authors that the ARIA 1.1 pattern is no longer valid. User agents and assistive technologies MAY phase out support for the ARIA 1.1 pattern at their own discretion.

**Comment by mcking65** [comment]
I would like to have feedback from @WilcoFiers and @zcorpan before submitting a PR.

**Comment by joanmarie** [comment]
Ping @WilcoFiers and @zcorpan re the feedback requested.

**Comment by carmacleod** [comment]
The ARIA Working Group just discussed `Add UA requirements for ARIA 1.1 under combobox`.

<details><summary>The full IRC log of that discussion</summary>
&lt;carmacleod> github: https://github.com/w3c/aria/issues/1178<br>
&lt;carmacleod> jamesn: need to ping Wilco<br>
</details>

**Comment by WilcoFiers** [comment]
@schne324 pinged me on this. I like the "User agents and assistive technologies MAY phase out support for the ARIA 1.1 pattern at their own discretion." phrasing. I think that's an excellent addition to this.

**Comment by zcorpan** [comment]
From #1118

> * Why should conformance checkers support the ARIA 1.0 pattern? If we want authors to use the 1.2 pattern, shouldn't conformance checkers flag an error when the 1.0 pattern is used?

Specifically, conformance checkers should give an error for the ARIA 1.0 pattern and recommend the current pattern instead.

> * What does it mean for UAs and ATs to support the ARIA 1.0 pattern? If it is required for web compat to support the legacy markup pattern, the processing model to handle both the 1.2 pattern and the 1.0 pattern should be clearly specified in the current spec.

I think it's not enough for the purpose of ending up with interoperable implementations to say "continue to support the ARIA 1.0 pattern". Conforming to the requirements of the features used by the patterns should be enough for browsers and ATs to end up with the desired result.

**Comment by mcking65** [comment]
@cookiecrook does not support normative requirements for user agents and conformance checkers related to earlier versions of the specification. His position, as I understand it, is that if the specification is to mention previous requirements at all, it should do so in the form of an informative note. I believe this is more consistent with accepted practice and have revised the proposed text as follows.

>#### NOTE
>The structural requirements for combobox described in this version of the specification are different from the requirements described in ARIA 1.0 and ARIA 1.1:
>* The ARIA 1.0 specification required the input element with the combobox  role to be a single-line text field and reference the popup element with aria-owns instead of aria-controls .
>* The ARIA 1.1 specification, which was not broadly supported by assistive technologies, required the combobox  to be a non-focusable element with two required owned elements -- a focusable textbox and a popup element controlled by the textbox .
>* The changes introduced in ARIA 1.2 improve interoperability with assistive technologies and enable authors to create presentations of combobox that more closely imitate a native HTML select  element.

You can view the above in a [RawGitHack view of the compare branch](https://raw.githack.com/w3c/aria/issue1178/index.html#combobox) for pull request #1123.
