### ISSUE TITLE
Explain "→" in Required Owned Elements

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1179]
There are several places in required owned elements that this "→" symbol is used, with a title of "containing". For example `table` has this:

> Required Owned Elements:
> - row
> - rowgroup → row

As far as I can tell, this "containing" thing is never explained anywhere in ARIA. I would expect it to be under [5.2.6 Required Owned Elements](https://www.w3.org/TR/wai-aria-1.2/#mustContain). This seems like an oversight.

**Comment by carmacleod** [comment]
In ARIA 1.3, we removed the right-pointing-arrow (such as in `table`) and the left-pointing arrow (such as in `row`) and replaced them with "containing" and "contained by" respectively.

Perhaps we should just go one further and replace "containing" with "owning", and "contained by" with "owned by".
