### ISSUE TITLE
WAI-ARIA 1.1: Link to DOM2 Core

### ISSUE THREAD

**Issue by momdo** [w3c/aria#118]
In <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#intro_ria_accessibility">section 1.1</a>,
> Document Object Model [DOM-Level-2-Core],

Why does the draft refer DOM2? We know the <a href="http://www.w3.org/TR/dom/">W3C DOM4</a> spec is the latest W3C Recommendation.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria/pull/262
