### ISSUE TITLE
What rules apply to descriptions?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1186]
The ARIA specification specifies for each element whether the labeling is a result of the content, comes from the author or is not possible. There is no indication for the description, i.e. it is not clear whether each element can get a description with title, aria-describedby or aria-description or only elements that have name from author

**Comment by aleventhal** [comment]
Things with prohibited names can still have a description.
A big reason names are prohibited is that they would override contents, but aria-description is used for additional annotation content. It's important to be able to annotate any kind of object.

**Comment by JAWS-test** [comment]
What I don't understand, however, is why [aria-describedby](https://w3c.github.io/aria/#aria-describedby) can be used for all roles ("Used in Roles: All elements of the base markup") and [aria-description](https://w3c.github.io/aria/#aria-description) cannot ("All elements of the base markup except for some roles or elements that prohibit its use"). Also, for which roles can aria-description not be used?

**Comment by aleventhal** [comment]
aria-describedby, aria-description and title should all be usable on all elements of the base markup.
If the spec says otherwise, then good catch, because that's wrong.

**Comment by scottaohara** [comment]
Agree, `aria-description` should match `aria-describedby`'s "All elements of the base markup"

**Comment by carmacleod** [comment]
Yep - good catch, @JAWS-test !

**Comment by aleventhal** [comment]
Pull request here: https://github.com/w3c/aria/pull/1193

**Comment by JAWS-test** [comment]
For me the question remains, what should AT do with a description on an element that does not get the focus? Output during linear reading with the virtual cursor? Currently NVDA and JAWS ignore the description when reading with the virtual cursor. Description is only output when the focus is set with the Tab key. Is this an error in JAWS and NVDA?

**Comment by aleventhal** [comment]
Yes, it's expected the description should be read, no matter how the user visits the element, including by focusing, via virtual buffer, or arrowing to the item in the editor.
However, screen readers may provide a setting to turn descriptions off.
I'm working with screen reader devs and others to define good behaviors for annotations and descriptions. This is not part of the spec -- it's more like suggestions. 
Feel free to read it -- your comments would be welcome and appreciated. LMK if you need it in a different format other than Google Docs. https://docs.google.com/document/d/1DYrsHDk6Y9071A1fRg8g8NZ_DtGYraX5BcVY-taBzMQ/edit?ts=5e1cbd7d#

**Comment by stes-acc** [comment]
It is a old Jaws habit not reading title attribute in VPC mode no matter how settings are. Something that must change to be straight with descriptions and annotation behaviour.

**Comment by JAWS-test** [comment]
Hi @aleventhal, thanks for the link. If I have time, I will have a look at the document. However, I tend to think that non-focusable elements should not have a description. If non-focusable elements have a description, this has two disadvantages:
* Keyboard users will not be able to perceive these descriptions. This is a violation of WCAG SC 2.1.1.
* Blind users will not be able to read texts without interruption if descriptions are output within the texts or a reference to the description. In this respect, I think the output of JAWS is correct in itself: descriptions are only output when the user focuses with the Tab key.

**Comment by sinabahram** [comment]
I agree with these two points. I’m unclear what it means for a keyboard or screen reader user to have descriptions on non-focusable items.

**Comment by LaurenceRLewis** [comment]
I’m probably confusing myself here, but, shouldn’t  the description being announced be related to a role rather than focus or non-focused elements?

**Comment by aleventhal** [comment]
Hi @JAWS-test, the intention of both aria-describedby and aria-description (not to mention aria-details), is that they can apply to anything. After all, anything can have an annotation, a description, a comment, etc.

- Screen readers may need updates to do a good job of announcing these to users in various modes. I'm working with a number of them on this.
- For keyboard users, the description may be available to keyboard users via navigating to the unfocusable object in an editor. This is similar to focusing, but not the same. As an example, a user who arrows onto a highlighted area in an editor, may visually observe additional information related to that area that is currently not exposed to a screen reader user. 
- For items that are not focusable and not in an editor, another possibility is that a description has a clear visual tie to that item, via placement, lines that are drawn, color, or other means of association

True, aria-description would make it possible to add information perceivable by a screen reader user that is not perceivable by a sighted keyboard user. However, this is also possible with aria-label, aria-roledescription, or other means. The same markup also makes it possible to do a better job with WCAG.

**Comment by sinabahram** [comment]
This phrase caught my ear:

As an example, a user who arrows onto a highlighted area in an editor, may visually observe additional information related to that area that is currently not exposed to a screen reader user.

 

Question:

Do we have a formalism for discussing that? Is that just point of regard, and do we formally differentiate between point of regard and focus? I understand it’s not exactly focus since the overall element may be what is focused, but does cursor position not functionally map to what focus maps to in non-editing contexts?

 

Also, clarifying point, but you mean highlighted in the sense of a background color to indicate a region, not highlighted in the sense of “selection”, correct; otherwise, that’s a selected area, and that introduces tons of other things to discuss. The former is how  a region would be used on a traditional page, right? e.g. start of Goal 3, end of Goal 3, where goal 3 is maybe a region in a complex document? Obviously, I’d prefer that be surfaced with a heading.

**Comment by aleventhal** [comment]
@sinabahram I mean visually highlighted, not in the sense of selection -- any type of visual indication. Developers may just use a text or background color change, or may end up being "creative" :) 
Additionally, something else in a sidebar may be highlighted simultaneously, to show association. Developers are "creative".

**Comment by aleventhal** [comment]
Here are some examples:

- A code editor or debugger with breakpoints or other interesting highlights. The breakpoints could have additional information such as conditions.
- A "data loss prevention warning" in Gmail that highlights text (you might not want to send your social security number). There is a visual indication that makes all of this apparent.
- "User soandso is editing in this area" in a collaborative editor
- Comments in a sidebar, associated with a piece of content (this would use aria-details most likely)

**Comment by JAWS-test** [comment]
> True, aria-description would make it possible to add information perceivable by a screen reader user that is not perceivable by a sighted keyboard user. However, this is also possible with aria-label, aria-roledescription, or other means.

I think there is a difference in the accessibility of aria-label and aria-description for seeing keyboard users:
* Each content has a visible label (if not, it is not visible to all users, including mouse users). aria-label can now provide a text alternative for a graphical label to comply with WCAG SC 1.1.1. Or aria-label can provide a meaningful label for elements whose purpose is apparent to sighted users from the context (to meet WCAG SC 1.3.1)
* Descriptions, on the other hand, are often not visible, but are only displayed on mouseover (for example, with the HTML attribute title). This is not accessible for keyboard users, especially if the elements do not get the focus.
