### ISSUE TITLE
WAI-ARIA 1.1: Editorial comments

### ISSUE THREAD

**Issue by momdo** [w3c/aria#119]
For W3C Working Draft 19 November 2015,
http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/

1) link in "Status of This Document"
>  Core Accessibility API Mappings 1.1 [[!CORE-AAM] 

Broken link.

2) incorrect link in <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#definition">definition role</a>
>HTML dfn

Correct link is http://www.w3.org/TR/2014/REC-html5-20141028/text-level-semantics.html#the-dfn-element .

3) incorrect link of <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#feed">feed (role)</a>
http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#articles is absent.

`#article` is correct.

4) missing space in <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#grid">grid (role)</a>
>To make a grid read-only, insert thearia-readonly attribute of the grid to true

should be

>To make a grid read-only, insert the aria-readonly attribute of the grid to true

5) old link in <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#aria-required">aria-required (property)</a>
>HTML 5 required

http://www.w3.org/TR/2010/WD-html5-20100624/common-input-element-attributes.html#the-required-attribute is too old.
Should be http://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-required-attribute .

6) missing anchor in <a href="http://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/#aria-invalid">aria-invalid (state)</a>
> XForms [XFORMS10] 'invalid' event http://www.w3.org/TR/2006/REC-xforms-20060314/slice4.html#evt-revalidate. 

In the draft, the URL actually isn't marked up by the `a` element.

**Comment by MichielBijl** [comment]
- [ ] link in "Status of This Document"
- [ ] incorrect link in definition role
- [ ] incorrect link of feed (role)
- [ ] missing space in grid (role)
- [ ] old link in aria-required
- [ ] Missing anchor in aria-invalid

**Comment by michael-n-cooper** [comment]
This appears to have been addressed or OBE.
