### ISSUE TITLE
Form elements should be able to be labeled via encapsulation

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1203]
Currently only some form elements can be labeled via [encapsulation](https://w3c.github.io/aria/#namefromencapsulation), but not all of them. For example, slider and combobox are missing. Is there a reason for this? If not, for consistency within ARIA, but also for consistency to HTML, all form elements should be able to be labeled like this

**Comment by joanmarie** [comment]
Marking for 1.3 because not in the stable/working-draft for 1.2

**Comment by jnurthen** [comment]
closing as name form encapsulation has been dropped
