### ISSUE TITLE
ARIA attribute for value on `combobox` role

### ISSUE THREAD

**Issue by smhigley** [w3c/aria#1220]
Right now, there is no way to specify a programmatic value separate from the name for comboboxes. This is an issue when creating a combobox out of something other than an `<input>` element.

Aside from the theoretical need, this means creating a select-only combobox requires either using an `<input readonly>` (undesired, since it is not readonly), or combining the value and name together.

`aria-valuetext` seems like it might be a reasonable solution, if it were allowed on `combobox`.

Thoughts? (This relates to the 3/17 aria-practices tf discussion on a select-only combobox example)

**Comment by JAWS-test** [comment]
This applies not only to combobox, but also to other form fields with value, such as textbox, see https://github.com/w3c/aria/issues/711

**Comment by jnurthen** [comment]
@smhigley Are you happy to close this and use #711 ? Please reopen if that doesn't work for you.
