### ISSUE TITLE
Consider `toast` role

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1230]
Perhaps for the 4.1 release? 🤔

**Comment by smhigley** [comment]
We still need solve the more general problem of toasts being difficult to find on the page, using either keyboard or screen reader.

I suggest also adding a `toaster` landmark role as a required parent of `toast`. Maybe it should inherit from an abstract `appliance` role.

**Comment by carmacleod** [comment]
> I suggest also adding a `toaster` landmark role as a required parent of `toast`. Maybe it should inherit from an abstract `appliance` role.

And `toaster` needs to require `aria-haspopup="true"`.

**Comment by sinabahram** [comment]
As well as aria-BurntBy, though the ID of the entity responsible may not still exist on the page, or at least that’s been my experience.

**Comment by scottaohara** [comment]
much like `dialog` and `alertdialog` i think we need a `toast` and `avocadotoast`

you know, for when you want people to really pay attention to your toast, but still know deep down that you've just put an expensive spread atop some burnt bread.

**Comment by aardrian** [comment]
Is there going to a `fork` role to handle cases where a toast does not display correctly, owing to script errors? Or would we rely on the browser to provide a fork-like override?

**Comment by sinabahram** [comment]
You know, I don’t think I agree with a fork role. I feel like the evidence shows that fork roles when used in combinations with toaster roles leads to the entire browser just crashing. In some circles, the error thrown is VoltageDropPotentialElectricutionException, though this can be mitigated against if appropriate rubberization requirements are complied with.

**Comment by smhigley** [comment]
Dunno, allowing both a `fork` + a `toaster` might help with the problem of too many developers using ARIA without understanding it.

**Comment by jnurthen** [comment]
Would `fork` be a fallback role in this case? If so wouldn't you also need a `campfire` role to complete the process
