### ISSUE TITLE
Tree inclusion section is ambiguous about whether to include certain elements that may receive focus.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1234]
Tree inclusion section is ambiguous about whether to include certain elements that may receive focus.
https://rawgit.com/w3c/aria/master/#tree_inclusion

I noticed a few weeks ago that the "skip to main content" link does not work on the US Census site. https://my2020census.gov

The web authors invalidated the link (`href="#"`) and called a function that focuses an empty span with `tabindex="-1"`. This is not user-focusable, and I don't believe the spec differentiates between "user focusable" versus "script focusable" so section 7.2 is ambiguous. The focus target element also has `aria-hidden="true"` set, so the focus event is smothered coming from an invalid tree. Keyboard focus works (partially), so presumably we want the UA accessibility implementation to expose this node (and others), as a workaround for the author error. 

I think the spec should be updated from:

> * Elements that are focusable, or have an ID attribute and an ancestor with the aria-activedescendant attribute that matches the implicit or explicit semantics of the required context role. In either case, the element may receive focus and may fire an accessibility API focus event.

To something like this: 

> * Elements that are user focusable.
> * Elements that become focused, even if they are not user focusable. 
> * Elements that have an ID attribute and an ancestor with the aria-activedescendant attribute that matches the implicit or explicit semantics of the required context role. (Note: This last bullet is pretty difficult to parse, but I left the prose alone for this issue.)

Furthermore, when an element "becomes focused" we should be clear on how the UA should correct the error and expose this. In the test case, the target element is both hidden and focusable:

```html
<span id="skip-focus" tabindex="-1" aria-hidden="true"></span>
```

So it's straightforward that the element above should be exposed at the time it receives focus. However, what if the hidden element was an ancestor of the element with focus?

```html
<div aria-hidden="true">
  <span id="skip-focus" tabindex="-1">target</span>
  <span>is this other hidden content exposed, too?</span>
</div>
```

Does focusing the child result in invalidating the "hidden" state of the ancestor? I lean towards yes, but I don't have a firm opinion.

**Comment by cookiecrook** [comment]
This issue may get rolled up into the independently filed #1100.

**Comment by JAWS-test** [comment]
I would prefer that aria-hidden be reliable. I.e. the other elements in aria-hidden (in the example above the span with content "is this other hidden content exposed, too?") should not be included in the tree when a sibling element gets the focus

**Comment by carmacleod** [comment]
In #1100 the pertinent point is:
- Elements that are focusable even if the element or one of its ancestor elements has its aria-hidden attribute set to true.

Does that cover everything? It seems clear to me that it only applies to the element in question, and not siblings. Also, I think "focusable" covers both "user focusable" (click, tab, ...) and "script focusable", and it might be confusing to split them out?

**Comment by jnurthen** [comment]
closing as covered by #1100
