### ISSUE TITLE
Consider camelCasing for markup languages

### ISSUE THREAD

**Issue by charmarkk** [w3c/aria#1264]
On behalf of metageeky (Kate Deibel) from Slack:

> camelCase would [help] make clear the word boundaries so that they can identified more readily [and better read by screen readers]. I've worked with a lot of blind/low vision programmers (including students) and they face many barriers when learning.

**Comment by jnurthen** [comment]
This was particularly with respect to role names

**Comment by cookiecrook** [comment]
There's not a straightforward way (or a fool-proof way) to enforce camel-casing of content attributes, but the DOM properties are already camel-cased.

**Comment by scottaohara** [comment]
Related issue: https://github.com/w3c/html-aria/issues/280.

**Comment by jnurthen** [comment]
lets close this unless someone wants to actively work on it
