### ISSUE TITLE
Importance of a `label` role for generating an accessible name

### ISSUE THREAD

**Issue by jongund** [w3c/aria#1271]
The introduction of the [`label` role](https://github.com/w3c/aria/pull/886) in ARIA 1.2 led to a proposal to allow the role for computing accessible names using an encapsulation technique for a limited set of roles.   

## Summary of Issues raised from 5/14/2020 discussion

| Arguments  | Action |  Notes |
|--------------|--------|-----------|
| Uncertain implementation of accessible name by encapsulation feature in user agents.  |  Remove | Reduce the number of items for implementation testing and getting to recommendation.  Free up limited developer resources to be used on other accessibility features. | 
| Importance relative to other implementation priorities | ??? |  Not clear what this is competing against for implementation resources. |
| Does not offer a accessible naming technique that cannot already be accomplished with current techniques | Remove |   The elimination of using IDs maybe useful when the alternative is using the `aria-labelledby` technique, but that is just convenience for developers.  |
| Allows authors to create accessible names for some types of widgets using the HTML `label` element.   |  Keep   |  Some authors already using this technique.  |
| `label` role does not fully mimic `label` elements in terms of activation behaviors |  Remove | Why give authors another opportunity to NOT do the right thing. |
|  Do we need a `label` role at all for HTML harmonization which is more about IDL interfaces than having a role for each HTML element |  Remove | If the `label` role does not provide any function for accessibility it will only be confusing and misused by developers. |

## Resolving Issue
* Keep current proposal
* Keep `label` role, but remove accessible name through encapsulation technique
* Remove role and remove accessible name through encapsulation technique
* File an issue with WHATWG for specification in HTML spec for `label` element feature for ARIA enabled widgets
 

## Discussion from ARIA working group meeting on 5/14/2020:

New Naming Methods - Discussion

jamesn: came up with these new methods when doing role parity

Matt_King_: is there a single issue to track this?

jamesn: no
... in 1.2 we have name from author, contents, and prohibited

<jamesn> legend: name comes from the text value of the first descendant element node with the role of legend. Although "legend" may be allowed in addition to "author" in some roles, "legend" is used in content only if higher priority "author" features are not provided. Priority is defined by the accessible name and description computation algorithm.

<jamesn> encapsulation: name comes from the text value of the element node with role label that is the closest ancestor. Although "encapsulation" may be allowed in addition to "author" and "contents" in some roles, "encapsulation" is used only if higher priority "author" features are not provided. Priority is defined by the accessible name and description computation algorithm.

jamesn: propose new concepts; name from encapsulation and legend [see details above]

<carmacleod> https://github.com/w3c/aria/issues/899#issuecomment-487607333

Matt_King_: was legend also meant to capture caption? i don't remember

jamesn: there's a caption role in 1.2
... conceptually, we're just talking something named by ancestor or descendent
... i struggle over the additional complexity we're adding
... would like an open discussion over should we do this? benefits for authors? users?

<carmacleod> https://w3c.github.io/aria/#namefromencapsulation

Matt_King_: most important question to ask, for me, is whether or not there's need for this in HTML parity space?
... if we're going to have these roles (label, caption, legend, etc.) in aria, wouldn't this be neecessary to support role parity?
... if there is -not- an absolute need, then we can answer the other questions

jongund: i think authors will do this, they're already doing it. so it's a bit undefined what browsers might do with it or if they'll do it. especially if it's about HTML parity; it might cause a disconnect for authors "why's it work here and not there?"

jamesn: back to Matt's question - maybe i'm seeing role parity as the ability to do everything the need to do, from an a11y POV
... if you're creating a web component that needs labelling from encapsulation, I'm not sure this way is the best way to do that
... i don't see the benefit of this over aria-labelledby etc.
... or the HTML label element can do a lot of this

Matt_King_: can't use an HTML label on a custom select made from a div

jamesn: correct

Matt_King_: using aria-labelledby on that is also not equivalent. that'd have to point to an element that contians just the label

jamesn: just tells me this will be even more complex, then

Matt_King_: not sure about that, that might be a thought for aaron
... same logic for HTML label
... if all this holds, would an HTML label work around an ARIA Combobox?

jongund: yes

<carmacleod> Here's the ARIA label role: https://w3c.github.io/aria/#label

jongund: i think i want to mirror what Matt said, we can use the label element now, it's standard HTML
... if we go through with this, i can use div role=label for encapsulation, vs a plain label. i worry about creating more gotcha's for developers or screen readers
... and i don't want to send people to spec more than necessary
... if we're not gonna do this, take it out

sina: i think this should be included, if we're doing role parity. but i agree with Jon, it'd be terrible to have it and force people to read a nuanced spec
... if you've already taken the time to learn a11y, which already isn't common, forcing another nuanced semantic on top of that might not be fair
... but if a div role=label encapsulates something, it should act like a label

jcraig: this is a complicated issue, but i want to acknowledge the need for encapuslation
... i'm not very up on this issue yet, but i want to look into it. that said, i agree with sina and jon
... it seems useful, value of role parity is there

<Zakim> joanie, you wanted to comment on divs "acting like" labels

joanie: i see both sides, but want to hone in sina's point about divs acting like labels. even if you slap a role on a div, the encapsulated element still needs some work to get it right. there's still -some- gotcha's

carmacleod: that's also true on the HTML side, a label with a for attr, for instance
... is the main driver for questioning this because it'll be difficult to write accname?

jamesn: it's good to question what we've done based on momentum
... and if that creates too much complexity, then maybe we should slow it down or not do it
... if we have to wait, we have the time to do so. and this seems worth discussing

Matt_King_: responding to jcraig - this rabbit hole started when we tried going a little beyond HTML
... like the idea of labelling a dialog with a heading

s/heading / heading, for instance

Matt_King_: it might be helpful to scope this to _first_ discuss the things that exactly mirror HTML in the simplest way
... like using label on a checkbox, combobox, etc.
... after we've done the simple stuff, the maybe go on to complicated things. jamesn it might be helpful to have a meta issue to group discussion and allow ansynchronous comments

jamesn: another way to go is to try and have HTML allow label on more things

<Zakim> jcraig, you wanted to state, technically we have parity in that the functionality to label exists, even if it's not a role per se

jcraig: the exercise for role parity was to allow devs to do in aria what they can do elsewhere
... doesn't necessarily mean we need 1:1 HTML:ARIA roles
... to joanie's comment - yes, adding label wont get the click focus, but it -can- be done with JS
... secondly, we could, as part of parity, is say these means and functionality exist via other things, like aria-labelledby

aaron: i hugely agree with jongund and want to get rid of gotchas. even if we do that, we might have the same group of gotchas. i feel a bit pinched, we have nowhere near enough a11y engineers to solve all these problems
... in other words, if this is a big issue, we've come really far and i agree generally. but this doesn't reduce gotcha's, like joanie said.

jcraig: it doesn't solve the need to make things possible, necessarily. web devs can already label things.... and adding the label role doesn't help the web driver testability problem either.

aaron: right, it's not adding capability or improving anything, necessarily, which are noble goals, and that all takes lots of engineering time

Matt_King_: true. thinking of the amount of time this would take versus other things we could do, it's important to prioritize things

jamesn: good comments everyone, thank you very much
... i'll open an issue for discussion and put these minutes in there.

**Comment by scottaohara** [comment]
with other methods labeling methods already available to name aria widgets, imo it does seem like this role should be put on the back burner for now

**Comment by jongund** [comment]
It looks like the HTML spec is already allowing for custom controls to at least get the `onclick` behavior for custom controls encapsulated by a `label` element:
[WHATWG Label spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element)

Maybe this issue should be reconsidered from creating an ARIA `label` role to an additional requirement for `label` element in the WHATWG spec.

**Comment by jongund** [comment]
Created a [test page for the use of the `label` element to label a custom checkbox]
(https://webedit.disability.illinois.edu/user/jongund/aria-label-test-1/output/).

It does not work in in Firefox or Chrome for computing an accessible name or for the activation behavior.

**Comment by jongund** [comment]
@jnurthen 

Is the resolution to remove the LABEL role form the spec for now until there can be more discussion?

We don't want authors to think that using the LABEL role to encapsulate standard HTML form controls would provide an accessible name , or that HTML LABEL element encapsulation would provide an accessible name to some ARIA widget roles.

Basically keep authors from thinking LABEL element  === LABEL role.

**Comment by carmacleod** [comment]
@jongund 
> It looks like the HTML spec is already allowing for custom controls to at least get the onclick behavior for custom controls encapsulated by a label element. ...
> Created a test page for the use of the label element to label a custom checkbox.
> It does not work in in Firefox or Chrome for computing an accessible name or for the activation behavior.

I think that for the label encapsulation to work, you need to specifically implement a "form-associated custom element". If you want to try that, there's a `my-checkbox` form-associated custom element example in the HTML spec: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example

However, maybe you're right that `role="label"` should be pulled from the ([ARIA 1.3](https://w3c.github.io/aria/#label)) spec in light of HTML allowing form-associated custom elements to be encapsulated by a `<label>`. (It's not in the [ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/#label) spec).

**Comment by jongund** [comment]
@jnurthen 
A `label` role that does not extend the ways to create an accessible name is not considered useful and would be misleading to authors who might think the `label` role has the same or similar labeling capabilities as the `label` element in HTML.
