### ISSUE TITLE
Question: mixed ARIA and native HTML (listbox)

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#1281]
I often come across a control, such as a listbox, that mixes ARIA roles and native HTML, for example:

`<button class="filter__btn" aria-expanded="true" aria-haspopup="listbox" aria-labelledby="uniqueID"><ul class="list_parent" role="listbox">
                    <li class="list_option">`

Should the `<li>` have `role="option"` ?

**Comment by jnurthen** [comment]
yes
