### ISSUE TITLE
Need an attribute to define whether role="list" is an ordered or unordered list

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#1283]
In HTML we have `<ol>` or `<ul>` but in aria we just have role="list"

I suggest a new aria attribute ...

aria-list="ordered"
aria-list="unordered"

So it would look like this.

```
<div role="list" aria-list="ordered"...>
<span role="listitem">...
...
```

**Comment by scottaohara** [comment]
This is a duplicate of #961
