### ISSUE TITLE
aria-haspopup should still be supported on link

### ISSUE THREAD

**Issue by majornista** [w3c/aria#1289]
#999 / #1023 deprecates use of `aria-haspopup` as a global property, but does not include `link` as one of the `role`s for which `aria-haspopup` is still valid. In my opinion, a popover or dialog is very much like an in-page link, in that expanding it moves focus to another location within the same page. 

One use case I recently encountered where `aria-haspopup` seems appropriate on a link is for progressive enhancement in documentation, where code examples for one component link to documentation for related components and class definitions. For this use case, on-site links display the related documentation in a popup dialog, while off-site links open the related documentation in a new window. I think it makes sense to distinguish between these two link behaviors, and it seems odd to have to add `role="button"` to the on-site links.

**Comment by cookiecrook** [comment]
My suggested phrasing (from today's call) of a new note: ~

> `aria-haspopup` is most relevant to use when there is a visual indicator in the element that triggers the popup. For example, most menu buttons are styled with a downward pointing triangle or chevron, which indicates to sighted users that the button will display a menu when clicked.
> 
> If there is no visual indication that a element will trigger a popup, authors are advised to consider whether use of `aria-haspopup` is necessary, and avoid using it when it's not.

Please feel free to change any or all of it.
