### ISSUE TITLE
WAI-ARIA 1.1: base concepts link to HTML 4

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#129]
A lot—if not all—base concept links, under [5.4 Definition of roles](http://www.w3.org/TR/wai-aria/roles#role_definitions), point towards the HTML 4 spec; these should be updated to point to HTML 5 spec.

There are also some that point to old HTML 5 documents; these should also be updated.

See for example the [`separator` role](http://www.w3.org/TR/wai-aria/roles#separator).

**Comment by momdo** [comment]
We should update following links.

**in section 5.4:**
button (role):
http://www.w3.org/TR/html4/interact/forms.html#edef-BUTTON
-> https://www.w3.org/TR/html5/forms.html#the-button-element

checkbox (role):
HTML input[type="checkbox"]
http://www.w3.org/TR/html401/interact/forms.html#edef-INPUT
-> https://www.w3.org/TR/html5/forms.html#checkbox-state-%28type=checkbox%29

columnheader (role):
th[scope="col"]
http://www.w3.org/TR/html4/struct/tables.html#edef-TH
-> https://www.w3.org/TR/html5/tabular-data.html#attr-th-scope-col

combobox (role):
http://www.w3.org/TR/html401/interact/forms.html#edef-SELECT
-> https://www.w3.org/TR/html5/forms.html#the-select-element

form (role):
http://www.w3.org/TR/html401/interact/forms.html#edef-FORM
-> https://www.w3.org/TR/html5/forms.html#the-form-element

grid (role):
http://www.w3.org/TR/html4/struct/tables.html#edef-TABLE
-> https://www.w3.org/TR/html5/tabular-data.html#the-table-element

gridcell (role):
http://www.w3.org/TR/html4/struct/tables.html#edef-TD
-> https://www.w3.org/TR/html5/tabular-data.html#the-td-element

group (role):
http://www.w3.org/TR/html401/interact/forms.html#edef-FIELDSET
-> https://www.w3.org/TR/html5/forms.html#the-fieldset-element

heading (role):
http://www.w3.org/TR/html4/struct/global.html#edef-H1
http://www.w3.org/TR/html4/struct/global.html#edef-H2
http://www.w3.org/TR/html4/struct/global.html#edef-H3
http://www.w3.org/TR/html4/struct/global.html#edef-H4
http://www.w3.org/TR/html4/struct/global.html#edef-H5
http://www.w3.org/TR/html4/struct/global.html#edef-H6
-> https://www.w3.org/TR/html5/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements

img (role):
http://www.w3.org/TR/html401/struct/objects.html#edef-IMG"
-> https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element

link (role):
http://www.w3.org/TR/html401/struct/links.html#edef-LINK
-> https://www.w3.org/TR/html5/document-metadata.html#the-link-element

list (role):
http://www.w3.org/TR/html4/struct/lists.html#edef-UL
-> https://www.w3.org/TR/html5/grouping-content.html#the-ul-element
http://www.w3.org/TR/html4/struct/lists.html#edef-OL
-> https://www.w3.org/TR/html5/grouping-content.html#the-ol-element

list (role):
http://www.w3.org/TR/html401/interact/forms.html#edef-SELECT
-> https://www.w3.org/TR/html5/forms.html#the-select-element

listitem (role):
http://www.w3.org/TR/html4/struct/lists.html#edef-LI
-> https://www.w3.org/TR/html5/grouping-content.html#the-li-element

option (role):
http://www.w3.org/TR/html4/interact/forms.html#edef-OPTION
-> https://www.w3.org/TR/html5/forms.html#the-option-element

radio (role):
input[type="radio"]
http://www.w3.org/TR/html401/interact/forms.html#edef-INPUT
-> https://www.w3.org/TR/html5/forms.html#radio-button-state-%28type=radio%29

region (role):
HTML Frame
http://www.w3.org/TR/html401/present/frames.html#edef-FRAME
->  ??
Note: <a href="https://www.w3.org/TR/html5/obsolete.html#frame">frame element</a> is obsolete.

roletype (abstract role):
HTML link (rel &amp; rev)
http://www.w3.org/TR/html401/struct/links.html#edef-LINK
-> https://www.w3.org/TR/html5/document-metadata.html#attr-link-rel ?
Note: <a href="https://www.w3.org/TR/2016/WD-html51-20160310/obsolete.html#element-attrdef-link-rev">rev attrbute</a> is obsolete.

row (role):
http://www.w3.org/TR/html4/struct/tables.html#edef-TR
-> https://www.w3.org/TR/html5/tabular-data.html#the-tr-element

rowgroup (role):
HTML thead, tfoot, and tbody
http://www.w3.org/TR/html4/struct/tables.html#edef-TBODY
-> https://www.w3.org/TR/html5/tabular-data.html#the-thrad-element
-> https://www.w3.org/TR/html5/tabular-data.html#the-tfoot-element
-> https://www.w3.org/TR/html5/tabular-data.html#the-tbody-element

rowheader (role):
HTML th[scope="row"]
http://www.w3.org/TR/html4/struct/tables.html#edef-TH"
-> https://www.w3.org/TR/html5/tabular-data.html#attr-th-scope-row

separator (role):
http://www.w3.org/TR/html401/present/graphics.html#edef-HR
-> https://www.w3.org/TR/html5/grouping-content.html#the-hr-element

textbox (role):
http://www.w3.org/TR/html4/interact/forms.html#edef-TEXTAREA
-> https://www.w3.org/TR/html5/forms.html#the-textarea-element
HTML input[type="text"]
http://www.w3.org/TR/html4/interact/forms.html#edef-INPUT
-> https://www.w3.org/TR/html5/forms.html#text-%28type=text%29-state-and-search-state-%28type=search%29

**in section 6.4:**
aria-describedby (property):
>Label in HTML [XHTML11]

-> ??

aria-label (property):
> (e.g., the <cite><a href="http://www.w3.org/TR/html401/struct/global.html#adef-title">title attribute in <abbr title="Hypertext Markup Language">HTML</abbr></a></cite> [<cite><a href="#bib-HTML401" class="bibref">HTML401</a></cite>]),

-> https://www.w3.org/TR/html5/dom.html#the-title-attribute

**in section 5.1.4:**
>For example, the checkbox defined in this document has similar functionality and anticipated behavior to a <a href="http://www.w3.org/TR/html4/interact/forms.html#checkbox">checkbox defined in <abbr title="Hypertext Markup Language">HTML</abbr></a>.

-> https://www.w3.org/TR/html5/forms.html#checkbox-state-%28type=checkbox%29

**Comment by michael-n-cooper** [comment]
Moving to ARIA 1.2. This is quasi-editorial but tricky discussion, and we might move to ARIA 2.0 or stop referencing base concepts.

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by joanmarie** [comment]
I'm not seeing any base concepts pointing to HTML4. So my conclusion is we fixed this as part of some other work and forgot about there being an issue here related to it.

Closing as fixed.
