### ISSUE TITLE
Inherited States and Properties Question 

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#1297]
For ARIA roles and attribute specs there is a table row called ‘Inherited States and Properties’. What or where are these state and properties inherited from?

https://www.w3.org/TR/wai-aria-1.1/#banner

For example the banner (role) has Inherited States and Properties:

aria-atomic
aria-busy (state)
aria-controls
aria-current (state)
aria-describedby
aria-details
aria-disabled (state)
aria-dropeffect
aria-errormessage
aria-expanded (state)
aria-flowto
aria-grabbed (state)
aria-haspopup
aria-hidden (state)
aria-invalid (state)
aria-keyshortcuts
aria-label
aria-labelledby
aria-live
aria-owns
aria-relevant
aria-roledescription

**Comment by JAWS-test** [comment]
https://www.w3.org/TR/wai-aria-1.1/#inheritedattributes
