### ISSUE TITLE
Can a complementary landmark be nested inside the main landmark

### ISSUE THREAD

**Issue by jha11y** [w3c/aria#1302]
I'm seeking clarification if a complementary landmark can be nested in the main landmark.

https://www.w3.org/TR/wai-aria-practices/examples/landmarks/complementary.html says "complementary landmarks should be top level landmarks (e.g. not contained within any other landmarks).", but SHOULD is not MUST.

The spec is kind of ambiguous: "A supporting section of the document, designed to be complementary to the main content at a similar level in the DOM hierarchy, but remains meaningful when separated from the main content."

**Comment by jongund** [comment]
This seems to be more of an ARIA Authoring Practices issue, than an ARIA issue.  We do not have any nesting requirements in the ARIA specification for landmarks and only guidance in the ARIA practices.

Not sure what the benefit there is to screen reader users for an author to identify information that is complementary to the main content that is already part of the main content.   If a main landmark has identifiable sub-sections, the use of a region landmark with an accessible names describing the sub-section makes more sense to me than a complementary landmark.  Another an important way to identify content in the main landmark is through the use of structured headings in the main landmark to identify the topics.

**Comment by kbunge63** [comment]
I more than agree! To me it makes more sense to identify the content with a region definition and, depending on the content structure, that definition may not be needed at all.

**Comment by jongund** [comment]
Landmarks are really about the screen reader experience to quickly identifty and navigate to the content areas of a website.  Too many landmarks dilutes their utility.

**Comment by jha11y** [comment]
@jongund darn it. I was going to put it there but then I thought it might be better here.  Should I close this issue and open it up in that repo?

I agree with what has been said. I asked this question here "W3C WAI Github" due to duscussions on the WebAIM listserv suggesting that a complementary landmark could be nested in a main landmark.  So I wanted an official ruling.

**Comment by JaninaSajka** [comment]
I believe we have a recent illustration among W3C/WAI AGWG publications. It
was desired to add an Editor's Note at the head of the document Abstract
section. Yet, without the HTML Aside element (and associated attributes) there
was no way for the screen reader user to know where the Editor's Note ends and
the actual Abstract text begins. The markup we settled on was tested and
worked all browsers (except Safari) in the publication: [Challenges with
Accessibility Guidelines Conformance and Testing, and Approaches for
Mitigating
Them](https://www.w3.org/TR/2020/WD-accessibility-conformance-challenges-20200604/#aside).
The point is that not only can it be important to know where the complementary
landmark content begins, but also where it ends.

**Comment by carmacleod** [comment]
@JaninaSajka 
I think that is what [note role](https://w3c.github.io/aria/#note) is intended for.

JAWS announces note role in browse mode, but unfortunately NVDA does not. There is an [open issue for NVDA to report notes in browse mode](https://github.com/nvaccess/nvda/issues/10439), but I don't know when that will be fixed.

**Comment by jongund** [comment]
@jha11y 

I agree close it here and put in the APG issue list.

**Comment by jongund** [comment]
@JaninaSajka 
Thanks for your comment, it makes some very good points.
