### ISSUE TITLE
remove must from note in https://w3c.github.io/aria/#mustContain

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1304]
The note - 	

> NOTE
> An element with a subclass role of the 'required owned element' does not fulfill this requirement. For example, the listbox role requires ownership of an element using the option or group role. Although the group role is the superclass of row, adding an owned element with a role of row will not fulfill the requirement that listbox must own a option or a group.

has a must - notes should not contain RFC keywords

**Comment by carmacleod** [comment]
just delete the word "must"? (and change a -> an)
> ... adding an owned element with a role of row will not fulfill the requirement that listbox own an option or a group.
