### ISSUE TITLE
Question: ARIA 1.2 Spec for aria-label

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#1306]
ARIA 1.1 spec for aria-label under the 'Used in Roles' reads: All elements of the base markup. The same section for aria-label in ARIA 1.2 spec reads'All elements of the base markup except for some roles or elements that prohibit its use'.

Could someone advise where to find a list of roles or elements that prohibit the use of aria-label.

Thanks

**Comment by JAWS-test** [comment]
https://www.w3.org/TR/wai-aria-1.2/#namefromprohibited
