### ISSUE TITLE
APG: Tidy up APG HTML

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#131]
HTML in the APG is a real mess; different tab styles, inconsistent indenting, white space at the end of lines, etc. This is easily solved with a .editorconfig file. Such a file contains settings for your editor that'll fix  these sort of things upon save.

We can add one to the practices folder (as to not interfere with other parts of this repo).

More information on editor config files can be found on the [Editor Config website](http://editorconfig.org/).

**Comment by MichielBijl** [comment]
Related to: https://github.com/w3c/aria/issues/95

**Comment by mcking65** [comment]
One thing I do not like is the html style of format we have where a paragraph is a single line. 

When I am working on an html paragraph, I end up putting every sentence and/or link on a separate line. Then, I join it back together when done. It is a pain. 

As a screen reader user, I like short lines so I do not have to listen to massive chunks of info or navigate through tons of text to get to a spot in the middle. In code, I like separating attributes onto separate lines so I can run through them quickly, skipping to the next one without hearing all of the current one just by pressing down.

I am just fine with any format though if I can style it one way with my editor when working on it and then have it automatically converted into something that other people like. That is a definite plus.

**Comment by MichielBijl** [comment]
You're right Matt, with a lot of attributes lines get crazy long. This doesn't interfere with us manually setting attributes on separate lines.

---

As discussed during the editors call: I will create a PR with an editor config file in the practices directory and some instruction on where to get a plugin for various editors out there.

**Comment by MichielBijl** [comment]
An [EditorConfig file is now provided](https://github.com/w3c/aria/commit/7444f55f4fedcc1df60d4c8ab82cf8bbf2fd48d3).
