### ISSUE TITLE
Add "Editor's Note" about missing element reflection attributes

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1318]
The [IDL Interface section](https://w3c.github.io/aria/#idl-interface) needs an "Editor's Note" about the missing element reflection attributes in the mixin and/or the correspondence table. (To see the Correspondence table, please wait until after https://github.com/w3c/aria/pull/984 is merged).

Here's an [example Editor's Note in combobox](https://w3c.github.io/aria/#combobox) and the corresponding markup on [index.html#L2098](https://github.com/w3c/aria/blob/master/index.html#L2098):
   ```
   <p class="ednote" title="Major Changes to combobox role in ARIA 1.2">
   The Guidance for <rref>combobox</rref> has changed significantly ...
   </p>
   ```

**Comment by carmacleod** [comment]
@domenic 
I'm not quite sure exactly what the note should say. I'm thinking something along the lines of "element reflection is still being defined, and so attributes like `aria-labelledby` that refer to element IDs are not currently shown in this table... for more info, see ??"

**Comment by domenic** [comment]
That makes sense, maybe with a link to some open issues? I think @cookiecrook has the latest status.

**Comment by cookiecrook** [comment]
I think this is no longer needed due to #1755. @jnurthen if you agree, please close.

**Comment by mrego** [comment]
Yeah, now that #1755 has been merged I agree we can close this.

**Comment by pkra** [comment]
Thanks for the reminder.
