### ISSUE TITLE
Reword banner, contentinfo, main to use "on a page" instead of "within any document or application"

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1320]
From https://github.com/w3c/aria/pull/1315#discussion_r485397469

https://w3c.github.io/aria/#banner
https://w3c.github.io/aria/#contentinfo
https://w3c.github.io/aria/#main
> Within any document or application, the author SHOULD mark no more than one element with the ... role.

@mcking65 said:
> Wow is this out of date language. I guess it's been a while since I read it. It does not jive with the definition of role application. And, we do not typically refer to an entire web page as a document in the rest of the spec.

@carmacleod replied:
I agree that "on a page" is easier to understand than "within any document (role) or application (role)" in that sentence.
However, I'm not sure whether the note box that follows that sentence (in banner, contentinfo, and main) needs to be reworded as well:
> NOTE
Because document and application elements can be nested in the DOM, they may have multiple banner elements as DOM descendants, assuming each of those is associated with different document nodes, either by a DOM nesting (e.g., document within document) or by use of the aria-owns attribute.

----
Note also that the wording "document or application" is used in the [abstract section role](https://w3c.github.io/aria/#section), but without the rrefs. Not sure whether that wording should be updated as well.

**Comment by spectranaut** [comment]
This has been fixed: https://github.com/w3c/aria/issues/1320
