### ISSUE TITLE
ARIA specification should have a designated role that allows for non-presentational sub content in interactive list items 

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#1329]
Many business applications have some interactive list variants with selectable items containing non-presentational sub content (buttons, links).

For this reason, the default interactive list mapping (**listbox** with **options**) of these instances would have to be changed to **list** with **listitems**, since listitem as ARIA role

-	allows for being focused (author decision)
-	allows for non-presentational sub content
-	provides count and position information

Doing so, we loose listbox and option attributes like aria-multiselectable and aria-selected. This could be resolved in a workaround using a custom “selected” attribute  (e.g. using aria-describedby) to “mimic” respective option attribute behavior.  

The question is now: **is this is an accepted workaround for those cases?**

But the origin of the problem is that **ARIA specification does not has a designated interactive role or a role specialization that allows for non-presentational interactive sub content in interactive list items.** Therefore the github issue is created here and not in the APG github to emphasize the need for such a role.

Recommending the grid role for this makes no sense since 

-	the items in lists are never editable by default <-> contradicting to grid role definition
-	grid is a two dimensional thing, lists are not (a one column table is not a table but a list)
-	grid requires always a row element in addition <-> classy HTML ul -li

**Comment by scottaohara** [comment]
is this not just another point in the discussion of #1325?  this overlaps with that issue / some things you mentioned on the last call when we were triaging 1325.

**Comment by stes-acc** [comment]
Yes there is overlap. But 1325 is addressing a new specialized List View Role whereas this topic deals with content in list items. If we can resolve both in a common approach, even better.

**Comment by jnurthen** [comment]
This will be covered by https://github.com/w3c/aria/issues/1440
