### ISSUE TITLE
FPWD of ARIA 1.3

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1331]
* [ ] ready for  CFC

## Issues and PRs

* [Issues Open](https://github.com/w3c/aria/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22ARIA+1.3%22)
* [Issues Closed](https://github.com/w3c/aria/pulls?q=is%3Aclosed+is%3Aissue+milestone%3A%22ARIA+1.3%22)
* [PRs Open](https://github.com/w3c/aria/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22ARIA+1.3%22)
* [PRs Merged](https://github.com/w3c/aria/pulls?q=is%3Aclosed+is%3Apr+milestone%3A%22ARIA+1.3%22)
* [PRs in `stable`](https://github.com/w3c/aria/pulls?q=is%3Aclosed+is%3Apr+milestone%3A%22ARIA+1.3%22+label%3A%22merged+to+stable%22)

### Projects

* [x] Outstanding Role Parity issues https://github.com/w3c/aria/projects/8 
* [x] Annotation https://github.com/w3c/aria/projects/7 (cf. below)
* [ ] Attribute Parity https://github.com/w3c/aria/projects/10
  * see also https://github.com/w3c/aria/wiki/Plans-regarding-attribute-parity 
* [ ] Owned Elements https://github.com/w3c/aria/projects/16
* [ ] Tables and Grids https://github.com/w3c/aria/projects/14
* [ ] live regions https://github.com/w3c/aria/projects/13
* [ ] taxonomy stuff https://github.com/w3c/aria/projects/17

Note: a checked item indicates that all 1.3-milestone issues of the project have been closed.

### AOM: Use element reflection for IDREF/IDREF list 

Project: https://github.com/w3c/aria/projects/11

* [ ] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/e182895
  * [ ] Working Draft: TODO
* [x] Core AAM: n/a
* [x] AccName: n/a
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: TODO (Link to issue until implemented)
  * [ ] Gecko: TODO (Link to issue until implemented)
  * [ ] Blink: TODO (Link to issue until implemented)
* [ ] Test Results: TODO

### Add `aria-rowindextext` and `aria-colindextext` 

* [x] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/55a66bc
  * [ ] Working Draft: TODO
* [x] Core AAM:
  * Editor's Draft: https://github.com/w3c/core-aam/commit/f114110 (N.B. needs macOS)
  * Working Draft: TODO
* [x] AccName: n/a
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1075
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: TODO (Link to issue until implemented)
  * [ ] Gecko: TODO (Link to issue until implemented)
  * [ ] Blink: TODO (Link to issue until implemented)
* [ ] Test Results: TODO

### `mark` - `mark` role

* [ ] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/b3017b3
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [x] Editor's Draft: https://github.com/w3c/core-aam/pull/63/
  * [ ] Working Draft: TODO
* [x] AccName: N/A
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1821
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: https://bugs.webkit.org/show_bug.cgi?id=206251
  * [x] Gecko: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/mark_role
  * [x] Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1006767
* [ ] Results: TODO

### `aria-description` property 

* [ ] ARIA:
  * [x] Editor's Draft: 
    * https://github.com/w3c/aria/commit/f262087
    * https://github.com/w3c/aria/commit/8420961 
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [x] Editor's Draft: https://github.com/w3c/core-aam/pull/61
  * [ ] Working Draft: TODO
* [ ] AccName: https://github.com/w3c/accname/issues/69
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1822
* [ ] WPT: TODO
* [ ] Implementations:
  * [x] WebKit: https://bugs.webkit.org/show_bug.cgi?id=206253
  * [x] Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1608961
  * [X] Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1006767
* [ ] Results: TODO

### `comment` role

* [x] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/eed0ef0
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [x] Editor's Draft: https://github.com/w3c/core-aam/pull/63/
  * [ ] Working Draft: TODO
* [ ] AccName: TODO
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1823
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: https://bugs.webkit.org/show_bug.cgi?id=206252
  * [x] Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1608969
  * [x] Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1006767
* [ ] Results: TODO

### `suggestion` role

* [ ] ARIA:
  * [x] Editor's Draft:
    * https://github.com/w3c/aria/commit/2a047fd
    * https://github.com/w3c/aria/commit/48282a0
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [x] Editor's Draft: https://github.com/w3c/core-aam/pull/63/
  * [ ] Working Draft: TODO
* [ ] AccName: TODO
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1824
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: https://bugs.webkit.org/show_bug.cgi?id=206251
  * [x] Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1608965
  * [x] Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1006767
* [ ] Results: TODO
 

### Update `aria-details`

* [ ] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/e8b2274
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [ ] Editor's Draft: TODO
  * [ ] Working Draft: TODO
* [ ] AccName: TODO
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/70
* [ ] WPT: TODO
* [ ] Implementations:
  * [ ] WebKit: TODO
  * [x] Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1608883
  * [ ] Blink: TODO
* [ ] Results: TODO 

### aria-brailleroledescription

* [ ] ARIA:
  * [x] Editor's Draft: 
    * https://github.com/w3c/aria/commit/2048cb523cba955e0161fbbe3fbf90f550805fef
    * https://github.com/w3c/aria/commit/db5a8c5e04031d910e54c4fddda2369e4a56379c
  * [ ] Working Draft: TODO
* [ ] Core AAM: 
  * [ ] Editor's Draft: https://github.com/w3c/core-aam/pull/134
  * [ ] Working Draft: TODO
* [ ] AccName: TODO
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1825
* [ ] WPT: TODO
* [x] Implementations:
  * [x] WebKit: DONE (https://bugs.webkit.org/show_bug.cgi?id=220719, announced in Safari Technology Preview 120)
  * [x] Gecko: DONE (by default // exposes anything aria-*)
  * [x] Chromium: DONE (https://bugs.chromium.org/p/chromium/issues/detail?id=1289234)
  * [x] Orca: DONE https://gitlab.gnome.org/GNOME/orca/-/issues/164
  * [ ] NVDA: https://github.com/nvaccess/nvda/issues/11829
    * [x] brailleRoleDescription https://github.com/nvaccess/nvda/pull/14748
  * [ ] JAWS: https://github.com/FreedomScientific/VFO-standards-support/issues/677
  * [x] VoiceOver (tested: Mac OS 13.2.1)
* [ ] authoring tools
  * [ ] nu validator https://github.com/validator/validator/issues/1453
  * [x] axe-core https://github.com/dequelabs/axe-core/issues/3899
* [ ] Test Results: TODO

### aria-braillelabel

* [ ] ARIA:
  * [x] Editor's Draft: https://github.com/w3c/aria/commit/99763b0cd439762e349d425cc9bf039854f51cbb
  * [ ] Working Draft: TODO
* [ ] Core AAM:
  * [ ] Editor's Draft: https://github.com/w3c/core-aam/pull/134
  * [ ] Working Draft: TODO
* [ ] AccName: TODO
* [ ] Authoring Practices: https://github.com/w3c/aria-practices/issues/1825
* [ ] WPT: TODO
* [ ] Implementations:
  * [x] WebKit: DONE (https://bugs.webkit.org/show_bug.cgi?id=220719, announced in Safari Technology Preview 120)
  * [x] Gecko: DONE (by default // exposes anything aria-*)
  * [x] Chromium: DONE (https://bugs.chromium.org/p/chromium/issues/detail?id=1289234)
  * [x] Orca: DONE https://gitlab.gnome.org/GNOME/orca/-/issues/164
  * [ ] NVDA: https://github.com/nvaccess/nvda/issues/11829
  * [ ] JAWS: https://github.com/FreedomScientific/VFO-standards-support/issues/677
  * [x] VoiceOver (tested: Mac OS 13.2.1)
* [ ] authoring tools
  * [ ] nu validator https://github.com/validator/validator/issues/1453
  * [ ] axe-core https://github.com/dequelabs/axe-core/issues/3899
* [ ] Test Results: TODO

**Comment by jnurthen** [comment]
Need to add some things to master first... What is ready to be merged for 1.3?

**Comment by pkra** [comment]
@jnurthen is it ok if I re-use this issue and edit/update  the top card with various bits of information for 1.3? (E.g., what's been merged into stable, relevant bits from the 1.3 the wiki pages.)

**Comment by jnurthen** [comment]
Sure. Go for it. Thanks.

**Comment by pkra** [comment]
I think I've now caught all merged PRs related to 1.3 issues and added them to the milestone. (From the time of merge, I suspect some of these may already have made it into 1.2 but that doesn't seem problematic to me.) 

Next step is going through the merged editorial PRs and merging them into stable.

**Comment by pkra** [comment]
@jnurthen should we add https://github.com/w3c/aria/wiki/non-parity-1.3-features to the top card here?
