### ISSUE TITLE
Need column header properties for resizable and fixed (frozen) columns in grids

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#1341]
Many data grids have resizable columns (width, by mouse drag or by keyboard special keys operating on column headers). 
Either all columns are resizable in such grids or just some of them (control configuration by app developer).

Data grids with many columns may have horizontal scrollbars that "scroll" the available columns. 
You can chose to "freeze" columns (control configuration, those columns are typically at the beginning) that they are not scrolled.

Currently ARIA has no properties for column headers to reflect these cases. 

Since ARIA is also used in speech output of screen magnifiers, an additional speech hint caused by those properties would be useful for better perception.

**Comment by jnurthen** [comment]
This issue is 3 years old and hasn't had any discussion in that time. I propose closing this. Please reopen with a more specific proposal if needed.
