### ISSUE TITLE
ARIA 1.2 - Combobox button is not associated with the Combobox

### ISSUE THREAD

**Issue by jspurlin** [w3c/aria#1343]
_This is in relation to discussion on [Resolving ARIA 1.1 Combobox Issues](https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues) and evident in the [Combobox With List Autocomplete Example](https://raw.githack.com/w3c/aria-practices/aria1.2-combobox-proposal/examples/combobox/combobox-autocomplete-list.html)_

Both from a semantic and visual standpoint the "menu button" portion of the combobox is not associated with the combobox (e.g. the input, which has `role="combobox"`). If you style the button to visually be connected to the combobox, that only fixes the visual aspect, but not the semantic/accessible representation.

With the current proposed guidance, if the user does AT navigation (e.g. "item navigation" or "virtual navigation"), the AT will stop on the button that is just labelled "open" and has no context what "open" is for... This problem is exacerbated if you think of the scenario where the user queries the AT for the active buttons on the page, now there will just be an "open" button floating around, and it doesn't even have an `aria-expanded` or `aria-haspopup`. This feels very broken and may result in even worse confusion for a subset of users.

The best approach to solve this issue seems to be that the "menu button" portion of the comboBox should be marked as `aria-hidden="true"`, that way the combobox is being fully represented with one element (and is more in line with how the HTML `<select>` element is represented)

**Comment by scottaohara** [comment]
should this be moved to https://github.com/w3c/aria-practices

this seems an issue with the example component, rather than with what's outlined in the ARIA spec.

**Comment by carmacleod** [comment]
@jspurlin 
Please see: https://github.com/w3c/aria-practices/issues/1375
Feel free to add a comment to that issue.
Also, please note that the current version of that example is here:
https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-list.html

Closing this issue.
