### ISSUE TITLE
Why does menuitemradio inherit from menuitemcheckbox?

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1347]
It seems a little odd that `menuitemradio` inherits from `menuitemcheckbox`, but that `radio` doesn't inherit from `checkbox`. I tried to find the answer in the spec and the only indication is a "(see structure)" text next to the superclass listing. If there's a reason for this difference, it would be good to explain it in the description of the role. If not it might be worth changing the inheritance so it is consistent.

**Comment by carmacleod** [comment]
I agree that it is definitely odd. It is because folks didn't want to support aria-expanded on radio.
Some discussion in this issue https://github.com/w3c/aria/issues/1277 and its corresponding PR https://github.com/w3c/aria/pull/1278

**Comment by JAWS-test** [comment]
> It is because folks didn't want to support aria-expanded on radio (but they were ok with it on menuitemradio).

I don't understand the argument. menuitemradio could have menuitem as superclass role instead of menuitemcheckbox. aria-expanded would then inherit it from menuitem and everything would be ok

**Comment by carmacleod** [comment]
People wanted to remove the multiple inheritance.
However, I believe we could just have `menuitemradio` subclass `menuitem` directly, and make it support `aria-checked`.
That would probably make the structure clearer (and more consistent).
I'll add the "agenda" label to discuss this possibility.

**Comment by jnurthen** [comment]
PR welcome for the change @carmacleod suggested above.
