### ISSUE TITLE
planar role for representing 2D and 3D position

### ISSUE THREAD

**Issue by ckundo** [w3c/aria#1363]
For consideration, a `planar` role for representing position of an element along multiple axes. Something like [`slider`](https://www.w3.org/TR/wai-aria-1.1/#slider) but with 2 or 3 directions. This would support communicating semantics of 2D and 3D canvas contents. could also be `<input type='planar' ...`.

```
<div role='planar' 
  aria-min-x='0'
  aria-max-x='1000'
  aria-current-x='520'
  aria-min-y='0'
  aria-max-y='800'
  aria-current-y='300'
  aria-label='sphere'>
</div>
```

changes to different axes would be announced by AT atomically.

currently this can be approximated with two elements:

```
  <div id="notices" aria-live="polite">
    <input id="position-x" type="number" value="0" max="1000" min="0" aria-label="X" />
    <input id="position-y" type="number" value="0" max="800" min="0" aria-label="Y" />
  </div>
```

**Comment by carmacleod** [comment]
See also: https://github.com/w3c/aria/issues/432

**Comment by jnurthen** [comment]
@ckundo we're going to close this and move discussion to #432 but I'll update that do make it more generic
