### ISSUE TITLE
What happens if aria-activedescendant points to an invisible node?

### ISSUE THREAD

**Issue by minorninth** [w3c/aria#1364]
The current specification describes what should happen when the focused node has an aria-activedescendant pointing to another valid element. However, what if that node is invisible (css visibility:hidden or display:none)?

Chrome currently has some logic to ignore the active descendant in that case - and when the active descendant later becomes visible it's treated as a change to the active descendant and/or focus.

The reason this can be useful is in the case of a collapsed combobox. We've seen cases where the combobox has aria-activedescendant set to an ID of an option element, even though it's hidden. When the user expands the combobox and the listbox and its options become visible, Chrome then exposes the active descendant as the focused node.

If this seems reasonable, let's add it to the specification.

If not, we can try changing our implementation.

**Comment by joanmarie** [comment]
I moved this to ARIA because the opening report does not sound like this is a platform-specific issue.

**Comment by accdc** [comment]
Hi Dominic, that sounds exactly like how I would expect it to behave. I also support specifically documenting this within the spec to take the guesswork out of it.

**Comment by accdc** [comment]
I pressed the wrong button and closed this. If it still needs to be open, please reopen the ticket.
