### ISSUE TITLE
Consider whether or not to change markup for left and right pointing arrows

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1368]
The Required Owned Elements characteristic for certain container roles specifies that its items can be grouped.
For example, one of the Required Owned Elements for `listbox` is `group → option`.

The markup to denote this currently uses a right-pointing arrow character in an `abbr` element with `title="containing"`, as follows:
```
<abbr title="containing" class="symbol">→</abbr>
```

After https://github.com/w3c/aria/pull/1359 is merged, the Required Context Role characteristic for "groupable" item roles will also use similar markup, except with a left-pointing arrow character in an `abbr` with `title="contained by"`:
```
<abbr title="contained by" class="symbol">←</abbr>
```

For example, one of the Required Context Roles for `option` is `group ← listbox`.

Unfortunately, [abbr with title is problematic in screen readers](https://www.powermapper.com/tests/screen-readers/labelling/acronym-abbr-title/). At best, the screen reader will say "right-pointing arrow" or "left-pointing arrow" (some screen readers have a setting for reading the title, but it is not the default).

This issue is to determine whether we should change this markup or leave it alone.
Random thoughts:
- if we wrap the arrow character in an aria-hidden span, do screen readers fall back to reading the title because there's no content?
- should we delete the abbr markup completely and just go with the text "containing" and "contained by"?

**Comment by carmacleod** [comment]
For those who may be wondering what the visual effect of simply dropping the arrow and going with the words would be, here's Required Owned Elements for listbox:

1. Using right pointing arrow for group -> option:
![image](https://user-images.githubusercontent.com/3331913/102507262-0af11600-4052-11eb-8ab1-cfa8eda8134a.png)

2. Using the word "containing" for group containing option:
![image](https://user-images.githubusercontent.com/3331913/102508172-1bee5700-4053-11eb-9874-e77e0d54b75d.png)

Using words looks totally fine to me. It's probably clearer for everyone.

**Comment by JAWS-test** [comment]
> Using words looks totally fine to me. It's probably clearer for everyone.

+1

**Comment by pkra** [comment]
> should we delete the abbr markup completely and just go with the text "containing" and "contained by"?

+1
