### ISSUE TITLE
Deprecate aria-level on listitem

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#1369]
The authoring practices task force has attempted multiple times to generate some kind of example of use of aria-level on listitem elements. We've not found a scenario that justifies doing so. In our March 31, 2020 meeting, we [concluded that we should suggest removing support for it](https://github.com/w3c/aria-practices/pull/1109#issuecomment-606857847).

The scenario that came closest to seeming reasonable is when the DOM does not contain all elements of a large nested list. However, unless the DOM is going to contain invalid HTML, even this scenario does not dictate the need for aria-level. It can certainly lead to the need for aria-setsize and aria-posinset, but the structure needed to calculate aria-level would need to be present. The only possible exception would be when the DOM contains a complete list that is not nested in another list but the author wishes it to be conveyed as a nested list. Realistically, though, whatever the author does to convey that nesting to non-AT users would also need to be exposed to AT users. Additionally, the value to the end user of AT is dubious. It is more likely to be confusing to add aria-level in such a scenario.

**Comment by WilliamTennisNFCU** [comment]
I will take this one. @michael-n-cooper

**Comment by WilliamTennisNFCU** [comment]
@michael-n-cooper @jnurthen I made the change on a branch that I created, but I can't push. I think I need push privs?

**Comment by pkra** [comment]
@WilliamTennisNFCU you can push to your own fork of the repository and then make a pull request from the fork to the main repository.

**Comment by jnurthen** [comment]
@WilliamTennisNFCU we need to get you into the w3c organization in order to add you to aria contributors team. @michael-n-cooper can you please make this happen. This goes for anyone else who is in the working group who is having difficulties. I thought this was sorted because I could assign you to the issue but apparently not as I can't add you to the team.

**Comment by WilliamTennisNFCU** [comment]
@jnurthen @michael-n-cooper For clarity, we want to fully remove this aria-level from the listitem, correct?
