### ISSUE TITLE
SVG-AAM: Issues with the use of title attribute in name and description calculation

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#137]
Section [10.1 Name and Description](https://rawgit.com/w3c/aria/master/svg-aam/svg-aam.html#mapping_additional_nd) has a couple of references to the "`xml:title` attribute". From some quick searching, I have yet to find any reference to that attribute; I have, however, found references and documentation for `xlink:title`. Typo?

**Comment by Joanmarie** [comment]
(I just found another potential issue with the same section and same(?) attribute, so I'll mention it here.)

Item 2 states:

> Replace [step 2D](http://w3c.github.io/aria/accname-aam/accname-aam.html#step2D) with the following:

> [...]
> If performing a text alternative computation for an accessible description:
> * If the current node has at least one direct child `desc` element, select the appropriate description based on the language rules for the SVG specification, and return the concatenated text content of the description.
> * If the current node is a `use` element, and there was no child `desc` element, but it has a valid `href` or `xlink:href` attribute pointing to another element in the same document, set the current node to the referenced element and compute the text alternative from step 2 as if that element had been referenced with `aria-describedby`.

With this in mind, consider the following example (taken from the in-progress testable statements):

      // aria-label, xlink title
      if given `<a id="test" aria-label="booth" href="../index.html" xlink:title="table" ></a>` then accessible description = "table"

Given the replaced step 2D text above:

* The current node (the `a` element) does not have at least one direct child `desc` element.
* The current node (the `a` element)  is not a `use` element.

So as I understand it, we can't get the description for the current node using step 2D.

One possibility (I _believe_) might be to keep/apply/whatever the original 2D text as a fallback. That text states:

> Otherwise, if the current node's native markup provides an attribute or element that defines a text alternative, return that alternative as a flat string, unless the element is marked as presentational (role="presentation" or role="none").

So if the `xlink:title` attribute "defines a text alternative" (arguably it does), it could be used.

If that is not an appropriate solution, then perhaps 2H applies -- though it would need to be tweaked slightly. The current text is:

> Otherwise, if performing a text alternative computation for an accessible description, and the current node has at least one direct child `title` element, but the title elements were not used when generating the accessible name for the node, then select the appropriate title based on the language rules for the SVG specification, and return the title text content as the description.

In the example above, there is not the required "one direct child `title` element," but there is an attribute on the current node providing the title. And the title text from the attribute isn't being used for the name....

**Comment by fredesch** [comment]
Amelia, said this was a typo and updated.

**Comment by Joanmarie** [comment]
Another question and possible issue: If we're to support SVG2, should there be explicit text in the SVG AAM regarding multiple `title` and `desc` elements, which are now allowed according to [4.5. The ‘desc’ and ‘title’ elements](https://www.w3.org/TR/SVG2/struct.html#DescriptionAndTitleElements)?

**Comment by fredesch** [comment]
Created issue 1006 https://www.w3.org/WAI/PF/svg-a11y-tf/track/issues/1006

**Comment by Joanmarie** [comment]
Another one for you. The tests in the wiki include:

> if given `<circle id="test" aria-label="bob" cx='50' cy='100' r='15'><title>bob</title></circle>` then accessible description = BLANK

But in the [SVG AAM's Name and Description](https://rawgit.com/w3c/aria/master/svg-aam/svg-aam.html#mapping_additional_nd), the spec states:

> Otherwise, if performing a text alternative computation for an accessible description, and the current node has at least one direct child title element, but the title elements were not used when generating the accessible name for the node, then select the appropriate title based on the language rules for the SVG specification, and return the title text content as the description.

Taking the spec as written and the test case above: The accessible name came from `aria-label="bob"` ([Step 2C of the Core ACCName AAM](https://w3c.github.io/aria/accname-aam/accname-aam.html#mapping_additional_nd_te)); NOT from the `title` element. Thus according to the spec text quoted above, because there is at least one direct child `title` element which was not used when generating the accessible name, user agents should return the title text content as the description.

Either the test expectations are incorrect or the spec needs some clarifying language.

If you believe the test expectations are correct, the new clarifying language should probably take into account things like the strings being different, but only with respect to case and/or whitespace.  (i.e. to what degree are user agents expected to judge "sameness" in author-provided strings?)

**Comment by fredesch** [comment]
Joanie,

Good point about clarifying language. I will bring it up at the next task
force meeting.  I am pretty sure we don't want an accessible description
that is the same as the accessible name.

As background, I wrote the testable statements using Amelia's branch. The
text in the note about the accessible description is clear (bold red is my
emphasis).

The alternative text values for the accessible description have the
following priority:
1.	aria-describedby
2.	a direct child desc element
3.	for a use element, the accessible description calculated for the
re-used content
4.	a direct child title element that provides a tooltip, when ARIA label
attributes are used to provide a different accessible name
5.	for an a element, the xlink:title attribute, when it is not the
accessible name


The testable statements include three tests that apply to step 4.  The
first has a title content that is different than the accessible name, the
latter two tests have the same title content as the accessible name. None
of the tests differ by whitespace or capitalization.

// description aria-label, title
if given <circle id="test" aria-label="bob" cx='50' cy='100'
r='15'><title>abc</title></circle> then accessible description = "abc"


Title is same as accessible name
// aria-labelledby, title
if given <circle id="test" aria-labelledby="t1" cx='50' cy='100'
r='15'><title>abc</title></circle><text id="t1" x="40" y="90">abc</text>
then accessible description = BLANK

// aria-label, title
if given <circle id="test" aria-label="bob" cx='50' cy='100'
r='15'><title>bob</title></circle> then accessible description = BLANK


                                                              
     Regards,                                                 
                                                              
    Fred Esch                                                 
 Watson, IBM, W3C                                             
  Accessibility                                               
                                                              
 IBM Watson       Watson Release Management and Quality

**Comment by Joanmarie** [comment]
> Good point about clarifying language. I will bring it up at the next task force meeting.  I am pretty sure we don't want an accessible description that is the same as the accessible name.

Thanks! A related discussion (perhaps) belongs in the ARIA WG because I myself don't see any good reason why this is an SVG-specific issue. (If it is, my apologies.)

> None of the tests differ by whitespace or capitalization.

I know. And apologies for being unclear. Please allow me to try again:

1. Given an element with `aria-label="bob"` and `<title>Bob</title>`, is the expected description "Bob" because "bob" is not the same as "Bob"?
2. Given an element with  `aria-label="bob"` and `<title> bob</title>`, is the expected description " bob" because "bob" is not the same as " bob"?

And I don't know if the answer to the above two questions is "yes" or "no." I could make a case for either: On the one hand, the those values are indeed different; on the other hand, at least for a speech-only screen reader user with capitalization indication set to pitch, they will for all intents and purposes be the same.

You stated:

> 4\. a direct child title element that provides a tooltip, when ARIA label attributes are used to provide a different accessible name

What constitutes a "different accessible name"? If the only difference is whitespace, is the name different? If the only difference is capitalization, is the name different?

**Comment by fredesch** [comment]
Joanie, the xml:titles have been replaces with xlink:title with latest commit

**Comment by fredesch** [comment]
Only meant to add comment.  other parts of issues are still open...

**Comment by AmeliaBR** [comment]
With the [latest commit](https://github.com/w3c/aria/commit/4cb2a9184d6354c6861d65c7eda0a048f7709794) (not yet merged to master), most of the issue raised here should be addressed.

Summing up the issues raised in this thread:

[x] [xml:title should be xlink:title.](#issue-126234699)  Just a typo, already fixed.
[x] [xlink:title not given as a fallback option for accessible description.](#issuecomment-171006315) I've added an extra paragraph to step 2H in the latest edits, so this would be the final fallback (lower priority than a child `<title>` element).
[x] [clarify language re multilingual title/desc elements](#issuecomment-173055415). For inclusion/exclusion rules, we make clear that it is included if there is at least one element, regardless of language. For name and description, we use the phrase "select the appropriate [title/description] based on the language rules for the SVG specification". I don't want to get more specific than that, since the SVG specs may change.
[x] [Clarify the note on description fallback priority](#issuecomment-174578387). Pending any further clarifications in the CORE-AAM, I've re-written to remove any suggestion that user agents need to test the actual string value. The only test is whether the title has already been used for the accessible name. Gets rid of any complication with respect to redundant content.
[] Update the testable statements to match these clarifications. 

@FredEsch, could you check whether the problematic tests Joanie highlighted are still there?

In the specific example:

>if given `<circle id="test" aria-label="bob" cx='50' cy='100' r='15'><title>bob</title></circle>` 

Both the accessible name and description would be "bob".  But the test as a whole can be dropped, since it was testing a distinction that was not in the normative parts of the spec.

**Comment by fredesch** [comment]
We think everything has been addressed.
