### ISSUE TITLE
respec-w3c-common is deprecated; migrate to respec-w3c

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1379]
At some point soon-ish, we should migrate all of the ARIA specs to respec-w3c (instead of respec-w3c-common).

Here's the warning message in the Console:
> "respec-w3c-common" profile has been deprecated in favor of the "respec-w3c" profile and will not receive any future updates, including the support for W3C 2020 process. [Please migrate to "respec-w3c" profile](https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide).

Note that the [migration guide](https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide) says:
> The respec-w3c profile contains security, performance, and new features plus support for the W3C's 2020 Process and future W3C Process/template updates. As such, it's highly recommended that you do upgrade.

I believe we need to remove jQuery first? (Or maybe include it ourselves? [Edit: actually, looks like we already include it?])
How much work would it be to [remove jQuery](https://github.blog/2018-09-06-removing-jquery-from-github-frontend/)?

See also: https://github.com/w3c/respec/issues/2889

Note that issue https://github.com/w3c/aria-common/issues/53 seems to be related to deprecated ReSpec events, so it may be appropriate to update ARIA's use of ReSpec events as well.

**Comment by carmacleod** [comment]
@schne324 is going to take a crack at removing jQuery first. Thank-you so much, Harris!

**Comment by jnurthen** [comment]
this is complete
