### ISSUE TITLE
HTML-AAM: audio UIA should have localized control type

### ISSUE THREAD

**Issue by cyns** [w3c/aria#138]
control type: group
localized control type: Audio

if @controls is present, each control is a child in the UIA tree, and mapped to button, range, etc. as appropriate for the type of control.

**Comment by jasonkiss** [comment]
See above commit. Tweaked sentence re @controls as follows, linking "button" and "slider" to relevant aria role mappings: "If the controls attribute is present, each control is a child in the UIA tree, and mapped as button, slider, etc. as appropriate for the type of control." If incorrect, let me know and will tweak further.

**Comment by cyns** [comment]
looks good. thanks.
