### ISSUE TITLE
Refactor jQuery out of ARIA editorial documents

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1380]
Related to (subtask or pretask?) #1379

**Comment by cookiecrook** [comment]
@michael-n-cooper @carmacleod and @jnurthen mentioned specific repo locations, but I missed those details

**Comment by jnurthen** [comment]
@schne324 please ping me and I'll talk you through the logic as I understand it

**Comment by carmacleod** [comment]
@schne324 
The file that @michael-n-cooper was referring to as using jQuery is:
https://github.com/w3c/aria-common/blob/master/script/mapping-tables.js

Two of the ARIA specs that use this file are CORE-AAM and HTML-AAM - I think other AAM's may use it as well.

This file (along with other aria-common files) is copied over to the common folder in each of the ARIA specs, so you will want to eventually merge your changes into the aria-common repo.

For testing, however, you will probably want to edit the file directly in the common folder of the spec you are testing.

I noticed the following 2 files in the aria-common/script folder:
https://github.com/w3c/aria-common/blob/master/script/jquery-1.9.0.min.js
https://github.com/w3c/aria-common/blob/master/script/jquery.details.min.js

These don't seem to be included in the ARIA spec itself, so any jQuery in the ARIA spec must be coming from the old ReSpec (which we need to remove in #1379).

The AAM specs seem to include jQuery in a couple of places.

CORE-AAM:
```html
<script src="https://www.w3.org/scripts/jquery/1.11.3/jquery.min.js"></script>  // hardcoded link included before ReSpec
...
<script src="common/script/jquery.details.min.js"></script>  // relative link, included after respecConfig is defined
```

HTML-AAM
```html
<script src="https://www.w3.org/scripts/jquery/2.2.4/jquery.min.js"></script>  // hardcoded link included before ReSpec
...
<script src="script/jquery.details.min.js"></script>  // relative link
```

**Comment by schne324** [comment]
@jnurthen I'm pretty sure everything here has been resolved. Can we close this ticket?

**Comment by jnurthen** [comment]
Yes. Thanks so much for your work on this.
