### ISSUE TITLE
Misleading note about AT changing aria attrs.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1394]
From https://w3c.github.io/aria/#ua_domchanges

```html
<p class="note">Many state and properties can be changed by assistive technologies through existing accessibility APIs by responding to a default action event. For example, the <sref>aria-selected</sref> state of a <rref>tab</rref> in a <rref>tabpanel</rref> can be changed by triggering the default action on the element.</p>
```

I don't think this is actually true. The AT just triggers the default action... That may convey user intent, but the AT isn't actually changing anything. The web app makes the change in response to the "intent."

We could reword or remove the note. Leaning toward remove, b/c I'm not sure it adds anything useful.

**Comment by cookiecrook** [comment]
Note: To avoid conflicts, I'm not going to change the "states and properties" in this one to "attributes" re: #1393. In this case, it's also a little bit ambiguous if the prose is referring to API "states and props" or ARIA content "attributes." An edit could also modify that to be more clear.

**Comment by carmacleod** [comment]
Agree that the note is not useful, and should just be removed.
