### ISSUE TITLE
role=img should allow accName other than aria-label or aria-labelledby

### ISSUE THREAD

**Issue by mitchellevan** [w3c/aria#1398]
Requested change:

I'm requesting `role=img` be edited to use @mcking65's phrase from pull request #785 comments: _authors MUST provide a label, which can be done with the aria-label or aria-labelledby attribute_

This was in response to @carmacleod's draft in issue #783 comments: _In order for elements with a role of img to be perceivable, authors MUST provide a label determined by the accessible name calculation._

Currently:

The ARIA spec for `role=img` currently says, "authors MUST provide a label using the aria-label or aria-labelledby attribute."

However, in some cases `role=img` can get its accessible name from a name from author mechanism, without actually using either `aria-label` or `aria-labelledby`. The ARIA spec should not prohibit these cases.

1. [ARIA in HTML](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties) allows `role=img` on an `<iframe>` element, which can get its accessible name from a `title` attribute.
2. `role=img` is "NOT RECOMMENDED" for an `<img>` element, but a valid reason may exist to use it, such as @scottaohara's [workaround for a Safari bug](https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html#image-elements-with-svg-source-exception). In this case the `alt` attribute of an `<img>` can still provide its accessible name.

**Comment by JAWS-test** [comment]
role=img is allowed for other HTML elements that can be labeled with the title attribute. Furthermore, role=img is allowed on SVG graphics that can be [labeled with the title element or per text content](https://www.w3.org/TR/svg-aam-1.0/#mapping_additional_nd)

**Comment by mitchellevan** [comment]
> role=img is allowed for other HTML elements that can be labeled with the title attribute.

I agree. This is not a coding best practice, but it should not fail ARIA validation.

> Furthermore, role=img is allowed on SVG graphics that can be labeled with the title element or per text content

When you say "labeled with," if you mean...
```html
<svg role="img" aria-labelledby="svg-title">
    <title id="svg-title">HTML5 logo</title>...
</svg>
```
... then that's a true statement, but not relevant to this issue, because it already passes with or without my proposed edit.

If you mean without `aria-labelledby`, then that is not a true statement because `role=img` does not allow name from content (notwithstanding issue #1330).

**Comment by JAWS-test** [comment]
> If you mean without aria-labelledby, then that is not a true statement because role=img does not allow name from content 

Yes, I meant that. And the title element is not "name from content", but "name from author". I think that here the [AccName specification is unclear](https://github.com/w3c/accname/issues/108) if within role=presentation labeling with author elements like label, title, caption etc. should be possible or not

**Comment by mitchellevan** [comment]
You're right @JAWS-test, my mistake. A `<title>` does name `<svg role="img">`. Thanks for adding these examples, which support the value of my proposed edit.
