### ISSUE TITLE
deep dive on "owned"

### ISSUE THREAD

**Issue by pkra** [w3c/aria#1423]
While prepping last week's meeting, I had created a project board trying to gather up issues around "ownership", https://github.com/w3c/aria/projects/16. 

There are couple of 1.3 blocking issues, a couple of PRs (which have stalled). Maybe a deep dive can move things forward.

**Comment by jnurthen** [comment]
Proposed deep dive on this on Thursday 18 March, 2021

**Comment by jnurthen** [comment]
closing this as we made good progress on understanding.
