### ISSUE TITLE
code role is not in a category

### ISSUE THREAD

**Issue by MarcelloPaiva** [w3c/aria#1432]
In section 5.3 of the WAI-ARIA 1.2 spec, [Categorization of Roles](https://www.w3.org/TR/wai-aria-1.2/#roles_categorization), I noticed that the `code` role is not listed under any of the categories. I don't think this is intentional, and I think it makes perfect sense for `code` to be in the Document Structure Roles category.

**Comment by jnurthen** [comment]
#1400
