### ISSUE TITLE
Suggestion: aria-hidden="true" should make focusable elements and their descendants un-focusable

### ISSUE THREAD

**Issue by ianthedev** [w3c/aria#1434]
One of the use cases is "a special table whose table body is scrollable and each of its static table headers also has a search box". Basically, the table headers remain static and the table body has a vertical scrollbar, and each table header also has a search box for searching for matching table rows.

An approach is creating a cloned table with `aria-hidden="true"` and using it as static table headers (its table body is made inaccessible with CSS `visibility: hidden`). And the original table serves as the scrollable table body (its table headers are made unseen with negative `margin-top`). This also involves wrapping both tables with `<div>`s and further CSS codings, but I'm not going into details here.

Although screen reader users can use the original table normally, the cloned table's search boxes are still focusable to screen readers, causing unexpected confusions. This issue could be solved if `aria-hidden="true"` makes the cloned table's descendants un-focusable to screen readers.

Incidentally, it appears that there also needs to be a way to make the original table's unseen headers inaccessible to sighted keyboard users, otherwise sighted keyboard users would still focus the search boxes in the unseen table headers, causing unexpected confusions.

**Comment by JAWS-test** [comment]
This is not possible because the browser does not know, or should not know, whether a screen reader is being used. Instead: aria-hidden=true must never contain focusable elements

**Comment by ianthedev** [comment]
> 
> 
> This is not possible because the browser does not know, or should not know, whether a screen reader is being used. Instead: aria-hidden=true must never contain focusable elements

Thanks for the advice. Then I came up with a potential alternative: not using `aria-hidden="true"` at all and making the original table's headers inaccessible with CSS `visibility: hidden`. Basically, now only the cloned table's headers and the original table's body are accessible.

But that brings another problem: the table headers and the table body now belong to different tables, respectively. Under such a condition, is it possible to make screen reader users use the tables normally as if they are using one single table?

**Comment by JAWS-test** [comment]
> is it possible to make screen reader users use the tables normally as if they are using one single table?

Yes, this is possible with the ARIA roles for tables. See https://www.w3.org/TR/wai-aria-practices-1.2/#table and https://www.w3.org/TR/wai-aria-1.2/#table. The HTML table elements that are not needed and do not get an ARIA role must then be marked with role=presenation

**Comment by JAWS-test** [comment]
See https://adrianroselli.com/2020/01/fixed-table-headers.html

**Comment by JAWS-test** [comment]
In HTML 2 tables, but for a screen reader only one table:

```
<div role=table>
	<table role=presentation>
		<tr role=row>
			<th role=columnheader>1
			<th role=columnheader>2
		</tr>
	</table>
	<table role=presentation>
		<tr role=row>
			<td role=cell>3
			<td role=cell>4
		</tr>
	</table>
</div>	
```

**Comment by ianthedev** [comment]
> In HTML 2 tables, but for a screen reader only one table:

Thank you very much! That's a brilliant solution!
