### ISSUE TITLE
"Accessible Name Required:" is not used consistently

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1437]
"Accessible Name Required:" some roles have false, some have true and some have nothing. It is unclear what applies if nothing is written.

My suggestion:

* set all roles to true or false OR
* mark only the roles with true

**Comment by JAWS-test** [comment]
Closed, because part of https://github.com/w3c/aria/issues/1466

**Comment by scottaohara** [comment]
thanks/sorry for the overlap @JAWS-test
