### ISSUE TITLE
Consider ARIA role for draggable resize handles

### ISSUE THREAD

**Issue by ashfordneil** [w3c/aria#1443]
Setting the `resize` property in CSS for an element (to a value other than `none`) creates a handle that can be used to resize the element. In applications that want to emulate that resize functionality, but require custom logic, often dedicated elements are added to the page to control resizing. These elements respond to click and drag events in a way that is similar to browser-native resize handles, but there is no clear documentation on how to make them either controllable via the keyboard, or accessible via a screen reader / other assistive technologies.

Keyboard control should be simple: these handles are just elements, and so like other form controls they could be focussed and then controlled using the arrow keys. I think the solution here would be to treat them like input sliders, only with two dimensions of movement.

Accessibility on these elements is a harder problem: I cannot find an ARIA role that would work for this resize handle. The closest things I could find would be the `slider` role or the proposed `splitter` role from #1348. However, neither of these handle two-dimensional resizing.

Is there an existing role / combination of roles that I've missed that should be used here, or is the solution that a new ARIA role would need to be created for resize handles?

**Comment by JAWS-test** [comment]
For resize [separator](https://www.w3.org/TR/wai-aria-1.2/#separator) is also suitable, but this does not solve your problem

**Comment by jnurthen** [comment]
sounds like another use case for #432

**Comment by jnurthen** [comment]
closing - please use #432 for this issue. If you disagree please reopen.
