### ISSUE TITLE
Can aria-selected by used on a button

### ISSUE THREAD

**Issue by wardav** [w3c/aria#1452]
Apologies if this has already been asked. But I've noticed that in the [ARIA specification](https://www.w3.org/TR/wai-aria-1.1/#aria-selected) that `aria-selected` is listed as being usable on elements with the following roles. 

- gridcell
- option
- row
- tab

However, one does see it being used (and inconsistently working) on buttons. For example, the [WAI ARIA 1.2 -Date Picker Dialog](https://www.w3.org/TR/wai-aria-practices-1.2/examples/dialog-modal/datepicker-dialog.html) uses it on a button, although this appears to have been removed in the [editors draft version](https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html). 

I wanted to check what the official line is on this. I assume that it is that it not supposed to be used and that folks should use `aria-pressed` instead. But as said, it would be good to get peoples thoughts.

**Comment by jnurthen** [comment]
correct - the specification does not allow aria-selected on a button
