### ISSUE TITLE
Support for css selectors in attribute values where ids are expected 

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria#1459]
For attributes such as `aria-describedby`, `aria-labeledby`, `aria-activedescendant` and so on, I often find the need to reference another element in the DOM which has no ID. 

The usual practice is to imagine and add an ID in the referenced element, but in many cases it would be more convenient to refer to the something like "the first item in the container". 

CSS selectors offer a robust mechanism for these kinds of expressions, available to js via `querySelector()`. Would it be a crazy idea to support this mechanism in aria attributes which expect IDs? Has this been discussed?

Use Case: Managing menu focus might be implemented using something like

`setAttribute("aria-activedescendant", "#productsmenu[role='menuitem']:nth-child(" + index + ")"` 

where arrow keys increment and decrement the index. No need to maintain an array of IDs, or count child elements. This would mean that adding ids to the menu items themselves would be unnecessary, leading to a cleaner and leaner DOM, simpler keyboard logic. etc.

**Comment by pkra** [comment]
Are you aware of the AOM work on attribute reflection? See https://github.com/WICG/aom/blob/gh-pages/explainer.md#reflecting-element-references 

In Chrome, you can try it out by enabling the experimental flag for ARIA element reflection. Then something like `myNode.ariaActiveDescendantElement = document.querySelector('...')` would set the active descendant.

**Comment by brennanyoung** [comment]
@pkra an AOM implementation like that would be enough so that supporting selectors via the attribute would be unnecessary.

Great! Thank you!
