### ISSUE TITLE
Problematic User Agents MUST NOT statement needs to be qualified

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#1476]
This [pull request](https://github.com/w3c/aria/pull/1408/files) introduced the following statement into ARIA 1.3:

> User Agents MUST NOT expose an ARIA attribute to the platform accessibilty API when the element's computed role prohibits use of the attribute.

Given something like `<div tabindex="0" aria-label="foo">bar</div>`, in which `aria-label` is prohibited (`generic` role), that means we need implementors to NOT expose "foo". We will not get vendor buy-in for this. Trust me. Yes, it's lousy authoring which is not ARIA compliant. But given the explicit author-provided label, user agents aren't going to ignore it in favor of "bar" or worse, nothing.

I think we need to modify the above statement to allow for User Agents to expose "foo" as part of handling author errors.

**Comment by spectranaut** [comment]
Discussed in: https://www.w3.org/2022/08/11-aria-minutes#t06
