### ISSUE TITLE
TPAC 2021

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1482]
Should we meet, and with whom?

**Comment by cookiecrook** [comment]
Fixed it for you. 

– Grammar snob. 😉

**Comment by cookiecrook** [comment]
https://www.w3.org/wiki/TPAC/2021

**Comment by cyns** [comment]
AOM 
Canvas and WebGL accessibility - what's still needed for a solution that would work for canvas-rendered apps with text editing etc. Relationship to SVG. Not sure who needs to be there.
SVG-AAM editorial handoff (joint with SVG WG)

**Comment by cyns** [comment]
Accessible Data Visualization (both complex visualizations and simpler charts, graphs and diagrams). How does this relate to canvas/webGL rendering and SVG accessibility?

**Comment by jnurthen** [comment]
Joint meeting with epub, i18n?, apa about ruby - see #1619 #1620
