### ISSUE TITLE
Allowed children of role=tablist includes any role including tabpanel?

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria#1486]
The frequently observed pattern for `tablist`, `tab` and `tabpanel` is for a `tablist` to only contain children with `role=tab`:

```
<div role=tablist><span role=tab>poot 1</span> <span role=tab>poot 2</span></div>
```
but there appears to be nothing (I can find) to prohibit a `tablist` being a container for both `tab`s and `tabpanel`s

```
<div role=tablist>
<span role=tab>poot 1</span>
<div role=tabpanel>...</div> 
<span role=tab>poot 2</span>
<div role=tabpanel>...</div> 
</div>

```

Is it the case that `tablist` with both `tab`s and `tabpanel`s as children is OK? 
Am asking as I found an example of a widget using this latter pattern.

**Comment by scottaohara** [comment]
I think this will be clarified with the work being done in #1454

for instance, "Required Owned Elements" is being changed to "Allowed Child Roles"

The first paragraph if this revised term is:
>Any <a>element</a> that is a direct <a>child</a> of the element with this <a>role</a>. For example, an element with the role <rref>list</rref> may own elements with the role <rref>listitem</rref>, but not elements with the role <rref>option</rref>.

and that should answer this question: i.e., a `tabpanel` is not allowed within a `tablist`

**Comment by thierryk** [comment]
> Am asking as I found an example of a widget using this latter pattern.

I am very interested in seeing the styling of that widget (how the layout is done with such construct) can you share an URL?

**Comment by stevefaulkner** [comment]
@thierryk unfortunately I don't have direct access to it, just a reduced test case provided via a government client. :-(

**Comment by thierryk** [comment]
Thanks @stevefaulkner 

I don't know if that may help your client but you could let them know that they can *keep the same kind of markup*, just by moving the closing `</div>` like so:
```
<div role=tablist></div>
<span role=tab>poot 1</span>
<div role=tabpanel>...</div> 
<span role=tab>poot 2</span>
<div role=tabpanel>...</div> 
```
and then rely on `aria-owns` like I do for [TabPanelWidget](https://tabpanelwidget.com/) and as I suggest for [MDN Doc](https://github.com/mdn/content/pull/3235)

**Comment by sinabahram** [comment]
This seems like it would be a usability nightmare unless very carefully thought through. Nested tabs is one thing, but that's a separate list of tabs as the contents of a given tab, to have an actual nesting within the top level list of tabs seems nonsensical to me for a variety of reasons, both UI/UX, as well as just semantically.

**Comment by stevefaulkner** [comment]
> 
> 
> This seems like it would be a usability nightmare unless very carefully thought through. Nested tabs is one thing, but that's a separate list of tabs as the contents of a given tab, to have an actual nesting within the top level list of tabs seems nonsensical to me for a variety of reasons, both UI/UX, as well as just semantically.

right, which is why i was surprised that it was allowed. But from what Scott said in https://github.com/w3c/aria/issues/1486#issuecomment-841678672 The spec is going to be tightened up.
