### ISSUE TITLE
Should aria-hidden cause presentational conflict?

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1489]
I was looking into presentational role conflict a little more closely. In short, if you put role=presentation on a thing that needs to be in the accessibility tree, the role will be ignored. For example, on the following button, the role is ignored because having this presented as a proper button in the accessibility tree is important.

```html
<button role="presentation">search</button>
````

This is true for all elements that are either interactive, or that have a global ARIA attribute. This makes sense for everything except `aria-hidden`. An element with aria-hidden=true is going to get ignored, so conflict resolution doesn't matter. But for aria-hidden="false" counter-intuitive behaviour can occur. Take this example:

```
<canvas role="none" aria-hidden="false">
```

Because of `aria-hidden=false`, the `role` gets ignored and the element put into the accessibility tree with whatever implicit role the browser gives canvas. It seems like a fairly odd gotcha for that to happen. Intuitively, an attribute set to "false" should behave no different than if it wasn't there. Yet that is exactly what happens. Web components being what they are, this can cause real issues. An example of that would be the following piece of VueJS, 

```html
<template>
  <div role="menu">
    ...
    <div role="none" :aria-hidden="isAdmin" :hidden="isAdmin">
      <div role="menuitem">Users</div>
      <div role="menuitem">Settings</div>
    </div>
  </div>
</template>
```

This is a bit speculative on my part. I haven't seen a real world example of it. But this seems like it exists in some form or another out there. And so since it doesn't matter for `aria-hidden="true"`, and `aria-hidden="false"` creates this surprising behaviour, it might be better to not to trigger presentational conflict resolution with `aria-hidden`.

**Comment by jnurthen** [comment]
Until there is a real world example of this causing an issue I would prefer to not expend the groups energy solving this kind of issue. Validators can flag issues of presentational conflict resolution as author errors and IMO this is good enough.
Closing this - feel free to reopen if you disagree and can provide real world examples.
