### ISSUE TITLE
Presentation conflict resolution section contains a difficult (impossible?)-to-parse sentence

### ISSUE THREAD

**Issue by jamesbeninger** [w3c/aria#1501]
Issue location: https://www.w3.org/TR/wai-aria/#conflict_resolution_presentation_none

In the description for the presentation role, under the "Presentational Roles Conflict Resolution" heading, there are extraneous commas and an extraneous "to" that make it difficult to parse.  Recommended changes marked with numbers below:

_Host languages elements, (1) having implicit presentational roles for which no roles, (2) may be applied, (3) MUST never be exposed to (4) in the accessibility tree_

I believe this reads better without the commas and "to":

Host languages elements having implicit presentational roles for which no roles may be applied MUST never be exposed in the accessibility tree.

**Comment by jnurthen** [comment]
This is already resolved in ARIA 1.2
https://www.w3.org/TR/wai-aria-1.2/#conflict_resolution_presentation_none
