### ISSUE TITLE
[meta] Please mark terms with standard definitions elsewhere as noexport

### ISSUE THREAD

**Issue by tabatkins** [w3c/aria#1509]
In <https://w3c.github.io/aria/#terms>, a large number of terms are defined that are already well-defined by the web platform elsewhere. Having local versions of these definitions, with descriptions that are more useful/specialized for readers of this specific spec, is fine, but by marking them all as `export` they're conflicting with definitions elsewhere in the web platform that are otherwise defined in only a single location, like "Event".

(This was not previously an issue for Bikeshedded specs, as the data source I was using didn't include this document, but I'm in the process of switching to a new data source that does.)

It would be great to have this entire list switched to noexport, with only terms for which this spec is actually a primary definition source marked as export. For example, "Accessibility API" might be appropriate to still export, but "attribute", "class", "DOMString", etc are not.

(Ideally these terms are also marked more explicitly as "local-only", by setting an empty `lt` attribute and putting the linking text into `local-lt`, like `<dfn lt local-lt="attribute">`. But at least marking them as unexported will avoid annoying conflicts across the entire web platform once I kick the data source over.)

**Comment by jnurthen** [comment]
@tabatkins We need to reference these from our other specifications. Is there a way of doing this without exporting them to everybody? We were requested to move our definitions to the relevant specifications - but we still need to reference them from the other specifications in the ARIA suite. This was the only method I could find to do this.

**Comment by tabatkins** [comment]
Hm, that's unfortunate. No, there's no way to expose a definition only to some specs. And hm, if you were using Bikeshed I'd know what invocations to tell you to keep them unexported but still usable in other ARIA specs, but as you're ReSpec I'm not sure. @marcoscaceres?

Could you elaborate more on why you need a definition for, say, "Event"? What is referencing that which can't be usefully pointed to the DOM spec instead?

**Comment by jnurthen** [comment]
An example usage is at https://www.w3.org/TR/core-aam-1.1/#mapping_events_menus - these are not DOM events do pointing to the DOM spec would not be appropriate.

**Comment by marcoscaceres** [comment]
Hi @jnurthen. There is a bit of a misunderstanding. You can still reference things in your spec(s) without the explicit `data-export=""` you've added to the DFNs. I'll send you a pull request. 

@tabatkins, I'll disallow that in ReSpec going forward (i.e., if data-cite="foo#bar", then `data-export=""` will be automatically removed and an error shown).

**Comment by marcoscaceres** [comment]
@tabatkins, we've made a bunch of progress here: 
https://github.com/w3c/aria/pull/1510

Starting to look good and we shouldn't see any conflicts. We just need to sort out "Event", as the definition used by aria is a little different to {{Event}}... but I think we are close!
