### ISSUE TITLE
HTML-AAM: <footer> that is not child of body should not be group in UIA

### ISSUE THREAD

**Issue by cyns** [w3c/aria#151]
Text or not mapped? Decide on best implementation

**Comment by jasonkiss** [comment]
Wouldn't `footer` that's not child of `body` be mapped the same as `div` since it creates a grouping of items related to the parent sectioning element?

**Comment by stevefaulkner** [comment]
On 10 February 2016 at 05:10, Jason Kiss <notifications@github.com> wrote:

> Wouldn't footer that's not child of body be mapped the same as div since
> it creates a grouping of items related to the parent sectioning element?
>

+1

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by jasonkiss** [comment]
@cyns Would you be happy with Control Type: Group for this?

**Comment by jasonkiss** [comment]
Set to Control Type: Group. Closing. Reopen if necessary.
