### ISSUE TITLE
Are properties just attributes?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/aria#1511]
Are things like "aria-atomic" always just DOM attributes? If so, we should define them as such (and we can probably get rid of the "properties" concept).

**Comment by jnurthen** [comment]
We separate states and properties historically. We try to simply refer to them as attributes in many places but don't think we can remove the concept completely.

**Comment by marcoscaceres** [comment]
HTML also has "states" for various input types. I'm hopeful we should be able to align there. 

When we (eventually) export the aria-* attributes, we can mark them up properly and add appropriate states.

**Comment by pkra** [comment]
Closing this as an answered question.
