### ISSUE TITLE
Add radiogroup supported states and properties to group role

### ISSUE THREAD

**Issue by fstrr** [w3c/aria#1512]
At the moment it's possible to use a series of states and properties on the `radiogroup` role to aid with the validation of groups of radio buttons. Confusingly, those aren't available for the `group` role, which is needed to group other components, for example: checkboxes. It would be useful to have the following `radiogroup` states and properties also available for the `group` role so that required groups of checkboxes can be implemented similarly to radio buttons:

- `aria-errormessage`
- `aria-invalid`
- `aria-readonly`
- `aria-required`

This would help in situations where users have to select one or more items, for example:

```html
<div aria-describedby="pets" aria-errormessage="errormsg" aria-invalid="true" aria-required="true" role="group">
  <div id="pets">Which of these pets do you have?<span aria-hidden="true"> (required)</span></div>
  <div id="errormsg">Please tell us about your situation.</div>
  <div>
    <input id="cats" type="checkbox">
    <label for="cats">Cats</label>
  </div>
  <div>
    <input id="dogs" type="checkbox">
    <label for="dogs">Dogs</label>
  </div>
  <div>
    <input id="fish" type="checkbox">
    <label for="fish">Fish</label>
  </div>
  <div>
    <input id="none" type="checkbox">
    <label for="none">I don't have any pets</label>
  </div>
</div>
```

**Comment by jnurthen** [comment]
Please see the comment https://github.com/w3c/aria/issues/542#issuecomment-682098865 
This seems identical and (for readonly and required at least) should be taken up with HTML to allow these on fieldset (and work out how conflicts between group-specified roles and item-specified roles would be resolved.

Radiogroup does not have these same conflicts as these attributes are not alllowed on `radio` only on the `radiogroup`

**Comment by scottaohara** [comment]
see also #1322
