### ISSUE TITLE
can we make terms normative?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/aria#1513]
"important terms" are defined as informative, but used in normative parts of the specification. This is also problematic from a W3C Process point, that normative parts of specifications should only use other normative parts of other specifications.  

So, questions is: can we just treat the important terms as normative? If no, which ones and why not (and maybe we can fix the informative ones or move them to their own section).

**Comment by Miss141hunter** [comment]
Legally we are abd will be handling all thus.

**Comment by jnurthen** [comment]
in general we can't but would be happy to accept PRs for terms that could be normative. 

We are moving away from the Important terms section in the future and will simply define terms inline so they may/may not be normative depending on the section in which they are defined.
