### ISSUE TITLE
HTML-AAM: UIA mappings for <footer>

### ISSUE THREAD

**Issue by cyns** [w3c/aria#152]
If child of body: Control Type: group
Localized Control Type: Footer
Landmark type: Custom
Localized Landmark Type: content information

**Comment by jasonkiss** [comment]
Fixed. Closing.

**Comment by cyns** [comment]
hmmm... not updated in master.

**Comment by jasonkiss** [comment]
Looks to be correct at http://rawgit.com/w3c/aria/master/html-aam/html-aam.html#el-footer-ancestorbody

**Comment by cyns** [comment]
you're right. I was looking at the one without body as parent.
