### ISSUE TITLE
html-AAM: remove aria-role and string stuff from <footer> UIA mapping

### ISSUE THREAD

**Issue by cyns** [w3c/aria#153]
Remove this:
Expose "contentinfo" as text string in AriaRole
(Expose as text string "footer" in UIAutomationType_String
??discuss exposing localized type for all unmapped elements, or is it better to expose as Group??)

**Comment by jasonkiss** [comment]
Fixed as part of https://github.com/w3c/aria/commit/d9de2d7bb3bdf53ce58110593e7ee15c039085af
Closing.
