### ISSUE TITLE
Author test case: 5.2.8 Accessible Name Calculation (ARIA 1.2)

### ISSUE THREAD

**Issue by cyns** [w3c/aria#1562]
5.2.8 Accessible Name Calculation
prohibited: the element has no name. Authors MUST NOT use the aria-label or aria-labelledby attributes to name the element.
test: https://joanmarie.github.io/aria/validator-tests/name-prohibited.html

**Comment by joanmarie** [comment]
The test has already landed as part of https://github.com/w3c/aria/commit/ebd22f8051c6f90191af18fe1031fdf8bd89854e
