### ISSUE TITLE
Author test case: group role (ARIA 1.2)

### ISSUE THREAD

**Issue by cyns** [w3c/aria#1566]
group role
However, when a group is used in the context of a listbox, authors MUST limit its children to option elements.

**Comment by spectranaut** [comment]
isn't this "must" just ONE of the cases that falls under this "must"? https://github.com/w3c/aria/issues/1522

**Comment by spectranaut** [comment]
Oh no! I wrote up a test case for this AND THEN notice @jongund had a PR opened for it :'( @jongund can you assign yourself to issues that you are working on? I see you somehow linked the PR to this issue but I don't see the PR from this issue...

**Comment by spectranaut** [comment]
Oh wait! Now I see that PR #1578 is slightly different! its about "option" being in a "group" or "listbox", as opposed to this issue, which is about "group" necessarily only having "option" child elements. I'll see if there is actually any test cases to write that are separate from what @jongund wrote.

Sorry for the confusion!

**Comment by jongund** [comment]
@spectranaut 
I am just making the test case html files for some of the ARIA 1.2 authoring requirement.  I couldn't get axe installed so I was not able to generate the `json` results files.  I was waiting for some feedback from James or Joanie before making anymore.
So I not sure what the status of my pull requests are, so feel free to to work on them, especially generating the `json` files.
What is your role?

**Comment by spectranaut** [comment]
hi @jongund I actually do have axe running so I'll try adding the json to this PR! I just started working at igalia on accessibility related work :)

**Comment by jongund** [comment]
@spectranaut 
Good news, you will be a great addition to the work on ARIA specs!
I assume you are working with Joanie, and therefore probably have more information on the work plan for the authoring requirement tests, so let me know how I can help.

**Comment by spectranaut** [comment]
Thanks @jongund I'm glad to be helping here and glad to see your name again! And I am working with Joanie :)
