### ISSUE TITLE
HTML-AAM: suggestion: add "see also NAME-AAM" to image alt is empty

### ISSUE THREAD

**Issue by cyns** [w3c/aria#157]

**Comment by jasonkiss** [comment]
Do you mean add something like "See also the Accessible Name and Description: Computation and API Mappings 1.1" and link to the ACCNAME-AAM?

How about something like "See the Note on the img element Accessible Name Calculation" and link to https://rawgit.com/w3c/aria/master/html-aam/html-aam.html#h-note3 ?

Or is that what you had in mind?

**Comment by cyns** [comment]
That works. thanks.

**Comment by jasonkiss** [comment]
Fixed. Closing.
