### ISSUE TITLE
HTML-AAM: remove Calendar mapping from input in date, date/time, month, week

### ISSUE THREAD

**Issue by cyns** [w3c/aria#158]
The UIA Calendar Control Type is a traditional grid-based calendar. We had assumed that these inputs would be implemented as a grid-based calendar, but the Edge UI is quite different.

change text to "depends on UI design or implementation"

**Comment by jasonkiss** [comment]
What specific control types or UIA structures does the Edge UI use?  Do you think it would be helpful/useful to note that it "depends on UI design or implementation" but also refer to the most common or likely UIA implementations, e.g. Calendar control type, what Edge implements, etc?

**Comment by cyns** [comment]
I added the Edge implementation as an example. I am concerned about being too specific about browser UI, since it could change.
