### ISSUE TITLE
HTML-AAM: add UIA LabeledBy info to input types

### ISSUE THREAD

**Issue by cyns** [w3c/aria#159]
Add to UIA column for input types. Double check that it makes sense for all of them.

"If the &lt;input&gt; is the target of &lt;label for&gt; or contained by &lt;label&gt;, its equivalent UIA element has a LabeledBy relationship pointing to the label."

**Comment by cyns** [comment]
@stevefaulkner or @jasonkiss I'd like to add this to every input type, but that seems like a lot of redundancy. Is there a better way to add a note that applies to multiple elements?

**Comment by jasonkiss** [comment]
I've a couple of thoughts:
1. Live with the repetition for labelable elements.
2. Add an extra note to the Notes section preceding the mapping table.
3. Add the same footnote to each labelable element.
4. Add another section about relations and how they are managed in the APIs  

Would be useful to get input from @Joanmarie and @asurkov on this too.

**Comment by asurkov** [comment]
I have no good answer. I think I should start over with those spec content structuring ideas I shared with you previously, so we can figure out a structure that lets easily to stuff like this.

**Comment by jasonkiss** [comment]
@cyns, @asurkov, @stevefaulkner See https://rawgit.com/w3c/aria/notes-to-html-role-mappings/html-aam/html-aam.html#html-element-role-mappings as an proposed approach to addressing this and related issues where we have API-specific notes that apply to multiple elements.

To address the question of a note about elements that participate in name computations (see #172), we could include a non-API-specific note to the effect that implementers should make sure to check the Accessible Name and Description Calculation section of the HTML-AAM for how an element might participate in various accessible name and description computations.

**Comment by jasonkiss** [comment]
Addressed as described above in merged PR #424. Closing.
