### ISSUE TITLE
ARIA 1.2 IDL can not include ariaDescription

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1599]
This is likely something that just got overlooked in editing. (You folks really should invest in some automated tests for this spec). But the `ariaDescription` attribute is listed as one of the properties to be added with the `AriaAttributes` interface mixin.

I think it is important that this be fixed, and reading up on #1598 it looks like there might yet be an opportunity.

Here's the link the the section: https://www.w3.org/TR/wai-aria-1.2/#AriaAttributes

**Comment by scottaohara** [comment]
[aria-description is slated for ARIA 1.3](https://w3c.github.io/aria/#substantive-changes-targeted-for-the-1-3-release), so that seems to be an errant instance that found its way into the 1.2 spec.  There is no other mention of `ariaDescription` or `aria-description` in the 1.2 spec.
