### ISSUE TITLE
w3c.github.io/aria/ 404s

### ISSUE THREAD

**Issue by pkra** [w3c/aria#1603]
I'm not sure if this should go into aria-common issues; please transfer if that's the case. 

A recent webAIM thread mentioned styling differences of published versions vs github pages. It looks like both https://w3c.github.io/aria/common/css/common.css and  https://w3c.github.io/aria/img/accessibleelement.png return 404s.

**Comment by jnurthen** [comment]
heh - was just looking at this

**Comment by pkra** [comment]
Thanks!
