### ISSUE TITLE
Element.prototype.role

### ISSUE THREAD

**Issue by jonathantneal** [w3c/aria#1612]
I’ve noticed that `Element.prototype.role` has an incomplete implementation in Safari.

```js
document.createElement('button').role // null

Object.assign(document.createElement('button'), { role: 'button' }).role // "button"
```

I would have expected this reflection:

```js
document.createElement('a').role // null
Object.assign(document.createElement('a'), { href: '' }).role // "link"

document.createElement('h1').role // "heading"
Object.assign(document.createElement('h1'), { role: 'button' }).role // "button"
```

Is there documentation or a proposal for this behavior specified somewhere?

Would this be part of ARIA, AOM, or something else?

**Comment by jnurthen** [comment]
@jonathantneal does https://wicg.github.io/aom/explainer.html#what-happened-to-accessiblenode help explain why this doesn't work today?

ARIA 1.2 only defines reflection of explicitly defined ARIA roles - it does not imply that implicit roles are exposed and indeed this is unlikely at this point in time. It sounds like you want https://wicg.github.io/aom/explainer.html#full-introspection-of-an-accessibility-tree---computedaccessiblenode which IMO is unlikely to ever be implemented outside of testing/developer tooling.

**Comment by jonathantneal** [comment]
The rationale in that document seems specific to one particular implementation that never shipped. Based on what ships in Safari, I would have expected `role` followed https://w3c.github.io/html-aam/. 

I’m pretty unsure where my issue belongs. Still, Perhaps I can better organize my questions:

1. Where is or is there documentation for `Element.prototype.role`?
2. Is there interest in or would this be the place to discuss defining `Element.prototype.role` (_as following `html-aam`_), or actively discouraging its usage?
