### ISSUE TITLE
Time to add a new role=carousel to the ARIA spec?

### ISSUE THREAD

**Issue by gmjellin** [w3c/aria#1617]
Let's face it, carousels/slideshows are with us whether we like it or not. They are everywhere and they aren't going away. I've always pushed back to clients who want to implement them, because they are very challenging for many users and are rarely accessible. 

My proposal is to create a new role=carousel. I think of it much like the role=dialog. We could then build a recommended implementation pattern with guidance on keyboard support, etc. In theory, this would allow SR software developers to support the carousel role, which would provide consistent interactions and instructions.

Thoughts? 

Note: Should this be moved to discussions or elsewhere?

**Comment by JAWS-test** [comment]
It probably works without a new role: https://www.w3.org/TR/wai-aria-practices-1.2/#carousel and https://www.w3.org/WAI/tutorials/carousels/

**Comment by gmjellin** [comment]
> It probably works without a new role: https://www.w3.org/TR/wai-aria-practices-1.2/#carousel and https://www.w3.org/WAI/tutorials/carousels/

Not really. that pattern still does not provide adequate SR instruction, IMO. We have done pretty extensive user testing with that pattern and all of our users had difficulty navigating. 

The new role would provide additional context for SR users with navigational hints, etc.

**Comment by jnurthen** [comment]
I'd encourage something like this to go through https://open-ui.org/ to actually document what is meant by a carousel in the first place. There are so many different implementations that we need to go through this kind of process to avoid creating a new role which doesn't solve the real world issues.

**Comment by scottaohara** [comment]
hi @gmjellin, thanks for moving the discussion over here.

So the issue I see here is with idea that screen readers would provide instructions on how to use the carousel.  

As you said “there are infinite implementations”, and there in lies the problem statement of “how” would one expect screen readers to provide instructions for a role, where the mechanism to control that role can be widely variable, and even how carousels can be displayed would dictate that a screen reader know that ‘this’ carousel implementation expects to be controlled.  For instance, it might be by previous/next buttons, pagination ‘dot’ controls, or even custom swiping events, where as another carousel implementation might allow for previous/next buttons exclusively.  The first hypothetical carousel example might show a single pane of content at a time, where the next carousel example might show 3 unique content cards at a time (and then may even have other content cards partially visually exposed, but with the majority of their content purposefully positioned off screen).

With many other ARIA roles, there's a wide understanding that a tree view behaves like x, a toolbar behaves like y, a dialog behaves like z.  With a carousel, there is no one right way (though there are plenty of wrong ways).

and, as @jnurthen got in right before i hit send, I think now that an issue has been filed for considering the role, hammering out what a carousel is, definitively, needs to go to open-ui next.

**Comment by sinabahram** [comment]
Huge +1 for this going to OpenUI for all the wonderful reasons listed.

**Comment by gmjellin** [comment]
Great points all. I was not aware open-ui, and that makes perfect sense as a next step. I do think it would be possible to provide some basic SR instruction (or at least provide context) by using the role=carousel. Even with tons of variation the user would know to expect multiple slides, etc. 

In agreement that more thought and definition needs to be made first. I'll investigate open-ui.

**Comment by jongund** [comment]
@mcking65 
The previous link provided to the ARIA APG carousel example is very outdated, the latest guidance and examples can be found at this URL:
https://w3c.github.io/aria-practices/#carousel

**Comment by jnurthen** [comment]
Closing this. Please progress with open-ui.

**Comment by cookiecrook** [comment]
For example, there are some Open UI presentations of tabs that look like carousels. https://open-ui.org/components/tabs.research.parts

IIRC, @bkardell was also discussing a more primitive UI pattern that may be more appropriate than tying carousel to the other baggage associated with "tab" views.
