### ISSUE TITLE
A role for furigana-for-enhanced-accessibility (a special type of ruby)

### ISSUE THREAD

**Issue by murata2makoto** [w3c/aria#1619]
On behalf of the Japan DAISY Consortium, I would like to request a role for furigana-for-enhanced-accessibility (a special type of ruby).  The idea is to use the same HTML document for both [general-ruby ](https://www.w3.org/TR/jlreq/#term.general-ruby)rendering and [para-ruby](https://www.w3.org/TR/jlreq/#term.para-ruby) rendering.  For example, 

`<ruby><rb>次</rb><rt role="furigana-for-enhanced-accessibility">つぎ</rt></ruby>の<ruby><rb>日本</rb><rt role="furigana-for-enhanced-accessibility">にほん</rt></ruby>の<ruby><rb>総理大臣</rb><rt>そうりだいじん</rt></ruby>は<ruby><rb>岸田氏</rb><rt role="furigana-for-enhanced-accessibility">きしだし</rt></ruby>である`

can be rendered as if it was 

`次の日本の<ruby><rb>総理大臣</rb><rt>そうりだいじん</rt></ruby>は岸田氏である`

for most people (the para-ruby rendering).  But the same document can be rendered in the general-ruby style: every CJK ideographic character is displayed together with its ruby.

More about this issue, see [Text to Speech of Electronic Documents Containing Ruby: User Requirements](https://github.com/Japan-Daisy-Consortium/documents/wiki/Text-to-Speech-of-Electronic-Documents-Containing-Ruby:-User-Requirements).

**Comment by jnurthen** [comment]
@murata2makoto If I understand correctly the purpose of this role is so the contents of the rt element are essentially ignored. Have I understood correctly?

**Comment by murata2makoto** [comment]
@jnurthen Yes, in most cases, lots of rt elements are ignored.  They are exposed to those who have particular difficulties with CJK ideographic characters.

**Comment by murata2makoto** [comment]
@jnurthen I18N and CSS.  APA and EPUB might also be interested.

**Comment by murata2makoto** [comment]
@cookiecrook Thanks.  I reported what happened in TPAC to Japan DAISY Consortium and will soon report to the W3C JLTF, which is lead by Kida-san  :-)  After hearing feedback from them, I will respond.

**Comment by cookiecrook** [comment]
@murata2makoto Is it okay to close this issue and #1620, or is there more you'd like to clarify before closing? Please do link any relevant issues in other repositories.
