### ISSUE TITLE
HTML-AAM: UIA mappings for <input type=file>

### ISSUE THREAD

**Issue by cyns** [w3c/aria#162]
In Edge, the file input is rendered as textbox and button together (rather just a button as in IE). To accommodate this implementation, change UIA mapping to 

If rendered as a single button
Control Type: Button

If rendered as a text entry box and button:
two controls
Control Type: Edit
Localized Control Type: file
Control Type Button

**Comment by jasonkiss** [comment]
I believe I've captured what you're after in https://github.com/w3c/aria/commit/63bd1c277034162f60f8b142bae06fbed9d6f6b0, so closing. Reopen if not quite right.
