### ISSUE TITLE
A role for indicating whether a given ruby represents phonetics 

### ISSUE THREAD

**Issue by murata2makoto** [w3c/aria#1620]
On behalf of the Japan DAISY Consortium, I would like to request a role for indicating whether or not a given ruby represents phonetics.

If a ruby represents phonetics, the T2S engine should render either the base or ruby.  If not, the T2S engine should render both.

More about this, see 4.4 in  [Text to Speech of Electronic Documents Containing Ruby: User Requirements](https://github.com/Japan-Daisy-Consortium/documents/wiki/Text-to-Speech-of-Electronic-Documents-Containing-Ruby:-User-Requirements).

**Comment by jnurthen** [comment]
@murata2makoto How does the T2S engine know which one of the base or the ruby it should render if this new role is encountered? Is it expected that the T2S engine will be supplied both and it decides or would the browser or AT be making this decision?

**Comment by murata2makoto** [comment]
> How does the T2S engine know which one of the base or the ruby it should render if this new role is encountered?

This depends on the interface between the T2S engine and screen reader or user agent.  Ideally, the T2S engine should receive the ruby base as such and receive the ruby text as such.  Based on these two information items, the T2S engine should make a good decision.  However, when the T2S engine receives flat text and nothing else or when the accessibility tree does not have these two information items, this idealistic scenario is not possible.  

[Text to Speech of Electronic Documents Containing Ruby: User Requirements](https://github.com/Japan-Daisy-Consortium/documents/wiki/Text-to-Speech-of-Electronic-Documents-Containing-Ruby:-User-Requirements) considers this issue thoroughly.  But the rule of thumb is to use the ruby base rather than the ruby text.

**Comment by aleventhal** [comment]
> What about proposing a new type attribute on the <ruby> element with values [phonetic-required | phonetic-optional | complementary]

+1, nice summary and crisp proposal.

**Comment by aleventhal** [comment]
Is it potentially confusing that complementary is nothing like role=complementary? Is it more like role=note? 

Perhaps not a big deal.

**Comment by aleventhal** [comment]
Another question, do the semantics only need to support 2 levels of readers (read all annotations or only difficult ones). Or are there plenty of intermediate readers where neither case fits perfectly?

**Comment by cookiecrook** [comment]
> Is it potentially confusing that complementary is nothing like role=complementary? 

I'm not particular to the term "complementary" so we should probably not use that. I was thinking, both the base text and the ruby text are complementary of each other, so both should be displayed in all modalities. However, the ruby text is not phonetic, so TTS engines should speak it but not use it to infer pronunciation hints.

> Is it more like role=note? 

Not all of these are notes. If you want to use the semantic distinction rather than a functional one, there may need to be more than 3 values.

**Comment by cookiecrook** [comment]
> Another question, do the semantics only need to support 2 levels of readers (read all annotations or only difficult ones). Or are there plenty of intermediate readers where neither case fits perfectly?

I assume this question is for @murata2makoto. 

However, my understanding is that it would be up to the app to display the optional ones or not, based in the in-app user preference, rather than some magic in the user agent. 

In either case, the TTS engine would rely on the phonetic-required, and could use or ignore the phonetic-optional.

**Comment by murata2makoto** [comment]
> The WG discussion continued after you left, and I spent several hours considering your [User Requirements page](https://github.com/Japan-Daisy-Consortium/documents/wiki/Text-to-Speech-of-Electronic-Documents-Containing-Ruby:-User-Requirements) and discussing with colleagues.

Thank you for studying this document carefully.  Shimono-san of Keio W3C converted to a ReSpec document, available at https://w3c.github.io/ruby-t2s-req/  We plan to create a W3C Note.

> The Working Group consensus is that the distinctions you're trying to make are not limited to the use case of accessibility APIs or assistive technology, so the ARIA spec isn't the best location for them. We suggest pursuing a new content attribute, most likely on the `<ruby>` or `<rt>` element that clarifies either:
> 
> * a semantic distinction between the known types of content, or
> * a functional distinction between the expected behaviors of user agents.

Both the JLreq TF and the Japan DAISY Consortium discussed the idea of creating HTML attributes rather than ARIA roles.   Nobody has a strong opinion.  We can go either way.

In the I18N session after the AIRA WG meeting, we discussed where in WHATWG or W3C we should discuss this issue.  Even within W3C, we might want to extend the charter of the HTML WG or create a community group dedicated to this issue.  It is not yet clear.

**Comment by murata2makoto** [comment]
@cookiecrook and @aleventhal  I sincerely welcome your suggestions.  Western examples by James are very useful.  But before I indulge in interesting discussions about ruby, I would like to summarize the status quo.

In OWP and EPUB, always-double-reading is unfortunately very common.  This is very bad for phonetic ruby, which is most common.  Always-base-only-reading (hopefully combined with better T2S engines for Japanese) would be a big improvement.  It might not be ideal but is OK.  Base-only-reading as the default and double-reading for non-phonetic ruby would be better but improving T2S engines is probably more important.  I don't believe ruby-only-reading is the right way to go forward.

> the English "My name is Knotnot" which means "My name is Knot" but may be misspoken by TTS (and misunderstood) as "My name is not Knot."

I appreciate this very much!  I will incorporate it into the upcoming note.

> in most cases, the TTS pronunciation of the rt or base will be identical.

Although most Japanese think so, I know that some practitioners strongly disagree.  I am not sure if I fully understand their reasons, but morphological analysis of kana-only ruby is likely to fail thus providing an unnatural accent and even incorrect pronunciation of は and へ.

**Comment by aleventhal** [comment]
> Their implementations examine code points of base characters.

Can we get an understanding of where this heuristic falls down? Or, if it's highly accurate, then do we actually need markup to differentiate between para-ruby and general-ruby?

If the heuristic can be accurate enough, and we only need to know when the ruby is used for a note, then all we really need is to apply role="note" to the `<rt>` when it is being used a complementary text. The benefit of this is that we could add it to an ARIA draft and easily implement it now. I'm not sure how long it will take to work with the HTML WG to define ruby semantics. I'm not saying we don't want to do that, but that I would seek more information on the real need to differentiate para-ruby and general-ruby in markup, if DAISY readers can already do it without markup.

Finally, I would like to know what the possibilities are for a heuristic that detects the note/complementary situation. Can we get an evaluation on how accurate that could be?

**Comment by cookiecrook** [comment]
>>  in most cases [of the "phonetic-optional" examples above], the TTS pronunciation of the rt or base will be identical.
> 
> Although most Japanese think so, I know that some practitioners strongly disagree. I am not sure if I fully understand their reasons, but morphological analysis of kana-only ruby is likely to fail thus providing an unnatural accent and even incorrect pronunciation of は and へ.

I agree there are edge cases, and that the は example is likely to be pronounced better if the base text is sent to the text-to-speech engine. However, once the text-to-speech engines understand ruby context, I think exposing both (to be pronounced as a single instance) is likely to result in better results, not worse. Ruby-unaware speech engines should just attempt to pronounce the base text in those instances of "phonetic-optional."

**Comment by cookiecrook** [comment]
@murata2makoto Is it okay to close this issue and #1619, or is there more you'd like to clarify before closing? Please do link any relevant issues in other repositories.

**Comment by aleventhal** [comment]
@murata2makoto , you mentioned that assuming we can announce the `<rt>` text instead of the base text would be catastrophic, because it could change the meaning. (I admittedly had a hard time understanding why, since the rt is supposed to be an announcement, and my understanding of Japanese is zero).  However, are there times that it would be better to read the rt instead of the base text, and is that something we might want to put in author control via a semantic? Right now, I think our semantics would suggest times to read both, but not just the rt text.

**Comment by aleventhal** [comment]
Should I be asking my questions about semantics in https://github.com/w3c/ruby-t2s-req/issues/7 ?

**Comment by murata2makoto** [comment]
@cookiecrook

I am very sorry for this belated reply.  I deeply appreciate all your suggestions.

Re: "phonetic-required" and "phonetic-optional"

Thank you very much for this suggestion.   But I am not sure if they should be separated.

First, ruby causes serious problems to some of the Japanese dyslexic people.  They mistakenly think that ruby is a strange radical and fails to recognize the base character.   Hiding every ruby is a sensible option.  (But using a different color for ruby is sensible.  Widening the gap between the base and ruby is also sensible.)

Second, when the same word is repeated, it is quite common to make ruby visible only for the first occurrence.  Thus, I do not think that some ruby should always be visible.
