### ISSUE TITLE
Deploy w3c/spec-prod

### ISSUE THREAD

**Issue by saschanaz** [w3c/aria#1623]
It seems the current Travis action somehow takes the previous state of the repository instead of the latest one.

For example, 3c8c9e364f0932181a7c3cc52f3228b7d19a7358 is triggered by 0d06a71dbedcc0aaca9a49bc1a5d83802da0d74e but it instead applied 7c5efbe270eaab1b9b255b9f2642aca2cf80effd (the previous commit).

I guess maybe time to migrate to w3c/spec-prod.

**Comment by jnurthen** [comment]
We have an open PR on this https://github.com/w3c/aria/pull/1504 but it seems @plehegar is stuck. If you know of any way to help unstick the PR that would be great.

**Comment by saschanaz** [comment]
Hmm, seems there is a ReSpec issue. Filed https://github.com/w3c/respec/issues/3805

**Comment by saschanaz** [comment]
The duplication issue was because of aria/common script, will open a PR for that.

**Comment by saschanaz** [comment]
w3c/aria-common#76 and #1631 should resolve other issues, and the remaining one is `role=time`. Still not sure who should be pinged?

**Comment by saschanaz** [comment]
Okay, `role=time` is being newly added by ARIA 1.2 and it's weird that the definition already uses itself. I think it can use `<time>` for now, what do you think @jnurthen?

**Comment by plehegar** [comment]
I believe gh-pages is [no longer outdated](https://github.com/w3c/aria/commits/gh-pages). Can we close this issue?

**Comment by saschanaz** [comment]
Can we use w3c/spec-prod to simplify the settings? Each repository having their own script leads to maintenance problem.

**Comment by saschanaz** [comment]
#1648 fixed this, thanks!
