### ISSUE TITLE
document inside a dialog

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria#1653]
Spec for `document` says

> the only circumstance where the document role is useful for changing assistive technology behavior is when the element with role document is a focusable child element of a widget or application.

However, a few a11y resources (such as [this one from Deque](https://www.deque.com/blog/aria-modal-alert-dialogs-a11y-support-series-part-2/)) suggest using the `document` role **specifically** for changing assistive technology behavior (to allow the browsing of rich text inside a **dialog** element). 

And a `dialog` is a subclass of **window**, not **widget**, so "the only circumstance" has at least one significant exception. I don't like this pseudo-normative wording. The guidance is neither normative nor correct.

As a side topic, I am wondering if we 'enable' the browse mode of (e.g.) NVDA in a dialog, using `document` inside a dialog, doesn't this also override keyboard events such as ESC, which might be intended to close the dialog?

**Comment by scottaohara** [comment]
some screen readers, like NVDA, used to default to forms mode when a dialog was rendered.  Back in late 2019/early 2020, I also noticed that if VO was set to quick nav on that a `role=document` was needed to navigate through the dialog's contents.

So, the resource you linked to from Deque (a 2016 post mind you), is essentially referencing these sorts of quirks that are browser/screen reader implementation quirks.  The spec isn't inaccurate, but reality has required some work arounds over the years.

I don't think there's a great need to update the spec here.

**Comment by jnurthen** [comment]
Closing as seems to be answered. Please reopen if needed.
