### ISSUE TITLE
Requesting extended review period of ARIA 1.2 CR2

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1664]
I sort of by accident discovered today that WAI-ARIA 1.2 went into its second CR period last week. It is somewhat unfortunate that this happens without much (any?) public announcement, and with the review period happening in a time where many folks are taking vacation. I therefor wanted to request the CR review period be extended at two weeks.

What feedback I can manage before that time is this:

I found a markup error in section D1, which reads:

> 30-Aug-2021: removed ariaDescription from IDL section as was added erroneouslyli>

Edit: looking at the W3C process, it seems at risk things can be removed without CR. Didn't realise that.

**Comment by jnurthen** [comment]
@WilcoFiers 
Of course more time is fine. We can extend the review period. Will discuss in the meeting today to see how to make this happen.

**Comment by WilcoFiers** [comment]
Much appreciated!

**Comment by pkra** [comment]
> I found a markup error in section D1, which reads:
>     30-Aug-2021: removed ariaDescription from IDL section as was added erroneouslyli>

This looks like an automation bug -- cc @michael-n-cooper

**Comment by pkra** [comment]
or perhaps not -- git blames @jnurthen for https://github.com/w3c/aria/blob/2021-12_CRD/index.html#L12869 :wink:

**Comment by pkra** [comment]
@michael-n-cooper Is there a way to do something about the markup typo on https://github.com/w3c/aria/blob/2021-12_CRD/index.html#L12869? I don't understand that part of the editorial process yet.
