### ISSUE TITLE
Two typos in section "11. Privacy and Security Considerations"

### ISSUE THREAD

**Issue by OwenEdwards** [w3c/aria#1672]
In https://www.w3.org/TR/wai-aria-1.2/#privacy-and-security-considerations, the words "programmatic" and "specification" are misspelled:

"In accordance with Web Platform Design Principles, this specification provides no _programatic_ interface to determine if information is being used by Assistive Technologies. However, this _specificaton_ does allow an author to present different information to users of Assistive Technologies ..."

should be:

"In accordance with Web Platform Design Principles, this specification provides no **programmatic** interface to determine if information is being used by Assistive Technologies. However, this **specification** does allow an author to present different information to users of Assistive Technologies ..."

**Comment by pkra** [comment]
Just to link here https://github.com/w3c/aria/issues/1664#issuecomment-1009915816

**Comment by pkra** [comment]
Wrong issue -- sorry.
