### ISSUE TITLE
Formatting error in section "D.1 Substantive changes since the previous Candidate Recommendation"

### ISSUE THREAD

**Issue by OwenEdwards** [w3c/aria#1673]
In https://www.w3.org/TR/wai-aria-1.2/#substantive-changes-since-the-previous-candidate-recommendation, the text:

- 17-Sep-2021: Revised IDL and enumerated attribute section to reflect implementations
- 30-Aug-2021: removed ariaDescription from IDL section as was added erroneouslyli>
- 14-May-2021: Added Privacy and Security Considerations section
- 05-May-2021: clarify accessible name prohibited definition

The entry for "30-Aug-2021" should not have "li>" at the end.

**Comment by pkra** [comment]
This was originally mentioned in #1664.

**Comment by michael-n-cooper** [comment]
Fixed in 24dbf5347ccb009efd435bf6b0be69d432ddf31f

Note the change log is in the publication branch, we'll need to migrate the content to the main and 1.2 branches as well.

**Comment by pkra** [comment]
Follow up at https://github.com/w3c/aria/issues/1688
