### ISSUE TITLE
Inconsistency with related concepts for landmarks

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1677]
Presently `region`, `form`, and `navigation` all point to their HTML counterparts in their characteristics table.

In comparison, `banner`, `complementary`, `main`, and `contentinfo` do not.

`search` presently has no related concept / element - but that will hopefully change soon.

Seems to me that one of two things happen here:
1. they all just point to their related HTML elements.  Seems easy enough. 
2. only the landmarks that have no special conditions point to their related HTML elements.  e.g., `main` should point to `<main>`, but maybe `region` and `form` should not point to `<section>` and `<form>` because those elements are not always exposed as landmarks.

I think either makes sense, with option 1 being my preference. But, maybe the inconsistency is because of the reasoning for option 2?  

Either way, I'll make a PR to at least make a reference to  `main`, and then I can finish it up based on whatever option the WG decides.

**Comment by JAWS-test** [comment]
[5.1.3 Related Concepts](https://www.w3.org/TR/wai-aria-1.2/#relatedConcept):

> Informative data about a similar or related idea from other specifications. Concepts that are related are not necessarily identical.

Therefore I am also for option 1

**Comment by scottaohara** [comment]
added in the remaining
