### ISSUE TITLE
Define navigation in Important Terms

### ISSUE THREAD

**Issue by chlane** [w3c/aria#1693]
I think defining `navigation` in the[ Important Terms](https://www.w3.org/TR/wai-aria/#terms) section of the spec will be helpful. The definition should mention routing. Doing this would support the resolution of https://github.com/w3c/aria/issues/1353. A link to the definition of `navigation` will be useful in the [link role](https://www.w3.org/TR/wai-aria/#link) as well.

**Comment by jnurthen** [comment]
Discussed on call - we will not define in ARIA but link to a definition elsewhere

**Comment by jnurthen** [comment]
closing this. If we need a definition when fixing a different issue we can create the term then. I don't propose creating terms without a substantive use.
