### ISSUE TITLE
HTML-AAM: UIA mapping for <label>

### ISSUE THREAD

**Issue by cyns** [w3c/aria#171]
the referenced or contained form element has a UIA LabeledBy property pointing to this element
participates in Name Computation

**Comment by jasonkiss** [comment]
Looks like the first part of this issue (re LabeledBy property) has been addressed: https://rawgit.com/w3c/aria/master/html-aam/html-aam.html#el-label

Re the mention of it participating in the name computation, how we do that for elements generally is being discussed in issue #172, so I'll close this issue.

Please reopen if you have concerns.
