### ISSUE TITLE
Consider revisions to aria-hidden

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1715]
Per all the changes that have occurred over the years to how `aria-hidden` is respected (or not), we need to give the attribute a critical review and determine what portions of the current definition need to be changed or expanded to match reality.

**Comment by jnurthen** [comment]
@scottaohara this issue seems a little generic. Can we close this until you have something more specific?

**Comment by scottaohara** [comment]
yup.  other issues have been made since this one that make it redundant anyway.
