### ISSUE TITLE
Combox example code is missing accessible name for the listbox

### ISSUE THREAD

**Issue by jongund** [w3c/aria#1725]
The `combobox` coding example in ARIA 1.2 does not include an accessible name for the `listbox`, according to the spec, listbox requires an accessible name.
https://www.w3.org/TR/wai-aria-1.2/#combobox

The APG call on 4/19/2022 discussed whether a listbox that is controlled by combobox needs an accessible name and is associated with the following APG issue:
https://github.com/w3c/aria-practices/issues/2290

**Comment by craigkovatch** [comment]
@jongund what was the result of the discussion on the 4/19/2022 call?

**Comment by charmarkk** [comment]
@craigkovatch you can read the [meeting minutes ](https://www.w3.org/2022/04/19-aria-apg-minutes.html)to see the gist of the discussion we had on 4/19.

**Comment by jongund** [comment]
@craigkovatch 
The short answer is that ARIA 1.2 requires an accessible name for LISTBOX.
There is sympathy in the APG that when referenced using `aria-controls` by a COMBOBOX that the accessible name should be optional, but that would require a change in the ARIA spec.

**Comment by a11ydoer** [comment]
This was mentioned at [APG isse 2290](https://github.com/w3c/aria-practices/issues/2290)

**Comment by craigkovatch** [comment]
Thank you for discussing this. I am disappointed with the decision to not update the spec; if we agree it's duplicative it seems like that's the right thing to do. But I appreciate the quick feedback and turnaround, thank you.
