### ISSUE TITLE
Update ARIA IDL to define AccessibilityRole and AriaAttributes instead of ARIAMixin

### ISSUE THREAD

**Issue by mrego** [w3c/aria#1726]
ARIA IDL only defines `ARIAMixin` interface: https://w3c.github.io/aria/#idl-interface

While AOM has 2 interfaces `AccessibilityRole` and `AriaAttributes`: https://wicg.github.io/aom/spec/aria-reflection.html#idl-interface

Both Chromium and WebKit implementations match AOM regarding this:
* Chromium: [accessibility_role.idl](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/accessibility_role.idl) & [aria_attributes.idl](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/aria_attributes.idl)
* WebKit: [AccessibilityRole.idl](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/accessibility/AccessibilityRole.idl) & [AriaAttributes.idl](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/accessibility/AriaAttributes.idl)

Should ARIA spec get updated?

**Comment by jnurthen** [comment]
@cookiecrook can you please let us know what to do with this

**Comment by cookiecrook** [comment]
IIRC, I had originally proposed them separated (role has a broader applicability than the ARIA attrs) but combining the interfaces in ARIA may have been @domenic's suggestion (practically speaking, it's not important to separate since implementations would likely want both). 

Unless @domenic has a reason, I think it makes sense to update the ARIA spec to match the implementations.

**Comment by domenic** [comment]
It's important to merge them for HTML's features which treat them the same, namely ElementInternals.

It is unobservable whether they are a single mixin or two, so implementations don't have much weight here IMO. They can change to update the spec or not, or they could split it into 5 different mixins. It's an implementation choice and not relevant to specs.

**Comment by cookiecrook** [comment]
I think this can be closed then. The original hand-off proposal from AOM to ARIA WG is no longer relevant IMO, but we could clean it up and have the AOM explainer just reference the new portion of the ARIA spec. What do you think @mrego?

**Comment by mrego** [comment]
> 

Sounds good, thanks. I wasn't sure this was relevant or not, but I saw some inconsistency, thanks for the clarifications.
