### ISSUE TITLE
Should aria-errormessage be an ID reference list rather than a single reference?

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#1730]
I'm thinking `aria-errormessage`, like `aria-details` might need to be an ID reference list rather than a single reference.

Use case: A password-creation field which may have/display multiple errors:
* "Password must be between 10 and 35 characters"
* "Password must contain at least one punctuation symbol"

**Comment by scottaohara** [comment]
but that could be achieved by pointing to the id of the parent of those individual messages.  maybe you're right and there's another use case where this could be helpful though?

**Comment by chlane** [comment]
Allowing multiple id references will allow both referencing a parent container or individual messages.

**Comment by mrego** [comment]
JFYI WebKit already support a list of ids for `aria-errormessage`.

**Comment by mrego** [comment]
I've drafted a PR in case we want to make this change: #1802

**Comment by cyns** [comment]
Core-AAM specifies multiple nodes for IA2 and ATK/ATSPI. 
UIA [ControllerFor](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids#:~:text=UIA_ControllerForPropertyId) can take an array, so we can change that mapping to multiple nodes - maybe using array language in linked UIA docs

Mac: 
Property: AXValidationError: textual content of the referenced element

@cookiecrook said in tpac meeting that it can be changed to a multiple elements, so this should be ok

**Comment by mrego** [comment]
BTW, it looks like WebKit code is using `AXErrorMessageElements` for this: https://github.com/WebKit/WebKit/blob/597d9d53ad4bc9ccc50eb87259778167ecf69329/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm#L2636
