### ISSUE TITLE
Should links have "Children Presentational: True"?

### ISSUE THREAD

**Issue by sivakusayan** [w3c/aria#1748]
I'm not sure if this was a mistake or intentional, but is there a reason that the link role doesn't have the "Children Presentational: True" flag? From what I understand, the purpose of this flag is to reinforce the rule that interactive elements shouldn't be inside interactive elements, and links certainly seem interactive to me.

Link to documentation: [ARIA 1.3 Link Role Documentation](https://w3c.github.io/aria/#link)

**Comment by pkra** [comment]
"Children Presentation: true" is stronger than "no interactive descendants". From https://w3c.github.io/aria/#childrenArePresentational

> 5.2.9 Presentational Children
> [...]
> The DOM descendants are presentational. User agents SHOULD NOT expose descendants of this element through the platform accessibility API. 

So for example, a heading wrapped in a link would be no longer be exposed as a heading in the accessibility tree. The proposed change would break a lot of content.

**Comment by sivakusayan** [comment]
Thank you for the example - I didn't consider that implementation at all. The reason I brought this up was because I thought it could possibly prevent bugs like FreedomScientific/VFO-standards-support#642, where it seems like JAWS is making some decisions based on the children of the link. I guess that processing is indeed necessary though.

Closing this because I also agree that this proposal would be a breaking change.
