### ISSUE TITLE
What is the name of the ‘press’ state within the ‘press-and-release’ cycle?

### ISSUE THREAD

**Issue by jonathantneal** [w3c/aria#1749]
# Describe your concern

When I click a button using a pointer or space bar, my understanding is that this a [‘press-and-release’](https://w3c.github.io/aria/#desc-aria-pressed) cycle.

During the ‘press’ and before the ‘release’; what is the name of this state?

If the name of this state is ‘pressed’, how might I distinguish it from [`aria-pressed`](https://w3c.github.io/aria/#aria-pressed) when discussing accessibility?

# Link to the version of the specification or documentation you were looking at at.

Link to documentation: https://w3c.github.io/aria/

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?

Yes.

**Comment by cookiecrook** [comment]
For a transient visual effect, you can utilize the `:active` pseudo-class on some elements, or JavaScript handlers for mousedown. 

If you're asking about what should be exposed to the accessibility APIs, that level of interaction transience isn't usually important to AT interaction. If you have a specific need where you think this is relevant for AT or the system to convey, please help us understand your use case better. Thanks!

**Comment by cookiecrook** [comment]
Or if this is just about terminology in an verbal explanation, I'd suggest any of the following may be okay: active, mousedown, press-before-release, etc.

**Comment by jonathantneal** [comment]
Thank you, @cookiecrook. I appreciate you clarifying that this is a transient state. I would place it somewhere between `:hover` and `:focus`, as `:active` can be activated with both a pointer or keyboard *.

I now see this issue is separate from ARIA, so I’ll close it with this final lament —

Without a specification claiming any particular term for this state, it makes the communication or implementation of ‘press-before-release’ transient feedback much more difficult to discuss or implement. If I adopt the term "press" then I think I will confuse authors of the meaning of `aria-pressed`. If I adopt the term `mousedown` then I inadvertently exclude all keyboard users. If I use the term `:active` then I’m very close * to descriptive accuracy, but I’m also misleading web developers. So, I appreciate the response, and that any response was even offered, but I’m still unsure where to get the answer I am looking for.

_*  The `:active` pseudo class is only keyboard activated from a form control element._
