### ISSUE TITLE
Editorial changes for ‘Translatable Attributes’

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1761]
@bert-github wrote:

The change to the draft specification (in [section 6.4 ‘Translatable Attributes’](https://w3c.github.io/aria/#translatable-attributes)) mostly defines the language of each attribute that contains text. But a few things remain unclear:

1) The ‘lang’ attribute is not the only thing in HTML that defines the language of an element. The text should probably just say that the language of the attribute is the same as the language of the element, without talking about the ‘lang’ attribute, but referencing the HTML5 specification (in particular the [definition of language](https://html.spec.whatwg.org/#language) in section 3.2.6.2.)

2) The new text implies that the language is just for making translations, but information about the language is also needed for proper pronunciation and layout. (I.e., for ‘rendering’, in the terms of the ARIA specification.)

3) What do you do if the attribute happens to be in a different language than the contents of the element? Or if two attributes have different languages?

   In the case of an aria-label attribute, you could replace aria-label by aria-labelledby and point to a separate element. (Maybe that should be a note or an example?)

   But what do you do for aria-valuetext?

4) For visual rendering, the direction of the text may also be needed. E.g., if the document is in Arabic and the attribute contains a phone number with dashes or spaces between the digits, it is important that the whole number is displayed 
left to right, otherwise the first group of digits will be displayed to the right of the second group. ([Here is an explanation](https://www.w3.org/International/articles/inline-bidi-markup/index.en#usecase7).)

Possibly the direction could be taken from the element's ‘dir’ attribute, but, like for the language, that leaves a problem when the attribute's direction is different from the direction of the element's content. E.g., you wouldn't want to set the ‘dir’ attribute on a slider, because it reverses the slider.

_Originally posted by @bert-github in https://github.com/w3c/aria/issues/1365#issuecomment-1128042375_

**Comment by cookiecrook** [comment]
@bert-github wrote:
> What do you do if the attribute happens to be in a different language than the contents of the element? Or if two attributes have different languages?

Do you know of a use case for that? If so, I would expect HTML would need to address it more broadly (e.g. `input title="" value=""`) rather than have one-off handling in the ARIA spec.

**Comment by cookiecrook** [comment]
@bert-github does the PR address your other concerns?

**Comment by r12a** [comment]
Editorial nit: Second sentence in the PR is not something that ARIA defines, it's defined in the HTML5 spec already.  Therefore it may be better to break that sentence out into an informative note.  

Otherwise, the i18n WG is satisfied. Thanks.
