### ISSUE TITLE
Most of ARIA reflection attributes must have CEReactions extended IDL attribute

### ISSUE THREAD

**Issue by rniwa** [w3c/aria#1767]
Since ARIA reflection attributes such as [`ariaLabel`](https://w3c.github.io/aria/#dom-ariamixin-arialabel) mutate element's content attribute, they must have [`CEReactions`](https://html.spec.whatwg.org/multipage/custom-elements.html#cereactions) extended IDL attribute.

**Comment by pkra** [comment]
Is this a duplicate of #1242? (Recent PR for that is at #1766.)

**Comment by rniwa** [comment]
Indeed, it is! It's a shame we had that issue filed last year and didn't fix it until now!
