### ISSUE TITLE
HTML-AAM: add note about UIA mapping to "Text"

### ISSUE THREAD

**Issue by cyns** [w3c/aria#177]
Add a note about UIA mappings to "Text"
Note: UIA Text is generally not a separate node in the accessibility tree, but just part of the Text Pattern implementation for the whole page. However, it will be added to the tree as a separate node if it has @aria- attributes or tabindex specified.

This could be added in each cell with Text mapping, or with an asterisk or footnote or something.

**Comment by cyns** [comment]
@stevefaulkner @jasonkiss this is another one that applies to multiple elements. What's the best way to do this in the spec so it's clear but not redundant?

**Comment by jasonkiss** [comment]
Since we now have a couple of these scenarios (this one and [the input/label one](https://github.com/w3c/aria/issues/159)), I'm starting to think a set of footnotes placed right after the table is starting to make sense.

**Comment by jasonkiss** [comment]
Added separate note to Notes section prefacing the role mapping table. See merged PR #424. Closing.
