### ISSUE TITLE
Consider adding an additional subheading under the role="presentation" entry

### ISSUE THREAD

**Issue by sivakusayan** [w3c/aria#1772]
# Link to the version of the specification or documentation you were looking at at.
https://www.w3.org/TR/wai-aria-1.2/#presentation

# Describe the change
Would it make sense to add an additional subheading above the paragraphs talking about `role="presentation"` inheritance for child elements? I like to link out to the specs a lot, and it would be nice if I could directly link to the inheritance rules for this role instead of having people find the paragraphs I'm referring to themselves.

# Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?
Yes

**Comment by spectranaut** [comment]
Seems like a reasonable suggestion, would you be comfortable opening a PR with this change, @sivakusayan ?

**Comment by sivakusayan** [comment]
Yeah, I would be happy to do this sometime this/next week 🙂
