### ISSUE TITLE
heading level "Note regarding the ARIA 1.1 none role." is wrong

### ISSUE THREAD

**Issue by pkra** [w3c/aria#1773]
E.g., in https://github.com/w3c/aria/blob/6d46a9a0f694a4a0ae9f1fc7cdcf4d9299ac7729/index.html#L6299 the heading in the note is marked up as `h5` but in https://w3c.github.io/aria/#note-regarding-the-aria-1-1-none-role-0 it comes out as `h3`. 

This is problematic since the automatically generated heading for the role's entry itself is an `h4`.

Maybe we shouldn't do headings inside notes. It definitely seems risky to add a fixed heading level below an automatically generated one.

**Comment by pkra** [comment]
Spotted via #1772

**Comment by sivakusayan** [comment]
I haven't actually stepped through with a debugger, so I could be totally off the mark, but I think the relevant codepaths (and why this happens) is as follows:

1. The heading level for role entries are hardcoded to be `h3` in [`ariaAttributeReferences`](https://github.com/w3c/aria/blob/16dfd46713ea7432a7128cbdf23cc53f42e8ee24/common/script/ariaChild.js#L150).
2. Respec has [`fix-headers.js`](https://github.com/w3c/respec/blob/471d6f5b20aab17e0b9db969418ef53f4b568d4c/src/core/fix-headers.js#L15) which automatically changes the heading level based on how many `section` parents a heading has.

I'm guessing this is some ordering issue where the second step happens before the first step?

I was also not sure if the change proposed in #1772 should still be done after seeing this in the [style guide](https://github.com/w3c/aria#document-style), unless I'm misunderstanding something:

> Subheadings: only use sub-headers (<h{x+1}> following <hx>) if there are at least two of them. If there isn't more than two sub-sections, it isn't a sub-section and should be integrated into the parent section.
