### ISSUE TITLE
Link to “ID Reference List” anchor in “Identifies” definition is broken

### ISSUE THREAD

**Issue by barnabywalters** [w3c/aria#1789]
Under https://w3c.github.io/aria/#dfn-identifies, the link to [ID reference list](https://w3c.github.io/aria/valuetype_idref_list) is broken. It links to the nonexistent https://w3c.github.io/aria/valuetype_idref_list rather than the correct https://w3c.github.io/aria/#valuetype_idref_list

**Comment by pkra** [comment]
Thanks for catching this -- https://github.com/w3c/aria/pull/1790 should fix it.
