### ISSUE TITLE
HTML-AAM: UIA mapping for <tr>

### ISSUE THREAD

**Issue by cyns** [w3c/aria#180]
Generally not mapped. If the element must be included per Core-AAM Section 5.1.2, map as <code>Group</code>.

**Comment by cyns** [comment]
Need to add respect link to CORE-AAM

**Comment by jasonkiss** [comment]
So it's not going to be normally mapped as role=row? Okay if not, but then wouldn't it be mapped as role=row (as DataItem ControlType) when it is included in the a11y tree?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#15
