### ISSUE TITLE
Add HTML5's output element as a Related Concept for role="status"

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria#1801]
I find the **Related Concept** field tremendously useful (where it appears). 

HTML in ARIA maps `<output>` to the status role. Can we add this as a Related Concept to the ARIA spec for status?

**Comment by JAWS-test** [comment]
I don't know if that would be correct. While output is a live region, the concepts are quite different:

output:

> The [output](https://html.spec.whatwg.org/#the-output-element) element [represents](https://html.spec.whatwg.org/#represents) the result of a calculation performed by the application, or the result of a user action.

status

> A type of [live region](https://www.w3.org/TR/wai-aria-1.2/#dfn-live-region) whose content is advisory information for the user but is not important enough to justify an [alert](https://www.w3.org/TR/wai-aria-1.2/#alert), often but not necessarily presented as a status bar.

**Comment by scottaohara** [comment]
>Concepts that are related are not necessarily identical

i don't see any reason not to mention it like other html elements with implicit aria roles are.
