### ISSUE TITLE
Richer text for aria-live

### ISSUE THREAD

**Issue by NSoiffer** [w3c/aria#1806]
# Description of bug or feature request

I don't have a specific ask (but do lean towards a potential solution below). I mainly want to raise awareness of a problem I've come up against when implementing accessible math editors. As the user navigates an expression, the math editor needs to tell AT what to say. `aria-live` is a good solution except:

* there is no way to control pronunciation. This is particularly important in English for "a" which can be spoken with a short or long "a" sound. In math, it should always be a long "a", but most speech engines use the short "a" and end up saying something like "ah squared" which can be very confusing (a short "a" is often lost in a longer expression).
* there is no way to control pausing or other prosody. Not surprisingly, speech engines are not tuned to produce speech geared towards math (and there is no way to tell them that a string is math). So barring AI in speech engines that recognizes math speech and changes the way a speech engine pauses, etc., a longer string of math text is very monotonic and harder to parse/listen to.
* there is no way to synchronously highlight parts of an expression with the speech. This is important for people with some visual processing impairments such as dyslexia.

One solution would be to allow SSML in `aria-live` since this can be sent to most speech engines. However, it needs to be marked as SSML so that are the markup is not spoken. SSML is probably easy to detect, but I think it would be best to add an attribute that says it is SSML: it is possible someone actually wants to speak the markup (although very unlikely). Speech engines don't auto-dectect the markup and need to be told it is SSML/set in SSML mode.

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?

If unknown, leave blank. If relevant, link bug.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?

Probably no change is need.

# PR tracking (for feature tracking, leave as is when submitting)

* ARIA PR:
   * Editor's Draft commit:
   * Working Draft commit:
* Core AAM PR:
* AccName PR:
* APG PR:

# Implementation tracking (for feature tracking, leave as is when submitting)

* WPT test:
* Implementations (link to issue or when done, link to commit):
   * WebKit: [ISSUE]()
   * Gecko: [ISSUE]()
   * Blink: [ISSUE]()

**Comment by edsummersnc** [comment]
Thank you @NSoiffer for opening this issue. I think the need for better control of speech is broad. aria-live is generally used as a workaround for complex UI controls or interactions that are not supported by ARIA. My personal experience is with non-visual access to data visualizations, grids, etc.

**Comment by edsummersnc** [comment]
I opened a related issue: #1809
