### ISSUE TITLE
Might we have an ARIA role for 'accessibility statement'?

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria#1822]
# Accessibility Info
I'd like to propose an ARIA role for... accessibility statements. This is a **semantic** category where (the role promises that) accessibility info will be available. A subset of role="contentinfo" perhaps?

The element that has this role may be a hyperlink or some part of a contentinfo block. For more complex RIA content, this might provide fine-grained guidance for using an elaborate feature with one or more ATs,

The focus of these statements should be where to find guidance, places to report errors, links to relevant AT vendor support, and so on. If you're disabled and/or use an AT and you're struggling, you should go to this place first. Accessibility conformance reports (whether VPAT-based or not) would be available here. Ideally, this would be a site-wide thing like "contentinfo".

AT vendors can then provide a shortcut for this info 

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?
Yes

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?
Preferably, yes.

**Comment by cookiecrook** [comment]
My first reaction is that it sounds too specific for an ARIA role. Then again, some EU countries are starting to require Accessibility Statements on some sites, so open to be convinced. 

How would this make a difference for AT? Are you expecting new AT feature support, or just a new role description?

**Comment by cookiecrook** [comment]
Also consider an adhoc `rel=a11yinfo` on a footer link. Speciaty `rel` values are pretty flexible, so general agreement from stakeholders and evangelism could help that move forward.

**Comment by brennanyoung** [comment]
Oh! I like `rel`. I thought it had fallen out of favour. That would be just fine.

**Comment by cookiecrook** [comment]
Great. Closing!

**Comment by jnurthen** [comment]
What a splendid idea - indeed there is already a matching rel="accessibility" in the Brainstorming section at https://microformats.org/wiki/existing-rel-values#brainstorming

**Comment by pkra** [comment]
schema.org might also be a good place to connect with. There's already https://schema.org/accessibilitySummary alongside accessibilityFeature, accessibilityHazard, and accessMode* properties (from dpub/epub land). It seems like a tangible benefits for users if accessibility statements get surfaced in search results.
