### ISSUE TITLE
ARIA 1.1 Recommendation: Schemata section has a leftover TODO item in it

### ISSUE THREAD

**Issue by maryjom** [w3c/aria#1835]
The first paragraph of the Schemata section reads:

> WAI-ARIA roles, states, and properties are available in a number of machine-readable formats to support validation of content using WAI-ARIA attributes. WAI-ARIA is not finalized, however, so these files are subject to change without notice. Todo: Remove disclaimers about not final at rec.

Need to remove the Todo sentence.

# Link to the version of the specification or documentation you were looking at

Link: [https://www.w3.org/TR/wai-aria-1.1/#a_schemata](https://www.w3.org/TR/wai-aria-1.1/#a_schemata)

Does the issue exist in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)? No, this Schemata section doesn't exist in ARIA 1.2 or or the editor's draft of ARIA 1.3. Not sure if it was moved to another document or this section simply deleted.

**Comment by pkra** [comment]
This appendix was removed, see https://github.com/w3c/aria/issues/977 and https://github.com/w3c/aria/pull/980 for some discussion.

I don't think we can change v1.1 at this point.

**Comment by pkra** [comment]
This issue was discussed at this week's WG meeting. All we can do at this stage is to issue an official errata for 1.1. Since 1.2 is in CR and hopefully REC soon, nobody can see a practical benefit from doing so.

Thank you again for raising this!
