### ISSUE TITLE
Consider BOLSTERING aria-flowto

### ISSUE THREAD

**Issue by medeaoblongata** [w3c/aria#1836]
`aria-flowto` is part of ARIA 1.2 but flaws in the specification have led to very poor usage stats, and only one fudged implementation in the JAWS screen reader.

Some of the flaws are mentioned in [the call for the attribute's deprecation](https://github.com/w3c/aria/issues/630) on this board, which is still open at time of writing.

The criticisms in that discussion are valid, but I am not alone in being skeptical about the proposed remedy. After much consideration, I would like to push not for deprecation, but for the opposite, **bolstering the spec**, not least because the proposed replacement `aria-details` does not address **any** of the flaws in the `aria-flowto` spec, and (IMO) is conceptually inappropriate for the use case that `aria-flowto` addresses head-on: Offering an alternate, perhaps branching reading order, at the user's discretion, independent of DOM order.

Let's **fix** the flawed spec of `aria-flowto` so that AT vendors and content authors have clearer expectations about how it should actually work.

To improve it we need UA, AT and author guidance for

- What (if any) accessible name should indicate any flowto target in the accessibility tree?
- Is there a difference between a connector and a flowto target? How will that be expressed?
- Do we need to think about connector direction or 'type'?
- Guidance for AT vendors when there is only one flow target.
- Guidance for AT vendors about how to offer a choice from among **more than one** flow target?
- Some considerations/guidance about AT round trip (flow to, and come back, 'history')

In this case, the dismal usage-stats works in our favour. We can move fast without actually breaking things.

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?
Perhaps.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?
Very much yes. I want to see an example showing how to make directed graphs (e.g. flowcharts, sequence diagrams) that work in AT 'browse-mode'. The pattern should **not** require operable elements except (perhaps) `<a>` or `link`.

**Comment by pkra** [comment]
We've discussed this on today's F2F. We have changed the title of #630 to make it clear that we are having a wider discussion. 

We will also add #630 to next week's agenda. But the WG doesn't see a benefit of keeping separate threads.

**Comment by cookiecrook** [comment]
WG is considering deprecation, due to the problems mentioned above, and others that have been enumerated over the years.
- https://github.com/w3c/aria/issues/2889
