### ISSUE TITLE
should aria-expanded be allowed on searchbox and textbox?

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1875]
# Describe your concern

Searchbox and textbox allow aria-autocomplete

aria-autocomplete says "When an element has aria-autocomplete set to list or both, authors SHOULD use the [aria-expanded](https://w3c.github.io/aria/#aria-expanded) state to communicate whether the element that presents the suggestion collection is displayed."

aria-expanded is not allowed on searchbox and textbox

# Link to the version of the specification or documentation you were looking at at.

https://w3c.github.io/aria/#aria-autocomplete

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?
Yes

**Comment by spectranaut** [comment]
Discussed at today's meeting: https://www.w3.org/2023/02/23-aria-minutes#t05

**Comment by jcsteh** [comment]
aria-expanded not being supported on textbox makes it difficult for screen readers to improve support for autocompletes in code editors such as VS Code. In that case, the code editor definitely isn't a combobox. I see in the WG minutes that this case was discussed and I acknowledge @mcking65's point that technically, the span of text is being expanded, not the whole textbox. However, I'm not convinced this really matters from a user perspective. As far as the user is concerned, they're only dealing with one set of suggestions at a time and that set of suggestions is linked to the code editor.

See https://github.com/nvaccess/nvda/issues/10887#issuecomment-1748168035 for the discussion with led me to raise this.

See also #1680, which should perhaps be closed in favour of this one.

**Comment by scottaohara** [comment]
closing this issue in favor of the existing issue, 1680 - simply because there was more discussion in that issue than this one.

i've carried over the comments / link to the minutes where this issue was discussed into the other one
