### ISSUE TITLE
HTML-AAM: UIA mapping for @lang

### ISSUE THREAD

**Issue by cyns** [w3c/aria#191]
open question. 
There is a culture text attribute in UIA, but TTS engines aren't using it. They're using heuristics instead to determine language. Not convinced that mapping this is valuable. Would like input...

https://msdn.microsoft.com/en-us/library/windows/desktop/ee872119(v=vs.85).aspx

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#19
