### ISSUE TITLE
[from public-aria] listbox example code lacks name by author

### ISSUE THREAD

**Issue by pkra** [w3c/aria#1911]
From https://lists.w3.org/Archives/Public/public-aria/2023Apr/0009.html:

> According to the spec each listbox must have a name by author.
> In the Spec’s Example 6 (https://www.w3.org/TR/wai-aria-1.2/#example-6) is this missing.

**Comment by jnurthen** [comment]
This is already fixed in the editors draft.
https://w3c.github.io/aria/#example-9

**Comment by pkra** [comment]
Thanks, James.
