### ISSUE TITLE
Accessibility Parent/Child follow ups

### ISSUE THREAD

**Issue by smhigley** [w3c/aria#1930]
Follow up from F2F meeting discussion: https://www.w3.org/2023/05/04-aria-minutes#t01

1. Add clarification on "intervening" or revisit the word
2. Editorial: turn definition into bulleted list
3. Editorial: add note that accessibility child/parent is not the same as the browser/platform accessibility tree parent/child
4. Figure out where examples should go relative to the definition (i.e. that the definition would benefit by being adjacent to HTML example snippets)
5. Add "Accessibility descendant" definition & use in place of unclear use of descendant (#1150)
6. Review/remove remaining use of owned/owning elements (#1161)
7. Follow up on #1817

**Comment by spectranaut** [comment]
I think also in the definition of "accessibility parent" we should make clear it is an "exclusive or". That is sort of over lapping with #1817 like you said in the F2F @smhigley, but I still think that the fact that "child" is all of the things and "parent" is one thing should be made clear.

**Comment by spectranaut** [comment]
Also I'm going to take a stab at 5. accessibility parent, because that will unblock 6.!
