### ISSUE TITLE
ARIA projects should include lint traps: white space, etc

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1934]
ARIA projects should include lint traps: white space, etc

I noticed a lot of the ARIA projects have inconsistent spacing: 
- EOL white space
- Tabs vs spaces in different specs
- Sometimes tabs vs spaces in the same doc, or even leading with a mixture in the same line. 

It’d be useful to set up a linter (like WPT’s) for whitespace and other nitpicks.

Note: I don’t care whether it’s spaces or tabs, as long as it’s consistent.

**Comment by cookiecrook** [comment]
Looks like @nschonni may have some or all of this already in: https://github.com/w3c/aria-common/pull/49

**Comment by pkra** [comment]
Latest experiment: https://github.com/w3c/graphics-aria/pull/10

**Comment by pkra** [comment]
Closing this in favor of https://github.com/w3c/aria-common/issues/99
