### ISSUE TITLE
Support aria-readonly on rows in grids

### ISSUE THREAD

**Issue by BrettLewisVispero** [w3c/aria#1972]
### # Description of bug or feature request
Currently, aria-readonly does not apply to role="row". This looks like an oversight in the spec. Aria-disabled is supported on role="row" and it seems like a logical extension to the specification to add aria-readonly to row.
There are grid authors adding aria-readonly="true" to role="row" expecting the readonly state to inherit to the grid cells but row does not support aria-readonly.
Grid authors may wish to indicate that only certain rows in a grid are readonly. At present the only way to accomplish this with ARIA is to add aria-readonly to the individual grid cells.

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?

If unknown, leave blank. If relevant, link bug.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?
Yes, the practices guide describes adding aria-readonly to grid cells but not to rows. This would need to be added.

**Comment by spectranaut** [comment]
Discussed briefly in an ARIA meeting: https://www.w3.org/2023/09/28-aria-minutes#t06

**Comment by mcking65** [comment]
@BrettLewisVispero 

Per discussion in today's ARIA WG meeting, there are broad concerns with the ambiguities in the ARIA specification related to how readonly and disabled trickle down to descendants (see related #2052). Current consensus is that the working group should consider adding constraints to where readonly and disabled can be used. That would mean that we may consider changes to the specification that require authors to declare readonly and disabled directly on the elements that should be readonly or disabled. For now, there isn't working group support, then, for expanding the number of grouping elements that support readonly.
