### ISSUE TITLE
"Required Accessibility Parent Roles" in characteristics table of "caption" role does not match the definition above

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/aria#1974]
While reviewing the specs for the "caption" role, I've realised that the characteristics table, in particular the "Required Accessibility Parent Roles" row, is not fully reflecting the requirements listed above.

In particular 
> The caption is a descendant of a [group](https://w3c.github.io/aria/#group), [figure](https://w3c.github.io/aria/#figure), [grid](https://w3c.github.io/aria/#grid), [radiogroup](https://w3c.github.io/aria/#radiogroup), [table](https://w3c.github.io/aria/#table), or [treegrid](https://w3c.github.io/aria/#treegrid).

while in "Required Accessibility Parent Roles" row, only
> figure, grid, table, treegrid
are listed

https://w3c.github.io/aria/#caption

**Comment by spectranaut** [comment]
also related to: https://github.com/w3c/aria/issues/1930
