### ISSUE TITLE
cell and treegrid roles are the only ones without any reference to the definition of "owned"

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/aria#1976]
"cell" and "treegrid" roles are the only ones containing "owned by" without any reference to the "owned" definition. For the other roles, there is at list one (usually the 1st one) "owned" anchor to its definition.

Added anchors also to "cell" and "treegrid" roles for a better understanding and comprehension of the requirements.

- https://w3c.github.io/aria/#cell
- https://w3c.github.io/aria/#treegrid

**Comment by spectranaut** [comment]
thanks for this! I'll fix with the other tasks here: https://github.com/w3c/aria/issues/1930

**Comment by spectranaut** [comment]
Oh! I didn't notice you already opened a PR - thanks! :)
