### ISSUE TITLE
HTML-AAM: @title on <abbr> and <dfn> needs to be covered in name calculation

### ISSUE THREAD

**Issue by cyns** [w3c/aria#199]

**Comment by MichielBijl** [comment]
Is this the case for anchors?

**Comment by cyns** [comment]
Anchors seem different. Abbr and dfn provide strings to replace or augment the target, which seem like they should be part of how the name and description are calculated. 

Date: Wed, 13 Jan 2016 00:38:58 -0800

**Comment by MichielBijl** [comment]
+1

—Michiel

**Comment by rahimabdi** [comment]
@scottaohara recently raised a PR prohibiting name for `<abbr>` and `<dfn>` however, similar to generics, `title` could be used for accDescription.
