### ISSUE TITLE
How will aria-actions evolve?

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#1999]
How will [aria-actions](https://github.com/w3c/aria/issues/1440) evolve (by [annotation spec](https://docs.google.com/document/d/1DYrsHDk6Y9071A1fRg8g8NZ_DtGYraX5BcVY-taBzMQ/edit?pli=1#heading=h.3ouywf2zdx7))? We need this SOON. 

Are [context menus](https://github.com/w3c/aria/issues/1971) for list items a viable alternative?

**Comment by spectranaut** [comment]
@smhigley is there anything to discuss about aria-actions at TPAC in September?

**Comment by scottaohara** [comment]
closing as this was to prompt discussion for the f2f, and we don't need an issue asking how another feature/issue that is working on, will evolve.  further questions can be asked in the existing issue / as part of the PR(s)
