### ISSUE TITLE
Status of UA/AT support for Accessibility (ARIA) Notification API

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#2001]
Status of UA/AT support for [Accessibility (ARIA) Notification API](https://github.com/WICG/aom/blob/gh-pages/notification-api.md) 

See also https://github.com/w3c/aria/discussions/1958#discussioncomment-6223785

Questions:

The problem using different live regions firing at same time and leave AT the sortout who wins and the queuing hinders broad implementation of live regions for component state signaling in app builder frameworks - is this solved with the Notification API?

Is there already a testable working implementation? Which Browser-Screen Reader combination has to be used to test?

**Comment by scottaohara** [comment]
this issue is premature.  We've been talking about spec'ing out the proposal for the notification API at the end of each ARIA meeting for the last few weeks.  There is no status update for implementation support of the API because it's still being discussed/worked on.

**Comment by stes-acc** [comment]
It is not an issue - was filed under "Questions". Github all calls them issues by default.

**Comment by scottaohara** [comment]
@stes-acc i have updated my reply

**Comment by spectranaut** [comment]
We are already discussing notifications during the F2F.
