### ISSUE TITLE
Can combo boxes be implemented with lists in popups instead of listboxes

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#2003]
Can combo boxes be implemented with lists in popups instead of listboxes?

This is done frequently in various HTML-based frameworks but there is no statement on this in ARIA APG or Spec.

**Comment by scottaohara** [comment]
can you provide examples of what you're referring to - if there are frameworks that are providing this pattern.

what is the use case to do this vs is this potentially just errors that there's no good reason to codify?

**Comment by stes-acc** [comment]
Combos in modern HTML-based frameworks are populated with all kinds of sophisticated stuff because there are real use cases behind that. Banning that by principle as "authoring error" won't make it better - it has a bit of a "don't look up" smell ;)

Starting with the fact that https://github.com/w3c/aria/issues/1440 is there for a reason, devs have simply no option to accomplish this with options in a listbox, they take extended listitems for that that require a list and not a listbox container.

Examples for frameworks with these patterns:

**Comment by spectranaut** [comment]
We an example before scheduling a discussion

**Comment by stes-acc** [comment]
This boils down to the question if "list" can be added to the allowed values of aria-haspopup since applying aria-haspopup on combobox role is perfectly OK in ARIA spec. 

Currently "list" it is not contained in allowed values, so maybe better create a separate issue for this and closing this one. I'm OK with it.

**Comment by stes-acc** [comment]
Closed and will be continued as issue for aria-haspopup.
