### ISSUE TITLE
Question regarding aria-haspopup=false

### ISSUE THREAD

**Issue by sivakusayan** [w3c/aria#2013]
[The specification says](https://w3c.github.io/aria/#aria-haspopup):
> [Assistive technologies](https://w3c.github.io/aria/#dfn-assistive-technologies) SHOULD NOT expose the aria-haspopup property if it has a value of false.

Did this mean to say: 
> User agents SHOULD NOT expose the aria-haspopup property if it has a value of false.

Or is the wording correct? I'm asking because the `aria-haspopup="false"` entry in the Core-AAM is not mapped _(well, for all APIs except IA2 it seems)_, which leads me to believe that this quote meant to refer to user agents.

I also notice "Expose" has the definition:
> Translated to platform-specific [accessibility APIs](https://w3c.github.io/aria/#dfn-accessibility-api) as defined in the [Core Accessibility API Mappings](https://w3c.github.io/core-aam/).

which seems like something user agents do rather than assistive technology.

 I'm trying to [address this issue](https://github.com/w3c/core-aam/issues/151) and just wanted to make sure I updated the mapping properly.

**Comment by MarioBatusic** [comment]
Yes, I think the wording is false and schould be: "User Agents".

**Comment by spectranaut** [comment]
If user agents shouldn't surface this value, then only IA2 will have to change in CORE-AAM: https://w3c.github.io/core-aam/#ariaHaspopupFalse

**Comment by spectranaut** [comment]
We discussed this in the [ARIA meeting](https://www.w3.org/2023/09/07-aria-minutes#t04) today and decided that the change should be:

> [Assistive technologies](https://w3c.github.io/aria/#dfn-assistive-technologies) and User Agents SHOULD NOT expose the aria-haspopup property if it has a value of false.

Would you like to make this change @sivakusayan ?
