### ISSUE TITLE
Suggestion - role="none" - EXAMPLE 13

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/aria#2026]
# Describe your concern

Example number 13 provided for the "none" role: https://w3c.github.io/aria/#example-13

In accordance with the specifications for the "img" role, img role children are intended to be presentational. Consequently, assigning the "none" role to a child image appears to be somewhat irrelevant.

It's not wrong but I'm contemplating whether it might be beneficial to relocate the child image, positioning it outside and above the `<div>` element with the "img" role. This adjustment could help clarify the effectiveness of the "none" role, regardless of its container. What are your thoughts on this proposed modification?

If the above makes sense I can open a PR.

**Comment by scottaohara** [comment]
existing issue: https://github.com/w3c/aria/issues/1455

**Comment by giacomo-petri** [comment]
Sorry, I searched for something similar before opening but didn't find it.
Closing as duplicated.
