### ISSUE TITLE
Decide what "draft PR" means

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria#2028]
we should decide what a draft PR means -- does it mean it's ready for review? that it doesn't have consensus?

**Comment by MelSumner** [comment]
1. Draft PR means it's not ready for review (as per the submitter)
2. We should use a label for consensus (e.g., `needs-consensus`)

**Comment by scottaohara** [comment]
just noting since we talked about this a bit more after moving on from this issue - but could add a "do not merge" label for PRs which need review/help to finish - but should not be considered 'drafts' because that should mean 'don't even review yet'

**Comment by spectranaut** [comment]
Ok great it sounds like "drafts" mean "not read for review -- I'll assign myself to update the documentation
