### ISSUE TITLE
Marking of directory as "Deprecated" in all places

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#2029]
# Describe the change

The role <code>directory</code> is "Deprecated" since ARIA 1.2. Unfortunately, this is not mentioned in the places where this role is referred to. This should still be done, analogous to the attributes that are deprecated. Alternatively, the reference to directory can simply be removed.

* https://w3c.github.io/aria/#namefromauthor
* https://w3c.github.io/aria/#document_structure_roles
* https://w3c.github.io/aria/#role_definitions (listitem)
* https://w3c.github.io/aria/#list
* https://w3c.github.io/aria/#listitem 

# Link to the version of the specification or documentation you were looking at

Link to documentation: https://w3c.github.io/aria

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?

Yes

**Comment by scottaohara** [comment]
not against the idea, but also not sure it's necessary?

for instance, there are various features in HTML which are referenced in different parts of the spec, but they aren't called out as deprecated/obsolete in each instance.  The marquee element is a good example where it is listed both under 'widgets' without any mention of its obsolete status, but the element definition has been moved to the 'obsolete' section.  

Additionally, there is a difference between calling out attributes as being deprecated on specific roles (as was done in ARIA 1.2) vs being deprecated outright.  E.g., aria-dropeffect and aria-grabbed are both deprecated attributes, but similar to directory this is mentioned in their definition, not each time they're referenced.

might be worth bringing this up in the F2F discussion about [future efforts for removal/deprecation process](https://github.com/w3c/aria/issues/1990#issuecomment-1664348686)

**Comment by spectranaut** [comment]
I will add to the agenda for TPAC

**Comment by jnurthen** [comment]
agree that we don't need to do this.

**Comment by jnurthen** [comment]
closing as not planned
