### ISSUE TITLE
Usage of "alternative text" in "presentation" role description

### ISSUE THREAD

**Issue by rahimabdi** [w3c/aria#2059]
# Describe the change

The `presentation` role section contains a reference to "alternative text" and it is the only such reference in the entire ARIA 1.2 spec. All other references appear to use "text alternative" and this aligns with WCAG (which has no instances of "alternative text" usage).

Should this instance be changed to "text alternative" for consistency?

# Link to the version of the specification or documentation you were looking at

Link to documentation: https://www.w3.org/TR/wai-aria-1.2/#presentation

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?

Yes

**Comment by rajivnas** [comment]
The suggestion to change "alternative text" to "text alternative" makes sense for consistency, as WCAG also uses "text alternative." This change would align the ARIA spec language with established accessibility terminology, enhancing clarity for readers who may be familiar with WCAG.

Regarding practical applications, it’s always useful to see how "text alternatives" are implemented in tools and projects to better understand their impact on accessibility. For example, different case-alternating tools, such as those found in accessibility-oriented text processing sites, demonstrate this principle by providing clear text outputs and formats for screen readers and other assistive technologies.
