### ISSUE TITLE
Consider working with PDFA on a PDF-AAM document

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#2070]
I attended [PDF Week 2023](https://pdfa.org/event/pdf-week-fall-2023/) a few weeks ago. One of the discussions in the PDF/UA liaison working group meeting (PDF/UA LWG) was on a [work-in-progress spreadsheet](https://pdfa.org/bridging-pdf-and-web-accessibility/)([direct Excel doc link](https://pdfa.org/wp-content/uploads/2023/07/2023-07_PDF-objects-and-API-mappings.xlsx)) that cross-referenced a lot of the concepts in [Core-AAM](https://w3c.github.io/core-aam/) and [HTML-AAM](https://w3c.github.io/html-aam/). 

I suggested it may be appropriate to work together so that the mappings would not be duplicated in multiple documents. The Excel doc could be converted to an AAM doc (leveraging a lot of the shared spec editing tools like ReSpec) and cross-referencing Core-AAM or HTML-AAM mappings, instead of duplicating them. While I did not agree to be a primary editor, I did offer to help @PaulRayius get it set up and running, if he and other responsible parties think it's a good path forward.

I do not know about the copyright, intellectual property, or other legal implications of a joint deliverable between W3C and PDFA. Counsel on both sides should consider that and probably develop a memorandum of understanding (MoU) or some other contractual agreement. FYI @DuffJohnson and @michael-n-cooper

**Comment by cookiecrook** [comment]
Filed in ARIA b/c that WG manages most AAM specs, but feel free to move if necessary.

**Comment by PaulRayius** [comment]
Thanks, James!

**Comment by DuffJohnson** [comment]
Thanks, James!

I was unable to attend this week’s PDF/UA Processor LWG meeting; I’ll check in with Paul to see if this possibility was reviewed and what that group wants to do. Assuming a positive response and some level of detail I’ll follow up with Michael.

Duff Johnson
PDF Association

**Comment by zakkinsey** [comment]
Hi @DuffJohnson, 

I was able to attend the PDF/UA Processor LWG meeting this week and this was discussed and I offered to head this parallel project up for the group so @PaulRayius can help keep the group primarily focused on their initial task of mapping the objects and generating the information to fill in this format. 

My next step was to get with you actually, and this is a great step in that direction. @cookiecrook brought up good points above we weren't able to answer around copyright, intellectual property, etc. 

Thanks,
Zak Kinsey
TargetStream Technologies

**Comment by DuffJohnson** [comment]
Thanks Zak!

Sounds good. Please send me a note offline with the questions and I’ll get back to you with answers.

Duff.

**Comment by cookiecrook** [comment]
Making sure you both know the conversation is public here: https://github.com/w3c/aria/issues/2070

Last few replies led me to believe you might think these were private email replies. No Reply Necessary. I'll delete this message from the public issue.

**Comment by cookiecrook** [comment]
Source PDF roles doc is here:
https://docs.google.com/spreadsheets/d/1BfMohZ7uDp2XtEvu71QraU6O7dLjMgEY7DkUSnhtx2M/edit?gid=1201054668#gid=1201054668

Likely access limited at the moment... I'll use that as the source and meet with Paul to get the AAM doc started.

**Comment by cookiecrook** [comment]
Editor's Draft: https://w3c.github.io/pdf-aam/
Issue repo: https://github.com/w3c/pdf-aam/issues
Source repo: https://github.com/w3c/aria/tree/main/pdf-aam

I think this issue (#2070) can be closed now.

**Comment by cookiecrook** [comment]
Thanks @daniel-montalvo
