### ISSUE TITLE
Consider ignoring prohibited global attributes on presentational roles due to conflicts with AAM

### ISSUE THREAD

**Issue by sivakusayan** [w3c/aria#2072]
According to [9.3 Presentational Roles Conflict Resolution](https://w3c.github.io/aria/#conflict_resolution_presentation_none):

> If an element has global WAI-ARIA states or properties, user agents MUST ignore the [none](https://w3c.github.io/aria/#none)/[presentation](https://w3c.github.io/aria/#presentation) role and instead expose the element's implicit role.

However, what happens if we have the following markup?

```
<caption role="none" aria-label="whatever">
    ....
</caption>
```

If I'm reading things right, the presence of the `aria-label` undos the `role="none"` and the element instead maps to `role="caption"`, since the [HTML-AAM specifies that mapping](https://w3c.github.io/html-aam/#el-caption) for `<caption>`. However, `aria-label` [is prohibited on the `<caption>` element](https://w3c.github.io/aria/#aria-label), so does the `aria-label` no longer apply? If so, does this element map back to `role="none"`?

If I'm not misunderstanding things, similar scenarios could be constructed from `aria-labelledby`, `aria-braillelabel`, etc.
Unless there is some reason that undoing the role would be better for users/authors, wouldn't it reduce complexity a lot if user agents could just ignore prohibited attributes? 

We're trying to figure out what to do in this [Blink PR](https://chromium-review.googlesource.com/c/chromium/src/+/4996512), which I thought was fine since it would fix [the web platform tests](https://wpt.fyi/results/wai-aria/role/role_none_conflict_resolution.html?label=master&label=experimental&aligned) until Aaron pointed out some [discussions around this in the AccName spec](https://github.com/w3c/accname/issues/121).

@aleventhal @joone

**Comment by scottaohara** [comment]
aria-label is only author prohibited at this point.  so it undoes role-none.

**Comment by sivakusayan** [comment]
I guess my confusion comes from the fact that undoing the `role="none"` puts `aria-label` again in a prohibited state in the above markup, since the implicit caption role doesn't allow aria-label. Would that mean we drop the aria-label afterwards, so

```
<caption role="none" aria-label="whatever">
    ....
</caption>
```

effectively becomes

```
<caption>
    ....
</caption>
```

and we drop both the `aria-label` and `role`?

**Comment by scottaohara** [comment]
again @sivakusayan, aria-label is prohibited _for authors_.  This would be an author error.  we do not have any agreement or requirements for user agents at this time for use of aria-label/aria-labelledby on roles in which they are author prohibited.

**Comment by sivakusayan** [comment]
Thanks, I think this can be closed.

I updated the discussion in https://github.com/w3c/accname/issues/121 so we don't run into this confusion again.
