### ISSUE TITLE
Fix 35 instances where "programming" was spelled with one m

### ISSUE THREAD

**Issue by fstrr** [w3c/aria#2109]
There are 35 instances where "programming" is spelled with one m inside `abbr` elements

This is in the current [ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/) and [Editor's Draft](https://w3c.github.io/aria/)

**Comment by pkra** [comment]
This seems to have been closed accidentally.

**Comment by pkra** [comment]
To add this here, too:

The spelling is outdated but not incorrect https://english.stackexchange.com/questions/244280/programming-versus-programing-which-is-preferred

I'm guessing it was once intentional (maybe for the same reason we have aria-labelledby).

But language has shifted.

**Comment by fstrr** [comment]
I closed this because of #2113, which would solve the issue by removing all of the `abbr` elements, which is where the issue occurred.
