### ISSUE TITLE
Insertions and deletions in PR diff preview are unreadable in dark mode

### ISSUE THREAD

**Issue by adampage** [w3c/aria#2133]
I’m not sure this is the proper home for this issue, but I just noticed that the color styles for the `ins` and `del` elements in our PR diff previews make their text unreadable if your OS environment is _in dark mode_.

<img alt="A video capture demonstrating how the colors for ins and del elements in htmldiff’d W3C documents become unreadable in dark mode" src="https://github.com/w3c/htmldiff-ui/assets/1395630/332c9805-35e1-442a-90b2-d41216a5391f" width="620" />

I tracked this back to issue w3c/htmldiff-ui#12, where @tabatkins says:

> ...The answer is to make your documents darkmode-aware...

Is that something we can/should do for our documents?

**Comment by daniel-montalvo** [comment]
@adampage 
Thanks for bringing this to our attention

Hopefully this is soon addressed in respec
Ref:
https://github.com/w3c/respec/issues/2651
