### ISSUE TITLE
`comment` roles might need language/direction

### ISSUE THREAD

**Issue by aphillips** [w3c/aria#2142]
`comment` role
https://www.w3.org/TR/wai-aria-1.3/#comment

> A comment contains content expressing reaction to other content.
>
> Comments can annotate any visible content, from small spans of text, to other comments, to entire articles. 

Unlike many of the other "roles" in ARIA, the `comment` one doesn't necessarily contain the same language or use the same directionality as the rest of the document. Should there be a way to modify these? Or is this done through the content of the `comment`?

**Comment by scottaohara** [comment]
i'm not sure that's actually unique to just comments.  many roles could contain content written in a language different than the primary document.  

does ARIA need parity with HTML's dir and lang attributes?  or should it be assumed that the host language is really the better place that these should be defined for elements with content in different languages?

**Comment by pkra** [comment]
I'd second @scottaohara. I think both `lang` and `dir` are supported in host languages.

**Comment by aphillips** [comment]
> Do the above comments resolve your concerns?

Yes. Thank you.
