### ISSUE TITLE
"Translatable Attributes" incomplete?

### ISSUE THREAD

**Issue by aphillips** [w3c/aria#2143]
Translatable Attributes
https://www.w3.org/TR/wai-aria-1.3/#translatable-attributes

> The HTML specification states that other specifications can define [translatable attributes](https://html.spec.whatwg.org/multipage/dom.html#translatable-attributes). The [language](https://html.spec.whatwg.org/multipage/dom.html#language) and [directionality](https://html.spec.whatwg.org/multipage/dom.html#the-directionality) of each attribute value is the same as the language and directionality of the element.

The attributes currently listed are:

> - [aria-label](https://www.w3.org/TR/wai-aria-1.3/#aria-label)
> - [aria-placeholder](https://www.w3.org/TR/wai-aria-1.3/#aria-placeholder)
> - [aria-roledescription](https://www.w3.org/TR/wai-aria-1.3/#aria-roledescription)
> - [aria-valuetext](https://www.w3.org/TR/wai-aria-1.3/#aria-valuetext)

Should this list include these:

- aria-braillelabel
- aria-brailleroledescription
- comment

**Comment by pkra** [comment]
Thanks for raising this.

For the braille properties, see https://github.com/w3c/aria/issues/1316 and https://github.com/w3c/aria/pull/2043

Roles (such as comment) are not attributes in the sense of this section of the spec.

**Comment by daniel-montalvo** [comment]
Hi @aphillips 

Do the above comments resolve your concern?

**Comment by stes-acc** [comment]
Don't forget [aria-description](https://w3c.github.io/aria/#aria-description).

**Comment by pkra** [comment]
> Don't forget [aria-description](https://w3c.github.io/aria/#aria-description).

That's also in the PR.

**Comment by aphillips** [comment]
#2043 appears to address this. Thank you.
