### ISSUE TITLE
The Prettier (pull_request) check is failing due to an incorrect closing <p> tag.

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/aria#2243]
There is an incorrect closing `<p>` tag on line 6265 that is causing the "Prettier / prettier (pull_request)" check to fail. This error is likely resulting in the automatic validation of all pull requests to fail.

**Comment by pkra** [comment]
This is somewhat strange since the prettier action is set up to ignore the aria spec.  Oh well, thanks for the PR.
