### ISSUE TITLE
Proposal: IPA for communicating pronunciation 

### ISSUE THREAD

**Issue by Jontes-Tech** [w3c/aria#2258]
# Description of bug or feature request

I'm new to Aria and don't know where to put feature requests like this, but this is my suggestion.

Why can't we just have an IPA attribute `<span aria-ipa="ˈlɪnʊks/">Linux</span>`? That would simplify creating accessible content which is actually read "correctly" (for example with obscure human names not known to the TTS engine)

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?

If unknown, leave blank. If relevant, link bug.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?

If unknown, leave blank. If relevant, link bug.

**Comment by pkra** [comment]
There is a dedicated task force working on pronounciation in the web platform - see https://www.w3.org/WAI/about/groups/task-forces/pronunciation/ and https://github.com/w3c/pronunciation/

Marking this as a duplicate of #1010

**Comment by Jontes-Tech** [comment]
I am so sorry for polluting your Github issues. I am not very educated about ARIA.

**Comment by pkra** [comment]
@Jontes-Tech no worries - it can be tricky to track down the right place sometimes. Thanks for closing this issue as resolved.
