### ISSUE TITLE
Usage of <hr> between <section>'s

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#228]
Between all design patterns (`section`-elements) in section 2 of the APG there are `hr`'s. Why are these placed there? The `section`-elements themselves already denote a thematic change, so these `hr`'s seem to only add more verbosity to the document.

> The section element represents a generic section of a document or application. **A section, in this context, is a thematic grouping of content.** The theme of each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element.

Source: [HTML 5 specification: section element](https://www.w3.org/TR/html5/sections.html#the-section-element)

**Comment by michael-n-cooper** [comment]
There was some specific reason we did this in the 1.0 version. It might 
have been that we found a benefit to screen readers in having the <hr> 
there; I do recall considering just doing CSS rules, and we decided it 
was insufficient.

I agree <section> elements ought to do the job on their own, now that 
we're using HTML 5. If we really thought rules between sections was 
important we could do it in CSS or, if absolutely necessary, inserted by 
a respec extension. But we should check if someone else has a strong 
reason to believe we should keep the horizontal rules, before we remove 
them. I'll put it on my editors' meeting agenda.

Michael

**Comment by MichielBijl** [comment]
Consensus: remove `hr`'s from all specs.

**Comment by MichielBijl** [comment]
This is fixed for the authoring practices guide in [commit: remove horizontal rules between section's](https://github.com/w3c/aria/commit/ad780ce75213732f05bd342262bd1a0b076e1d91).

**Comment by Joanmarie** [comment]
Just noticed there's an issue for this. So for the sake of documentation, I fixed the ARIA spec the other day. (Commit dd120fc3f)
