### ISSUE TITLE
Fix dpub/graphics/mathml/svg aam spec links to monorepo

### ISSUE THREAD

**Issue by rahimabdi** [w3c/aria#2282]
# Describe the change

The following repo READMEs have broken links to their respective ARIA monorepo locations where it’s stated:
 “To open a PR, please see the [main ARIA repository where the specification lives]()”:
- [dpub-aam](https://github.com/w3c/dpub-aam?tab=readme-ov-file)
- [graphics-aam](https://github.com/w3c/graphics-aam?tab=readme-ov-file)
- [mathml-aam](https://github.com/w3c/mathml-aam?tab=readme-ov-file)
- [svg-aam](https://github.com/w3c/svg-aam?tab=readme-ov-file)

Monorepo spec links to use for the "[main ARIA repository where the specification lives](url)" link:
	⁃	dpub-aam: https://github.com/w3c/aria/tree/main/dpub-aam
	⁃	graphics-aam: https://github.com/w3c/aria/tree/main/graphics-aam
	⁃	mathml-aam: https://github.com/w3c/aria/tree/main/mathml-aam
	⁃	svg-aam: https://github.com/w3c/aria/tree/main/svg-aam

No issues with these specs:
- [accname](https://github.com/w3c/accname?tab=readme-ov-file) (PR: https://github.com/w3c/accname/pull/242)
- [html-aam](https://github.com/w3c/html-aam?tab=readme-ov-file)
- [core-aam](https://github.com/w3c/core-aam?tab=readme-ov-file) (PR https://github.com/w3c/core-aam/pull/235)

**Comment by spectranaut** [comment]
Ah! Nice catch, ty Rahim. Can you review?
* https://github.com/w3c/dpub-aam/pulls/42
* https://github.com/w3c/graphics-aam/pull/18
* https://github.com/w3c/mathml-aam/pull/36
* https://github.com/w3c/svg-aam/pull/37

**Comment by spectranaut** [comment]
Also I missed:
* https://github.com/w3c/graphics-aria/pull/13
* https://github.com/w3c/dpub-aria/pull/69

**Comment by rahimabdi** [comment]
All look good, thanks @spectranaut!

**Comment by spectranaut** [comment]
oh specifically @rahimabdi could you do an approving review on these PRs? ^ just so I don't get a warning when merging :)

**Comment by rahimabdi** [comment]
Done.
