### ISSUE TITLE
Prettier removed a line break from a pre-formatted code example

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#2286]
# Describe your concern
Prettier removed a line break from a pre-formatted code example

# Link to the commit
https://github.com/w3c/aria/pull/2284/commits/be75e5864fb12e61b9997539692a34391b58dd15

In this particular case, it might not matter, but this has the potential to cause problems with other diffs.

For what it's worth, I think the line breaks it added elsewhere were also undesirable.

**Comment by pkra** [comment]
Prettier should generally leave PRE elements alone. Maybe the action is not using an up to date version. Needs investigating.

**Comment by jnurthen** [comment]
we could add   // prettier-ignore
before pre blocks if we can't work out how to make it work automatically

**Comment by MelSumner** [comment]
Here's what I can find: 

> Prettier cannot ignore specific elements globally through its configuration file. You’ll need to rely on the `prettier-ignore` comments for now.

**Comment by pkra** [comment]
This was hopefully addressed by #2342.
