### ISSUE TITLE
Documented support for aria-multiselectable attribute on tablist not present in RDF schema.

### ISSUE THREAD

**Issue by majornista** [w3c/aria#229]
In order to support [the Accordion design pattern](https://www.w3.org/TR/wai-aria-practices/#accordion), `tablist` should [support `aria-multiselectable` as documented](https://www.w3.org/TR/wai-aria/roles#tablist), however the RDF schema at http://www.w3.org/WAI/ARIA/schemata/aria-1.rdf omits support for `aria-multiselectable` on `tablist`. This is problematic for validators, like Google's Accessibility Developer Tools, that use the RDF schema for generating test cases.

**Comment by michael-n-cooper** [comment]
RDF is updated for ARIA 1.1.
