### ISSUE TITLE
 New Role: taglist

### ISSUE THREAD

**Issue by MarioBatusic** [w3c/aria#2304]
# Description of bug or feature request

There are several desktop and web applications that use similar GUI constructs for creating and selecting tags as found in the “To” fields of MS Outlook and Gmail. These widgets are often known as “tagging” or “chips” components.

Although with similar visual design and the same functionality, these components are not standardized. There is neither an HTML element nor an ARIA role to express their semantics. 

The tagging pattern has been in use already for a long time - both on the web and in desktop applications. The most representative example is the *To* field in email programs such as Outlook and GMail. 
Other software programs use it to create or select tags.

## Different Implementations

Here are some examples:

### *To* field in Microsoft Outlook (desktop app)

It is a combined control consisting of an input field/combo box and entered email addresses, each with a separator behind it if several are entered. UIA presents the control as a *document* that, in addition to the text for separators, spaces and input strings, also contains *buttons* with the entered email addresses. This flexibility allows you to enter an email address in any sequence position.

![Outlook to-field with accessibiliy tree](https://github.com/user-attachments/assets/baf95727-3246-4c38-a465-777a5d512e15)
![Outlook to-field-popup with accessibility tree](https://github.com/user-attachments/assets/c8d7230e-16cd-41ef-9c0d-e945afa19f83)

### GMail

"To" field in GMail uses a complete different, non-valid ARIA: In a *listbox* *options* represent already entered mail adresses. On the end as a last child of the *listbox* there is a *combobox* to select / create a mail adress.

![GMail to-field](https://github.com/user-attachments/assets/29bc241e-254f-4521-898d-65342ac9d944)

![GMail to-field accessibility tree](https://github.com/user-attachments/assets/dcd973c1-e851-43fb-8e25-70a0590f0e69)

### Select2 - JQuery Library

![Select2 - JQuery screenshot](https://github.com/user-attachments/assets/dd2ad244-8231-4b2a-878e-75e65cbe2a90)

![Select2 - JQuery accessibility tree](https://github.com/user-attachments/assets/ba225388-12e8-4741-95c8-14a6e6e630ca)

Example for tagging with JQuery multi-value select boxes: [https://select2.org/tagging](https://select2.org/tagging)

### Jira

Jira offers extensive tagging options for issues. Users can enter labels and choose from suggestions.

![Jira Screenshot](https://github.com/user-attachments/assets/a889ab46-d9e2-4461-84b9-1d18615a53b1)

![Jira accessibility tree](https://github.com/user-attachments/assets/e22f6ea1-0b1e-4f28-976f-ba5df5c889e3)

Example: [https://react-select.com/home#custom-styles](https://react-select.com/home#custom-styles)

## Component Discussion

Regardless of whether ARIA roles are chosen differently or are completely absent in these widgets, they always consist of

- a horizontal arrangement of entered tags

- followed by a combo box for selecting or creating further tag.

Both visualization and the use of mouse and keyboard differ from implementation to implementation.

- The widget is sometimes in the tab order. After entering the widget, the cursor is either in the empty input field /  *combo box* or at the end of an element with the role of *document* (MS Outlook).

- After the creation / selection of a tag is complete, the tag is entered as an *option* or a *button* and visually inserted to the left of the input field. The input field is emptied and the cursor remains mostly within it.

- If the cursor is in the first position of the input field, the *left arrow* command focuses the previous entry as a whole.

- In some cases it is possible to move between entries using horizontal arrow keys.

- Mostly the tags have a context menu.

## Accessibility Issues

Screen reader users in particular have problems with all implementations of tagging:

- Without a correct role, it is impossible to understand what is going on here:
    - Where to disappear entered tags?

    - Why does the focus remain on the emptied input field after an entered tag disappears?

    - If I success to find the entered tag afterwards, it is no longer a text but a button or a *listbox option*. And the list is arranged horizontally.

### Name

I would suggest *tagbox* or *taglist* as a working name. There may be of course a more suitable name.

### ARIA for the Widget

The new role must be noted on the common container for the *combobox* and for entered entries in order to clearly indicate the semantics of the entire construct.

There are two possible starting roles that can be renamed and adapted for the purpose:

1. *toolbar*, which should be restrected so that it contains only *button* and *combobox* as accessible children, or

2. *listbox*, which could be allowed to contain a *combobox* in addition to *option* children.

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?

If unknown, leave blank. If relevant, link bug.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)? 

Yes.

**Comment by JAWS-test** [comment]
Related: https://github.com/w3c/aria/issues/689

**Comment by JAWS-test** [comment]
See APG example using role=grid: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/#ex2_label

**Comment by MarioBatusic** [comment]
@JAWS-test Thanks for calling the previous issue - that was similar but not completely explained. 

The APG example is also only yet another implementation of the tagging widget and not at least clearer and intuitive for SR users. Using a grid in this peculiar way - adding new columns on each recipint input is not easy to understand.

I think the tagging pattern is so often used and so different implemented that an ARIA role can be a big help for SR users.

**Comment by JAWS-test** [comment]
@MarioBatusic I agree with you. But I wanted to refer to the old discussions. role=grid is not a good way to implement tags: https://github.com/w3c/aria-practices/issues/1233#issuecomment-547256458

**Comment by spectranaut** [comment]
Discussed briefly in new issue triage: https://www.w3.org/2024/08/08-aria-minutes#t01

**Comment by MarioBatusic** [comment]
There is a "tag" widget in the openUI project and it should be tried to get this widget accessible as much as possible.
