### ISSUE TITLE
Decide on PR naming/labelling convention

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria#2312]
Right now, we are using a mix of the PRs starting with a string like `[Editorial]` and `[html-aam]`, and, we have tags for these things. Maybe we should just do one or the other?

**Comment by spectranaut** [comment]
Maybe add a github action to add labels?

**Comment by spectranaut** [comment]
Also add information to PR template!

**Comment by pkra** [comment]
> Maybe add a github action to add labels?

=> #2318

**Comment by daniel-montalvo** [comment]
@daniel-montalvo  to test this on his own fork before merging.

**Comment by daniel-montalvo** [comment]
The labeler has been failing for a while (my fault) but should be fixed now.

Tested in https://github.com/daniel-montalvo/aria/pull/2 and it automatically assigns spec:accname and spec:core-aam based on the files changed.
