### ISSUE TITLE
[AriaNotify] Is ariaNotify the best name for the new notification API?

### ISSUE THREAD

**Issue by alisonmaher** [w3c/aria#2332]
The topic around naming of the `ariaNoify` API, as noted in the [spec PR](https://github.com/w3c/aria/pull/2211) and the [explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Accessibility/AriaNotify/explainer.md), has been raised in the past. The reasoning with the push back is that the API is not really an ARIA property, so should the name be tied to ARIA or something else?

Opening this issue to discuss if there are other ideas for naming, or if the group is happy to stick with `ariaNoify`.

**Comment by alisonmaher** [comment]
This was discussed at TPAC with the relevant minutes quoted below:

> keithamus: the other thing is naming, I think we discussed notificationId, we can change. I think everyone is happy with the name ariaNotify, should we litigate priority?
> 
> jcraig: I don't think this needs to have aria, maybe accessibilityNotify
> 
> Jamie: accNotify?
> 
> aaronlev: I like ariaNotify, everyone knows it's related to accessibility. No one knows what AT is
> 
> jcraig: I like accessibilityNotify, it's longer to type
> 
> smockle: is it an accessibiltiy only feature, I coudl see someone who wants to use ear-cons who's not an AT user
> 
> Jamie: I think it should be aria, by virtue of it being a prefix like everything else. It's just simpler
> 
> Matt_King: no matter how broad the use is, it's still accessibility
> 
> cyns: and if I were making a setting in the OS, I'd put it in the a11y settings
> 
> jcraig: I think Leonie mentioned a feature where having air pods in and getting a text message, you get it spoken to you. I can see a point to having a broader use case
> 
> 00:42:07 [jcraig]
> s/Leonie mentioned a feature/Leonie mentioned she'd just learned of the feature/
> 
> jamesn: WE ARE DONE
> 
> sarah: risk with making the use case broader is that it stops working as well , better to keep it accessibility specific

Given the above, I think we had converged on keeping the name accessibility specific. There were some suggestions around potentially `accessibilityNotify` or `ATNotify`. However, given the arguments for the name `ariaNotify` by @aleventhal and @jcsteh, my proposal will be to keep the name the same, and close this issue as no change.

**Comment by aleventhal** [comment]
I prefer the current name. ARIA doesn't only have to mean aria-foo attributes. ARIA stands for Accessible Rich Internet Applications, which is where authors will want to use this. ARIA is like a brand for authors implementing that.
