### ISSUE TITLE
[AriaNotify] Braille Support

### ISSUE THREAD

**Issue by alisonmaher** [w3c/aria#2334]
As discussed in https://github.com/w3c/aria/discussions/1958#discussioncomment-6200866, there may be cases where an author would want to provide a separate notification string for braille users. @cookiecrook noted that if so, it should align with `aria-braille*` attributes.

I think this is a great idea, and I could imagine use cases where an author would want to provide different strings for braille. However, I would like to propose that we consider this for a future version of the API instead to allow us to gather feedback from developers and end users as `ariaNotify` starts to get adopted with its current set of functionality. This will help inform the best way to incorporate this additional customizability going forward.

**Comment by alisonmaher** [comment]
This was discussed at TPAC:

> keithamus: there are a couple open issues I can lump together that I think we can defer. But I think braille support and speech markup we can design around those later

The group seemed to agree with deferring this till a future version

**Comment by keithamus** [comment]
I think we've successfully captured a resolution around this, which is that we should defer support for these until a future version.

I'll close this for now but I think we can revisit it once we know more about how this API is used once it ships!
