### ISSUE TITLE
[AriaNotify] IA2 Support

### ISSUE THREAD

**Issue by alisonmaher** [w3c/aria#2336]
As discussed in https://github.com/w3c/aria/discussions/1958#discussioncomment-9653452, we plan to support `ariaNotify`on Windows solely through UIA. Some questions were raised around whether we should support this for IA2, as well.

The most widely used ATs already listen to UIA Notification events. If we fallback to live regions in the case of IA2, how do we best handle cases where ATs, like JAWs and NVDA, listen to both mechanisms on Windows? This would require some way to avoid duplicate events.

Some had also raised the question around how this would work for browsers that don’t support UIA. Chromium is in the process of experimenting with UIA. And Firefox is currently implementing UIA.

As such, my proposal is to only plumb `ariaNotify` through the UIA Notification event on Windows, and IA2 will be ignored. This will prevent duplicate events being fired on ATs, like JAWS and NVDA.

**Comment by smockle** [comment]
@alisonmaher This was discussed during TPAC. Here’s a relevant excerpt from the IRC log (minutes aren’t available):

> **keithamus:** how do we resolve this for IA2, the current API relies on UIA
> **aardrian:** I thought that NVDA had committed by reading both, based on a comment I saw?
> **Jamie:** more or less the same thing, I don't see any benefit to having an IA2-specific way to do it, both from the browser side and the SR side
> **Jamie:** it makes it harder rather than easier
> **Sarah:** I originally brought that up mostly to make sure that this was considering other platforms, not just IA2
> Jamie: agree entirely, just not for IA2
> alisonmaher: it is very UIA-based, I'm not aware for any support outside for this

If I understand correctly, there is consensus that `ariaNotify` can be supported on Windows through UIA alone.

**Comment by keithamus** [comment]
I think we've successfully captured a resolution around this, which is that we should _not_ implement this for IA2 in any capacity.

I'll close this for now but if there are strong objections to that resolution we can re-open and revisit.
