### ISSUE TITLE
HTML-AAM: UIA mapping for <time> element

### ISSUE THREAD

**Issue by cyns** [w3c/aria#235]
not mapped

**Comment by stevefaulkner** [comment]
Does this imply it won't be mapped?

**Comment by cyns** [comment]
We don't have anything equivalent to map it to. For the time being, it won't be mapped. It will be treated the same as a span. We can look at adding something to UIA in the future.

**Comment by cyns** [comment]
updated mapping:
No accessible object for the <code>time</code> element itself.
Create an <code>Annotation</code> object containing the value of the <code>datetime</code> attribute.
In the parent <code>Text Pattern</code> (usually the page), create a <code>TextRange</code> corresponding to the <code>time</code> element, and expose an <code>UIA_AnnotationObjectsAttributeId</code> pointing to the <code>Annotation</code> object containing the <code>datetime</code>, with <code>UIA_AnnotationTypesAttributeId</code> of <code>AnnotationType_Unknown</code>
