### ISSUE TITLE
Do we need aria-mathml to replace the nonstandard data-mathml attribute being used?

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#2353]
Both MathJax and Google Sheets currently use data-mathml to expose math markup, and both JAWS and NVDA consume this.
As we working to move Windows ATs away from using nonstandard attributes (which they can consume via ISimpleDOMNode), we would like to provide a satisfactory alternative, and eventually end the practice of using this attribute.

This attribute comes into play when there is an image or another element with role="math", as a way to provide the MathML text.

Question: when role="math" is used, how is the math content supposed to be supplied by the content? A new attribute might not be necessary. The author could have a child `<mathml>` element for the role="math", and ensure that it is rendered offscreen, etc.

**Comment by aleventhal** [comment]
Note: NV Access strongly prefers that everyone standardize on MathML, and not use LaTeX (just discussed with them).

**Comment by spectranaut** [comment]
Turns out MathJax does not use attribute, according to @pkra, Aaron will try to find a different solution for Google Sheets.
