### ISSUE TITLE
HTML-AAM: UIA mapping for input type=telephone

### ISSUE THREAD

**Issue by cyns** [w3c/aria#236]
control type: edit
 localized control type: telephone

If it has a suggestions source, ControllerFor pointing to the suggestions source.

**Comment by cyns** [comment]
@stevefaulkner the dif is about aside not telephone. Is this the right issue?

**Comment by stevefaulkner** [comment]
@cyns it's in there, amongst other stuff, sorry for the confusion

**Comment by cyns** [comment]
@stevefaulkner got it. thanks.

**Comment by cyns** [comment]
PR #251 took out extra word "telephone"
