### ISSUE TITLE
CORE-AAM: UIA mapping for role=main

### ISSUE THREAD

**Issue by cyns** [w3c/aria#238]
Control Type: Group
Localized Control Type: main (all lower-case)
Landmark Type: Main
Localized Landmark Type: main (all lower-case)

**Comment by klown** [comment]
Thanks @cyns.

Created ACTION-2009:
https://www.w3.org/WAI/ARIA/track/actions/2009

**Comment by klown** [comment]
@cyns, I've made the edits.  Can you check, and if satisfied, close this issue?
http://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-main

Diff:
https://github.com/w3c/aria/commit/711c18b040743774c95867d30309c9d72005ddbb

Thanks.

**Comment by cyns** [comment]
fixed. thanks!
