### ISSUE TITLE
Text-to-background contrast in tables under ARIA's Definition of Roles too low

### ISSUE THREAD

**Issue by stiiin** [w3c/aria#2394]
The headings of the tables under the [Definition of Roles](https://w3c.github.io/aria/#role_definitions) sections are unreadable under dark mode. This is because the `th` elements have `color: var(--text)` (through `base.css`), which computes to `color: #ddd` (when `dark.css` is applied), and `background-color: #eee` (through [this repository's `common.css`](https://github.com/w3c/aria/blob/5973a12f7d225be85be774fc4c2093c8e5572843/common/css/common.css#L93)).

**Comment by pkra** [comment]
> A solution for this either lies in, or is blocking on, #2226.

Could you leave a comment on the other issue? Then we can close this to avoid duplicate issues.

**Comment by stiiin** [comment]
Commented as requested.
