### ISSUE TITLE
HTML-AAM: how to map Inner Phrasing Content for <meter>?

### ISSUE THREAD

**Issue by cyns** [w3c/aria#240]
HTML spec on <meter> has examples like this 

&lt;meter value="0.5"&gt;Moderate activity&lt;/meter&gt;

Where should the inner phrasing content "Moderate activity" be mapped in the AAPIs? Is this a value? Part of name or description? Something else?

**Comment by cyns** [comment]
@stevefaulkner @jasonkiss @Joanmarie we're blocked on this one. should it be mapped at all?

I thought about mapping it to aria-valuetext, but that uses the same uia property that we're using for the result of optimal calculation (Value.Value). 
The fallback content doesn't seem like it would make a good name.

**Comment by cyns** [comment]
#334 is related

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#27
