### ISSUE TITLE
All tables have a white background making it hard to read in dark mode

### ISSUE THREAD

**Issue by kevin-samson** [w3c/aria#2400]
![image](https://github.com/user-attachments/assets/39868f0d-f46e-4eff-81ec-1611b9eb012b)

Link to documentation: https://w3c.github.io/aria/#aria-expanded

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)? - Yes

**Comment by SamB** [comment]
Doesn't really look like the same issue: in particular, the "or inline" option doesn't sound like it would help at all with dark mode.
