### ISSUE TITLE
Needs mappings for datetime-local

### ISSUE THREAD

**Issue by dstorey** [w3c/aria#248]
https://w3c.github.io/html/semantics.html#local-date-and-time-state-typedatetimelocal

This isn't included in the list of mappings in the HTML AAM spec

Supported by MS Edge and Chrome.

CC @cyns

**Comment by jasonkiss** [comment]
Thanks. Done: https://rawgit.com/w3c/aria/master/html-aam/html-aam.html#el-input-localdateandtime
