### ISSUE TITLE
HTML-AAM: Make presentation of UIA mapping properties consistent

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#252]
Settle on single way to indicate/present names and values for various UIA structures, properties, attributes, e.g. control patterns, control type, localized control type, landmark type, localized landmark type, text style attributes.
Currently there is some variance in how these are indicated.

**Comment by jasonkiss** [comment]
@cyns @stevefaulkner @asurkov Please take a look at the UIA mappings from `<a>` to `<meter>`. I took a stab at a single, consistent way to present the properties and values. Any comments/concerns?

**Comment by asurkov** [comment]
I'm not sure whether we should put a control type name into "", for example, <code>"figure"</code> and UIA_IsItalicAttributeId looks less ambitious than IsItalic, otherwise it looks like a good cleanup.

**Comment by jasonkiss** [comment]
The reason quotes are used for Localized Control Type and similar property values is because they are strings, as opposed to constants as you get with Control Types. We do the same with AXRoleDescription.

> UIA_IsItalicAttributeId looks less ambitious than IsItalic

Do you mean less ambiguous? "IsItalic" is the name of the text attribute, while "UIA_IsItalicAttributeId" is the identifier used when retrieving the value of the IsItalic attribute. Should we be referring to the property identifiers, or the the actual name of the property? What do you think, @cyns?

**Comment by asurkov** [comment]
> The reason quotes are used for Localized Control Type and similar property values is because they are strings, as opposed to constants as you get with Control Types. We do the same with AXRoleDescription.

it's probably ok, I'm just not sure if makes sense to show a type of the constant

> Do you mean less ambiguous? 

yes :) I guess spelling correction.

> "IsItalic" is the name of the text attribute, while "UIA_IsItalicAttributeId" is the identifier used when retrieving the value of the IsItalic attribute. Should we be referring to the property identifiers, or the the actual name of the property? What do you think, @cyns?

note, same time we use ATK_ROLE_BLABAL and IA2_ROLE_BLABLA

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#28
