### ISSUE TITLE
HTML-AAM - test and update name calc for labelable elements

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria#259]
test the following elements (where label not already included in name calc) and update where necessary to reflect implementations.

list of labelable elements in HTML5 includes
button input (if the type attribute is not in the hidden state)keygen meter output progress select textarea  

http://www.w3.org/TR/html5/forms.html#category-label

**Comment by stevefaulkner** [comment]
test file http://thepaciellogroup.github.io/AT-browser-tests/test-files/label.html

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#29
