### ISSUE TITLE
Simplify usage of kbd element

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#261]
To show which key or keys to press to achieve something in an APG design pattern, we use the [`<kbd>` element](http://w3c.github.io/html/semantics.html#the-kbd-element) like so: `<kbd>ctrl</kbd>+<kbd>Page Up</kbd>`.

As Steve points out, a single `<kbd>` around the key combination would suffice.

~~The HTML specification clearly states, that if a combination of key presses is to be conveyed, they should be wrapped in a `<kbd>` element like so: `<kbd><kbd>ctrl</kbd>+<kbd>Page Up</kbd></kbd>`.~~

~~It's important to follow the spec when writing a spec; so this should be corrected.~~

**Comment by stevefaulkner** [comment]
>
> It's important to follow the spec when writing a spec; so this should be
> corrected.
>

Note the following example in the spec:

Such precision isn’t necessary; the following is equally fine:
>
> <p>To make George eat an apple, select <kbd>File | Eat Apple...</kbd></p>
>
> There are no normative requirements in the spec about the use of <kbd>,
only statements about what it represents when used.


--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by MichielBijl** [comment]
Fair enough, but shouldn't the APG reflect that as `<kbd>ctrl + Page Up</kbd>` rather than `<kbd>ctrl</kbd> + <kbd>Page Up</kbd>`?

**Comment by stevefaulkner** [comment]
Perhaps, but suggest it is a low priority as it has no meaningful effect
for anyone or any software, does it?

On Saturday, 20 February 2016, Michiel Bijl <notifications@github.com>
wrote:

> Fair enough, but shouldn't the APG reflect that as <kbd>ctrl + Page
> Up</kbd> rather than <kbd>ctrl</kbd> + <kbd>Page Up</kbd>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/issues/261#issuecomment-186570060>.
>


-- 
--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by MichielBijl** [comment]
Not to my knowledge, no. Does make it a bit easier to read/write, but I'll self assign this and take it up when I feel like fixing something that doesn't have a meaningful effect.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria/commit/f444eb23d8b0fc3489dcd025747e1c706121d085
