### ISSUE TITLE
HTML-AAM: UIA mapping for address

### ISSUE THREAD

**Issue by cyns** [w3c/aria#270]
Control Type: Group
Localized Control Type: address
Landmark Type: Custom
Localized Landmark Type: content information

**Comment by cyns** [comment]
The above mapping assumes that this is a landmark and equivalent to ARIA role=contentinfo. Waiting on resolution of #273 before updating html-aam

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#32
