### ISSUE TITLE
HTML-AAM: should address be treated as seciton/landmark in AAPIs?

### ISSUE THREAD

**Issue by cyns** [w3c/aria#273]
Apple maps address as an aria landmark role of content-info. IA2 and ATK map it like a div. I think it was at some point mapped to aria role=content-info, but I can't find when that was changed. 

I can see how it is similar to contentinfo, though not a perfect match. I also don't think it's important enough (on most web pages) to be part of the landmark loop, which should cover major chunks of the page.

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#33
