### ISSUE TITLE
HTML Accessibility API  doesn't specific how accessible name calculation is applied to iframes

### ISSUE THREAD

**Issue by mraccess77** [w3c/aria#274]
It isn't clear if the accessible name calculation rules defined for groupings and other sectioning elements also apply to iframes.  If this is the case then it would be helpful to have iframes listed in this portion of the document.

**Comment by cyns** [comment]
I think iframes should be treated like any other element. This is the current behavior in Chrome, and what Edge is leaning towards.

Iframe name
Default: empty string
Treated like any other element in name calc (@title overrides the above, @aria-label overrides @title, etc.)

Framed document name
Default: empty string
Overridden by <title>

**Comment by jasonkiss** [comment]
Addressed in https://github.com/w3c/aria/commit/e2f656c56df37ea1184353d40877508036332c3d.
Closing.
