### ISSUE TITLE
Header element semantics

### ISSUE THREAD

**Issue by jongund** [w3c/aria#276]
The current draft has the phrase:
"nearest ancestor sectioning content or sectioning root element is not body"

Not sure what this means.

**Comment by jasonkiss** [comment]
See https://www.w3.org/TR/html51/semantics.html#the-header-element

A `header` element serves as the 'header' for some ancestor sectioning content or sectioning root element. That might be the `body` element (in which case the `header` has a default ARIA role of banner), or it might be something else, like a `section` or a `blockquote` (in which case it's mapped more or less like a `div`). This is just distinguishing between those two scenarios using the language from the HTML spec.

**Comment by jasonkiss** [comment]
See w3c/aria#277
