### ISSUE TITLE
[CORE-AAM] application no longer a landmark

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria#281]
The API mapping for `role=application` in some APIs reflect it's landmark semantics
https://www.w3.org/TR/core-aam-1.1/#role-map-application

I think these need to be updated.

**Comment by klown** [comment]
Hi @stevefaulkner 
For clarification, are you referring to the AXAPI mapping, only?  Or other platforms?

For the record, the latest editor's draft is at the following URL, but the AXAPI mapping isn't different from the latest TR:
 http://w3c.github.io/aria/core-aam/core-aam.html#role-map-application

**Comment by stevefaulkner** [comment]
On 3 March 2016 at 16:06, Joseph Scheuhammer <notifications@github.com>
wrote:

> For clarification, are you referring to the AXAPI mapping, only? Or other
> platforms?


definitely the AX mapping, unsure about whether others would be effected.

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by klown** [comment]
@cookiecrook Can you advise, please?  Given that the application role is no longer a landmark, what is the correct AXAPI mapping?
Thanks.

**Comment by cookiecrook** [comment]
AX: "AXLandmarkApplication" is an inappropriate subrole for ARIA "application" since it's no longer a landmark
http://webkit.org/b/155403

**Comment by klown** [comment]
Thanks @cookiecrook 
Created w3c tracker [ACTION-2022](https://www.w3.org/WAI/ARIA/track/actions/2041).

**Comment by joanmarie** [comment]
I knew this one sounded familiar. This was fixed quite some time ago by Joseph (60b7947)
