### ISSUE TITLE
Definition for aria-kbdshortcuts references old specification

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria#284]
The definition for aria-kbdshortcuts references Dom Level 3 KeyboardEvent Key Values. This spec is now UI Events KeyboardEvent Key Values.
https://www.w3.org/TR/DOM-Level-3-Events-key/

**Comment by michael-n-cooper** [comment]
Addressed by 19dd98bec7e8aeb93e75b3542cd4d8a0688d9157
