### ISSUE TITLE
Suggest attribute name change for aria-kbdshortcuts

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria#285]
The "kbd" abbreviation seems counter to conventional ARIA attribute naming. It reads poorly with a screen reader, and generally feels clunky. Recommend changing it to aria-shortcuts (as suggested by Dominic Mazzoni.

**Comment by MichielBijl** [comment]
+1

**Comment by michael-n-cooper** [comment]
The property was renamed to aria-keyshortcuts some time back, but this issue wasn't closed. Closing now.
