### ISSUE TITLE
[practices WD] math

### ISSUE THREAD

**Issue by pkra** [w3c/aria#290]
Over on a11ySlackers I stumbled upon http://w3c.github.io/aria/practices/aria-practices.html#math again which always leaves me somewhat confused. Since I'm only a beginner, I was hesitant to post a confused question but @MichielBijl encouraged me to do so, so here I go.

Specifically, I don't understand the example 43 in the Practices WD. 

Shortened version:

```html
<div role="math" aria-label="a times x squared plus b times x plus c equals 0">
  <math xmlns='http://www.w3.org/1998/Math/MathML'>
  <!-- snip -->
  </math>
</div>
```

Since I'm only a beginner, I was wondering what the expected result of this is. 

At first I thought this should lead to double-rendering by MathML-capable AT (first the label, then the MathML). However, most ATs I tested simply ignore anything with `role=math` so the label will not be read (or anything else). If I drop `role=math`, then NVDA(+MathPlayer) will voice both the label and the MahtML in Firefox. 

Then I thought the label would override the remaining content (e.g., that's what Chrome's a11y dev tool extension indicates), but that would mean that AT with MathML support is forced to use the lower-quality option. So I'm probably wrong about that, too.

To give some context, I don't care too much about the MathML, actually. The real problem I see is to make HTML renderings of mathematics accessible and neither the Practices nor the `math` role description help much with this. 

For as simple an example as the one in the Practices, "deep" labels provide quite decent accessibility, e.g.,

```html

 <math>
    <mrow>
      <mrow>
         <mrow>
            <mi>a</mi>
            <mo aria-label="times">&#x2062; <!-- invisible times --></mo>
            <msup aria-label="x squared">
              <mi aria-hidden="true">x</mi>
              <mn aria-hidden="true">2</mn>
            </msup>
         </mrow>
         <mo>+</mo>
         <mrow>
            <mi>b</mi>
            <mo aria-label="times">&#x2062; <!-- invisible times --></mo>
            <mi>x</mi>
         </mrow>
         <mo>+</mo>
         <mi>c</mi>
      </mrow>
      <mo>=</mo>
      <mn>0</mn>
    </mrow>
  </math>
````

would seem to make more sense to me. But due to the absence of MathML support almost everywhere in the a11y stack, this doesn't actually work. (I would point out that the label actually enhances the original MathML as superscripts carry no semantic meaning in Presentation MathML either.)

However, if one follows the suggestion to use a <s>polyfill</s> MathML-to-HTML5 converter, then there's actually a good chance this could become more accessible than a fixed label. Cf. http://codepen.io/pkra/pen/zqrwQx: the third example renders nicely on NVDA, even allowing some level of exploration. Just to be clear, this only works well for relatively "flat" equations like this one but that likely covers a worthwhile amount of content, especially inline equations.

And one last, related question regarding the "generic HTML" example in the Practices WD. Why can we not expect AT to render this as well as it would render the MathML counterpart, once we add a `role=math` to it?

```html
<span role="math"><i>a</i><i>x</i><sup>2</sup> + <i>b</i><i>x</i> + <i>c</i> = 0</span>
```

There's not really a semantic difference between `msup/msub` and `sup/sub`, albeit a difficulty of parsing of `sup/sub`; but that is something Practices can actually help with by recommending wrapping, e.g.,

```html
<span role="math"><i>a</i><span><i>x</i><sup>2</sup></span> + <i>b</i><i>x</i> + <i>c</i> = 0</span>
```

Not that this works today, but I'm wondering why it shouldn't be. (But I realize this leads to the larger problem of `role=math` and the lack of ARIA roles for mathematics so I better stop here.)

**Comment by MichielBijl** [comment]
Thank you for your elaborate issue report! What I take from it is that the current example isn't the most accessible. So is your suggestion we replace the example with something else? Your second example looks good to me, but I don't know much about maths so can't really tell what it should convey.

**Comment by pkra** [comment]
> So is your suggestion we replace the example with something else?

I don't know. My initial question was: What is the expected result of the example in the spec? 

AT is inconsistent in what it voices (sometimes the label, sometimes the MathML, sometimes both sometimes neither); it's not clear to me what the expected result should be so it's hard to report issues with AT (let alone create reliable content).

> Your second example looks good to me,

Thanks, but it works in even fewer AT combinations than the original example from the spec. Again, I'm not sure if that's expected behavior or not.

Let me stop here, perhaps, before adding too much noise.

**Comment by MichielBijl** [comment]
I can bring this up during the ARIA or APG calls. Will report back once discussed.

**Comment by pkra** [comment]
Thanks, @MichielBijl. I'm happy to provide more input if that helps.

**Comment by pkra** [comment]
FYI I've updated the codepen at http://codepen.io/pkra/pen/zqrwQx and added test results (not completely done but as far as I'll get for now; additions are welcome).  The results are rather inconsistent.

**Comment by laughinghan** [comment]
I'm also a novice in this area and I'm not the main accessibility developer on my project but for us, the equivalent of:

```html
<span class="we-need-a-container-anyway" aria-label="x superscript 2 baseline y"><span aria-hidden="true">x<sup>2</sup>y</span></span>
```

has been working in the screen readers we've been testing (I've been testing with VoiceOver and Safari; I believe our main accessibility developer tests mostly with WindowEyes but also with JAWS and NVDA.

Is that surprising to anyone? Does that sound like a bad approach?

**Comment by MichielBijl** [comment]
This issue was moved to w3c/aria-practices#26
