### ISSUE TITLE
min-width on table headings causes issues

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria#302]
There seems to be a minimum width set on table headings; this quickly causes problems if you have more than two columns:

![Table grows beyond document width due to minimum width on table headings as shown by the web inspector in Chrome](https://cloud.githubusercontent.com/assets/5457769/13697990/241680ee-e769-11e5-94f3-95985e0605f6.png)

**Comment by jnurthen** [comment]
I think the easiest solution is to special-case this table and leave min-width for all the others. comments?

**Comment by MichielBijl** [comment]
Why is it on there anyway?

—Michiel

**Comment by jnurthen** [comment]
I originally thought it was so the main patterns have a certain look (i.e. they all look the same) but it certainly isn't very small-screen or zoom friendly. 

However, I just noticed that their width is actually being controlled by
.widget-description-head, .widget-keyboard-head, .widget-mouse-head, .widget-styling-head, .widget-aria-head, .widget-example-head {
    width: 20em;
}

I think we should be safe to remove the min-width on td and th. Doing so didn't provide any issues IMO other than the empty patterns looking a bit weird (like Media Player) but empty stuff I'm not prepared to worry about.

I also think we should reduce the min-width on the patterns to give more space for content and less for the headings. I think modifying to 
.widget-description-head, .widget-keyboard-head, .widget-mouse-head, .widget-styling-head, .widget-aria-head, .widget-example-head {
    width: 15em;
}

would improve the document, particularly on small-screen and zoomed.

**Comment by MichielBijl** [comment]
Agreed. As discussed on IRC, I'll make a branch in which all tables—for the description/keyboard support/etc—are removed and replaced by headings.

**Comment by MichielBijl** [comment]
As we now use headings; this is fixed. I have also removed all custom CSS, as that was no longer used by anything because of the change.
