### ISSUE TITLE
CORE-AAM: cell mapping specifies TableItem as UIA Control Type, but is a Control Pattern

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#303]
UIA Control Type for role=cell is TableItem, but that is a Control Pattern, not a Control Type. See http://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-cell

Should it be DataItem ControlType?

**Comment by joanmarie** [comment]
@boggydigital: Your platform. :)

If you could do a pull request providing any needed changes (or comment if no changes are needed), that would be great. Thanks in advance!

**Comment by boggydigital** [comment]
https://github.com/w3c/aria/pull/623

**Comment by joanmarie** [comment]
This issue was fixed through #623 and #638. As a result, https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-cell lists the UIA mapping to the `DataItem` Control Type and `TableItem` Control Pattern.
