### ISSUE TITLE
HTML-AAM: need string values for all HTML form elements to plug into accname-aam step 2E

### ISSUE THREAD

**Issue by cyns** [w3c/aria#307]
&lt;input type=checkbox id=foo&gt;
&lt;label for=foo&gt;Include items from &lt;input type=date value="2016-04-01"&gt;?&lt;/label&gt;

the accessible name of foo should be something like "Include items from April 1, 2016?"
We need to define how those values stringify for the html date, time, color, and all other form elements that aren't of one of the specified roles
If the embedded control has role textbox, return its value.
◾If the embedded control has role menu button, return the text alternative of the button.
◾If the embedded control has role combobox, return the text alternative of the chosen option.
◾If the embedded control has role range (e.g., a spinbutton or slider):

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#35
