### ISSUE TITLE
HTML-AAM: input element in search state should map to ARIA 1.1 role=searchbox

### ISSUE THREAD

**Issue by cyns** [w3c/aria#310]
currently mapped to textbox, but the new searchbox is a better mapping.

**Comment by dstorey** [comment]
@cyns: related to this, when testing Safari, it maps "accessibilitySubrole" to "AXSearchField", rather than just following the ARIA mapping for textbook. 

I suspect that is consistent with the searchbox mapping you suggest.

**Comment by jasonkiss** [comment]
Thanks. Done. Closing.
