### ISSUE TITLE
Example letters are inconsistent: aria-practices, Widgets within Widgets

### ISSUE THREAD

**Issue by mitchellevan** [w3c/aria#312]
Actual:

In aria-practices.html, under "Widgets within Widgets" it says:

> For example, if there are two widgets A and B on a page where widget A contains within it Widget A1 and Widget A1 contains within it Widget A2, the focus sequence when pressing the tab key would be A1, A2, A3, B.

Expected:

It should end with "...would be A, A1, A2, B."

**Comment by jnurthen** [comment]
Thanks @mitchellevan
