### ISSUE TITLE
WAI-ARIA 1.1: Needs to update link to SIML

### ISSUE THREAD

**Issue by momdo** [w3c/aria#320]
in <a href="https://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/#aria-expanded">aria-expanded (state)</a>:
https://www.w3.org/TR/1998/REC-smil-19980615/
-> https://www.w3.org/TR/SMIL3/

in <a href="https://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/#bib-SMIL">F.2 Informative references</a>:
Synchronized Multimedia Integration Language (SMIL 2.0) - [Second Edition].
-> Synchronized Multimedia Integration Language (SMIL 3.0)

**Comment by momdo** [comment]
Additionally:
section (abstract role) https://www.w3.org/TR/2016/WD-wai-aria-1.1-20160721/#section :
http://www.w3.org/TR/REC-smil/smil-timing.html#edef-par
->https://www.w3.org/TR/SMIL3/smil-timing.html#edef-par

**Comment by Joanmarie** [comment]
Thanks for the report! Should be fixed. If I missed anything, please reopen.
