### ISSUE TITLE
2.13 Grid (Simple Data Tables) - changes

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#323]

**Comment by jnurthen** [comment]
* Re-title to "Grid"
* Have 2 sub-sections within the description for "Data Grids" and "Layout Grids"
* Keyboard Section
  * Need to add something about navigating to the cell or the content (Matt to write)
* Re-write description section to remove information which is no longer relevant in ARIA 1.1 and to add content about new features in ARIA 1.1

**Comment by MichielBijl** [comment]
Do we also have Complex Data Tables? i.e. why is simple in there?

**Comment by MichielBijl** [comment]
This issue was moved to w3c/aria-practices#29
