### ISSUE TITLE
WAI-ARIA 1.1: Update Authoring Practices links to 1.1 ?

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#328]
March 17 WAI-ARIA 1.1 Working Draft
(https://www.w3.org/TR/wai-aria-1.1/ aka http://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/)

Should all links to "WAI-ARIA Authoring Practices" be updated now to point to 1.1 ?(https://www.w3.org/TR/wai-aria-practices-1.1/)
(Including links to sections in the Authoring Practices, such as "Using Tabindex to Manage Focus Among Widgets" and "Providing Keyboard Focus in WAI-ARIA Authoring Practices" and "Drag-and-Drop Support in the WAI-ARIA Authoring Practices").

Also note that some (but not all) references to "WAI-ARIA Authoring Practices" in WAI-ARIA 1.1 have the word "Guide" in them (i.e. "WAI-ARIA Authoring Practices Guide"). Should the word "Guide" be deleted, for consistency?

**Comment by mcking65** [comment]
Looks like all links are good. There are several where fragments could direct the reader to specific sections, including links related to:
* combobox
* feed
* grid
* tabs
* tri-state checkbox
