### ISSUE TITLE
WAI-ARIA 1.1: Editorial comments for Sections 1 and 2

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#329]
March 17 WAI-ARIA 1.1 Working Draft (http://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/)
Sections 1 and 2:

1) Consider using "semantics" instead of "semantic" in this phrase:

> regardless of any semantic inherited from the implementing host language

2) Use present tense "manipulate" in this phrase:

>  need to be able to recognize and effectively manipulated and communicate various interaction states (e.g., disabled, checked) to the user

3) This example is odd. Did you mean, "by determining that **a set of elements having** a role of menuitem"?

>  For example, by determining that an element has a role of menuitem each containing text content representing a different flavor, a speech system might state to the user that, "Select one of three choices: chocolate, strawberry, or vanilla."

4) Plural/singular mismatch in this phrase:

>  It is not appropriate to create objects with style and script when the host language provides a semantic element for that type of objects.

- probably want something like the following (keep the initial plural of "objects" because the next sentence uses plural as well):

>  It is not appropriate to create objects with style and script when the host language provides a semantic element for that type of object.

5) First sentence of 1.5.1 Authoring Tools: "state" should be plural:

>  Many of the requirements in the definitions of WAI-ARIA roles, state, and properties 

6) Should probably change "needed" to "needs":

>  This could reduce the amount of information the user needed to process at any one time.

7) https://www.w3.org/TR/wai-aria-1.1/#usage: "state" should be plural:

>  WAI-ARIA divides the semantics into roles (the type defining a user interface element) and state and properties supported by the roles.

8) 2.1 WAI-ARIA Roles: delete "the" before "the Role Attribute" link.

>  A WAI-ARIA role is set on an element using a role attribute, similar to the role attribute defined in the Role Attribute [ROLE-ATTRIBUTE].

9) Aside (not important, but just curious, because it makes it a little harder to discover): Why is the role attribute defined in a separate document?

10) 2.1 WAI-ARIA Roles:  "state" should be plural:

>  supported state and properties for each role (e.g., a checkbox supports being checked via aria-checked).

11) https://www.w3.org/TR/wai-aria-1.1/#dfn-state: I think the definition of state should say "characteristic" singular (not "characteristics" plural) because each state (i.e. pressed, disabled, hidden, invalid, checked, etc) represents a single characteristic:

>  A state is a dynamic property expressing characteristics of an object that may change in response to user action or automated processes.

12) 2.2 WAI-ARIA States and Properties:  "state" should be plural:

>  WAI-ARIA provides a collection of accessibility state and properties

13) There are 8 instances of the string "state and properties" that should be "states and properties". These can be found with ctrl+F, so I won't list any more of them.  :)

14) Should be "toggle **the** value of...":

> JavaScript events will capture mouse and keyboard events to toggle value of aria-checked

15) Probably need the possessive apostrophe on "by modifying elements' navigation attributes" in the following sentence:

>  SVG authors may place elements in the navigation order by manipulating the focusable attribute and they may dynamically specify the navigation order by modifying elements navigation attributes.

16) Change "which" to "that" in the following phrase so that it reads "the last descendant that was active":

>  the container is responsible for tracking the last descendant which was active

**Comment by Joanmarie** [comment]
Thanks (again) for such a thorough review! I have fixed most of the issues. Remaining is:

> 3) This example is odd. Did you mean, "by determining that a set of elements having a role of menuitem"?
> 
> For example, by determining that an element has a role of menuitem each containing text content representing a different flavor, a speech system might state to the user that, "Select one of three choices: chocolate, strawberry, or vanilla."

There's a larger issue: That paragraph is describing "speech-based command and control systems" (i.e. input). But the example seems to be describing a tool with speech output. Granted, there is no reason a tool cannot have both speech input and output. But I don't think the example suits the paragraph, even if worded properly.
