### ISSUE TITLE
WAI-ARIA 1.1: Editorial comments for Sections 3 and 4

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#333]
Editorial comments for March 17 WAI-ARIA 1.1 Working Draft Sections 3 and 4:

1) https://www.w3.org/TR/wai-aria-1.1/#ua_domchanges
> Assistive technologies, such as voice recognition systems

I think this should be "speech recognition" not "voice recognition" (https://en.wikipedia.org/wiki/Speech_recognition).

2) Either "notify **a** web application", or "notify web application**s**" in the following:
> The ability for assistive technologies to notify web application of necessary changes is essential 

3) In the note in section 3.3, it would be useful to have "tab" and "tabpanel" link to their respective sections (https://www.w3.org/TR/wai-aria-1.1/#tab and https://www.w3.org/TR/wai-aria-1.1/#tabpanel) in this sentence:
> For example, the aria-selected state of a tab in a tabpanel can be changed by triggering the default action on the element.

4) https://www.w3.org/TR/wai-aria-1.1/#dfn-live-region  should be "updated as **a** result" (missing 'a')
> These regions are not always updated as result of a user interaction. 

5) https://www.w3.org/TR/wai-aria-1.1/#dfn-live-region  delete "how to" from:
> WAI-ARIA has provided a collection of properties that allow the author to identify these live regions and how to process them

**Comment by Joanmarie** [comment]
@carmacleod: Wow, thanks so much for your thorough review!  I believe I have addressed all issues you identified here, making the corrections you suggested. As such I'm closing this issue. If, upon review, you find something I missed then please reopen.

Thanks again!

**Comment by carmacleod** [comment]
Joanie!! So good to hear your voice!
So this is what you have been doing in your spare time.  ;)
 
You are very welcome, by the way. Glad to be a help.  :)
I am just getting up to speed on github, and I will try opening PR's for simple things instead of issues in future - hopefully that will make your life a tiny bit easier.  :)
 
Are you still working on Orca?
 
I hope all is well,
Carolyn (aka Car)
 
 
----- Original message -----From: Joanmarie <notifications@github.com>To: w3c/aria <aria@noreply.github.com>Cc: Carolyn MacLeod/Ottawa/IBM@IBMCA, Mention <mention@noreply.github.com>Subject: Re: [w3c/aria] WAI-ARIA 1.1: Editorial comments for Sections 3 and 4 (#333)Date: Wed, Apr 20, 2016 1:24 PM 
@carmacleod: Wow, thanks so much for your thorough review! I believe I have addressed all issues you identified here, making the corrections you suggested. As such I'm closing this issue. If, upon review, you find something I missed then please reopen.
Thanks again!
