### ISSUE TITLE
HTML-AAM: 5.12 name/description calculation for Section and Grouping elements overrides accname-aam

### ISSUE THREAD

**Issue by cyns** [w3c/aria#336]
The first bullet under name says that accname-aam is to be used if aria-label or aria-labelledby is present. Bullets 2 and 3 do not refer to it. Does that mean that if there is no aria, the accname-aam algorithm is not used? This would result in different names in some circumstances.

&lt;article&gt;Lorem ipsum...&lt;/article&gt;
using accname-aam would have a "Lorem ipsum..." as its name. using only title, it would not have a name, which seems problematic. Which is correct?

**Comment by cyns** [comment]
@AmeliaBR another naming question

**Comment by klown** [comment]
@cyns According to the [html-aam mapping table](https://rawgit.com/w3c/aria/master/html-aam/html-aam.html#el-article), &lt;article&gt; is mapped the same as role="article".  According to the ARIA spec for the [article role](https://www.w3.org/TR/wai-aria-1.1/#article):
- article supports name-from author only.
- article does not require an accessible name.

**Comment by cyns** [comment]
thanks.
