### ISSUE TITLE
WAI-ARIA 1.1: Inconsistent value for aria-expanded for role combobox

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#339]
In https://www.w3.org/TR/wai-aria-1.1/#combobox
EXAMPLE 5 shows a text input with aria-expanded="true", yet the 2nd sentence after the example says, "Elements with the role combobox have an implicit aria-expanded value of false".
Which one should it be? Is the example implying that authors do need to manage the aria-expanded attribute for combobox?

**Comment by jnurthen** [comment]
Should be clarified once we have sorted out the required properties.
