### ISSUE TITLE
HTML-AAM: UIA mapping for placeholder

### ISSUE THREAD

**Issue by cyns** [w3c/aria#340]
UIA mapping for placeholder should be
Not mapped to accessibility tree. Participates in name calculation (with link to name calculation).

The ARIA mapping for UIA uses the ARIAProperties field, which is only for aria, not html.

**Comment by klown** [comment]
@cyns 

> Not mapped to accessibility tree. Participates in name calculation (with link to name calculation).

GIven this example:
 `<input aria-label="Enter date:" placeholder="DD-MM-YYYY" ...>`

The `placeholder` is not exposed?  How is the format of the input communicated to ATs?
