### ISSUE TITLE
HTML-AAM: possible aria mapping for meter

### ISSUE THREAD

**Issue by cyns** [w3c/aria#344]
should we map meter to the following aria?

role = progressbar
aria-roledescription = meter
aria-readonly = true
aria-valuemax = max attribute
aria-valuemin = min attribute
aria-valuenow = value attribute
aria-valuetext = localized string representing the result of optimal calculation (we use "good", "fair", "poor")

**Comment by cyns** [comment]
@stevefaulkner @jasonkiss @Joanmarie thoughts?

**Comment by stevefaulkner** [comment]
Looks good to me

On Saturday, 23 April 2016, cyns <notifications@github.com> wrote:

> @stevefaulkner <https://github.com/stevefaulkner> @jasonkiss
> <https://github.com/jasonkiss> @Joanmarie <https://github.com/Joanmarie>
> thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/issues/344#issuecomment-213834351>
>


-- 
--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#42
