### ISSUE TITLE
Landmarks - Assistive technologies SHOULD; user agents MAY...

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#350]
The 3rd paragraph for region (role) says:
"Assistive technologies should enable users to quickly navigate to elements with role region. Mainstream user agents may enable users to quickly navigate to elements with role region."

but the 3rd paragraph for banner, complementary, contentinfo, form, main, navigation, and search say:
"User agents should treat elements with the role of banner as navigational landmarks."
....and they don't say anything about assistive technologies. Which seems really odd, because currently assistive technologies enable landmark navigation, but user agents don't do a thing with them... (I wish they did).

I think (?) all of the landmark roles should use the wording in region role.

(((Although if I could, I'd spec it so that user agents MUST enable users to quickly navigate to landmark roles... ;)  Just kidding. Sort of.)))

**Comment by mcking65** [comment]
Agree; I have been meaning to do some more work to make the landmark descriptions more consistent where appropriate. After I take care of some other hi-pri issues, if no one else has brabbged this one, I will.
