### ISSUE TITLE
ARIA 1.1: Feed supports aria-setsize

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#351]
The role description for feed: https://www.w3.org/TR/wai-aria-1.1/#feed
says:
"If the number of articles available in a feed supply is static, authors may specify aria-setsize on article elements in that feed. "

but aria-setsize is not in the inherited or supported states & properties list.
Should it be in the "supported" list?

**Comment by Joanmarie** [comment]
Both `aria-posinset` and `aria-setsize` are supported on the `article` role though. And as the text you quoted states, authors may specify `aria-setsize` on _article elements_ (emphasis added).

As stated in the spec's definition for [`aria-setsize`](https://rawgit.com/w3c/aria/master/aria/aria.html#aria-setsize):

> This property is marked on the members of a set, not the container element that collects the members of the set.

That said, do you have any suggestions that would eliminate this confusion?

**Comment by carmacleod** [comment]
Oh, right. I knew that once. I guess the wording is ok, in that case - I'll close this issue.
(It just feels "wrong" to have setsize on the members of the set and not the container, but that is for a different discussion, and I'm sure that discussion was closed long ago.)
