### ISSUE TITLE
ARIA 1.1: Label navigation landmarks if more than one per page

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#355]
If there's more than one navigation landmark on a page, authors should label them.
I thought that this was spec'd somewhere already, but I can't find it.
Perhaps it should be added to the spec?
https://www.w3.org/TR/wai-aria-1.1/#navigation

**Comment by jnurthen** [comment]
This sounds like Authoring Practices to me.
We have this in the new Landmarks section of the APG at
https://rawgit.com/w3c/aria-practices/master/aria-practices.html#general-principles-of-landmark-design

**Comment by carmacleod** [comment]
Thanks, James - that must be where I saw it.
So just one follow-up question: Should it be a "SHOULD" in the spec? It's a very common use case to have 2 navs - one across the top (often, but not always, for site navigation), and one down the left side (often, but not always, for in-page navigation). If they are both listed in a dialog as "navigation", or both spoken as "navigation landmark" by a screen reader, then the user is going to have to guess which one by navigating there first and figuring out the context, which is sort of sub-optimal.
I think it's an important enough recommendation that perhaps authors SHOULD do it?

**Comment by jnurthen** [comment]
I really think the authoring practices are the right place for such content. I wouldn't object to a PR but think we have more important issues to address.

**Comment by jnurthen** [comment]
👍
