### ISSUE TITLE
HTML-AAM: determine right mappings for browser generated form validation error messages

### ISSUE THREAD

**Issue by cyns** [w3c/aria#360]
UIA covered in #160. Other APIs need this too.

**Comment by cyns** [comment]
IA2_STATE_INVALID_ENTRY
how can error message UI be connected to input and caused to speak in the various APIs?

**Comment by cyns** [comment]
@Joanmarie @asurkov What's the right way to map the error messages that show up with the required attribute, and validated inputs (eg URL, email, number) in IA2 and ATK? These don't work well with NVDA in Firefox or Chrome on Windows.

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#47
