### ISSUE TITLE
footer and header element context as landmarks (main element context change from parent to descendant)

### ISSUE THREAD

**Issue by jongund** [w3c/aria#362]
Recommend changing:

"footer (nearest ancestor sectioning content or sectioning root element is not body, or parent is main)"
to
"footer (nearest ancestor sectioning content or sectioning root element is not body or is a descendant of main)"
# 

"footer (nearest ancestor sectioning content or sectioning root element is body)"
to
"footer (nearest ancestor sectioning content or sectioning root element is body and not a descendant of main)"
# 

"header (nearest ancestor sectioning content or sectioning root element is not body, or parent is main)"
to
"header (nearest ancestor sectioning content or sectioning root element is not body or is a descendant of main)"
# 

"header (nearest ancestor sectioning content or sectioning root element is body)"
to
"header (nearest ancestor sectioning content or sectioning root element is body and not a descendant of main)"

**Comment by jasonkiss** [comment]
Getting the language right here is admittedly tricky. 

I think you're trying to describe a scenario where the `header` or `footer` is not a descendant of `main`, not that the nearest ancestor sectioning element itself is not a descendant of `main`, which is how I read the proposed text. So I don't think the proposed text is exactly right. 

See also issue #277. How would you feel about the following phrase to define the use of `header` and `footer` that should not be landmarks: "descendant of `main`, or of sectioning content or sectioning root element other than `body`"?

Conversely, `header` and `footer` should be landmarks only where they are "descendant of body but not descendant of main or of other sectioning content or sectioning root element".

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#65

**Comment by stevefaulkner** [comment]
We need to file bugs aganst the browsers, to get them to implement this change
have got ball rolling
firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1316285

**Comment by Wildebrew** [comment]
What is the definition of "main" in this context? Is it only the <main> html5 element, or is it any container element with role="main"?
I would strongly recommend including both.
I am seeing a lot of pages that use <header> and <footer> in containers with role="main" and, at least in IE11, they consistently get mapped to banner/contentinfo landmarks, which is not correct and does not match the definition of those landmarks (see ARIA 1.1 definitions for banner and contentinfo).
In fact I would expand the wording to:
Footer (or <header>)is not mapped as an ARIA landmark if it the descendant of:
* <header> element (or element with role="banner", 
* <main> (or element with role="main")
* <footer> (or element with role="contentinfo)
* sectioning element (<section> or <article>).

**Comment by joanmarie** [comment]
@jasonkiss, regarding:
> This issue was moved to w3c/html-aam#65

Does that mean this (ARIA) issue is a dup of the html-aam issue and can be closed as such?

**Comment by jasonkiss** [comment]
Yes.
