### ISSUE TITLE
HTML-AAM: determine right mappings for popup ui for input type=color

### ISSUE THREAD

**Issue by cyns** [w3c/aria#363]
The color picker dialog that pops up from input type=color is not reliably mapped to accessibility APIs in browsers and does not reliably work with screen readers. We need to determine the right way to map the relationship between the launcher (button or edit) and popup UI, so that screen readers can find it.

**Comment by cyns** [comment]
Here's what we're doing in UIA:
Control Type: Button
Localized Control Type: color picker
ControllerFor: points to the popup
The popup and its children must be present in the UIA tree, and mapped as button, slider, etc. as appropriate for the type of control.

Would it work to do something similar with ControllerFor/ControlledBy in IA2 and ATK?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#48
