### ISSUE TITLE
HTML-AAM: determine right mappings for popup ui for date and time inputs

### ISSUE THREAD

**Issue by cyns** [w3c/aria#364]
The UI that pops up from date and time inputs is not reliably mapped to accessibility APIs in browsers and does not reliably work with screen readers. We need to determine the right way to map the relationship between the launcher (button or edit) and popup UI, so that screen readers can find it.

This applies to 
input (type attribute in the Date state)
input (type attribute in the Date and Time state)
input (type attribute in the Local Date and Time state)
input (type attribute in the Month state)
input (type attribute in the Week state)

Where these inputs have popup UI. (time doesn't on Chrome.)

**Comment by cyns** [comment]
@Joanmarie @asurkov similar to the issues with color picker (#363) and validation errors (#360 #160)
Here's what we're doing in UIA:
Control Type: Edit
Localized Control Type: (element state name)
ControllerFor: points to the popup
The popup and its children must be present in the UIA tree, and mapped as button, slider, etc. as appropriate for the type of control.

Would it work to do something similar with ControllerFor/ControlledBy in IA2 and ATK?

**Comment by asurkov** [comment]
I would say this is a reasonable suggestion, but iirc there's a bunch of examples, where people use aria-owns relations.

**Comment by mcking65** [comment]
aria-owns creates problems ... pls go w/controling relationship.

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#49
