### ISSUE TITLE
html-aam: generic text elements should take name from contents, be consistant with accname-aam

### ISSUE THREAD

**Issue by cyns** [w3c/aria#367]
name calculation for "5.13 Text Level Elements Not listed Elsewhere" conflicts with accname-aam step [2G](https://rawgit.com/w3c/aria/master/accname-aam/accname-aam.html#step2G)
"G. Otherwise, if the current node is a Text node, return its textual contents." In addition, "tooltip attribute" such as title is in step H, and intended to be lower priority than textual content.

Suggest changing name calculation for generic text elements to

1. If the element has an aria-label or an aria-labelledby attribute the accessible name is to be calculated using the algorithm defined in Accessible Name and Description: Computation and API Mappings 1.1.

2. Otherwise, use the text content of the element
3. Otherwise use the title attribute
4. If none of the above yield a usable text string there is no accessible name

accessible description remains unchanged.

**Comment by jasonkiss** [comment]
Merged in https://github.com/w3c/aria/commit/e2f656c56df37ea1184353d40877508036332c3d.

Closing.
