### ISSUE TITLE
html-aam: output element should take name from contents, have its own section

### ISSUE THREAD

**Issue by cyns** [w3c/aria#368]
The output element should have a section describing its name and description behavior, which includes aspects of both form and text elements.

In particular, output should take name from contents, to enable this scenario:
&lt;label&gt;Your total is &lt;output&gt;75&lt;/output&gt; dollars.&lt;/label&gt;

This should be read as "Your total is 75 dollars."

**Comment by jasonkiss** [comment]
Merged in https://github.com/w3c/aria/commit/e2f656c56df37ea1184353d40877508036332c3d.
Closing.
