### ISSUE TITLE
html-aam: name calculation doesn't seem to cover embedded controls

### ISSUE THREAD

**Issue by cyns** [w3c/aria#369]
This markup
&lt;label&gt;Wait &lt;input type=number value=5&gt; minutes before rebooting&lt;/label&gt;
should result in an accessible name of "Wait 5 minutes before rebooting" for the number input. The recursive algorithm in accname-aam will result in that string, but it is not clear reading html-aam that this is covered. Is it the expectation that the accname-aam algorithm will be run for all elements, or only for form elements that contain aria-label, aria-labelledby, or aria-describedby?

**Comment by cyns** [comment]
@stevefaulkner @jasonkiss @AmeliaBR thoughts?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#50
