### ISSUE TITLE
HTML-AAM Update AX mappings for sub and sup elements

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria#374]
`<sub>`
AXRole: AXGroup 
AXSubrole: AXSubscriptStyleGroup 
AXRoleDescription: group 

`<sup>`
AXRole: AXGroup 
 AXSubrole: AXSuperscriptStyleGroup 
AXRoleDescription: group 

source: http://trac.webkit.org/changeset/200214/trunk/LayoutTests/platform/mac/accessibility/roles-exposed-expected.txt

**Comment by jasonkiss** [comment]
Done.
