### ISSUE TITLE
DPUB roles should remove sub-level hyphenation other than for dpub- prefix.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#38]
DPUB roles should remove sub-level hyphenation other than for issue #36 prefixing. E.g. page-list should be dpub-pagelist.

**Comment by cookiecrook** [comment]
From 9 March 2015: 
https://lists.w3.org/Archives/Public/public-pfwg/2015Mar/0021.html

**Comment by mattgarrish** [comment]
Hyphenation was previously removed from the role names.

**Comment by cookiecrook** [comment]
Okay
