### ISSUE TITLE
HTML-AAM: how to treat &lt;img alt&gt; with no value

### ISSUE THREAD

**Issue by cyns** [w3c/aria#381]
Should &lt;img alt&gt; be treated like &lt;img alt=""&gt; (mapped to role=presentation) or like &lt;img&gt; with missing alt attribute?

**Comment by cyns** [comment]
@stevefaulkner @jasonkiss this implementation question came up today. I'm inclined to treat alt with no equals or value as a missing alt, rather than an empty string. What do you think?

**Comment by AmeliaBR** [comment]
Browser dev tools do not distinguish between alt attribute set to an empty string ( `<img alt="" />` ) and alt attribute without a value (`<img alt />`).  Chrome normalizes both to the Boolean format (without a value), while Edge and Firefox normalize both to the empty string version.

I haven't tested whether there are currently any differences in how they are exposed to the accessibility tree.  However, I am fairly confident that authors would expect them to be interchangeable.  So, to Cynthia's question: alt without a value should be treated like alt with an empty string, which is different from no alt at all.

**Comment by AmeliaBR** [comment]
PS: [Test case as JSBin output page](http://output.jsbin.com/gisulebafu)

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#55
