### ISSUE TITLE
[SCRIPTS] Add (or restore/fix) programmatic way to mark required inherited properties

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#386]
([Reported via Twitter](https://twitter.com/cookiecrook/status/735745101926780928))

In ARIA 1.0, required states and properties which were inherited were marked as "required" in the characteristics table. This is no longer happening. See, for example, [menuitemcheckbox for 1.0](https://www.w3.org/TR/2014/REC-wai-aria-20140320/complete#menuitemcheckbox) compared to [menuitemcheckbox for 1.1](https://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/#menuitemcheckbox). I've not yet researched how it happened before, and while I could go in and manually add "(required)" everywhere it belongs, it would be cool if it magically JustWorked(tm).

@halindrome: Do you happen to know off the top of your head if this used to be done by the scripts?

**Comment by halindrome** [comment]
I am sure it was.  I will put it on my list.
