### ISSUE TITLE
Importing jquery-1.9.0.min.js

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/aria#394]
A few of the aria specs seem to import jquery-1.9.0.min.js. This is not needed as ReSpec imports jQuery for you into the global object. Also, ReSpec's jQuery is newer so having two of them around is not great (ReSpec is probably trashing 1.9).

**Comment by halindrome** [comment]
Static versions of the specs rely upon jquery.  We cannot remove our dependency on it.  But it does not cause any conflicts.

**Comment by marcoscaceres** [comment]
My question was about importing it twice: you get it for free in the global scope with ReSpec, so why d/l it twice?

**Comment by halindrome** [comment]
Because 99% of the time this document is static and has no respec loaded.
