### ISSUE TITLE
Several of the DPUB roles are too specific. "learning-outcome" and "learning-objective" for example.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#40]
Several of the DPUB roles are too specific. "learning-outcome" and "learning-objective" for example.

From 9 March 2015: 
https://lists.w3.org/Archives/Public/public-pfwg/2015Mar/0021.html

**Comment by mattgarrish** [comment]
Again, these were removed.

**Comment by cookiecrook** [comment]
Okay. This is feedback from March, Sarika requested today that I add it to the tracker.
