### ISSUE TITLE
HTML-AAM: Remove MSAA+UIA Express column

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#404]
Bringing this over from [W3 Bugzilla 29180](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29180).

[Action-1717](https://www.w3.org/WAI/ARIA/track/actions/1717) and [Action-1706](https://www.w3.org/WAI/ARIA/track/actions/1706) are now closed, and the CORE-AAM includes[ this commit from @cyns](https://github.com/w3c/aria/pull/398/commits/847124041e2fee0557083d8c6bc4fe45d27c58c8) with the note encouraging use of UIA over UIAExpress.

@asurkov What's Mozilla's disposition at this point with respect to this question? Can we remove the MSAA+UIAExpress column and add the same note re UIAExpress from the CORE-AAM?

I note that [David Bolter suggested the possibility of including UIAExpress notes in the UIA column](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29180#c6). That might be something to consider, but then again, it seems like MS is discouraging use of UIAExpress.

@stevefaulkner @cyns @klown Any opinions to inform this question?

**Comment by klown** [comment]
Hi @jasonkiss 
> Any opinions to inform this question?

I have no opinion.  I'm following @cyns advice here.

**Comment by asurkov** [comment]
there's no recent changes in Gecko's UIA support, neither UIAExpress nor UIA. However UIA doesn't feel different from UIAExpress in terms of API mapping, they shouldn't go into a large conflict as they expose same patterns. 

What kind of UIAExpress notes that would be? MSAA related comments?

**Comment by jasonkiss** [comment]
See thread from wai-xtech: https://lists.w3.org/Archives/Public/wai-xtech/2016Aug/0014.html

Moving discussion here. I have created branch "html-remove-uiaexpress" where I'll move the role information from the MSAA+UIAExpress column into the MSAA+IA2 column for review.

**Comment by jasonkiss** [comment]
@asurkov Please review https://rawgit.com/w3c/aria/html-remove-uiaexpress/html-aam/html-aam.html#html-element-role-mappings to makes sure the MSAA+IA2 mappings are correct. I've tried to move all relevant role/state mappings from MSAA+UIAExpress into MSAA+IA2.

Other questions: 

1. For elements that have no accessible object but whose various styles/properties are exposed in attributes on the "text container", is the "text container" the element itself, its immediate parent, or its nearest ancestor accessible object?
2. Please review mappings for `input type=file`, `label`, `rp`, `rt`, `span`, and `time`.

@cyns, you might want to take a peek, as well.

**Comment by asurkov** [comment]
@jasonkiss do you have a diff at hands?

**Comment by jasonkiss** [comment]
@asurkov The commit is here: https://github.com/w3c/aria/commit/f4075353a61fc79e1dd1cba0de444f009c15d12e?diff=split

Sorry, but there were too many changes and GH won't display the diff, so you'll need to view it in a local Git client, or you could use some other diff tool to compare them.

**Comment by jasonkiss** [comment]
Closing as 'html-remove-uiaexpress' branch merged in https://github.com/w3c/aria/pull/429
