### ISSUE TITLE
aria-describedat is still in the images of ARIA SVG, PNG

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#408]
https://www.w3.org/TR/wai-aria-1.1/img/rdf_model.svg
https://www.w3.org/TR/wai-aria-1.1/img/rdf_model
https://www.w3.org/TR/wai-aria-1.1/img/rdf_model.png
etc...

**Comment by michael-n-cooper** [comment]
Addressed by 6ee805e384e8cebfba4bf9e283b4a64779192342 supported by a4f8afbcf85e19ac4f6dfcf043cd98cdc2af9d51 and d757d0138cefa87f59028c5ba383bfd08e40dc63
