### ISSUE TITLE
The WAI-ARIA Role, State, and Property Quick Reference is still a placeholder

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#409]
Sent in email by @stevefaulkner at https://lists.w3.org/Archives/Public/w3c-wai-ig/2016JulSep/0076.html

The WAI-ARIA Role, State, and Property Quick Reference is still a placeholder

Placeholder for global states and properties

> Placeholder for quick reference table
> 
> https://www.w3.org/TR/wai-aria-1.1/#quickref

**Comment by michael-n-cooper** [comment]
I have commented out the appendix, since we didn't set up auto generation of the content. We may restore it later, or move this appendix to other resources.

**Comment by jnurthen** [comment]
Looks like this can be closed. Reopen if necessary.
