### ISSUE TITLE
Tab panel doesn't use role=application, but example does

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#415]
https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel

The tab panel correctly doesn't use role="application but the example listed form open AJAX does.
http://www.oaa-accessibility.org/examplep/tabpanel1/
http://www.oaa-accessibility.org/examplep/tabpanel2/

May want to check other examples throughout the document for the same issue where examples apply role="application" but the document doesn't

**Comment by jnurthen** [comment]
We no longer link to anything from OAA
