### ISSUE TITLE
CORE-AAM: need UIA mapping for aria-autocomplete

### ISSUE THREAD

**Issue by cyns** [w3c/aria#419]

**Comment by joanmarie** [comment]
@boggydigital: As you'll see in the [Core AAM](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaAutocompleteInlineListBoth), the mapping is currently:

> Expose `autocomplete=<value>` in `AriaProperties`

There is no mention of `controllerFor`.

You should know the routine by now. :) But just in case: If a change is called for, please do a pull-request with that change. If no change is called for, please comment documenting why and close this issue. And please clear the "needinfo" flag once you've done either. Thanks much!

**Comment by boggydigital** [comment]
After thinking about this for some time I've decided that the only consistent solution that does make sense here is match AX API and set this as "Not mapped" to reflect the fact there is no clear concept like MSAA/IA2/ATK here.

https://github.com/w3c/aria/pull/627 has more explanation. The earlier proposal, while made in good spirit and intent - would be extremely hard to specify, implement and would make UIA very inconsistent here - for very little value. 

As a result - I believe "Not mapped" makes the most sense here, actually.

**Comment by joanmarie** [comment]
Thanks! Merged.
