### ISSUE TITLE
DPUB: "landmarks" is going to confuse a lot of authors.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#42]
DPUB: "landmarks" is going to confuse a lot of authors. Even once the prefix is added (#36), it will still be unclear as to how this differs from the "landmark" role in ARIA.

From 9 March 2015: 
https://lists.w3.org/Archives/Public/public-pfwg/2015Mar/0021.html

**Comment by mattgarrish** [comment]
Landmarks is not in the proposal.

**Comment by cookiecrook** [comment]
This is feedback from March, entered directly into the tracker. Are you saying it has been removed since then or something else?

**Comment by mattgarrish** [comment]
The landmarks role was removed subsequent to your raising the issue. A simple rename did not seem appropriate, and the directory role already is related to the daisy guide element, which is a forerunner of the epub 3 landmarks nav.

We might reintroduce something later, if needed, but we also want to take more time on that one to see how the epub-web proposal develops.

**Comment by cookiecrook** [comment]
Thanks. Closing.
