### ISSUE TITLE
CORE-AAM: clean up UIA mapping for aria-haspopup

### ISSUE THREAD

**Issue by cyns** [w3c/aria#428]
add to beginning 
"Expose ExpandCollapse pattern. if aria-expanded is not specified, set ExpandCollapseState to collapsed"

**Comment by klown** [comment]
@cyns,
Could you give a bit more information?  aria-haspopup has a number of values -- true, false, dialog, listbox, menu, and tree.  I think the only case where your suggested text does not apply is "false".  Otherwise, add the above sentence to all the other cases.

Right?

**Comment by klown** [comment]
Created [ACTION-2120](https://www.w3.org/WAI/ARIA/track/actions/2120) in W3C tracker, and assigned to Bogdan.

**Comment by boggydigital** [comment]
Created https://github.com/w3c/aria/pull/467 to clean this up
