### ISSUE TITLE
DPUB "notice" role should have clarifying text and/or a required context role

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#43]
In the context of published content, an object of role "notice" seems a lot like a tip or comment or annotation. Presumably a non-interactive one.(?) In the context of a web application, however, a "notice" might be something that pops up when you give focus to a password field to let you know Caps Lock is locked or that you're about to be logged out from your banking site. In the former case, a screen reader might want to provide a means to navigate to it on demand; in the latter case, the screen reader should potentially announce it automatically. In the former case, on my platform, the mapping would be ATK_ROLE_COMMENT; in the latter case ATK_ROLE_NOTIFICATION.

The current definition of role "notice" doesn't say anything about whether or not a "notice" is interactive or not, whether a screen reader should automatically present it or not, in what context it should appear or not. I think it would be helpful if such text was added for content/app, user agent, and AT developers.

**Comment by Joanmarie** [comment]
Might also be worth pointing to https://rawgit.com/w3c/aria/master/aria/aria.html#alert in the clarifying text.

**Comment by mattgarrish** [comment]
Some brief history from epub: originally we had both notice and warning, but consolidated them into one common term. The "notice" name was generally agreed upon as being the most neutral way to refer to the group of warnings, cautions, alerts, etc. that appear in books.

notice and tip are similar, but the distinction is one of importance. A notice contains information that has to be presented to reader at the point they encounter it, whereas a tip is secondary information that could potentially be skipped if the reader only wants to follow the logical reading order.

Currently, neither are conceived as interactive, and notice is not intended to be a live region like the existing alert role.

I definitely agree that we can, and should, provide more guidance. I was expecting we'd get to fleshing out some more detail post-FPWD, as there are other roles I'm sure would likewise benefit from more info. Right now they're mostly just definitions and characteristic tables.

**Comment by Joanmarie** [comment]
Another idea occurs to me based on what you said, what I'm concerned about, and related(ish) needs for web apps for document editing: What about a superclass "annotation" or "note" role? Your notice and tip roles might fit nicely under there. A "comment" role for document editing web apps would too.  And anything that is a subclass of an annotation/note is (I would hope) clearly not an interactive thing. :)

**Comment by Joanmarie** [comment]
Sorry for being spammy. But you said:

> a tip is secondary information that could potentially be skipped if the reader only wants to follow the logical reading order.

And currently you have the superclass role of tip being region. Were you aware that region became a subclass of landmark? See https://rawgit.com/w3c/aria/master/aria/aria.html#substantive-changes-since-the-last-public-working-draft under "29-Jan-2015." (And yes, we really do need to get a new heartbeat draft of the ARIA spec out. We plan to do so soon.)

**Comment by mattgarrish** [comment]
Ah, that is problematic. And tips are not intended for inclusion in a table of contents.

Note definitely looks like a more appropriate choice.

**Comment by Joanmarie** [comment]
I think note would be a cool superclass that ultimately would be useful in ARIA core. We (ARIA core) wordsmith things pretty thoroughly (I am amongst the guilty), but if you all like it in DPUB it could start there. :)

**Comment by mattgarrish** [comment]
I just pushed an update to change.

**Comment by TzviyaSiegman** [comment]
@Joanmarie @mattgarrish is this sufficiently resolved by revision of document in accordance with https://www.w3.org/WAI/PF/wiki/ARIAExtensions? Superclass is still region. Is this candidate for 1.1?

**Comment by mattgarrish** [comment]
That's interesting. I pushed a change to the superclass, so no idea where it went. Please leave open as we'll have to update again.

**Comment by mattgarrish** [comment]
Updated again.
