### ISSUE TITLE
Typo in aria-rowindex example code

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#430]
https://rawgit.com/w3c/aria/master/aria/aria.html#aria-rowindex
There are 6 instances of ```>>``` in the example code that should just be ```>```.
For example:
```<span role="gridcell">>Acme, Inc.</span>```

**Comment by Joanmarie** [comment]
Thanks for the report. Should be fixed. Closing this issue. Feel free to reopen if anything was missed.

**Comment by carmacleod** [comment]
Wow - that was incredibly fast! Nice! :)
