### ISSUE TITLE
aria-required vs required: spec mismatch between ARIA 1.1 and HTML 5.1

### ISSUE THREAD

**Issue by dd8** [w3c/aria#433]
In HTML 5.1 the required attribute is allowed on input type=radio and input type=checkbox. See 'Content attributes' table here:
https://www.w3.org/TR/html51/sec-forms.html#attr-input-type-keywords

In ARIA 1.1 the aria-required attribute is not listed as a property of the 'radio' or 'checkbox' roles.

To see this causing a problem paste the following into validator.w3.org/nu:

```
        <input type="radio" aria-required="true" required="required" />
        <input type="checkbox" aria-required="true" required="required" />
```

The aria-required attribute isn't allowed (and produces an error) but the required attribute is allowed.

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by stevefaulkner** [comment]
> The aria-required attribute isn't allowed (and produces an error) but the required attribute is allowed

this is no longer the case `aria-required` is conforming to use on any HTML5 element that allows the `required` attribute, but if present along with `required` its value must be `true`

refer to: http://w3c.github.io/html-aria/#attr-required

**Comment by carmacleod** [comment]
discussion points for aria 1.3 attribute parity:
- what does it mean to "require" a checkbox? does it mean that the user must check it?
- what does it mean to "require" a radio? makes more sense to "require" the containing [radiogroup](http://w3c.github.io/aria/#radiogroup) (which already does support `aria-required`)

**Comment by jnurthen** [comment]
Per @stevefaulkner comment closing this as it doesn't seem to be an issue any more
