### ISSUE TITLE
[ARIA] Menubar superclass and required owned elements are not consistent with native equivalents

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#434]
The [ARIA spec for menubar](https://rawgit.com/w3c/aria/master/aria/aria.html#menubar) states:
- **Required owned elements:** `group`→`menuitemradio`, `menuitem`, `menuitemcheckbox`, `menuitemradio`
- **Superclass Role:** `menu`

On my platform, and I believe on others, the children of native menubars are almost always menus; not menuitems. For instance, when you open the File menu, the screen reader calls File a "menu". Furthermore, at least on my platform, if you use an accessibility inspector to examine native menubar children, those children have the role of menu; not menu item. Moreover, one would expect (and one does find) the grandchildren of menubars (i.e. File->New, File->Open..., Edit->Copy, etc.) to have role menuitem (item of a menu).

The above is a long way of saying: I think that required owned elements should include (if not entirely consist of) menu to be consistent with what is seen for native menubars.

As for the superclass role, admittedly my thoughts above color my opinion, but a menubar is not an instance/subclass of a menu; it's an instance/subclass of a toolbar (imho).

**Comment by carmacleod** [comment]
Not sure if this is helpful, but here is a screen snap of the Notepad menubar on Windows 7 with the File menu open and the New menu item selected. In the Inspect window, "File" is a "menu item" with a "popup menu" child that has ("New", "Open", etc) "menu item" children.
JAWS says "Menubar, File" when the user types Alt to go to the menubar. If the user types down arrow, JAWS says "Menu, File menu, New".
NVDA for some reason says "File submenu" after the user types Alt, and then "New" after the down arrow.

If you inspect the Linux menu bar, what does the inspector call the File, Edit, etc "buttons"?
![windows-menubar](https://cloud.githubusercontent.com/assets/3331913/18751676/d4871a8c-80ad-11e6-9880-a373d1c1d2b4.png)

**Comment by Joanmarie** [comment]
File, Edit, etc are ATSPI_ROLE_MENU.

**Comment by klown** [comment]
On 2016-09-25 3:02 PM, Joanmarie wrote:
    
    
      File, Edit, etc are ATSPI_ROLE_MENU.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/w3c/aria","title":"w3c/aria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/w3c/aria"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Joanmarie in #434: File, Edit, etc are ATSPI_ROLE_MENU."}],"action":{"name":"View Issue","url":"https://github.com/w3c/aria/issues/434#issuecomment-249439630"}}}
    
    
    It's odd, but at the level of GTK, a menubar
        has menuitem children, at least according to the GNOME developer
        documentation:
    "GtkMenuBar — A subclass of
      GtkMenuShell which holds GtkMenuItem widgets"
      (https://developer.gnome.org/gtk3/stable/GtkMenuBar.html)
    
    
    
      
        File, Edit, etc are ATSPI_ROLE_MENU.
      
      
    
    That implies that GTK simplifies the GtkMenuBar -> GtkMenuItem
      -> GtkMenu hierarchy when mapping to ATK/AT-SPI.
    
    
    -- 
;;;;joseph.

'Die Wahrheit ist Irgendwo da Draußen. Wieder.'
                 - C. Carter -

**Comment by Joanmarie** [comment]
That may be the case. And we can close this as WONTFIX in light of the fact that I was incorrect about other platforms having this same structure.
