### ISSUE TITLE
DPUB nit: The "Is Abstract" value of role "part" should not be section

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#44]
See: https://github.com/w3c/aria/blob/master/aria/dpub.html#L2256

**Comment by halindrome** [comment]
I think this is a typo - should be the superclass role.

On Wed, Apr 22, 2015 at 9:19 PM, Joanmarie <notifications@github.com> wrote:

> See: https://github.com/w3c/aria/blob/master/aria/dpub.html#L2256
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/issues/44>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by mattgarrish** [comment]
Yes, got added to the wrong table row. Updated now.
