### ISSUE TITLE
HTML-AAM: IA2 and ATK mappings for input type=number

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#442]
Email from @asurkov: "el-input-number - UIA part looks fair, I'd say IA2/ATK should say something similar"

You thinking something like this for both IA2 and ATK?
	
> If implemented as a spinbutton, use WAI-ARIA mapping.
> If implemented as a textbox, use WAI-ARIA mapping.

Or do you want IA2 object attribute `text-input-type:number`?

@Joanmarie, what are your thoughts?

**Comment by Joanmarie** [comment]
If implemented as a spinbutton, use WAI-ARIA mapping _for spinbutton_.
If implemented as a textbox, use WAI-ARIA mapping _for textbox_.

I'm not opposed to some object attribute also being exposed, but the AtkRole should reflect the widget as implemented.

**Comment by jasonkiss** [comment]
Thanks, @Joanmarie.

I like it, and to better differentiate between the generic discrete widgets from their ARIA roles, how about:

If implemented as a spin button, use WAI-ARIA mapping for `spinbutton`.
If implemented as a text input, use WAI-ARIA mapping for `textbox`.

Whatever the terminology, do the above two lines more or less address your concern that AtkRole reflect the implemented widget? Or should we add a statement expressly addressing it?

And are you happy with the unofficial "text-input-type" object attribute with a value of "number"?

On that last question, @asurkov, should you update Mozilla's [list of unofficial object attributes supported by Gecko](https://developer.mozilla.org/en-US/docs/Web/Accessibility/AT-APIs/IA2/Attrs)? It doesn't list "text-input-type".

**Comment by Joanmarie** [comment]
> Whatever the terminology, do the above two lines more or less address your concern that AtkRole reflect the implemented widget? Or should we add a statement expressly addressing it?

I would hope that implementors were already planning on basing the AtkRole on the implemented widget type. And the lines you provided should eliminate any doubts they might have. So if you or others think we need a statement expressly addressing it, I have no objection. But I myself think/hope such an additional statement isn't needed.

> And are you happy with the unofficial "text-input-type" object attribute with a value of "number"?

I have no opinion on that personally. The exposed role should mean there is no need for me to check the object attributes for role information. If Jamie and @asurkov are happy with it, it's fine by me.

**Comment by jasonkiss** [comment]
>  But I myself think/hope such an additional statement isn't needed.

Agreed.

@asurkov Can you confirm you are happy with text-input-type:number as obj attr? Do you want to confirm with Jamie?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#63
