### ISSUE TITLE
remove line-height declaration from common.css

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#445]
The lovely new design for W3C specs sets a line-height of 1.5 in line 79 of [base.css](https://www.w3.org/StyleSheets/TR/2016/base.css). 

This is overwritten by a line-height of 1.2 set in line 4 of [/aria/common/css/common.css](https://github.com/w3c/aria/blob/master/common/css/common.css). 

The [mapping-tables.css](https://github.com/w3c/aria/blob/master/common/css/mapping-tables.css) sets a line-height of 1.4 on the `body` element (see line 1), and 1.3 for the items in the mapping table cells (see line 50). 

The smaller line-heights reduce legibility. Can we just remove the declarations from common.css and mapping-tables.css and let the 1.5 line-height be?

**Comment by jnurthen** [comment]
This issue was moved to w3c/aria-common#18
