### ISSUE TITLE
DPUB: Shouldn't role "part" require an accessible name?

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#45]
The definition of role "part" is currently "A major structural division in a work that contains a set of related sections dealing with a particular subject, narrative arc or similar encapsulated theme." To me that sounds like something we'd want content creators to provide an accessible name for. (Right?)

**Comment by halindrome** [comment]
+1

On Wed, Apr 22, 2015 at 9:31 PM, Joanmarie <notifications@github.com> wrote:

> The definition of role "part" is currently "A major structural division in
> a work that contains a set of related sections dealing with a particular
> subject, narrative arc or similar encapsulated theme." To me that sounds
> like something we'd want content creators to provide an accessible name
> for. (Right?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/issues/45>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by mattgarrish** [comment]
Fixed to true for that field.

**Comment by richschwer** [comment]
This would be a name supplied by the author.

**Comment by mattgarrish** [comment]
Right, and the "name from" fields were changed as requested earlier. Checked again for part, and it does indicate author.
