### ISSUE TITLE
DPUB: Should there be an "endnotes" role?

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#46]
Feel free to say "no" and close this. :) But with all of the other roles for parts of publications, the lack of endnotes struck me as curious. So I'm asking via issue. :)

**Comment by mattgarrish** [comment]
We had one, but it led to a really long debate in the dpub group about the nature of notes, whether html5 needs a dedicated element, and whether there are other ways to express placement (foot, end, side, etc.) and/or if it actually represents some other metadata about the note (e.g., primacy if a footnote, secondary if an endnote).

From a web ontology writing perspective, it was really hard to express what differentiates a group of endnotes from a group of footnotes. Publishers already tend to group all their footnotes at the end of documents, and refer to them as footnotes. The only unique quality of endnotes is that they occur in backmatter, but that isn't an exclusive requirement.

For simplicity, we chose to start the vocabulary with footnote/footnotes, but we're not ruling out other additions.

**Comment by cookiecrook** [comment]
Seems like this could be covered by existing roles (`<section>`, chapter, region, etc.) with a labeling heading.

**Comment by TzviyaSiegman** [comment]
As Matt explained endnote(s) is another way to display footnote(s), so we chose to include only one in the vocabulary.
