### ISSUE TITLE
CORE-AAM 1.1: Create MacOSX Mappings for aria-rowcount

### ISSUE THREAD

**Issue by richschwer** [w3c/aria#462]
Moved from tracker action: https://www.w3.org/WAI/ARIA/track/actions/2119

**Comment by richschwer** [comment]
Note: one issue we are discussing with NVDA and Freedom Scientific is the issue of dealing with aria-colindex and aria-rowindex, aria-rowspan, aria-colspan in the mappings when rows or columns are discontinuous.

**Comment by cookiecrook** [comment]
Dupe of #459
