### ISSUE TITLE
CORE-AAM 1.1: aria-roledescription ensure proper macOS mappings including handling of white space and empty strings

### ISSUE THREAD

**Issue by richschwer** [w3c/aria#464]
Moved from tracker action: https://www.w3.org/WAI/ARIA/track/actions/2119

**Comment by cookiecrook** [comment]
empty roledescription
https://bugs.webkit.org/show_bug.cgi?id=163647

roledescription role limitations blocked by issue #500
https://www.w3.org/WAI/ARIA/track/issues/1048

**Comment by klown** [comment]
Closing, noting that the restrictions will be part of the [ARIA 1.1 testing effort](https://www.w3.org/wiki/ARIA_1.1_Testable_Statements).
