### ISSUE TITLE
input format property

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#466]
Provide new attribute property that aligns with HTML 5.1 type https://www.w3.org/TR/2016/REC-html51-20161101/sec-forms.html#element-attrdef-input-type

**Comment by michael-n-cooper** [comment]
Note the lovely password issue #166 could potentially also be handled as a format type under this issue. https://www.w3.org/2016/11/03-aria-minutes.html

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by joanmarie** [comment]
Marking as a duplicate of #962. (Yeah, I know this one here came first, but I hadn't seen it when I opened #962, and the newer issue has more discussion.)
