### ISSUE TITLE
required context role is misused throughout DPUB draft

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#47]
Required context is the parent context role, but the examples are mismatched. For example, "biblioentry" has a required context of "bibliography" but it's used here in the context of "list", not "bibliography"... 

```
<section role="bibliography">
   <h1>Cited Works</h1>
   <ul>
      <li role="biblioentry" id="b8cab5dd-bc24-459c-9858-7afa9da69b64">
         John Steinbeck, The Grapes of Wrath (New York: The Viking Press, 1939)
      </li>
      …
   </ul>
</body>
```

The list's required owned may be satisfied by having biblioentry subclass listitem, but then the list or the bibliography in this example is left hanging. You could try moving the role from the `<section>` to the `<ul>`, but then you may not get the landmark subclass you were hoping for.

**Comment by cookiecrook** [comment]
PS. The `</body>` typo above is from the DPUB spec.

**Comment by halindrome** [comment]
Do you have a suggestion for what the proper context role(s) should be?

On Fri, Apr 24, 2015 at 3:55 AM, James Craig <notifications@github.com>
wrote:

> PS. The </body> typo above is from the DPUB spec.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/aria/issues/47#issuecomment-95857642>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by cookiecrook** [comment]
I think it would just be a generic list in the bibliography section.

```
<section role="bibliography">
   <h1>Cited Works</h1>
   <ul>
      <li id="b8cab5dd-bc24-459c-9858-7afa9da69b64">
         John Steinbeck, The Grapes of Wrath (New York: The Viking Press, 1939)
      </li>
      …
   </ul>
</body>
```

**Comment by cookiecrook** [comment]
Some of the other examples would need to be updated, too.

**Comment by TzviyaSiegman** [comment]
Updated examples will be provided in 2nd or 3rd draft.

**Comment by TzviyaSiegman** [comment]
This has been resolved in later drafts.
