### ISSUE TITLE
@multiple

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#470]
Need an ARIA feature to correspond with HTML 5.1 @multiple https://www.w3.org/TR/html51/sec-forms.html#the-multiple-attribute

**Comment by michael-n-cooper** [comment]
HTML-AAM maps to multiselectable but that doesn't sound right

**Comment by michael-n-cooper** [comment]
http://www.w3.org/2016/11/10-aria-minutes.html

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by joanmarie** [comment]
https://github.com/w3c/aria/wiki/Plans-regarding-attribute-parity

Not planned for input; already have parity with it for select (aria-multiselectable)
