### ISSUE TITLE
HTML list attribute

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#472]
Need to explore HTML list attribute https://www.w3.org/TR/html51/sec-forms.html#the-list-attribute

Sort of maps to aria-haspopup but not quite right. HTML-AAM needs update. May need a feature correspond.

http://www.w3.org/2016/11/10-aria-minutes.html

**Comment by michael-n-cooper** [comment]
Also need to deal with datalist in this context https://www.w3.org/TR/html51/sec-forms.html#the-datalist-element

**Comment by jnurthen** [comment]
@michael-n-cooper Do we need to track this. Seems like it would be html-aam and they have datalist covered.

**Comment by jnurthen** [comment]
IMO we have this covered with aria-controls for a combo box. Closing. Please reopen if necessary
