### ISSUE TITLE
HTML optgroup element

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#473]
HTML optgroup
https://www.w3.org/TR/html51/sec-forms.html#the-optgroup-element

currently mapped to group role, but might want something better.

**Comment by jnurthen** [comment]
related old bugzilla issue - https://www.w3.org/Bugs/Public/show_bug.cgi?id=27788

**Comment by jnurthen** [comment]
closing based on https://github.com/w3c/aria/issues/719
