### ISSUE TITLE
ARIA role for HTML p

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#474]
Need role for p
https://www.w3.org/TR/html51/grouping-content.html#the-p-element

**Comment by michael-n-cooper** [comment]
In [15 December 2016 Teleconference](https://www.w3.org/2016/12/15-aria-minutes.html#item03) onsider if this needs to be a generic block role, e.g., to also address [HTML 5 address](https://www.w3.org/TR/html51/sections.html#the-address-element).

**Comment by cookiecrook** [comment]
@michael-n-cooper wrote:

> consider if this needs to be a generic

I could go either way. `<p>` has some semantic meaning over `<div>` even though most UAs and ATs don't use it. If you want to dupe to the generic issue, it's #525.

**Comment by joanmarie** [comment]
Closing as fixed. We added a `paragraph` role to ARIA master last week.

**Comment by afroguy16** [comment]
Somehow `role="paragraph"` is still not supported 🤔

**Comment by scottaohara** [comment]
@afroguy16  in what way are you anticipating support that is not met?

chromium, webkit and firefox browsers all expose a paragraph role if one were to go to the effort to do `<div role=paragraph>` rather than more simply using the `<p>` element.

**Comment by afroguy16** [comment]
> @afroguy16  in what way are you anticipating support that is not met?
> 
> chromium, webkit and firefox browsers all expose a paragraph role if one were to go to the effort to do `<div role=paragraph>` rather than more simply using the `<p>` element.

Thanks for sharing. I guess it's a vdom problem, which is a library specific issue. To be clear, I tried accessing `role=paragraph` in React Testing Library"
