### ISSUE TITLE
HTML blockquote

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#476]
Need role for HTML 5 blockquote
https://www.w3.org/TR/html51/grouping-content.html#the-blockquote-element

**Comment by michael-n-cooper** [comment]
I would think the q element from #485 should be handled together with blockquote.

**Comment by cookiecrook** [comment]
Filed a new issue #528 to address blockquote, cite, and q together.

**Comment by joanmarie** [comment]
Blockquote was added to master. Closing as fixed.
