### ISSUE TITLE
HTML definition list and definitions

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#477]
HTML 5 definition lists <dl> https://www.w3.org/TR/html51/grouping-content.html#the-dl-element, <dt> https://www.w3.org/TR/html51/grouping-content.html#the-dt-element, and <dd> https://www.w3.org/TR/html51/grouping-content.html#the-dd-element may map to ARIA term and defintion roles. But also HTML <dfn> https://www.w3.org/TR/html51/textlevel-semantics.html#the-dfn-element. We need to sort these out and determine if new ARIA roles are needed, or clarify the mappings.

**Comment by jasonkiss** [comment]
See related CORE-AAM issue #455

**Comment by scottaohara** [comment]
#951 closes this issue
