### ISSUE TITLE
Roles with required states missing from characteristics table for those states

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#48]
In http://www.w3.org/TR/wai-aria-1.1/#aria-selected, option is missing from "used in roles"; "treeitem" is missing from "inherits into roles".

In http://www.w3.org/TR/wai-aria-1.1/#aria-checked, checkbox and radio are missing from "used in roles"; menuitemcheckbox and menuitemradio are missing from "inherits into roles".

There may be others. I have a potential fix.

**Comment by Joanmarie** [comment]
The branch above solves the problem for me. Disclaimer: What I know about jquery, I pretty much learned looking into this bug while multitasking. ;)

In addition, I see that something is pulling the "checked" state in twice for role radio, which I'm betting is a spec duplication. I'll check next. In the meantime, if someone who actually is familiar with jquery and our scripts could take a look, it would be teh awesome. Thanks!

**Comment by Joanmarie** [comment]
Aha, radio currently has "checked" as a "required property" (which makes sense). But the superclass of radio is checkbox which, of course, has "checked" as a "required property" as well. I guess the aria.js method needs to filter out duplicates.

**Comment by halindrome** [comment]
It was supposed to filter out duplicates as a matter of course.  Hrm.  I will walk through it, but it might not be today.

**Comment by Joanmarie** [comment]
Well, maybe it does but my change breaks that. ;) I'll give it a bit more time today. If not, I'll defer to you to fix it.

**Comment by Joanmarie** [comment]
Found it! https://github.com/w3c/aria/commit/3af0455 Now that branch includes the roles that were missing, but only does so once.

The disclaimer above still applies. So @halindrome when you get a chance, could you please review? And if there's a better way to do it -- and it's faster for you to just do it, please do. Now that I see this bug, it's pretty bad....

Thanks!

**Comment by halindrome** [comment]
I will look at it tomorrow. I actually noticed it a few weeks back but
thought it was isolated to one role.  My bad.

**Comment by halindrome** [comment]
Your changes look good to me.  I think I will need to push the into ariaChild.js too.  Do you want to make the pull request, or do you want me to do it?

**Comment by michael-n-cooper** [comment]
Appears to be fixed, closing.
