### ISSUE TITLE
rel attribute values

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#480]
HTML a attribute has rel attribute with various values:

https://www.w3.org/TR/html51/links.html#allowed-keywords-and-their-meanings

We don't think these things are currently used by AT, so no point doing in ARIA, but it would be useful if AT did support this. Putting in ARIA 2 to revisit in a couple years.

**Comment by jnurthen** [comment]
According to https://github.com/w3c/aria/wiki/Plans-regarding-attribute-parity this is not mapped so closing
