### ISSUE TITLE
Need feature for href attribute

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#482]
Need way to expose where a link goes like href https://www.w3.org/TR/html51/links.html#element-attrdef-a-href

**Comment by MichielBijl** [comment]
So, we also need to be able to expose other link specific things like the `download` attribute?

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by jnurthen** [comment]
Seems like very low priority - moving to 1.4

**Comment by brennanyoung** [comment]
It's **definitely** a hassle adding "opens in a new window" (or similar) to the link text using aria-label, and making sure this appended text is copy edited and translated appropriately for different audiences. 

I am sure developers would not care so much if the 3rd party auditors did not complain about the missing "opens in new window" or "download" cue being a WCAG violation. Which they certainly do.

Browsers typically often offer a **visual** affordance for different link types on hover, by changing the cursor, or modifying the status line. 

Aria should offer a standard, non-visual, human-language-independent, machine-readable alternative mechanism to do the same.

**Comment by jnurthen** [comment]
@brennanyoung This doesn't sound like the same thing as this issue. (tbh this issue should be closed).

The fact that the target attribute in HTML (which is not exactly new) is not mapped in accessibility APIs - https://www.w3.org/TR/html-aam-1.0/#html-attribute-state-and-property-mappings says a lot to me about whether this is something that is required by users. 
IMO such a request should start with implementing the feature for native HTML before coming up with an equivalent ARIA feature.

**Comment by pkra** [comment]
Random note. TIL that `blockquote` has a `cite` attribute for adding a URL https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote. Whatever we eventually do with href, we might want to consider doing it for this attribute as well.

**Comment by cookiecrook** [comment]
I didn't see the related HTML-AAM issue linked, so https://github.com/w3c/html-aam/issues/434

**Comment by cookiecrook** [comment]
Mac AX API property is AXURL

**Comment by spectranaut** [comment]
"wontfix" means we aren't going to get to it unless someone comes up with a better reason to do it, and API support.

**Comment by spectranaut** [comment]
closed during issue triage in this meeting: https://www.w3.org/2024/05/30-aria-minutes.html#t08
