### ISSUE TITLE
Feature for type of link target

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#484]
Feature to indicate MIME type of linked resource like HTML 5 a type https://www.w3.org/TR/html51/textlevel-semantics.html#the-a-element

**Comment by michael-n-cooper** [comment]
Could relate to #482

**Comment by michael-n-cooper** [comment]
Could relate to #481

**Comment by hartman** [comment]
At Wikipedia we have lots of different links, including to PDFs, and screenreader users have often asked us to indicate these to them as such downloads are intrusive in their usage of the software if they follow them without realising they are opening up a PDF.

Having such information at this level, would significantly simplify supporting screenreader users with problems like these.

**Comment by spectranaut** [comment]
closed during issue triage in this meeting: https://www.w3.org/2024/05/30-aria-minutes.html#t08
