### ISSUE TITLE
[Role Parity] HTML 5.1 Ruby

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#488]
Investigate how ruby works and whether ARIA needs to provide a feature.

https://www.w3.org/TR/html51/textlevel-semantics.html#the-ruby-element
https://www.w3.org/TR/html51/textlevel-semantics.html#the-rb-element
https://www.w3.org/TR/html51/textlevel-semantics.html#the-rt-element
https://www.w3.org/TR/html51/textlevel-semantics.html#the-rtc-element
https://www.w3.org/TR/html51/textlevel-semantics.html#the-rp-element

**Comment by cookiecrook** [comment]
I would avoid role parity for `ruby` and related elements. It's unlikely any web author would be able to implement this correctly in all contexts. 

This could be duped to #529.

**Comment by jnurthen** [comment]
see #74

**Comment by jnurthen** [comment]
As detailed at https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#no-consensus-yet-will-do-for-1-3 moving to 1.3

**Comment by jnurthen** [comment]
agree with @cookiecrook - unlikely to be useful. Closing.
