### ISSUE TITLE
Section 1.3 User Agent Support references UAIG 1.0

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#489]
In [section 1.3](http://w3c.github.io/aria/aria/aria.html#ua-support), it says:

> Mainstream user agents use WAI-ARIA to alter how host language features are exposed to accessibility APIs in order to improve accessibility. The mechanism for this is defined in the WAI-ARIA User Agent Implementation Guide.

**Comment by jnurthen** [comment]
Can't find this any more - assume overcome by other changes. Closing
