### ISSUE TITLE
Replace mentions of primer with Authoring Practices

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#490]
The spec includes 4 mentions and links to the primer. They should be deleted or replaced with links to the Authoring Practices.

For example, in the 
[Introduction[(http://w3c.github.io/aria/aria/aria.html#introduction)
the primer is mentioned twice, the first time is in the paragraph after the list of objectives:

> WAI-ARIA is a technical specification that provides a framework 
> to improve the accessibility and interoperability of web content and applications. 
> This document is primarily for developers creating custom widgets and other web application components. 
> Please see the WAI-ARIA Overview  for links to related documents for other audiences, 
> such as the WAI-ARIA Primer 
> that introduces developers to the accessibility problems that WAI-ARIA is intended to solve, the fundamental concepts, and the technical approach of WAI-ARIA.

It is also mentioned in section 1.1 and section 2.

**Comment by russmaxdesign** [comment]
@mcking65 maybe actually list the four references with URLs etc so that the issue is a little more clear?

**Comment by mcking65** [comment]
They are the only uses of the word "primer" so searching the spec reveals them instantly.

**Comment by mcking65** [comment]
OK, Added an example for clarity.

**Comment by xfq** [comment]
It's also mentioned in AAM: https://w3c.github.io/aria/core-aam/core-aam.html#intro

**Comment by joanmarie** [comment]
The Core-AAM listed both the Primer and Practices, so I just removed the former from it (16eb402).
