### ISSUE TITLE
[core-aam] Rule for excluding elements with children presentational true is out of date

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#493]
Section [5.1.1 Excluding Elements from the Accessibility Tree](http://w3c.github.io/aria/core-aam/core-aam.html#exclude_elements2) 
includes the following list of roles that have children presentational true.

1. button
2. img
3. math
4. progressbar
5. separator
6. scrollbar
7. slider

This list needs to be updated to be in sync with aria 1.1.

**Comment by klown** [comment]
Thanks for the pointer, @mcking65.

I've updated the list of roles with children presentational true:
https://github.com/w3c/aria/commit/72fb105ee84cbca11a20903242881dde07f2bedd

[Rawgit version](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#exclude_elements2
).

If it looks good to you, feel free to close this issue.

**Comment by joanmarie** [comment]
> If it looks good to you, feel free to close this issue.

Since this issue has been addressed with the aforementioned commit, closing as FIXED.
