### ISSUE TITLE
Add aria-posinset and aria-setsize to definition and term roles

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#497]
http://www.w3.org/2016/12/08-aria-minutes.html

**Comment by scottaohara** [comment]
These attributes should no longer be on `term` and `definition` due to their updates in ARIA 1.2.

However, seems that these should instead be added to the `associationlist` roles

**Comment by jnurthen** [comment]
They are on `associationlistitemvalue` and `associationlistitemkey`

Closing
