### ISSUE TITLE
Handle abbr

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#498]
Need feature to correspond to HTML abbr https://www.w3.org/TR/html51/textlevel-semantics.html#the-abbr-element

**Comment by jnurthen** [comment]
Mappings in HTML-AAM seem bogus. Suggest we don't need this.

**Comment by joanmarie** [comment]
This is generic. See wiki. Closing as fixed.

**Comment by joanmarie** [comment]
HTML-AAM is the issue tracker for mapping. We got role parity via generic. Closing as fixed.
