### ISSUE TITLE
WAI-ARIA 1.1 and DPUB-ARIA 1.0 in BlueGriffon

### ISSUE THREAD

**Issue by therealglazou** [w3c/aria#505]
FWIW, I just added support for WAI-ARIA 1.1 and DPUB-ARIA 1.0 to the trunk of BlueGriffon. The next public version will include these changes.

A OS X trial version is available from http://bluegriffon.org/freshmeat/2.2pre/ , the implementation being inside the new panel Panels > ARIA.

**Comment by therealglazou** [comment]
Total implementation time: 13 hours.

**Comment by TzviyaSiegman** [comment]
@therealglazou is it possible to write a short testimonial outlining what aspects of DPUB-ARIA and ARIA Blue Griffon supports? For example, if there are any UI changes brought about by the vocabulary, it would be helpful to know about them. Thanks!
