### ISSUE TITLE
Figure out what the heck to do with the <time> element

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#507]
[HTML time element](https://www.w3.org/TR/html51/textlevel-semantics.html#the-time-element) doesn't quite map to ARIA, but may need a mapping or other action. Also see [HTML AAM on time](https://w3c.github.io/html-aam/#el-time).

From [5 January 2017 ARIA telecon](https://www.w3.org/2017/01/05-aria-minutes.html).

**Comment by jnurthen** [comment]
https://github.com/w3c/aria/issues/878
