### ISSUE TITLE
Figure out <mark> element

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#508]
[HTML 5 mark](https://www.w3.org/TR/html51/textlevel-semantics.html#the-mark-element) needs handling. Could relate to drag and drop. This could have multiple ARIA features.

**Comment by MichielBijl** [comment]
For those interested: `<mark>` has default styling in Chrome, Firefox, Safari, and Edge. It applies a yellow background to the element (regardless of text colour I might add).

**Comment by aleventhal** [comment]
https://github.com/w3c/aria/pull/1133
Examples and more context in ARIA annotations explainer.

**Comment by pkra** [comment]
Closing this as resolved via #1133. I've opened https://github.com/w3c/html-aam/issues/316 which seems like a detail that's missing. Please re-open if anything else is missing.
