### ISSUE TITLE
HTML language directionality <bdi> and <bdo>

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#509]
HTML [bdi](https://www.w3.org/TR/html51/textlevel-semantics.html#the-bdi-element) and [bdo]https://www.w3.org/TR/html51/textlevel-semantics.html#the-bdo-element) need ARIA corolaries to support web components. HTML mappings may also need care to ensure content exposed to a11y tree in right order.

[5 January 2017 ARIA telecon](http://www.w3.org/2017/01/05-aria-minutes.html).

**Comment by jnurthen** [comment]
Looks like these simply map to text with an extra attribute.
Suggest adding an aria-writingmode attribute which could potentially be used on any text container.

**Comment by jnurthen** [comment]
I'm unsure how adding this would help. HTML has `dir` available on any element, SVG has `writing-mode` which performs the equivalent. I can't see how we would want a different writing mode exposed to Accessibility APIs than the base markup language.
I also presume any other language which purports to support rtl would have an equivalent too. 
Closing this. Please reopen if needed.
