### ISSUE TITLE
ARIA 1.1 should incorporate some DPUB roles

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#51]
Some obvious choices: chapter, table of contents, subheading (from dpub-subtitle).

**Comment by cookiecrook** [comment]
glossary and toc (expanded?) should probably be landmarks.

**Comment by cookiecrook** [comment]
bibliography, too

**Comment by Joanmarie** [comment]
Footnote would be helpful. Also the tip and notice (though with some clarification as per issue #43) -- perhaps through a "comment" or "note" role. These objects show up in document editors like LibreOffice Writer and MS Word.

**Comment by cookiecrook** [comment]
We have a note role in ARIA 1.0. Is that sufficient?

**Comment by Joanmarie** [comment]
As a superclass or substitution?

**Comment by MichielBijl** [comment]
+1 to footnote

**Comment by richschwer** [comment]
The problem with cherry picking is that the DPUB community is going to have a problem remembering when something has a prefix and when they do not. This is why they also wanted to go to a doc- prefix. It is more generic and easy to remember regardless of where it is used.

**Comment by TzviyaSiegman** [comment]
@richschwer the DPUB community is already using the ARIA core vocabulary. Explicit example: we removed doc-glossterm from dpub-aria because definition exists in core. If there are benefits to shifting  footnote to core, we may want to consider. cc @mgylling @mattgarrish

**Comment by richschwer** [comment]
I understand but we did have this discussion and I recall, perhaps it was Ivan, that wanted to keep them with a single prefix. I understand that you do have ARIA roles that you are using. If this is no longer a concern by the publishing community that is fine.

**Comment by tsiegman-wiley** [comment]
Decided in meeting on 20150107 [http://www.w3.org/2016/01/07-dpub-aria-minutes.html] to leave roles in DPUB-ARIA alone for now. Issue can be revisited with ARIA 1.2 and later.

**Comment by halindrome** [comment]
Well remembered.
