### ISSUE TITLE
HTML br and wbr

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#510]
HTML 5 [br](https://www.w3.org/TR/html51/textlevel-semantics.html#the-br-element) and [wbr](https://www.w3.org/TR/html51/textlevel-semantics.html#the-wbr-element) may need ARIA features.

**Comment by cookiecrook** [comment]
These should be mapped to whatever "generic" role you use for `div` and `span` #525

**Comment by scottaohara** [comment]
Note that the wiki currently states that:
`br` will be generic
`wbr` is tentatively mapped

Weighing in, i'm not convinced that there's anything meaningful to map for `wbr`.

**Comment by joanmarie** [comment]
The wiki currently states neither are mapped. And I personally don't think they should be.
