### ISSUE TITLE
Errors in section 5.3 "Categorization of Roles" 

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#512]
There are several points where section "5.3 Categorization of Roles" conflicts with the definitions of roles in section 5.4. This is potentially confusing to readers and could lead to incorrect interpretations of the specification.

The first list of roles in section [5.3.2 Widget Roles](http://w3c.github.io/aria/aria/aria.html#widget_roles) 
erroneously includes the following roles, which are not subclasses of widget:

1. alert: is already in the list of live regions.
2. alertdialog: should be in a separate list of window roles.
3. dialog: should be in a separate list of window roles.
4. log: is already in the list of live regions.
5. marquee: is already in the list of live regions.
6. status: is already in the list of live regions.
7. timer: is already in the list of live regions.
8. tooltip: belongs in the list of structures

This same list omits the `separator` role, which ARIA 1.1 changed to be a widget when the element is focusable.

There are 3 errors in section [5.3.3 Document Structure](http://w3c.github.io/aria/aria/aria.html#document_structure_roles):

1. The list includes `region`, which is now listed in landmarks so should be removed from the structure list.
2. The `separator` line should include the text "when not focusable".
3. The list omits `tooltip`, which is a subclass of section.

**Comment by Joanmarie** [comment]
Yikes. Thanks @mcking65! Should be fixed. Please re-open if I missed anything.

**Comment by mcking65** [comment]
Looks perfect!
