### ISSUE TITLE
Accessible name calc doesn't clearly say what happens with invalid reference or empty

### ISSUE THREAD

**Issue by mraccess77** [w3c/aria#515]
> if computing a name, and the current node has a non-empty aria-labelledby attribute, and the current node is not already part of an aria-labelledby traversal, process its IDREFs in the order they occur:

First part: The term "non-empty aria-labelledby" attribute is not clear. Are you talking about an empty aria-labeleldby or aria-labelledby that points to something that is empty?

Second part: Even if it's implied that an invalid reference would then have an empty result -- it should clearly say valid aria-labelledby reference.  Some would argue that an invalid reference passes and then we'd have an empty acc name.  What should happen with an invalid reference is that the logic should proceed to the next step and get the acc name from something else if available -- it shouldn't stop.

**Comment by klown** [comment]
Proposed edit:

"if computing a name, and the current node has an aria-labelledby attribute that is non-empty and contains at least one valid IDREF, and the current node is not already part of an aria-labelledby traversal, process the IDREFs in the order they occur:
..."

**Comment by mraccess77** [comment]
@klown that is better.  But I still work about aria-labelledby is not empty -- perhaps "If computing a name, and the result calculated by the current node's aria-labelledby attribute is non-empty..."

**Comment by mraccess77** [comment]
Also the term "non-empty" is confusing.  Is " " non-empty?  For example, in the Chrome developer tools <input aria-label=" " title="test" /> has an accessible name of " ".    <input type="text" title="test" aria-label="" /> has an accessible name of "test".  Is this what was intended by the name calculation?  It's fine with me if it does -- but we need to document the intention of these edge cases and be clear.

**Comment by klown** [comment]
@mraccess77 wrote:

>  ... But I still worry about "aria-labelledby is not empty"

Technically, aria-labelledby is [specified](https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby) to take one or more IDREFs as its value.  Anything else is invalid, including the empty string.  I suggest dropping the term "non-empty" completely:

""if computing a name, and the current node has an aria-labelledby attribute that contains at least one valid IDREF, and the current node is not already part of an aria-labelledby traversal, process the IDREFs in the order they occur: ..."

**Comment by jnurthen** [comment]
This issue was moved to w3c/accname#29
