### ISSUE TITLE
Audio and video roles

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#517]
Need ARIA roles for HTML 5 [video](https://www.w3.org/TR/html51/semantics-embedded-content.html#the-video-element) and [audio](https://www.w3.org/TR/html51/semantics-embedded-content.html#the-audio-element).

**Comment by michael-n-cooper** [comment]
This could mean exposing the [track](https://www.w3.org/TR/html51/semantics-embedded-content.html#the-track-element) element as well.

**Comment by michael-n-cooper** [comment]
Discussed in [26 January 2017 ARIA telecon](http://www.w3.org/2017/01/26-aria-minutes.html).

**Comment by cookiecrook** [comment]
For ARIA 1.2, you could approach this as an abstract ~"native" role that are not available for authors to use in content.

**Comment by jongund** [comment]
An important reference on previous work:
https://www.w3.org/TR/media-accessibility-reqs/

**Comment by joanmarie** [comment]
What about the following:
* Partial parity via the `group` role (i.e. like we're achieving with the to-be-created generic role)
* Additional parity (so screen readers know the group plays media and might wish to customize their presentation) via a to-be-created ARIA attribute (like `aria-playsmedia`)

@cookiecrook: Thoughts?

**Comment by joanmarie** [comment]
I believe we're blocked until the native APIs for video and audio are something which authors and ATs can utilize so that custom players behave in exactly the fashion as native ones.

**Comment by jnurthen** [comment]
@jongund Can you please add the required information in #1001 - what specifically are we hoping to accomplish in the meeting?

**Comment by jnurthen** [comment]
@jongund Can you please update #1001 with details about why you want this on the TPAC agenda.

**Comment by brennanyoung** [comment]
"track is never exposed to the user"

Video players often have a GUI to select alternative language audio tracks, captions tracks, audio description tracks. Having a formal role would make way for some AT sugar for choosing between or enabling/disabling these.

**Comment by scottaohara** [comment]
yes, but those GUIs are not exposing the track elements themselves, but rather buttons/menuitems to select a track.  

A custom built video player would likely have the various tracks defined in the scripting that fed into the player, so the "tracks" themselves would still never be exposed to the user.

**Comment by jnurthen** [comment]
punting to 1.4 - too big for 1.3

**Comment by zbraniecki** [comment]
We have a use case where we'd like to annotate an element as "video" to allow VUI / Screen Reader to perform actions such as play/pause etc. on it.

**Comment by cookiecrook** [comment]
@zbraniecki How would you expect to receive that play/pause event?

**Comment by spectranaut** [comment]
closed during issue triage in this meeting: https://www.w3.org/2024/05/30-aria-minutes.html#t08
