### ISSUE TITLE
Document use cases for audio and video

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#518]
Need to document full use cases for audio and video. Relates to #517.

**Comment by michael-n-cooper** [comment]
Discussed in [26 January 2017 ARIA telecon](http://www.w3.org/2017/01/26-aria-minutes.html).

**Comment by jnurthen** [comment]
Audio and Video will not make 1.2

**Comment by jnurthen** [comment]
Any updates on this @johnfoliot @JaninaSajka - if this is not useful to leave open I'm going to close it.
