### ISSUE TITLE
Accname-AAM: Alt text computation should distinguish between nameFrom contents during root node calculation versus recursive calculation.

### ISSUE THREAD

**Issue by klown** [w3c/aria#523]
Moving  from tracker's [ISSUE-642](https://www.w3.org/WAI/ARIA/track/issues/642):

Alt text computation should distinguish between nameFrom contents during root node calculation versus recursive calculation. For example, it makes sense to calculate the nameFrom contents on the current element, but it doesn't necessarily make sense to concatenate all the subgroup contents recursively into the current element's computed label.

**Comment by jnurthen** [comment]
This issue was moved to w3c/accname#26
