### ISSUE TITLE
Allow aria-setsize on container elements

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#524]
ARIA allows specifying aria-colcount and aria-rowcount on elements that provide the context for elements that support aria-colindex and aria-rowindex.
So, for example, aria-colcount can be set on a grid.

In contrast, the feed, list, listbox, menu, radiogroup, tablist, and tree roles do not support aria-setsize.

This is problematic when the setsize in a large set changes; every member of the set has to be touched to change the setsize value.

Make aria-setsize consistent with aria-colcount and aria-rowcount by allowing it to be specified on container elements.

**Comment by jessebeach** [comment]
Consider a list of 500 elements in a browser. Changing an attribute on 500 nodes would block main JS thread for a significant amount of time and also thrash the render tree. On a site like Pinterest, Tumblr, Twitter, Facebook, etc it would not be unusual to amass hundreds of items in a set in the UI. We can't set a requirement for this feature that requires updating the set size on each item in the set.

**Comment by jnurthen** [comment]
+1 to allowing this

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by mcking65** [comment]
@cookiecrook, 

I don't recall reaching an agreement to limit ARIA 1.2 scope to strictly html 5.1 role parity during our TPAC discussions. 

The outcome I recall is that other minor, non-controversial changes that are ready-to-go would be considered for inclusion. This particular proposal is closer to correcting an error than adding something new. It is not the kind of issue that would slow down 1.2.

**Comment by cookiecrook** [comment]
> I don't recall reaching an agreement to limit ARIA 1.2 scope to strictly html 5.1 role parity during our TPAC discussions.

@michael-n-cooper mentioned there was some agreement to limit the scope for the benefit of focus.

> The outcome I recall is that other minor, non-controversial changes that are ready-to-go would be considered for inclusion.  This particular proposal is closer to correcting an error than adding something new. It is not the kind of issue that would slow down 1.2.

If the W3C has "famous last words," they are "This won't slow down the release." The WG leadership intended the same small scope for ARIA 1.1, but it's now going on 3 years.

**Comment by cookiecrook** [comment]
Actually, it may be closer to 4 years. I recall branching the 1.1 draft well before the 1.0 TR.

**Comment by mcking65** [comment]
I think it would not be that hard to set criteria for ready-to-ship that won't slow things down and then boot things out that don't meet those criteria.

**Comment by caseyjhol** [comment]
One workaround that I've implemented (that may not work for everybody) is to only set the `aria-setsize` attribute when that item is focused (i.e. when `aria-activedescendant` is updated). This prevents having to unnecessarily set the attribute on every element.

**Comment by jnurthen** [comment]
@mcking65 do you think you might get this done in the 1.3 timeframe?

**Comment by spectranaut** [comment]
Closed in favor of more recent issue and PR: https://github.com/w3c/aria/issues/2158
