### ISSUE TITLE
Role parity for html:code, html:var, html:samp, html:kbd

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#527]
`code` https://www.w3.org/TR/html51/textlevel-semantics.html#the-code-element
`var` https://www.w3.org/TR/html51/textlevel-semantics.html#the-var-element
`samp` https://www.w3.org/TR/html51/textlevel-semantics.html#the-samp-element
`kbd` https://www.w3.org/TR/html51/textlevel-semantics.html#the-kbd-element

**Comment by scottaohara** [comment]
as it's not referenced in this issue, [`code`](https://rawgit.com/w3c/aria/master/#code) is in the editors drat.

**Comment by joanmarie** [comment]
Generic. As per https://github.com/w3c/aria/wiki/Plans-regarding-role-parity

Closing as fixed.
