### ISSUE TITLE
Role parity for html:blockquote, html:cite, html:q

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#528]
`blockquote` https://www.w3.org/TR/html51/grouping-content.html#the-blockquote-element
`cite` https://www.w3.org/TR/html51/textlevel-semantics.html#the-cite-element
`q` https://www.w3.org/TR/html51/textlevel-semantics.html#the-q-element

**Comment by joanmarie** [comment]
Blockquote was added to master, q will be generic inline, cite will get a specific role. The latter two are on the wiki so I don't think we need to keep this issue open for tracking.
