### ISSUE TITLE
DPUB title role is not necessary for accessibility

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#53]
This semantic is already covered by by role="heading" aria-level="1" (or `<h1>` in HTML)

**Comment by cookiecrook** [comment]
subtitle is useful; i think we should adopt that as "subheading" to match the 1.0 role

**Comment by TzviyaSiegman** [comment]
Title/subtitle are not intended to be used in <hx> elements, so using heading and subheading would not be appropriate. The intent is to label component titles, such as listheads, figure titles (not the same as captions). Using <role = "heading"> in <figcaption> would trigger unwanted results, just as putting <h2> in <figcaption> would. Perhaps these proposed roles need better names? (I do like the idea of subheading in core.)

**Comment by cookiecrook** [comment]
Updated comment above to escape @TzviyaSiegman markup examples.

**Comment by cookiecrook** [comment]
We've gone back and forth on a `label` role. Perhaps that is what you want. I think it's on the table for ARIA 1.1 again.

**Comment by TzviyaSiegman** [comment]
Thank you for your feedback. This issue has been resolved by editing the document to comply with the rules for extending ARIA (https://www.w3.org/WAI/PF/wiki/ARIAExtensions).
