### ISSUE TITLE
Roles, states, and properties to support an accordion pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#530]
Even though ARIA 1.0 and 1.1 do not mention accordions, a common expectation has been that accordion patterns would be implemented using multi-selectable `tablist` elements. For instance, this expectation is mentioned by @majornista in issue #229.

The authoring practices task force has found the `tablist` approach to be problematic so has developed an [accordion pattern](http://w3c.github.io/aria-practices/#accordion) 
 based on headings containing buttons with `aria-expanded` and `aria-controls`.

Some of the problems with the `tablist` approach are:
1. It does not support heading semantics, which are very helpful in many applications of accordion.
2. The DOM sequence of accordion structure is typically header/panel/header/panel/header/panel. This prevents the headers from being grouped in a tab list where the sequence of the structure is tab/tab/tab/panel/panel/panel.

One disadvantage of the accordion pattern currently recommended in the Authoring Practices is that there is no way to indicate that all the headers and panels are part of a set and what there position in that set is. The authoring practices task force has concluded that this deficiency is outweighed by the many advantages of its recommended pattern. Nonetheless, the task force has received feedback, such as that from @MarioBatusic in w3c/aria-practices#210, suggesting there is value in finding a solution to this gap in the pattern. The practices task force agrees and believes changes are required in the ARIA specification to achieve this objective.

**Comment by carmacleod** [comment]
Agree that this is needed, and that not knowing the position and count of the headers/panels is a real problem.

Another disadvantage of the current pattern is that the very useful (optional, but really ought to be standard) feature of Up and Down Arrows moving focus between accordion headers cannot be supported by screen readers, which forces the user to tab through all of the focusable bits of any open accordion panels before they can get to the next header. Definitely sub-optimal.  :)

**Comment by stes-acc** [comment]
I second the need for a special accordion role since Assistive Technology needs to switch its interaction modes based on active role assignments and does entity recognition based on composite roles. This also includes recognition of the scope of internal sets. 
At least a container with role=application with aria-roledescription="Tabpanel Accordion" or similar may work in the meantime but the APG needs to DEFINE that.

**Comment by jnurthen** [comment]
Is this overcome? We have an accordion pattern in APG which seems to work reasonably well. 
Closing - but reopen if disagree
