### ISSUE TITLE
ARIA roles in ToC

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/aria#534]
Can we please make the aria role show up in the ToC? It's super frustrating for people trying to find them that they are not listed and easily **accessible**.

**Comment by jnurthen** [comment]
I'm happy to do this if we think it is a good idea. @joanmarie @michael-n-cooper what do you say?

**Comment by TzviyaSiegman** [comment]
Depending on how this is done, it could obviate [doc-toc](https://www.w3.org/TR/dpub-aria-1.0/#doc-toc).

**Comment by joanmarie** [comment]
Hmmmm.... 

On the one hand "super frustrating" sounds bad. :( On the other hand, for people who aren't using the sidebar popout, the current table of contents is already pretty huge, and adding every single role would make it even more huge. As someone who uses rotated monitors (table of contents is not popped out, but instead appears at the top of the page), I don't think I'd like to see the table of contents to double in size.

Thinking out loud....

We currently already have the following items in the Table of Contents:
* Categorization of Roles (which has links to the items I list below)
* Abstract Roles
* Widget Roles
* Document Structure
* Landmark Roles
* Live Region Roles
* Window Roles

And, at least in the TR version (the github.io version seems a tad broken in this regard), each of those sections has links to each role. For instance, see [Widget Roles](https://www.w3.org/TR/wai-aria-1.2/#widget_roles).

So, I'd like to find a way to make the roles easier to find without necessarily growing the table of contents significantly. @marcoscaceres do you have any ideas on a compromise solution, or do you feel it is essential that we add all rows to the TOC?

**Comment by jnurthen** [comment]
Based on @joanmarie comments - @marcoscaceres do you have any ideas to resolve this?

**Comment by marcoscaceres** [comment]
So, did a little poking around... the problem is that "rdef" are rewritten after the TOC is generated.  

Is @halindrome still working on this spec? If yes, maybe he can get it to expand those before the conformance runs and when ReSpec starts up?

**Comment by pkra** [comment]
Re-reading this, I'm not sure there ever was agreement on what to do.  Since this has been stale for years, I'll close it. @marcoscaceres feel free to re-open.

FWIW I agree with Joanie - adding every a link for every role to the TOC seems very noisy to me, especially since I feel we should then also add every state and property.
