### ISSUE TITLE
[Core AAM] AXAPI exposure of buttons with a popup is not specified

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#539]
(I've created a branch with describing the issue and seeking review from Apple. See 9b1e5ec. I've copied the commit message text here for convenience.)

In both Safari and Chrome, a button where aria-pressed is undefined and aria-haspopup is true has the following mapping:

    AXRole: AXPopUpButton
    AXSubrole: <nil>
    AXRoleDescription: 'pop up button'

This is not reflected in the Core AAM.

Note: At the present time, the new role values for aria-haspopup (e.g. `aria-haspopup="dialog"`) are not mapped as `AXPopUpButton`. It is assumed that `AXPopUpButton` is preferred over `AXButton` in those cases as well. Confirmation will be sought from Apple.

(Edited to correctly camel-case the AXRole in the paragraph beginning with "Note:")

**Comment by Joanmarie** [comment]
Assigning to @cookiecrook. Please review the _proposed_ change shown here: https://github.com/w3c/aria/commit/9b1e5ec04

(Note that it is proposed because the commit is in a branch; not in the spec itself.)

**Comment by Joanmarie** [comment]
I just filed https://bugs.webkit.org/show_bug.cgi?id=171204 for the inconsistent exposure of `button` with non-`false` value of `aria-haspopup`.

**Comment by joanmarie** [comment]
This issue was addressed via commit 280a1a7. Don't know why I failed to close it. Doing so now.
