### ISSUE TITLE
DPUB locator, glossref, biblioref, are not useful for accessibility.

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#54]
These should use the link role with a standardized rel value such as:
`<a href="#def_bagel" rel="glossary">bagel</a>`

**Comment by TzviyaSiegman** [comment]
Thank you for your feedback. This issue has been resolved by editing the document to comply with the rules for extending ARIA (https://www.w3.org/WAI/PF/wiki/ARIAExtensions).
