### ISSUE TITLE
I have to ask this question: role="logo"

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/aria#540]
I have to ask this question, why does WAI-ARIA not have a: `role="logo"` for example:

`<img role="logo" aria-label="This is the official logo of Google" src="./google-logo.png alt="google logo" width="100" height="100">`

**Comment by AmeliaBR** [comment]
Could you explain why you think a logo needs a different role than an image? What function or clarity would it add?

**Comment by ayumihamsaki** [comment]
@AmeliaBR Hi, the way I look at it is, say a blind person uses a website, how would they know if the image was a photograph or a logo etc. Also every website these days has a logo to create their brand.  I know some people may say wel you could use an ARIA-LABEL to a role="img" but not everyone is going to add the word logo. Also it would help searchers having a group for logo. Maybe someone would want to search a website for all the logo's only and not the images in the primary content etc.

I could give endless examples, just seems strange to me WAI-ARIA doesn't have a role="logo" as other API's, Schema and Semantic models all have logo as an attribute.

**Comment by mcking65** [comment]
@ayumihamsaki commented:

> Hi, the way I look at it is, say a blind person uses a website, how would they know if the image was a photograph or a logo etc.

If the fact that the image is a logo is important and relevant to understanding the page and its function, then the word logo can be used in the label.

> Also every website these days has a logo to create their brand. 
> I know some people may say wel you could use an ARIA-LABEL to a role="img" but not everyone is going to add the word logo.

Often the logo is just a link to the home page of a site. As a screen reader user, I believe the company or site name to be adequately descriptive. Adding extra words, like logo, can be distracting.

If the brand owners feel strongly that a description of there logo is helpful, then putting a description of the logo in an element referenced by aria-describedby is a good idea. Personally, I do like learning about the design of logos. But, I don't like it when the description interferes with normal use of the site.

> Also it would help searchers having a group for logo. Maybe someone would want to search a website for all the logo's only and not the images in the primary content etc.

The rationale for adding to ARIA needs to fit within its accessibility scope.

> just seems strange to me WAI-ARIA doesn't have a role="logo" as other API's, Schema and Semantic models all have logo as an attribute.

Do you have examples of accessibility APIs and semantic models that distinguish logos from other images?

As a screen reader user, I am not aware of use cases where semantic distinction of logos is important enough to justify adding another role.

**Comment by klown** [comment]
@mcking65 wrote:

> Do you have examples of accessibility APIs and semantic models that distinguish logos from other images?

FWIW, none of the accessibility APIs have a "logo" role.

**Comment by ayumihamsaki** [comment]
Microformats and schema.org use logo attribute in their api's. But klown is correct with his comment.

**Comment by klown** [comment]
Perhaps this is a case for using the new ARIA 1.1 [aria-roledescription](https://rawgit.com/w3c/aria/master/aria/aria.html#aria-roledescription) property?  Something like:
`<img aria-roledescription="logo" ... >`

It seems to fit, since the spec says to use aria-roledescription:
- as a human-readable, author-localized description for the role.
- the element must have a valid explicit or implicit WAI-ARIA role.  Here, the role="img" is implied).

**Comment by mcking65** [comment]
This would be an appropriate use of roledescription. I don't know if I would go as far as recommending it in the authoring practices. This, of course, comes with the authoring responsibility of localization.
