### ISSUE TITLE
new attribute aria-readonly for role=form

### ISSUE THREAD

**Issue by stes-acc** [w3c/aria#542]
We need an attribute on form level indicating that all members of a particular form are readonly but are potentially editable in certain scenarios.

This is a typical situation in business apps in the web. Example:

https://openui5.hana.ondemand.com/explored.html#/sample/sap.ui.layout.sample.SimpleForm354/preview

**Comment by jnurthen** [comment]
need a form project...

**Comment by jnurthen** [comment]
@stes-acc if you want this in 1.3 you need to own it and move it foreward.

**Comment by cookiecrook** [comment]
IMO, if you want this, it should be an HTML issue, not an ARIA issue... 

A read-only state inherited from a container role will never override the host language's "equivalent semantic" attribute in the host language. For example, the absence of `readonly` on `<input>` means it's explicitly not read-only. So I don't see a lot of value in adding a read-only state for containers.

**Comment by spectranaut** [comment]
Reviewed from the working group decided this is an issue for HTML, not ARIA.

**Comment by spectranaut** [comment]
closed during issue triage in this meeting: https://www.w3.org/2024/05/30-aria-minutes.html#t08
