### ISSUE TITLE
Inserting content into live region vs turning on visibility

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#546]
In Example 15 there is this code in a live region
``` 
... style="visibility:hidden"> Invalid time:  the time must be between 9:00 AM and 5:00 PM" </span>
```

Which changes to visible. I'm wondering about the accessibility support of `visibility:hidden` vs. injecting the text in with JS. About a year ago I did some testing and found changing `display:none`  to `display:block` in a live region did not work for VoiceOver on Mac and NVDA on NVDA. 
http://davidmacd.com/blog/test-aria-live-display-none.html

Perhaps that has changed, but it's worth investigating.

**Comment by jnurthen** [comment]
If you want to provide a different example please submit a PR with the change.

**Comment by JAWS-test** [comment]
Current test results with JAWS: https://github.com/FreedomScientific/VFO-standards-support/issues?utf8=%E2%9C%93&q=is%3Aissue++live+region+visibility+

**Comment by jnurthen** [comment]
@JAWS-test If you want a different example please submit a PR with the change.

**Comment by jnurthen** [comment]
@JAWS-test adding a link to a bunch of other issues doesn't really help resolve this and is just adding to the noise.

**Comment by JAWS-test** [comment]
I think the issue can be closed because the incorrect implementation in AT cannot be a reason to change the ARIA specification. A notice about the incorrect implementation could be included in APG.

**Comment by jnurthen** [comment]
@JAWS-test We can change an example if there is an example which works more consistently and is still simple enough to demonstrate the concept. If such an example exists please submit a PR for it.

**Comment by JAWS-test** [comment]
That's what I'm going to do. It seems to be about [Example 19](https://w3c.github.io/aria/#example-19). The main problem here in my opinion is not the change of visibility, but the change of `aria-live`. A live region is only output correctly if it already exists and then the content is changed. However, due to `aria-live=off` there is no live region at all.

**Comment by JAWS-test** [comment]
@jnurthen I tried to create a PR, but unfortunately I did not succeed. I created a fork and wanted to edit the index.html. But it only seems to contain placeholders for the ARIA attributes. I couldn't find a file where the attributes are defined. Can you help me or send me a link with further instructions on how to edit the specification? Alternatively, I can also send you the necessary changes and you create the PR.
Thanks a lot!

**Comment by jnurthen** [comment]
Everything is in index.html 
The examples are certainly there.

**Comment by JAWS-test** [comment]
The index.html is only displayed up to line 10088, i.e. up to `aria-autocomplete`. I use Firefox. I'll try it in Chrome

**Comment by JAWS-test** [comment]
@jnurthen I've tried various computers and browsers: The index.html is not displayed completely. Maybe you can replace the code. Below is the correct code. It doesn't work in all browser-screenreader combinations, but it at least meets the ARIA specification for live regions.

```
<!-- Initial valid state -->
<label for="startTime"> Please enter a start time for the meeting: </label>
<input id="startTime" type="text" aria-errormessage="msgID" value="" aria-invalid="false">
<span id="msgID" aria-live="assertive"><span style="visibility:hidden">Invalid time: the time must be between 9:00 AM and 5:00 PM</span></span>

<!-- User has input an invalid value -->
<label for="startTime"> Please enter a start time for the meeting: </label>
<input id="startTime" type="text" aria-errormessage="msgID" aria-invalid="true" value="11:30 PM" >
<span id="msgID" aria-live="assertive"><span style="visibility:visible">Invalid time: the time must be between 9:00 AM and 5:00 PM</span></span>
```

**Comment by jnurthen** [comment]
I take it from this you are trying to perform changes in github using a browser. 
We don't normally work that way and to be honest I'm not surprised that browsers have limits on the file size you can edit inline.

We would normally expect someone to clone their remote github repository locally using git and  work locally before pushing their changes back to their fork and then submitting a pull request against the origin repository.

**Comment by JAWS-test** [comment]
I've never worked with GitHub before and thought it only works directly in the browser. I'll see what I need to install in order not to work in the browser.
