### ISSUE TITLE
aria/aria.html#aria-live refers to "Section 5.2.1" of aria-practices, which does not exist

### ISSUE THREAD

**Issue by OwenEdwards** [w3c/aria#547]
`aria/aria.html#aria-live` refers to "Section 5.2.1" of `aria-practices`, which does not exist:

`<cite><a href="#liveprops" class="practices">Live Region Properties and How to Use Them</a></cite> ([[WAI-ARIA-PRACTICES]], Section 5.2.1)`

**Comment by joanmarie** [comment]
@mcking65: Suggestions regarding what the ARIA spec should be referencing instead? Or should the reference just be removed?
