### ISSUE TITLE
Inconsistency in rowgroup description

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#553]
Under rowgroup, the ARIA 1.1 spec says "Authors must ensure elements with role rowgroup are contained in, or owned by, an element with the role table or grid."

This would seem to indicate that a rowgroup cannot be in a treegrid.

However, in the table directly below it says "Required context role: table, grid, treegrid".

**Comment by joanmarie** [comment]
Change landed. Closing. Thanks for the report!
