### ISSUE TITLE
Should DPUB appendix role be a synonym for ARIA 1.0 "contentinfo" landmark?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#56]
DPUB appendix role is not necessary for accessibility. Use 1.0 "contentinfo" landmark.

**Comment by cookiecrook** [comment]
Or we could add "appendix" as a synonym for "contentinfo" since appendix is a better name.

**Comment by TzviyaSiegman** [comment]
Thank you for your feedback. This issue has been resolved by editing the document to comply with the rules for extending ARIA (https://www.w3.org/WAI/PF/wiki/ARIAExtensions).
