### ISSUE TITLE
Core-AAM: Need to update mappings for aria-orientation

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#560]
As stated in a [note from the ARIA 1.1 spec](https://rawgit.com/w3c/aria/master/aria/aria.html#aria-orientation):

> In ARIA 1.1, the default value for `aria-orientation` changed from `horizontal` to `undefined`. Implicit defaults are defined on some roles (e.g., `slider` defaults to horizontal; `scrollbar` defaults to vertical) but remain undefined on roles where an expected default orientation is ambiguous (e.g., `radiogroup`).

It appears we've neglected to update the Core AAM accordingly. See:
* https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaOrientationHorizontal (claims to be default)
* There is nothing at https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaOrientationUndefined (whereas there is for other `true`/`false`/`undefined` attributes such as [aria-pressed](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaPressedUndefined) and [aria-expanded](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaExpandedUndefined).

**Comment by klown** [comment]
Roles other than `slider` and `scrollbar` that have an implicit value of `aria-orientation` when `aria-orientation` is `undefined`, not mentioned in the Core-AAM:
- [listbox](https://rawgit.com/w3c/aria/master/aria/aria.html#listbox) (vertical)
- [menu](https://rawgit.com/w3c/aria/master/aria/aria.html#menu) (vertical)
- [menubar](https://rawgit.com/w3c/aria/master/aria/aria.html#menubar) (horizontal)
- [separator](https://rawgit.com/w3c/aria/master/aria/aria.html#separator) (horizontal)
- [tablist](https://rawgit.com/w3c/aria/master/aria/aria.html#tablist) (horizontal)
- [tree](https://rawgit.com/w3c/aria/master/aria/aria.html#tree) (vertical)
- [toolbar](https://rawgit.com/w3c/aria/master/aria/aria.html#toolbar) (horizontal)

**Comment by klown** [comment]
@Joanmarie, I propose that the mapping of an undefined `aria-orientation` is generally "not mapped", with specific exceptions for roles for which it has an implicit value.

**Comment by joanmarie** [comment]
Fixed in a9fcb07ed
