### ISSUE TITLE
Core-AAM: accessibilityIsAttributeSettable() is deprecated

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#561]
The Core AAM has several references to accessibilityIsAttributeSettable(). But according to the developer docs from Apple, [this method is deprecated](https://developer.apple.com/reference/objectivec/nsobject/1529207-accessibilityisattributesettable). I believe that we want to update Core AAM to [AXUIElementIsAttributeSettable()](https://developer.apple.com/reference/applicationservices/1459972-axuielementisattributesettable) instead.

**Comment by klown** [comment]
@Joanmarie, I made the modifications.  The changes are here:
https://github.com/w3c/aria/commit/387e6d291be5d77b4ab92c8e8031b7bb8d9c4eb5

Is this simply editorial, or an ARIA 1.1 feature?  I'm leaning towards editorial, but your call.

If it is editorial, however, this is done and you could close it (if it's done to your satisfaction).

**Comment by Joanmarie** [comment]
It probably needs to be marked as "ARIA 1.1." I wouldn't call it a "feature" per se. But the Core AAM has outdated information as a consequence of the owners of the API being mapped (i.e. Apple) deprecating the method we're telling people to implement. And user agents really should update their implementations if they have not already done so. Thus we want to test for that.

**Comment by klown** [comment]
@Joanmarie Done.

Core-AAM changes: https://github.com/w3c/aria/commit/d5894fd98bf98c10f8d1fc0cfad300d5888e7e85

New "needs test" section in testable statements wiki:  https://www.w3.org/wiki/ARIA_1.1_Testable_Statements#AX_API_accessibilityIsAttributeSettable.28.29_deprecated_.28NEEDS_TEST.29

**Comment by Joanmarie** [comment]
Thanks! I'm going to close this as I believe you've taken care of it all. If I'm wrong, sorry and please reopen.
