### ISSUE TITLE
Core-AAM: Update AXRoleDescription for grid role for AXAPI

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#562]
The AXRoleDescription for the grid role changed from "grid" to "table" in 2015. This [changeset](https://trac.webkit.org/changeset/188203/webkit/trunk/LayoutTests/platform/mac/accessibility/roles-exposed-expected.txt) shows evidence of the WebKit/Safari implementation.

**Comment by klown** [comment]
@Joanmarie Done:

- https://github.com/w3c/aria/commit/610970549e3c9c3194417455fdc4baf9fb5c3185
- https://github.com/w3c/aria/commit/e81674c7719fa12e86588b46efc0d266e282f23d

Close as you see fit.

**Comment by Joanmarie** [comment]
Closing. Thanks!
