### ISSUE TITLE
Core-AAM: Need to verify (and possibly correct) AXARIA{Column,Row}Index value

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#563]
AXColumnIndexRange is a (location, length) range where location is 0-based. HOWEVER, the Core AAM states that AXARIAColumnIndex returns a value that is also 0-based. My testing with Safari is not showing that; instead, I'm finding that AXARIAColumnIndex is exposing the value of aria-colindex (which given the property name does seem to make sense).

I'm in the middle of other test-related work, but filing this now so I don't forget. Assigning it to me to do the code digging in WebKit/Safari to verify that it's on purpose and (if need be) follow up with Apple.

I'm assuming that this problem also exists for aria-rowindex so for now, adding that to the issue title.

**Comment by klown** [comment]
@Joanmarie, the Core-AAM statements about zero-based `location` values for  `AXColumnIndexRange` and `AXRowIndexRange` are based on @cookiecrook's [comment](https://github.com/w3c/aria/issues/459#issuecomment-273186130) from issue #459.

The index range is documented as (my emphasis) "`location=<**column index**>` ... where location is 0-based".   The `location` _is_ a column index -- the starting index of the range. For example, an AXColumnIndexRange might specify, "it starts at column 0 (`location`) for a `length` of 3".  If AXColumnIndex is 1-based, how does one access a range starting at a `location`/index of 0?  Possible answer:  there are -1 or +1 conversions as necessary.  I guess you'll find out during your code digging.

Finally, you are correct:  analogous comments for AXRowIndexRange and AXRowIndex.

**Comment by Joanmarie** [comment]
@klown, regarding this:

> @Joanmarie, the Core-AAM statements about zero-based location values for AXColumnIndexRange and AXRowIndexRange are based on @cookiecrook's comment from issue #459.

Sure. But at the risk of stating the obvious, those are different attributes. I finally took the time to dig. Here's what I found:

* [The value of AXARIAColumnIndex comes from WebCore Accessibility's ariaColumnIndex()](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm#L2801
) and [ariaColumnIndex() returns the value of aria-colindex unmodified](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/accessibility/AccessibilityTableCell.cpp#L374).

* [The value of AXColumnIndexRange comes from WebCore Accessibility's columnIndexRange()](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm#L2786) and [columnIndexRange() gets its index from the cell's renderer](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/accessibility/AccessibilityTableCell.cpp#L327).

The row-related properties work the same way.

De-assigning myself and assigning @klown since he indicated that it's often faster to make simple changes oneself than to deal with pull requests (something I fully agree with, btw. :)). Besides, I have testable statements to modify and test files to regenerate. ;)

**Comment by klown** [comment]
@Joanmarie, I manged to get the changes done for this as well, but couldn't push them until today:
https://github.com/w3c/aria/commit/40257190725588f5dc0c05b5e0052f17e86aaf99

Rawgit urls:
- aria-colIndex: https://rawgit.com/w3c/aria/40257190725588f5dc0c05b5e0052f17e86aaf9/core-aam/core-aam.html#ariaColIndex
- aria-rowindex: https://rawgit.com/w3c/aria/40257190725588f5dc0c05b5e0052f17e86aaf9/core-aam/core-aam.html#ariaRowIndex

**Comment by Joanmarie** [comment]
LGTM. Thanks much!!
