### ISSUE TITLE
Core-AAM: Make Interface statements consistent for ATK/AT-SPI2

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#565]
For most interfaces, Core AAM does not prefix the interface name with "Atk". However, for the `term` role, it says "Interfaces: `AtkText`; `AtkHypertext`.

Also, some of the interface lines for ATK/AT-SPI2 say "Implement Interface:". But not all do (e.g. `scrollbar` and`term`).

While these are arguably nits, it would be nice to be consistent.

**Comment by klown** [comment]
@Joanmarie Done, see:
https://github.com/w3c/aria/commit/deacd4ff8e5e1deb8304a445c83068d8ddfde675

**Comment by Joanmarie** [comment]
Thanks! Closing.
