### ISSUE TITLE
typo in 7.4 Implicit WAI-ARIA Semantics

### ISSUE THREAD

**Issue by jasonkiss** [w3c/aria#566]
In section 7.4 Implicit WAI-ARIA Semantics, the word "form" in the second sentence should be "from":

> WAI-ARIA markup is only intended to be used to enhance the native semantics (e.g., indicating that the element is required with aria-required), or to change the semantics to a different purpose _**form**_ the standard functionality of the element.

**Comment by Joanmarie** [comment]
Thanks for spotting (and reporting) this! Fixed.
