### ISSUE TITLE
DPub-AAM: UIA landmark mappings not consistent with Core AAM

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#571]
If you look at the [role-mapping table in the Core AAM](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#mapping_role_table), you'll notice that all landmarks have UIA mappings in the form:

* Control Type is `$TYPE`.
* Localized Control Type is `$LOCALIZED_TYPE`.
* Landmark Type is `Custom`.
* Localized Landmark Type is `$LOCALIZED_TYPE`.

If you look at the [same table in the DPub AAM](https://rawgit.com/w3c/aria/master/dpub-aam/dpub-aam.html#mapping_role_table), you'll notice that all landmarks have UIA mappings in the form:

* Control Type is `Text`
* Localized Control Type is `$LOCALIZED_TYPE`.

Where the value of `$LOCALIZED_TYPE` is the name of the DPub ARIA role, minus the `doc-` prefix. As an example, see the mapping of [`doc-acknowledgments`](https://rawgit.com/w3c/aria/master/dpub-aam/dpub-aam.html#role-map-acknowledgments).

There are quite a few DPub ARIA roles which subclass the `landmark` role and which are mapped as landmarks by all the other platforms. Unless the lack of Landmark Type and Localized Landmark Type is a deliberate omission, we have a bunch of incorrect mappings for UIA.

@boggydigital: If the omission is indeed deliberate, please state so. If it's a mistake, please do a pull request fixing the mappings for your platform. Then we'll get @richschwer to review and commit the fixes. Thanks in advance!

**Comment by boggydigital** [comment]
Thanks for the heads up - I'm looking at this now.

**Comment by boggydigital** [comment]
https://github.com/w3c/aria/pull/576

**Comment by Joanmarie** [comment]
Closing this issue as the changes have been merged. Thanks again @boggydigital!
