### ISSUE TITLE
No CORE-AAM mapping for MSAA/IA2 of aria-pressed="mixed"

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#573]
The section for aria-pressed="mixed" seems to indicate that the mapping is no different from aria-pressed="true" in MSAA/IA2.

In both cases, CORE-AAM says:
> Set the STATE_SYSTEM_PRESSED state.
> IAccessible2: If on a button, expose the role as IA2_ROLE_TOGGLE_BUTTON.

Suggestion: use STATE_SYSTEM_MIXED as the checkbox does, and as ATK does. 
I believe this is what was intended, and this is just an oversight.

**Comment by joanmarie** [comment]
Ironically (or depressingly), ATK/AT-SPI says:

> Expose STATE_INDETERMINATE/STATE_SYSTEM_MIXED.

There is no such thing as "STATE_SYSTEM_MIXED" in ATK/AT-SPI. &lt;Insert sigh here.&gt;

**Comment by joanmarie** [comment]
@asurkov: Do you agree that in [`aria-pressed="mixed"`](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaPressedMixed) for MSAA + IAccessible2, we want to change:

> Set the STATE_SYSTEM_PRESSED state.

To: "Set the STATE_SYSTEM_MIXED state."

**Comment by asurkov** [comment]
aria-pressed='mixed' caught me by surprise :) the change itself looks reasonable

**Comment by joanmarie** [comment]
@asurkov: Thanks! Done.
