### ISSUE TITLE
Issues with role: checkbox

### ISSUE THREAD

**Issue by LukeButters** [w3c/aria#579]
Hi

I noticed that in some java script representation of roles that the `checkbox` roles seems to have an additional property. In the java script:
https://github.com/w3c/aria/blob/master/aria/script/roleInfo.js#L366
the `checkbox` role has `localprops` `aria-readonly`. Which is odd because when looking at https://www.w3.org/TR/wai-aria/roles#checkbox it does not.

I also noticed another discrepancy in the properties on checkbox between:
* [SVG](https://www.w3.org/TR/wai-aria/rdf_model.svg) this has `aria-checked` but not `aria-readonly`
* [UML](https://www.w3.org/WAI/ARIA/schemata/aria-1.uml) this neither `aria-checked` or `aria-readonly`
* [RDF](https://www.w3.org/WAI/ARIA/schemata/aria-1.rdf) this has both `aria-checked` and `aria-readonly`
I don't know if this is exactly the right place to report this but I imagine the scripts in this git repo are used to generate those files so maybe a problem exists with the scripts?

**Comment by stes-acc** [comment]
Hi,

In ARIA 1.1 it is supported:

http://w3c.github.io/aria/aria/aria.html#checkbox

Regards
