### ISSUE TITLE
ARIA 1.1 has backwards-incompatible change for listitem names

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#581]
ARIA listitem used to have nameFrom: contents, and now it doesn't. Meanwhile, implementations still do this. I'm not saying it's wrong, necessarily, but there should be some followup with browser vendors such as Mozilla. I didn't think ARIA 1.1 was supposed to have backwards-incompatible changes. Is that wrong?

This was the commit:
https://github.com/w3c/aria/commit/e8d542ce06c6a3610ccb84d2cccc9e044561fcde

**Comment by Joanmarie** [comment]
Thread: https://lists.w3.org/Archives/Public/public-pfwg/2015Sep/0003.html

**Comment by aleventhal** [comment]
Ok, Firefox still computes names for listitems. So does Chrome.

Is there a list of incompatible changes between ARIA 1.0 and ARIA 1.1?
