### ISSUE TITLE
ARIA 1.1: Determine if any features should be marked as "at-risk"

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#588]
If items are not marked as at risk, and we don't get implementation, we cannot advance past CR. But my understanding is that marking something as at risk, and then getting implementations, will not cause our advancement to be stalled. Therefore, it seems to me that if we suspect features might be at risk, we should identify them as such.

The following items strike me as being potentially at-risk, especially if we want to show more than the bare-minimum "two implementations":

**aria-keyshortcuts**
1. UIA: ?
1. IA2: Implemented in Chrome Canary; not implemented in Firefox
1. ATK: Passes in Firefox (but there's no deliberate implementation*); not yet implemented in WebKit
1. AX API: [No mappings defined](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaKeyshortcuts), not implemented in Safari, and James Craig has concerns about implementability: https://bugs.webkit.org/show_bug.cgi?id=159215

*The only mapping we could come up with for my platform, given the nature of the feature, is object attribute. And the way Gecko's code works is that if an element has a property in the form of "aria-foo='bar'", "foo:bar" is automatically added to the AtkObject attribute set.

**aria-errormessage**
1. UIA: ?
1. IA2: Implemented in Firefox and Chrome (grepped code; not tested).
1. ATK: Not implemented yet (and I have concerns: https://github.com/w3c/aria/issues/587)
1. AX API: [No mappings defined](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaErrorMessage), not implemented in Safari: https://bugs.webkit.org/show_bug.cgi?id=165190

**aria-details**
1. UIA: ?
1. IA2: Implemented in Firefox and Chrome (grepped code; not tested).
1. ATK: Not implemented yet (but I don't have concerns on this one, and will implement).
1. AX API: [No mappings defined](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaDetails), not implemented in Safari, and James expressed some reservations: https://bugs.webkit.org/show_bug.cgi?id=165842

**Comment by joanmarie** [comment]
@boggydigital: Since Edge's status with respect to the three items above is unknown, could you please let us know if you've already implemented each? For those you have not, do you intend to?

**Comment by boggydigital** [comment]
Pardon my slightly delayed reply. We have not implemented most new ARIA 1.1 attributes and don't plan to add support for the next coming release (Windows 10 Fall Creators Update). It's too early to say anything about following release at the moment - we have not started prioritization discussions yet.

Hope this clarifies the question!

**Comment by joanmarie** [comment]
Update: There are now ATK implementations for aria-details and aria-errormessage. There remains one bug in the errormessage support (related to the situation described in #587 and the testable statement's markup).

**Comment by joanmarie** [comment]
We concluded that we don't need to mark anything as at-risk during today's concall.
