### ISSUE TITLE
CORE-AAM Link Role mappings for MSAA+IAcessible2 need to update constant names

### ISSUE THREAD

**Issue by jongund** [w3c/aria#593]
ROLE_SYSTEM_LINK + STATE_LINKED
Expose STATE_LINKED on all descendants
  
I think they should be:
  
ROLE_SYSTEM_LINK + STATE_SYSTEM_LINKED
Expose STATE_SYSTEM_LINKED on all descendants

**Comment by joanmarie** [comment]
That jives with these API docs: https://msdn.microsoft.com/en-us/library/dd373609(VS.85).aspx
