### ISSUE TITLE
No MSAA role mapping for switch role

### ISSUE THREAD

**Issue by jongund** [w3c/aria#600]
Core Accessibility API Mappings 1.1
https://www.w3.org/wiki/ARIA_1.1_Testable_Statements#spinbutton_readonly_false

**Comment by joanmarie** [comment]
@jongund: Looking in the Core-AAM, I agree that there is not an MSAA role mapping for the switch role. But there are other roles for which there is not an MSAA role, like the landmarks and form. I'm not sure if the right thing to do is force something like ROLE_SYSTEM_PUSHBUTTON for MSAA because that's the closest thing, or not include a role for MSAA because a switch is not a push button.

@richschwer and/or @asurkov: Thoughts?

**Comment by asurkov** [comment]
so the issue is about switch not spinbutton as opposed to a link from the first comment, correct?
According to the spec [1], the switch is a special kind of checkbox. Shouldn't we proceed then with ROLE_SYSTEM_CHECKBUTTON?

[1] https://www.w3.org/TR/wai-aria-1.1/#switch

**Comment by stes-acc** [comment]
Shouldn't we proceed then with ROLE_SYSTEM_CHECKBUTTON?

How will AT then detect the role specialization? Switch is a control thtat changes its internal label representing a value on activation, it is not just a boolean.


-          Stefan

**Comment by joanmarie** [comment]
@stes-acc:

> How will AT then detect the role specialization? Switch is a control thtat changes its internal label representing a value on activation, it is not just a boolean.

If you look at the mapping for [switch](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-switch), there are IA2 mappings. So your question is really "How will *an AT that only relies upon MSAA* detect the role specialization?" And if such an AT still exists, maybe it looks at the DOM? My question to you would be, does such an AT -- that is still actively maintained -- still exist?

**Comment by joanmarie** [comment]
@asurkov:

> so the issue is about switch not spinbutton as opposed to a link from the first comment, correct?

Correct.

> According to the spec [1], the switch is a special kind of checkbox. Shouldn't we proceed then with ROLE_SYSTEM_CHECKBUTTON?

Done. Thanks!

**Comment by asurkov** [comment]
Do you mean how to distinguish a checkbox and switch on AT level. I believe
IA2 exposes xml-roles='switch' in this case.
