### ISSUE TITLE
Remove links to ARIA Primer

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/aria#603]
Remove links to WAI-ARIA-PRIMER both from 
* the introduction  https://www.w3.org/TR/wai-aria-1.1/#introduction
* Also from section 1.1 Rich Internet Application Accessibility https://www.w3.org/TR/wai-aria-1.1/#intro_ria_accessibility
* ALso from 2. Using WAI-ARIA https://www.w3.org/TR/wai-aria-1.1/#usage
* and from E2 Informative references https://www.w3.org/TR/wai-aria-1.1/#bib-WAI-ARIA-PRIMER

Rationale: The Primer doc has been retired, the doc is basically empty now.

**Comment by joanmarie** [comment]
Looks like a dup of issue #490. Closing as such. If my assessment is incorrect, please reopen. Thanks!
