### ISSUE TITLE
Core AAM: Ensure UIA mappings are correct for menuitemcheckbox and menuitemradio

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#615]
Looking at the mappings for [menuitemradio](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-menuitemradio), I have the following questions:

1. Is the value of `SelectionItem.IsSelected` really impacted by the value of `aria-checked`?
   * Isn't that redundant, given the value of `aria-checked` is (according to the same spec) exposed via `Toggle.ToggleState`?
   * How then does one distinguish between selected (as in `aria-selected="true"` + visually highlighted) and unselected (`aria-selected="false"` + visually not highlighted) menuitemradios?
      
      For instance, if you use the keyboard to arrow amongst a set of menuitemradios, you're changing the selection/highlight, but not the checked state. To change the checked state of the currently-selected item, you'd presumably press Space or Return.
1. Presumably similar properties and expectations for implementations apply to menuitemcheckbox, but nothing is said about that in the [spec](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-menuitemcheckbox).

@boggydigital: You are probably getting familiar with the routine, but just in case: If no changes need to be made to the spec regarding this issue, please explain in a comment. Otherwise, please create a pull request with the corrected language for your platform. Thanks in advance! :)

**Comment by joanmarie** [comment]
I just noticed the radio role also seems to couple Toggle.ToggleState and SelectionItem.IsSelected, so please also take a look at that.

**Comment by joanmarie** [comment]
@boggydigital: In order to track which issues I'm waiting on others to respond, versus those I can proceed to work on, I've created and used a "needinfo" label. When you've responded, please remove that label. Thanks!

**Comment by boggydigital** [comment]
I've tried this in Edge and this is exactly how it's implemented, after spending some time to think about this I believe this is correct model for UIA and Windows. There is a lot to unpack here, so I'll use a list to talk about specific implementation details and motivations behind this design:

1) There is actually semantic coupling between TogglePattern and SelectionPattern. Both are set to a specific value, that that is the effect, not the cause. 

The right model to understand this is that TogglePattern applies to individual elements, while SelectionPattern applies to a group. 

2) When aria-checked is set to true both should be affected.

TogglePattern.Toggle state would represent checked state from individual element perspective, while SelectionPattern.IsSelected would represent checked state from the group perspective. This is specific to radio buttons (be it role=radio or role=menuitemradio) as that's the only control that has group affiliation.

3) To your specific question: "Is the value of SelectionItem.IsSelected really impacted by the value of aria-checked? Isn't that redundant, given the value of aria-checked is (according to the same spec) exposed via Toggle.ToggleState?" 

It should be clear at this point that it's not. The example here is that when you're focused on one of the radio controls in a group, when other control is "checked" - your current selection will not have TogglePattern.Toggle state "On", while through the SelectionPattern you will be able to understand which element is current selected in a group. In this context SelectionPattern.IsSelected is just a result of SelectionPattern support, not goal by itself. Let me know if this example requires further clarification!

4) To your specific question: "How then does one distinguish between selected (as in aria-selected="true" + visually highlighted) and unselected (aria-selected="false" + visually not highlighted) menuitemradios? For instance, if you use the keyboard to arrow amongst a set of menuitemradios, you're changing the selection/highlight, but not the checked state. To change the checked state of the currently-selected item, you'd presumably press Space or Return."

I don't believe that's the Windows interaction model. At least that's not how it's implemented in Edge as far as I can tell - arrow keys change selected item immediately (both for visual state and accessibility APIs). Generally speaking there wouldn't be a problem with this model either - currently selected element would likely have focus (even if it's not "checked") which would be reflected in HasKeyboardFocus UIA property. SelectionPattern would be right solution for this either - as it corresponds to currently activated ("checked" in this case) control in a group. Let me know if this example requires further clarification!

5) To your specific question: "Presumably similar properties and expectations for implementations apply to menuitemcheckbox, but nothing is said about that in the spec."

Actually, no - the specification is correct in this case. Checkboxes (role=checkbox or role=menuitemcheckbox) are selected individually and their selection state doesn't affect other checkboxes in the group - so it wouldn't make sense to support SelectionPattern in this case. TogglePattern does make sense as it reflects only individual "checked" state.

===

All things considered I believe the specification is currently correct and doesn't require further changes for the following roles:
- checkbox
- menuitemcheckbox
- radio
- menuitemradio

Please let me know if you disagree given the rationale above, happy to revisit this!

**Comment by joanmarie** [comment]
Wow and thanks for the detailed information! I need to wake up a bit more before I read it and think about it. :smile: So I'm keeping the issue open until I do, but clearing the "bug" and "needinfo" labels.

**Comment by joanmarie** [comment]
We really should collect detailed and informative answers like this one. Thanks again, @boggydigital! I don't want to keep this open since there's nothing to fix. I've created a new "answer" label so that I can quickly relocate this (and other informative/reference content). :smile:
