### ISSUE TITLE
Core-AAM: Confirm MSAA/IA2 term role mapping

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#618]
As stated in issue #455, the term role is not a list item, but the MSAA/IA2 mappings map it as if it were. We need to confirm that this mapping is correct, or fix it if it is not.

@asurkov: Thoughts?

**Comment by asurkov** [comment]
yep, role='term', which is "A word or phrase with a corresponding definition. See related definition." [1], should not be exposed as a list item. I agree with @jasonkiss that dfn element is a better match for it.


[1] https://www.w3.org/TR/wai-aria-1.1/#term

**Comment by joanmarie** [comment]
> yep, role='term', which is "A word or phrase with a corresponding definition. See related definition." [1], should not be exposed as a list item. I agree with @jasonkiss that dfn element is a better match for it.

So looking at the [current mapping for term](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-term), under MSAA + IA2, it says:

    * ROLE_SYSTEM_LISTITEM
    * STATE_SYSTEM_READONLY

1. If we agree that ROLE_SYSTEM_LISTITEM is incorrect, we should remove that. What do we replace it with? Exposing the role via xml-roles seems appropriate. Is there any other mapping, like an MSAA and/or an IA2 role?
1. I assume the reason STATE_SYSTEM_READONLY is there is because of the ROLE_SYSTEM_LISTITEM which, in MSAA, is a role which needs an explicit STATE_SYSTEM_READONLY. So we should remove STATE_SYSTEM_READONLY as well, correct?

**Comment by asurkov** [comment]
yep for 1 and 2. I would say to go with IA2_ROLE_TEXT_FRAME for IA2/MSAA

**Comment by joanmarie** [comment]
Thanks @asurkov! Change made.
