### ISSUE TITLE
Section 5.3.2 Widget Roles Inconsistence

### ISSUE THREAD

**Issue by JavierJF** [w3c/aria#621]
The section present a list of 'standalone user interface widgets' but it includes into it the elements:

- **[alert](https://www.w3.org/TR/wai-aria-1.1/#alert)**
- **[alertdialog](https://www.w3.org/TR/wai-aria-1.1/#alertdialog)**
- **[dialog](https://www.w3.org/TR/wai-aria-1.1/#dialog)**
- **[log](https://www.w3.org/TR/wai-aria-1.1/#log)**
- **[marquee](https://www.w3.org/TR/wai-aria-1.1/#marquee)**
- **[tabpanel](https://www.w3.org/TR/wai-aria-1.1/#tabpanel)**
- **[timer](https://www.w3.org/TR/wai-aria-1.1/#timer)**
- **[tooltip](https://www.w3.org/TR/wai-aria-1.1/#timer)**

While none of them has widget as a "Superclass Role". This can be checked in any of the provided links or in the [hierarchical sheet](https://www.w3.org/TR/wai-aria-1.1/img/rdf_model.svg).

**Comment by mcking65** [comment]
We redid section 5.3 for ARIA 1.1. See:

http://w3c.github.io/aria/aria/aria.html#roles_categorization
