### ISSUE TITLE
Confusing Sentence for `aria-multiline`

### ISSUE THREAD

**Issue by cycomachead** [w3c/aria#631]
The ["NOTE" for `aria-multiline`][spec] contains the following sentence:

> The WAI-ARIA aria-multiline attribute, so authors are advised to be aware of this distinction when designing the field.

It seems like a few words were eaten by some gremlins. I'm assuming this is trying do say "The WAI-ARIA aria-multiline attribute does not change the behavior of input elements, ..." or something similar.

[spec]: http://w3c.github.io/aria/aria/aria.html#aria-multiline

**Comment by joanmarie** [comment]
Thanks for the report. Fixed in master and will do a new snapshot once rawgit wakes up.

**Comment by joanmarie** [comment]
Rawgit woke up. Snapshot generated. https://w3c.github.io/aria/aria/aria.html#aria-multiline

If I missed something, please reopen and comment. And thanks again for the report!

**Comment by cycomachead** [comment]
Thanks! :)
