### ISSUE TITLE
Core-AAM: Remove ARIA 1.1 notes from macOS mapping column

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#645]
The mapping table has a few non-normative notes about “ARIA 1.1” specific to the macOS mappings. I believe all of these are irrelevant or misleading. For example: The macOS mapping for “grid” did not change. The user presented string “table” is not related to the ARIA 1.1 role token “table” so this “[ARIA 1.1]” note should be removed.

Likewise, the platform specific AXSubrole “AXApplicationGroup” and the updated user string for “status” have no relation to ARIA 1.1, so these “[ARIA 1.1]” notes should be removed.

role | macOS mapping
-- | --
grid | AXRole: AXTable<br>AXSubrole: &lt;nil&gt;<br>AXRoleDescription: 'table' _**[ARIA 1.1]**_<br>AXColumnHeaderUIElements: a list of pointers to the columnheader elements<br>AXHeader: a pointer to the row or group containing those columnheader elements<br>AXRowHeaderUIElements: a list of pointers to the rowheader elements
group | AXRole: AXGroup<br>AXSubrole: AXApplicationGroup _**[ARIA 1.1]**_<br>AXRoleDescription: 'group'
status | AXRole: AXGroup<br>AXSubrole: AXApplicationStatus<br>AXRoleDescription: 'application status' _**[ARIA 1.1]**_

**Comment by joanmarie** [comment]
Those notes are flags for mappings which changed during the "1.1" cycle. They are for our purposes and will be removed before REC.

Again, I fully understand and appreciate the "living standard" approach to mapping specs. But because the Core AAM is currently existing under W3C's non-living, versioned system.... <insert shrug here>

**Comment by joanmarie** [comment]
Notations gone. Closing as FIXED.
