### ISSUE TITLE
Using pos-inset and aria-setsize with a toolbar

### ISSUE THREAD

**Issue by RegexEmpire** [w3c/aria#649]
Hey w3c,

We have a toolbar implementation that has the following structure:
```

<ul role="toolbar>
  <li role="button" aria-posinset="1" aria-setsize="7" />
  ...
</ul>
```

https://www.w3.org/TR/wai-aria/states_and_properties#aria-posinset
This above link includes:

Characteristics of aria-posinset
Used in Roles:	
listitem
option
Inherits into Roles:	
menuitemradio
radio
treeitem

Does posinset make sense in our usage above?

Thanks,
Taylor

**Comment by jnurthen** [comment]
I don't believe it makes sense as I don't think any AT exposes information about the number of buttons in a toolbar. If you find an example of AT which exposes this then we could reconsider allowing it.
