### ISSUE TITLE
ARIA: how to handle large numbers

### ISSUE THREAD

**Issue by adamliptrot-oc** [w3c/aria#650]
Screen readers such as Voiceover seem to handle numbers (such as 1001) one of two ways - either reading each digit out individually (one, zero, zero, one) or reading the whole number out (one thousand one). This is normally set by the user and the setting applies to all numbers.

This global nature can cause issues.
If a user has set the global toggle to 'whole numbers' this becomes an issue when reading a bank account number.
If set to reading out single digits it becomes less useful when taking about currency amounts.

I'd like to see the ability for content authors to adjust this on a per-case basis, for example by adding an attribute to an element wrapped around the number.
Allowing content authors to set a verbosity level on content would allow the global setting to be opted out of (if the user allows it) where it would enhance understanding of the copy.

**Comment by AmeliaBR** [comment]
The [CSS Speech `speak-as`](https://www.w3.org/TR/css3-speech/#speak-as) property is supposed to cover this. It's not universally supported, but I think (?) it is at least recognized in a few browser/screen-reader combos, which is much better than the rest of the CSS Speech module.

**Comment by adamliptrot-oc** [comment]
Thanks - I tested `speak-as` and unfortunately it looks like it is not supported in Voiceover/Safari or NVDA/Firefox at the moment. Will close this issue as that definitely looks to be the best place for this feature to sit.
