### ISSUE TITLE
Datepicker requirements no longer available due to 1.0 page redirection

### ISSUE THREAD

**Issue by gilesedinburgh** [w3c/aria#655]
I am not exactly sure if the issue is that 1.0 w3 pages are now redirecting to the working draft of 1.1 or that the 1.1 working draft is missing content from 1.0

Currently, the aria 1.0 page redirects users to the latest 1.1 working draft version.
However, 1.1 is missing some key pieces, such as the date picker requirements.

Page reference:
https://www.w3.org/TR/2009/WD-wai-aria-practices-20090224/#datepicker

Therefore, it appears there are no longer standard requirements for those datepicker controls.  However, this is a pretty popular control with assistive technology expectations on keyboard navigation.

**Comment by joanmarie** [comment]
Since this is an aria-practices issue, could you please file it in their issue tracker: https://github.com/w3c/aria-practices/issues? Sorry for any inconvenience.

**Comment by gilesedinburgh** [comment]
Thanks! for anyone following- logged https://github.com/w3c/aria-practices/issues/516
