### ISSUE TITLE
[PR-dpub-aria-1.0-20171102] example 34 typo

### ISSUE THREAD

**Issue by notabene** [w3c/aria#657]
Hi,

In example 34,

```   <h2>Pages</h2<```

should read

```   <h2>Pages</h2>```

**Comment by joanmarie** [comment]
Please note that dpub-aria is not longer part of this repo; just the ARIA spec lives here now. If this issue is still present, please file it in https://github.com/w3c/dpub-aria.

Thanks in advance and sorry for any confusion!
