### ISSUE TITLE
Propose new attribute for SSML to provide pronunciation or presentational hinting to AT

### ISSUE THREAD

**Issue by alia11y** [w3c/aria#659]
Currently, there is no standards-based mechanism for incorporating SSML into HTML to provide pronunciation or presentational hinting to assistive technologies which render text using text to speech synthesis (such as screen readers and read aloud tools). Across assessment vendors, a variety of approaches have been used to solve this problem, ranging from misuse of the WAI-ARIA standard, to creation of custom and data-attributes. Some of these approaches are problematic for braille users when hinted text intended for TTS is also rendered on the refreshable braille display.  We propose for your consideration a new ARIA attribute tentatively 'ARIA-SSML' that utilizes JSON to encapsulate SSML functions, attributes, and values in manner that allows for easy consumption by Assistive Technologies.

Further details are available at : https://github.com/mhakkinen/SSMLinHTMLproposal

Thanks,

**Comment by joanmarie** [comment]
At a recent-ish APA meeting, ETS presented the use cases. It appears this work will be done in APA rather than ARIA.

**Comment by alia11y** [comment]
Should I close this ticket here and open another one in APA?

**Comment by joanmarie** [comment]
yes please

**Comment by michael-n-cooper** [comment]
Issue in APA: https://github.com/w3c/apa/issues/8
