### ISSUE TITLE
Graphics AAM: Verify UIA mappings

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#663]
The UIA Mappings in Graphics AAM each state: "Expose as text string '$ROLE' in AriaRole"

That's sort of exposure is not in the Core AAM, nor in the DPub AAM, nor in the SVG AAM (though admittedly SVG AAM almost entirely points to other mapping specs). So I'm wondering why it is present in the Graphics AAM.

@boggydigital: Insight please. And I'm guessing if those mappings are incorrect, @AmeliaBR might appareciate a pull request. Please and thank you. :smile:

**Comment by boggydigital** [comment]
https://github.com/w3c/aria/pull/664

**Comment by joanmarie** [comment]
Pull request #664 was manually merged. Closing this as fixed.
