### ISSUE TITLE
REFID and Shadow DOM

### ISSUE THREAD

**Issue by sspi** [w3c/aria#668]
The new modular approach of Web Components and Shadow DOM (https://developers.google.com/web/fundamentals/web-components/shadowdom) makes the id / refid principle impractical.
For example, `document.getElementById('myId')` return null if the element is in a shadow tree.

We are developing a new framework based on Shadow DOM. Each widget and structural section of the page is in its own subtree to respect CSS isolation and eliminate conflicts.

To solve this problem, do you plan to allow js fields as aria properties and states (in addition to DOM attributes)?
Examples : 
```
myElement.getAttribute('aria-labelledby') // -> REFID string (old approach)
myElement['aria-labelledby'] // -> Element (new approach)
myElement['aria-owns'] // -> Array of Elements instead of REFIDS string
```

**Comment by mcking65** [comment]
That is one of the goals of the accessibility object model.

That project is in incubation. It is partially implemented behind a flag in Chrome. The team is actively seeking input from potential users.

See:
https://github.com/WICG/aom

In particular, look at the explainer and the demo slide deck, both of which are linked in the readme.

**Comment by sspi** [comment]
Awesome project, it's perfect, thanks!
