### ISSUE TITLE
RDF model still useful?

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#672]
The RDF model for ARIA creates confusion and it is unclear if it adds value. We should explore whether to deprioritize inline references or remove it altogether.

**Comment by LJWatson** [comment]
I'd suggest removing it. It's never been particularly helpful IMO.

**Comment by marcoscaceres** [comment]
I'm happy to help with this. Please let me know how I can be of assistance.

**Comment by iherman** [comment]
I am 👍 removing this. I do not think it achieves what it was set up to achieve (as far as I can understand the goals). I also do not think the schema has been looked at and/or updated recently (nobody should publish an RDF ontology in RDF/XML these days...)

**Comment by marcoscaceres** [comment]
the xforms stuff can probably go too... plus a bunch of dtd related things, by the looks of it.

**Comment by jnurthen** [comment]
Is this still relevant? If so @marcoscaceres we'd gladly accept help to do whatever needs to happen

**Comment by marcoscaceres** [comment]
This is still extremely relevant, but it's a big task. It needs someone who knows the spec well to go through and remove mentions of RDF and decouple the whole spec from it.
