### ISSUE TITLE
Previous recommendation link https://www.w3.org/TR/wai-aria-1.0/ broken

### ISSUE THREAD

**Issue by slauriat** [w3c/aria#687]
At the top of https://www.w3.org/TR/wai-aria-1.1/ the Previous Recommendation link of https://www.w3.org/TR/wai-aria-1.0/ brings up an error page.

**Comment by michael-n-cooper** [comment]
This URI (and others) were supposed to be set up when WAI-ARIA 1.1 and companion publications were published as Recommendations, but I didn't verify that this was done. I've sent a chaser message to the webmaster requesting this be completed.

**Comment by michael-n-cooper** [comment]
The webmaster tells me this is fixed now.
