### ISSUE TITLE
DPUB-ARIA: doc-abstract's description has 'principle' where it should be 'principal'

### ISSUE THREAD

**Issue by quasicomputational** [w3c/aria#692]
This occurs twice, but that might be springing from a single occurrence in the source. There's a cromulent use of 'principle' elsewhere that should be left unchanged.

**Comment by mattgarrish** [comment]
Thanks, fixing will embiggen the specification.

**Comment by joanmarie** [comment]
Please note that dpub-aria is not longer part of this repo; just the ARIA spec lives here now. If this issue is still present, please file it in https://github.com/w3c/dpub-aria.

Thanks in advance and sorry for any confusion!
