### ISSUE TITLE
[ROLE PARITY] Verify we do NOT need new roles for these "not mapped" elements

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#693]
The following elements lack an ARIA role, but their mapping in the HTML AAM for all platforms is "not mapped."

Assumption: If no platform has a need for them to be mapped, we presumably do not need a role for them. Confirmation needed.

* `base`
* `br` (has [issue](https://github.com/w3c/html-aam/issues/118))
* `col`
* `data`
* `head`
* `html`
* `input` (`type=hidden`)
* `link`
* `map` (when used as an imagemap)
* `meta`
* `noscript`
* `param`
* `picture`
* `script`
* `source`
* `style`
* `template`
* `title`
* `track`

If you agree with the above, please explicitly indicate so (e.g. with a +1/thumbs-up "reaction"). If you disagree, please comment with the element(s) for which you feel a role is needed. Thanks!

**Comment by cookiecrook** [comment]
Most of these are not rendered by default due to display:none being in the user agent style sheet. If a user overrides the display (for example: "style { display: block; }") , these will become rendered and then examples as generics.

**Comment by cookiecrook** [comment]
So… Mapping table could probably map these to the `none` role... Parity achieved.

**Comment by cookiecrook** [comment]
I think `picture` is the only oddball in that list. It should definitely be mapped.

**Comment by domenic** [comment]
`picture` is just a container for `img` though, so probably doesn't need its own mapping?

I agree in general there's no role needed.

**Comment by cookiecrook** [comment]
@domenic wrote:

> `picture` is just a container for `img` though, so probably doesn't need its own mapping?

Since `picture` can contain a set of related images, ASCII, or other contents, it's not generic or hidden like the rest. I think `picture` deserves its own mapping, even if it just maps to the same thing as `img`

**Comment by domenic** [comment]
How would that work in practice? You'd have an accessibility tree which contains an image-role node that has as its child another image-role node?

In general picture is meant to be a helper to let the browser select a single one of its child img nodes, depending on which media queries match. Only one of those images would be displayed.

Are you perhaps thinking of figure? picture certainly cannot contain ASCII or other contents besides img elements.

**Comment by LJWatson** [comment]
Given that the ```<picture>``` element is intended to contain multiple ```<source>``` elements, but only one ```<img>``` element, and it's the ```<img>``` that's actually rendered, it doesn't appear that ```<picture>``` needs a role.

**Comment by cookiecrook** [comment]
Retracting my previous comment... I was momentarily thinking of alternate uses of the ARIA `img` role rather than the `picture` element, which can also contain image elements.

**Comment by joanmarie** [comment]
Based on the above comments, closing this issue with no further action being required. If I'm wrong please let me know. Thanks!
