### ISSUE TITLE
[ROLE PARITY] Determine which of these mapped elements require a specific role, versus a generic role

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#697]
_N.B. All of the "Role Parity" issues are intended to gather feedback from stakeholders who need role parity from us including, but not limited to, groups working on Web Components and AOM. Comments on matters other than determining "which of these mapped elements require a specific role, versus a generic role" should be raised in another GitHub issue. Thank you for your understanding!_

The following elements lack a corresponding ARIA role in the HTML AAM, but they are mapped on ALL platforms.

Assumption: Since all platforms map them, all platforms have a need for them. Thus they require a new role. But we need to determine which of these require a dedicated/specific role versus a generic role.

* `a` (no href) (generic - role `inline`)
* `abbr` (generic - role `inline` - with TBD attribute)
* `address` (specific)
* `audio` (specific)
* `blockquote` (specific: #718)
* `canvas` (needs more discussion)
* `caption` (specific: #718)
* `details` (needs more discussion)
* `div` (generic - role `block`)
* `dl` (specific)
* `embed` (needs more discussion)
* `fieldset` (specific)
* `figcaption` (specific #718)
* `footer` not scoped to `body` element (generic: #718)
* `form` without accessible name (generic - role `block`)
* `header` not scoped to `body` element) (generic: #718)
* `iframe` (specific)
* `input` (`type=color`) (more discussion)
* `input` (`type=date`) (more discussion)
* `input` (`type=datetime`-local) (more discussion)
* `input` (`type=file`) (more discussion)
* `input` (`type=month`) (more discussion)
* `input` (`type=password`) (more discussion)
* `input` (`type=time`) (more discussion)
* `input` (`type=week`) (more discussion)
* `label` (specific)
* `legend` (specific, `caption` will be expanded when `fieldset` is added to ARIA)
* `mark` (generic `inline` with TBD attribute)
* `meter` (specific)
* `object` (needs more discussion, see `embed` above)
* `p` (specific: #718)
* `pre` (generic `block` with TBD attribute)
* `q` (generic `inline`  with possible TBD attribute)
* `ruby` (more discussion, check with i18n)
* `section` (without accessible name) (generic `block`)
* `summary` (needs more discussion)
* `time` (specific)
* `video` (specific)

**Comment by cookiecrook** [comment]
IMO `audio` and `video` should be reserved `native-audio`/`native-video` as in Issue #529.

**Comment by domenic** [comment]
> But we need to determine which of these require a dedicated/specific role versus a generic role.

As with https://github.com/w3c/aria/issues/696#issuecomment-363497911, for web components what matters is achieving the ability to create the same experience for AT users using web components as when using native elements. So, specific vs. generic depends largely on how existing ATs treat each of these cases; do they announce them specifically, or generically. I am hopeful those with domain expertise can help elucidate that subject.

**Comment by joanmarie** [comment]
This is a meta issue. The 1.3 TODO's can be found on https://github.com/w3c/aria/wiki/Plans-regarding-role-parity
