### ISSUE TITLE
Latest rec link in 1.2 editor's draft points to 1.0

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#701]
In the editor’s draft for 1.2:
http://w3c.github.io/aria/
The latest rec link points to 1.0 instead of 1.1:
https://www.w3.org/TR/2014/REC-wai-aria-20140320/

**Comment by joanmarie** [comment]
Closing as fixed. Thanks for the report!

**Comment by joanmarie** [comment]
The two commits are for master and stable. (We had branched prior to officially becoming Rec.)
