### ISSUE TITLE
Clarify aria-hidden wording

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#705]
The [spec for aria-hidden](http://w3c.github.io/aria/#aria-hidden) should be _very_ clear about what `aria-hidden="false"` means. There are some good, clear, words in the [section on excluding elements from the accessibility tree in the Core AAM spec](https://w3c.github.io/core-aam/#exclude_elements2):

> ... user agents SHOULD NOT include the following elements in the accessibility tree:
> - Elements, including their descendants, that have a WAI-ARIA global attribute of aria-hidden="true". **In other words, aria-hidden="true" on a parent overrides aria-hidden="false" on descendants.**

We should include that final sentence right in the ARIA spec for aria-hidden so that  authors (who are unlikely to read the Core AAM) know what to expect. The ARIA spec currently says this:

> An element is considered hidden if it, or any of its ancestors are not rendered or have their aria-hidden attribute value set to true.

... which doesn't explicitly call out the fuzzy case of what happens to an element that has `aria-hidden="false"`. We need to make it explicit that `aria-hidden="false"` **does _not_ put an element "back into" the accessibility tree** if it has an ancestor with `aria-hidden="true"`.

Also, we should clarify to authors that they SHOULD NOT (or maybe even MUST NOT?) put `aria-hidden="true"` on rendered interactive elements, because doing so causes a broken state in AT where the user can interact with the element but it has no identity because it is not in the accessibility tree.

If we can clarify these 2 points in the aria-hidden spec, then hopefully the Firefox devs will not be afraid to implement aria-hidden correctly.

**Comment by eps1lon** [comment]
This is especially important for developers (such as myself) that assume it works similar to `visibility: hidden;`. In  CSS-land `visbility: visible;` can make an element visible again if a parent is `visibility: hidden;`.

Though I understood my mistake by reading the current text: 

> An element is considered hidden if it, or any of its ancestors are not rendered or have their aria-hidden attribute value set to true.

But I can see how this is still considered too fuzzy.

Also want to note that https://w3c.github.io/core-aam/#exclude_elements2 seems to no longer link to a valid section

**Comment by jnurthen** [comment]
http://w3c.github.io/aria/index.html#tree_exclusion is now in the ARIA spec.... Clear enough?
