### ISSUE TITLE
Is the use of the word "node" correct in aria-atomic

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#709]
https://www.w3.org/TR/wai-aria-1.1/#aria-atomic 

> False: Assistive technologies will present only the changed node or nodes.

Sometimes the entire node changes but most of the text is the same. For instance a calendar widget refreshes the date at the top of the page

```<h2 aria-live="Wed 04/04/2018">Wednesday 04/04/2018</h2>```

The user hits next and the node refreshes to:
```<h2 aria-live="Wed 04/04/2018" >Thursday 05/04/2018</h2>```

Screen readers only read Thursday 05 because that is all that changed.

Screen readers are not announcing the entire node but only the changed text content.

Suggest amending the table to say.
> False: Assistive technologies will present only the changed text content in the node or nodes.

**Comment by jnurthen** [comment]
@DavidMacDonald I don't understand your example. I'm also not sure my results correlate with yours. What screen readers did you test this with?

**Comment by JAWS-test** [comment]
Test results with JAWS 2019: https://github.com/FreedomScientific/VFO-standards-support/issues/290 and https://github.com/FreedomScientific/VFO-standards-support/issues/298

**Comment by jnurthen** [comment]
@DavidMacDonald I don't think your premise is correct.

Testing the following 
```
<h2 id="a" aria-live="true" aria-atomic="false">Wednesday 04/04/2018</h2>
<button onclick="a.innerHTML = 'Thursday 05/04/2018'">click me</button> 
```
Clicking the button will read 'Thursday 05/04/2018' as expected
