### ISSUE TITLE
aria-valuemin, aria-valuenow and aria-valuemax listed as required properties for scrollbar but they have default values

### ISSUE THREAD

**Issue by kbae00** [w3c/aria#710]
Is this a possible contradiction in the spec for scrollbar? The spec says "Authors MUST set the aria-valuemin, aria-valuemax, and aria-valuenow attributes" but then goes on to say that they have default values if not set explicitly. The 3 properties are also listed under "Required States and Properties". But if they have default values, why are they listed as required and why does the spec say the author must set them?

**Comment by jnurthen** [comment]
These issues are all resolved in the latest editors draft. Thanks for pointing them out.
