### ISSUE TITLE
Why is toolbar as a document structure role?

### ISSUE THREAD

**Issue by Jinjiang** [w3c/aria#713]
As [5.3.3 Document Structure](https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#document_structure_roles) mentioned: "Document structures are not usually interactive." But from my understanding, a `toolbar` is interactive like `menubar`, and it "commonly used function buttons or controls".
Or is there any code sample to explain it more?
Thanks.

**Comment by jnurthen** [comment]
It is mostly not a widget due to the following
https://lists.w3.org/Archives/Member/w3c-wai-pf/2012OctDec/0246.html

I think this stems from implementation differences on different platforms

**Comment by pkra** [comment]
@jnurthen FYI the link you included is not public.

**Comment by mcking65** [comment]
There are many widgets with native implementation variations. Even within operating systems there are variations.

In practice, toolbar is frequently implemented as a composite widget. Personally, I think the role would have more value if it were specified to be a composite.
