### ISSUE TITLE
concatenate non identical sources for ACCNAME and AccDescription Computation 

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#715]
Here's a thread

## Bryan says:
I'd like to verify the expectation for the following testable statement.

```<input type="text" aria-label="LabelText" title="TitleText" id="test" aria-describedby="descid"><div id="descid">DescriptionText</div>```
Current results:
```accName: "LabelText"````
``accDesc: "DescriptionText"```
The title is lost. Is this the expected result?

## Stephan says
I understood this as override accepted by the group ever since the very beginning. 
Not clear where exactly this is handled in the accessible description computation requirements.
Personally, I feel unhappy with this override.

## David Says
It is the expected result because the title is a swing attribute that fills an empty accname or accdesciption
My preference would be that if it is different then it is a concatenation with the accdescrption...
There a lot if override errors in the wild

## Bryan says
 I understand, and have always thought the invisible loss of accessible information was strange.
Should this be raised as an issue to be added to the naming computation, or should this be ignored as something everybody knows and just deals with?
>“The trick is redundancy... can the user agents recognize identical strings of information and not pass that through”

If this is dealt with in the spec, I’m sure this can be done, since it is already happening in some browsers when the description and name properties match, so description is suppressed so that only name is set. Technically this is possible, it just needs to be dealt with in the algorithm.

## David Says: 
I filed a [bug against Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=829352&can=2&q=os%3Dchrome) to have them show the ```title``` attribute on tab keyboard focus... 
With respect to the original question there is also the same issue with aria-errormessage and aria-describedby I expect.
The fact is in the real world the title attribute is used a lot... and if browsers can suppress a redundant title (or aria-describedby etc.) and let additional content pass through, this would be desirable... 

# The suggestion

Change the computation to let **non redundant** sources pass through the accessibility tree and be concatenated to the AccName or AccDescription as appropriate.

- if an html label and an aria-labelledby are used, they will be concatenated in the accname if they are not identical.
- If an aria-error-message and aria-describedby are on a field they will both be concatenated in the accdescription
- if a title attribute offers more information and there is already an accdescription then it will be concatenated if it is not identical.

**Comment by joanmarie** [comment]
@DavidMacDonald. Wrong repo. Accname issues belong in the "accname" repo. Mind copying and pasting your issue there? (I've not yet found a way to transfer issues, preserving the original author, subscribers, etc.) Thanks and sorry!
