### ISSUE TITLE
Confusing sentence in presentation role discussion

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#717]
In the [section on ARIA "presentation" role](http://w3c.github.io/aria/#presentation), I find the following sentence confusing:
> Likewise, although an HTML table element does not have an implicit native semantic role corresponding directly to a WAI-ARIA role

Isn't "[table](http://w3c.github.io/aria/#table)" the implicit native semantic role for an HTML table element?

**Comment by carmacleod** [comment]
Another confusing sentence in the [same section, but a little further along](http://w3c.github.io/aria/#conflict_resolution_presentation_none):
> Host languages elements, having implicit presentational roles for which no roles, may be applied, MUST never be exposed to in the accessibility tree.

**Comment by jnurthen** [comment]
This looks to have been fixed in master
