### ISSUE TITLE
Clean up instances of "space-delimited", "space delimited", and "space-separated."

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#728]
From [Bug 26037](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26037)

From [ACTION-1037](https://www.w3.org/WAI/PF/Group/track/actions/1037)

**Comment by jnurthen** [comment]
HTML uses Space-separated - https://html.spec.whatwg.org/#space-separated-tokens
We should do the same
