### ISSUE TITLE
aria-hidden content misleading

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#731]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28677

> The current spec lists a bunch of things related to aria-hidden that is distracting and misleading.
> 
> The important part of the spec is the following text
> 
> "authors may, with caution, use aria-hidden to hide visibly rendered content from assistive technologies only if the act of hiding this content is intended to improve the experience for users of assistive technologies by removing redundant or extraneous content. Authors using aria-hidden to hide visible content from screen readers must ensure that identical or equivalent meaning and functionality is exposed to assistive technologies"
> 
> All the other text related to how one might map this to CSS should be moved out of the normative portion and placed into an understanding section.

**Comment by jnurthen** [comment]
@dylanb is this still an issue... I believe most of the information which was problematic has been moved to notes.

**Comment by dylanb** [comment]
not an issue anymore
