### ISSUE TITLE
Expand value types for aria-invalid

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#751]
From https://www.w3.org/WAI/ARIA/track/issues/103

The set of values for aria-invalid should expand to give hints about the condition making the value invalid.

maxlength : the input has exceeded the maximum length
out-of-range : the valuenow is greater than the valuemax or less than the valuemin

**Comment by DavidMacDonald** [comment]
see also #1000

**Comment by jnurthen** [comment]
aria-errormessage makes this unnecessary.
