### ISSUE TITLE
Add role="image" as synonym for role="img"

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#758]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28934

> With the exception of "combobox" and "contentinfo", all existing ARIA roles are complete words or concatenations of complete words. In almost all cases, the role's name is the same as the complete word or term by which the element is conventionally referred to, e.g. link, article, button, list, listitem, combobox. The "img" role is the exception, and authors are prone to mistakenly, but understandably, use role="image", which won't work. 
> 
> Recommend adding role="image" as a synonym for role="img" to avoid author confusion and error.

**Comment by brennanyoung** [comment]
"image" should be the 'preferred' identifier, and "img" should be the synonym

**Comment by cookiecrook** [comment]
https://webkit.org/b/224617

**Comment by cookiecrook** [comment]
Sorry that should have been https://webkit.org/b/224615
