### ISSUE TITLE
Modify the glossary cleanup code to ensure that aliases for terms work the same as a term

### ISSUE THREAD

**Issue by halindrome** [w3c/aria#76]
If a term is defined and not referenced, that term is removed from our specs.  When a term is referenced as an alias, that term might not get preserved correctly.  We need to fix this.

**Comment by jnurthen** [comment]
@halindrome Is this ARIA or should this be somewhere else?

**Comment by jnurthen** [comment]
This issue was moved to w3c/aria-common#17
