### ISSUE TITLE
Add informative note that authors should not rely on rowgroup mappings on all platforms and therefore should not use additional attributes on an element with role rowgroup.

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#760]
from https://www.w3.org/Bugs/Public/show_bug.cgi?id=26046

> Add informative note that authors should not rely on rowgroup mappings on all platforms and therefore should not use additional attributes on an element with role rowgroup.

**Comment by jnurthen** [comment]
This suggests to me that it shouldn't have ANY states or properties allowed on it. Is this the only role which is not mapped on a platform?

**Comment by cookiecrook** [comment]
I don't recall why this was assigned to me, and I'm not sure I understand the context of the note enough to draft it. Removing my assignment for now.

**Comment by jnurthen** [comment]
lets close this - if someone wants to reopen with more details please do so.
