### ISSUE TITLE
Allow role status/alert for noscript?

### ISSUE THREAD

**Issue by Malvoz** [w3c/aria#763]
As javascript may be crucial for some application functionality or to enhance accessibility, I find it sensible to allow the roles [`status`](https://www.w3.org/TR/wai-aria-1.1/#status) and/or [`alert`](https://www.w3.org/TR/wai-aria-1.1/#alert) for [`noscript`](https://www.w3.org/TR/html/semantics-scripting.html#the-noscript-element) elements when in context of `<body>`.

I personally do not deem [`dialog`](https://www.w3.org/TR/wai-aria-1.1/#dialog) and [`alertdialog`](https://www.w3.org/TR/wai-aria-1.1/#alertdialog) viable or necessary, but I may be wrong. Thoughts? 😄

**Comment by jnurthen** [comment]
Please log this against https://github.com/w3c/html-aria
The ARIA spec does not define HTML conformance requirements.
