### ISSUE TITLE
Editorial comments on WAI-ARIA 1.1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#77]
Filed at https://lists.w3.org/Archives/Public/public-pfwg-comments/2015JulSep/0000.html by Momdo Nakamura <xmomdo@gmail.com>

Hello,
I send following comments for WAI-ARIA 1.1 (Working Draft 14 May 2015).

1) section 1
The draft says "WAI-ARIA Authoring Practices [WAI-ARIA-PRACTICES], a planned W3C Working Group Note, ", but [WAI-ARIA-PRACTICES] is now W3C Recommendation.

2) command (abstract role) in section 5.4
The HTML5 spec doesn't define command element.

3) columnheader (role) in section 5.4
> Applying the aria-selected state on a columnheader MUST not cause the user agent to automatically propogate the aria-selected state to all the cells in the corresponding column.
"propogate" is maybe misspelling.

4) contentinfo (role) in section 5.4
In note section, missing closed parenthesis.

5) link (role) in section 5.4
> (such as an HTML anchor with an href value value).
What is "value value" ?  This pattern is found in several places.

6) aria-describedat in section 6.4 
The draft says "longdesc in HTML 4[HTML401]" on characteristics table, but now we know HTML5 Image Description Extension spec is W3C Recommendation.
http://www.w3.org/TR/html-longdesc/

7) aria-label (property) & aria-labelledby (property)
> Related Concepts: A related concept is title in HTML [XHTML11].
While "HTML" link is expected XHTML 1.1 spec, the draft actually links to XHTML1.
I feel that linking to HTML4, XHTML1 and XHTML11 in the draft can be replaced with HTML5.

8) A.2 WAI-ARIA Attributes Module
> This module is available from http://www.w3.org/MarkUp/DTD/aria-attributes-1.mod.
In my view, it is not necessary for DTD to mark up abbr element with URL.

9) B. Mapping WAI-ARIA Value types to languages
HTML 5's column links are too old.

10) F. References
The draft cites " Mathematical Markup Language (MathML) 1.01 Specification", but now the latest MathML spec is 3.0 2nd Edition.

Thanks and regards,
Nakamura, Momdo

**Comment by Joanmarie** [comment]
3 is already fixed: 1b1146ef
4 is already fixed: d588a717
5 is already fixed: f8c62648

**Comment by Joanmarie** [comment]
10 is now fixed: 5bbd15cee

**Comment by Joanmarie** [comment]
6 is now fixed: 61bcd80

**Comment by Joanmarie** [comment]
With respect to item 1:
* http://www.w3.org/TR/wai-aria-practices/ points to a spec which claims to be a working draft; not a rec
* Independent of the above, do we want to point to http://www.w3.org/TR/wai-aria-practices-1.1/ instead?

I am making no changes on this item without further input from the group.

**Comment by michael-n-cooper** [comment]
Yes it should references the 1.1 version of practices. At least for now, our biblio.js has that as [ARIA-PRACTICES].

**Comment by Joanmarie** [comment]
2 is now fixed: c5ba1193

**Comment by Joanmarie** [comment]
7 is now fixed: 341549e

**Comment by Joanmarie** [comment]
Would like group input regarding item 8. Thanks!

**Comment by richschwer** [comment]
Hi Joanie, where I am not seeing a URL in the module. I am confused.

**Comment by michael-n-cooper** [comment]
Appears all points in this comment were previously addressed except item 8. The <abbr> code is inserted by the script (which marks all instances of an abbreviation it finds), and while strange would be hard to fix. It seems non-critical, so closing.
