### ISSUE TITLE
Clarify whether owned-by author rules need explicit role attributes

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/aria#772]
There are sentences in the ARIA spec which state document-conformance requirements for role values that have owned-by relationships with other role values. However, the spec fails to unambiguously state whether or not elements must have explicit role attributes containing those values in order for the requirements to be relevant.

PR #511 provides a proposed fix for that problem.

For the record, I object to ARIA 1.2 transitioning to CR without this problem being resolved.

I would have objected to ARIA 1.1 transitioning to CR and to Rec without this problem being resolved — had the WG ever actually responded in any way at all to PR #511, which I raised in January 2017 (long before ARIA 1.1 transitioned to CR without the WG even mentioning to the Director that the spec had an open unresolved PR which the WG hadn’t responded to).

**Comment by joanmarie** [comment]
Sorry for the frustration or for addressing this during the 1.1 time frame. Your pull request was a meeting topic a number of months ago, and members said they would review it. Then it fell off our collective radar. My apologies. We'll re-raise it.

That said, the Working Group uses milestones to prioritize deliverables. ARIA 1.1 went out the door already. As a result, if you would like your issue addressed for ARIA 1.2, it needs to have the ARIA 1.2 milestone.  I've adjusted that accordingly. The Working Group used to use labels for this purpose. Same thing applies re 1.1/1.2.

And _that_ said, please don't assign milestones and labels. Instead, please prefer bug reports (such as the one you filed here) to communicate how you feel the Working Group should prioritize issues. Then the Working Group can triage and assign the appropriate labels and/or milestones.

Thanks, and again my apologies.

**Comment by michael-n-cooper** [comment]
I apologize for the oversight that led to this situation. It is my role to ensure that, prior to requesting transition, the Working Group has processed open issues on the document version being advanced. I do this, in large part, by looking at the [issues list](https://github.com/w3c/aria/issues). But that list does not show pull requests, and I had not considered that there might be open pull requests that constituted their own issue and which needed to be included in the issues list presented to the Director. I am exploring changes to our procedures to avoid this sort of oversight in future transitions. In the meantime, the Working Group is now actively considering the issue contained in the pull request.

**Comment by mcking65** [comment]
@sideshowbarker,

I've reviewed validator/validator#425 and all changes proposed in #511.

My understanding of the ARIA spec is that it does unambiguously state that an implicit role can meet both ownership and required context role requirements associated with a role. At least, that is how I interpret the second paragraph of section [7.4 Implicit WAI-ARIA Semantics](http://w3c.github.io/aria/#implicit_semantics):

>These host language features can be viewed as having "implicit WAI-ARIA semantics". User agent processing of features with implicit WAI-ARIA semantics would be similar to the processing for the WAI-ARIA feature. The processing might not be identical because of lexical differences between the host language feature and the WAI-ARIA feature, but generally the user agent would expose the same information to the accessibility API. Features with implicit WAI-ARIA semantics satisfy WAI-ARIA structural requirements such as required owned elements, required states and properties, etc. and do not require explicit WAI-ARIA semantics to be provided. On elements with implicit WAI-ARIA roles, authors can also use WAI-ARIA states and properties supported by those roles without requiring explicit indication of the WAI-ARIA role.

Do you have a different perspective on this paragraph? Rather than taking the approach you propose in #511, could you propose a change that would remove any ambiguity from this paragraph?

**Comment by sideshowbarker** [comment]
> Do you have a different perspective on this paragraph?

Yes. My perspective is that it’s not relevant to to what this issue is about.

This issue isn’t about what states/properties are allowed on elements with implicit roles. It’s instead about owned-by author rules, and whether those apply to elements with no explicit role attributes.

> Rather than taking the approach you propose in #511, could you propose a change that would remove any ambiguity from this paragraph?

No, because the approach I propose in #511 is exactly the fix I believe necessary to resolve the problem described in this issue. I have no change to propose to the paragraph cited, because as I said, it’s unrelated to the problem described in this issue.

**Comment by sideshowbarker** [comment]
OK thanks yes in the paragraph cited, I do see the following sentence:

> Features with implicit WAI-ARIA semantics satisfy WAI-ARIA structural requirements such as required owned elements… and do not require explicit WAI-ARIA semantics to be provided

Given that, I think I can change the checker behavior such that cases like the one discussed in https://github.com/validator/validator/issues/425#issuecomment-269841829 will no longer cause the checker to report an error.

That is, if the checker finds an element with `role=gridcell` that’s owned by a `tr` element with no explicit `role` attribute, then the checker won’t report an error (since `tr` has the implicit `row` role).

**Comment by jnurthen** [comment]
@sideshowbarker can we close this issue?

**Comment by sideshowbarker** [comment]
> @sideshowbarker can we close this issue and the corresponding PR?

Yep, now closed

**Comment by sideshowbarker** [comment]
PSA: In https://github.com/validator/validator/commit/15e8584 I committed a fix to the HTML checker for taking implicit roles into account when doing owned-by checking, and I’ve pushed the fix to https://validator.w3.org/nu/
