### ISSUE TITLE
Is aria-controls a required properties for Combobox?

### ISSUE THREAD

**Issue by cpandhi** [w3c/aria#775]
As per the ARIA 1.1 spec it states that the aria-controls a required properties for Combobox but technically the aria-controls a required property on the textbox input element as shown in the example. Can you please clarify?
`<div aria-label="Tag" role="combobox" aria-expanded="true" aria-owns="owned_listbox" aria-haspopup="listbox">
    <input type="text" aria-autocomplete="list" aria-controls="owned_listbox" aria-activedescendant="selected_option">
</div>`

**Comment by carmacleod** [comment]
Hi @cpandhi ! You might want to close this one as a dup of https://github.com/w3c/aria/issues/776

**Comment by cpandhi** [comment]
Dup of #776
