### ISSUE TITLE
Consider treating nameless forms similar to nameless regions

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#778]
In ARIA 1.1, we added the requirement that authors MUST name their regions. Then, in the Core AAM, we added conditional mappings: Expose as a landmark if it has an explicit name; don't expose as a landmark if it lacks a name.

It has been suggested that we do something similar for the form role. See #514). This issue was closed and moved to Core-AAM for the conditional mappings (https://github.com/w3c/core-aam/issues/11). However, we cannot take steps on that Core-AAM issue until we decide what to do in the ARIA spec itself.

**Comment by stevefaulkner** [comment]
note this is how its is defined for [HTML form element](https://w3c.github.io/html-aam/#el-form)
