### ISSUE TITLE
Consider moving normative, NON-mapping content from Core AAM to ARIA

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#779]
(Edited to include more things I've found which I think we should consider moving out of the Core-AAM and adding to the ARIA spec.)

1. [Inclusion](https://w3c.github.io/core-aam/#include_elements) and [Exclusion](https://w3c.github.io/core-aam/#exclude_elements2) from the Accessibility Tree
2. [ID Reference Error Processing](https://w3c.github.io/core-aam/#mapping_additional_relations_error_processing)
3. The bulk of [General rules for identifying the correct ARIA role, not exposing abstract roles, etc.](https://w3c.github.io/core-aam/#roleMappingGeneralRules)
4. The bulk of [General rules for exposing states and properties](https://w3c.github.io/core-aam/#statePropertyMappingGeneralRules)
5. [Supporting keyboard navigation](https://w3c.github.io/core-aam/#keyboard-focus)
6. The bulk of [Author Errors](https://w3c.github.io/core-aam/#document-handling_author-errors)

To be clear: This content is incredibly important. If user agents fail to do what we state in the above sections, ARIA won't work. HOWEVER, nearly every statement in the content above has nothing to do with a given platform accessibility API or its mappings. I believe that such information, when not platform-specific, should be in the ARIA spec rather than the Core AAM: The ARIA spec should state what user agents should expose regardless of platform; the Core AAM should state how user agents should convey the information to be exposed in ATK, IA2, UIA, AXAPI, etc.

**Comment by joanmarie** [comment]
Related aside: I just opened https://github.com/w3c/core-aam/issues/14 to move more stuff out of the Core AAM. In that case, however, the content doesn't belong in the ARIA spec. But if we're going to have a Working Group discussion on what content belongs where, I'd like this issue to also be taken into account.

**Comment by joanmarie** [comment]
Note to self (from discussion during ARIA call): We need to make sure this information is easy to find.

**Comment by joanmarie** [comment]
* Inclusion and Exclusion from the Accessibility tree: https://github.com/w3c/aria/pull/792

**Comment by spectranaut** [comment]
This appears to be done.
