### ISSUE TITLE
Clarify whether alt attribute is valid alternative text for role="img"

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#783]
The [ARIA spec for role="img"](http://w3c.github.io/aria/#img) says:
> In order for elements with a role of img be perceivable, authors MUST provide alternative text or a label determined by the accessible name calculation.

My understanding is that the phrase "alternative text" in the sentence above _does NOT mean_ that authors can go ahead and use the `alt` attribute to specify alternative text for any old type of element with `role="img"`. I would think that the `alt` attribute is only applicable on html elements for which it is supported: `<img>`, `<area>`, and `<input type="image">`.

If my understanding is correct, then a `div` (which does not support `alt`) with `role="img" alt="alt text"` is not following the spec, i.e. there is no guarantee that screen readers will read the `alt` text.

I tried this with both NVDA and JAWS. Here is my [test case](https://carmacleod.github.io/playground/img-role.html), which has 2 divs with role="img", one with `alt` and one with `aria-label`.
- NVDA did NOT read the `alt` text
- JAWS did read the `alt` text
- both read the `aria-label`

I would say that NVDA is following the spec, and JAWS is adding it's own heuristics.

I have seen the phrase "MUST provide alternative text" in the spec equated with "MUST provide an alt attribute" more than once now, so I think it needs to be clarified.

**Comment by jnurthen** [comment]
Can we simply strike alternative text from the definition. It would then read

> In order for elements with a role of img be perceivable, authors MUST provide a label determined by the accessible name calculation.

**Comment by carmacleod** [comment]
Sounds good to me. :)
Thanks!

**Comment by carmacleod** [comment]
Actually, apparently there was a missing "to" that I completely failed to notice...
> In order for elements with a role of img **to** be perceivable, ...

**Comment by carmacleod** [comment]
I can submit a PR, if you're not working on one already...  :)

**Comment by jnurthen** [comment]
A PR would be welcome.

**Comment by carmacleod** [comment]
Wow - I tried to create the PR and apparently I need to have a W3C account now?
I've submitted PRs before - has something changed?

**Comment by jnurthen** [comment]
Thanks... merged.
