### ISSUE TITLE
Please clarify group role

### ISSUE THREAD

**Issue by prlbr** [w3c/aria#786]
The `group` role is defined as:

> A set of user interface objects which **are** not intended to be included in a page summary or table of contents by assistive technologies.

Should it say “**is**” instead of “**are**”? I think that it is supposed to mean that **the set** of objects **is** not intended to be included in a page summary as a whole, but **objects** inside that group **are** able to be included in a summary.

Let’s look at an HTML example:

```html
<div role="group">
  <h1>The Example</h1>
  <p>by prlbr, 26 June 2018</p>
</div>
```

The `<h1>` is intended to be included in a summary or ToC. It’s just that `role="group"` does not cause another entry in the summary or ToC for the `<div>`, or am I mistaken?

Apart from the choice between “are” and “is”, a clarifying sentence would be helpful.

**Comment by jnurthen** [comment]
Looks to be resolved in latest editors draft.
