### ISSUE TITLE
Questions regarding dialog

### ISSUE THREAD

**Issue by kristofferlium** [w3c/aria#794]
Greetings. First time commenting here. Just want to say great work with making the web way more accessible! :smile:

I have some questions regarding dialog according to the ARIA spec and the HTML spec.

According to the HTML spec the `<dialog>` element, whether opened by `showModal()` (modal) or `show()` (non-modal), should receive initial focus and should manage focus.

The WAI-ARIA 1.1 spec on the other hand indicates that `role="dialog" aria-modal="true"` (modal) should receive initial focus and should manage focus, while `role=dialog"` (non-modal) should not.

What are your thoughts on the differences between the HTMLs concept of `<dialog>` and ARIAs `role="dialog"`?
According to the HTML spec the `<dialog>` element default has `role="dialog"` (we do not need to set it) so technically they should be able to work in symbiosis?

**Comment by jnurthen** [comment]
I don't see a conflict between the ARIA and HTML specs here.

The ARIA spec makes the following statement about focus in modal and non-modal dialogs ```Authors SHOULD ensure that all dialogs (both modal and non-modal) have at least one focusable descendant element. Authors SHOULD focus an element in the modal dialog when it is displayed, and authors SHOULD manage focus of modal dialogs.``` it makes no statement about what should happen to the focus when a non-modal dialog is opened deliberately as the desired interaction differs from application to application.

The HTML spec does imply that a dialog (whether opened by show() or showModal() would take focus) but one opened with show() would allow focus to leave the dialog. ARIA supports this same model but has more flexibility in allowing the dialog to open without focusing it in the non-modal case.

If you have more questions please feel free to reopen.
