### ISSUE TITLE
Option role has confusing/contradictory/circular context roles specified

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#809]
The [role definition for option](http://w3c.github.io/aria/#option) states the following:
> A selectable item in a select list.
>
> Authors MUST ensure elements with role option are contained in, or owned by, an element with the role listbox or group. Options not associated with a listbox might not be correctly mapped to an accessibility API.

1. The first sentence says that an option is a selectable item in a `select` list, where `select` can be:
- combobox
- listbox
- menu
- radiogroup
- tree

2. The next sentence says that authors MUST ensure elements with role option are contained in, or owned by, an element with the role `listbox` or `group`, where `listbox` is just `listbox`,  and `group` can be:
- group
- row
- select
- toolbar

3. The third sentence says options not associated with a `listbox` might not be correctly mapped to an accessibility API.

The `group` context role was added for 1.2, but I think the other sentences still need cleanup. It is strange that `listbox` is singled out as being "the" required context role, yet there are other allowed context roles. Additionally confusing is that `select` is a subclass of `group` but both are mentioned.

The following wording is cleaner, although I'm not sure if this corresponds to the actual mappings:
> A selectable item in a `group`.
>
> Authors MUST ensure elements with role `option` are contained in, or owned by, an element with the role `group` or one of its subclasses. Options not associated with a `group` might not be correctly mapped to an accessibility API.

**Comment by carmacleod** [comment]
Also, the **Required Context Role:** for `option` currently contains both:
- group
- listbox

Again, it is strange to single out listbox, when these other concrete roles are also allowed:
- combobox
- menu
- radiogroup
- tree
- row
- toolbar

So I think the Required Context Role: section for `option` should either contain only `group`, or all of the possible concrete roles.

**Comment by jnurthen** [comment]
I think the problem is the first sentence. As far as I know option only applies for listbox. Would changing the first sentence to "A selectable item in a listbox." sort out all the other issues?

**Comment by carmacleod** [comment]
> As far as I know option only applies for listbox.

Oh, interesting. So, why was `group` added as context role?

If it really-truly is only for `listbox` then those sentences need to be:
> A selectable item in a `listbox`.
>
> Authors MUST ensure elements with role option are contained in, or owned by, an element with the role `listbox`. Options not associated with a `listbox` might not be correctly mapped to an accessibility API.

i.e. also need to remove "or group" from sentence 2.

And the Required Context Role: section needs to only contain `listbox` (i.e. delete `group`).

But `group` was recently added, so there must be discussion about that around here somewhere.

**Comment by jnurthen** [comment]
options would be allowed inside a group in a listbox too.

**Comment by carmacleod** [comment]
https://github.com/w3c/aria/issues/719
https://github.com/w3c/aria/pull/782

**Comment by carmacleod** [comment]
> options would be allowed inside a group in a listbox too.

Ah, I see. So how about:
> A selectable item in a `listbox`.
>
> Authors MUST ensure elements with role `option` are contained in, or owned by, an element with role `listbox` or `group` (as long as `group` is contained in a `listbox`). Options not associated with a `listbox` might not be correctly mapped to an accessibility API.

**Comment by kevinSuttle** [comment]
Something I've noticed that I don't see listed anywhere else, which may be adding to this confusion with `listbox` and `option`

`listbox` seems to be the only role which attempts to emulate the `<select multiple>` pattern. 

Could just be me, though.
