### ISSUE TITLE
Allowed structures for spinbutton widgets is ambiguous

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#812]
The [ARIA spinbutton specification](https://www.w3.org/TR/wai-aria-1.1/#spinbutton) says: 

>Authors MAY create a spinbutton with children or owned elements, but MUST limit those elements to a textbox and/or two buttons.

It also says:

>When a spinbutton receives focus, authors SHOULD ensure focus is placed on the textbox element if one is present, and on the spinbutton itself otherwise. Authors SHOULD NOT include contained button elements in the primary navigation ring, e.g., the Tab ring in HTML, because they are superfluous for people using keyboard devices.

The above text is describing a composite structure like:

~~~
<div role="spinbutton">
  <button tabindex="-1">decrease</button>
  <input type="text">
  <button tabindex="-1">Increase</button>
</div>
~~~

Another structure supported by this spec language is:

~~~
<div role="spinbutton" tabindex="0">
  <span>Decrease</span>
  <span>text of value</span>
  <span>Increase</span>
</div>
~~~

However, the most common way of implementing a spinbutton widget that has a textinput has the increment and decrement buttons as siblings like:

~~~
<button tabindex="-1">decrease</button>
<input type="text" role="spinbutton">
<button tabindex="-1">Increase</button>
~~~

The description should more clearly permit building a spinbutton in this way.

This is related to APG issue w3c/aria-practices#826.

**Comment by pkra** [comment]
Fixed by https://github.com/w3c/aria/pull/813
