### ISSUE TITLE
A case perform about focus differently between Chrome + VoiceOver and Safari + VoiceOver

### ISSUE THREAD

**Issue by Jinjiang** [w3c/aria#825]
Here is the code sample:

``` html
<div>
  <button>1</button>
    <div role="row">
      <button>22</button>
    </div>
  <button>3</button>
  <button>4</button>
</div>
```

Firstly it is a bad case because as [mentioned in `role="row"`](https://w3c.github.io/aria/#row) a `row` must be in a `grid|rowgroup|table|treegrid` and own `cell|columnheader|gridcell|rowheader`. But when it goes wrong, I get different effects when I use TAB to focus the second button.

Chrome + VoiceOver:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/206848/47130847-1871b080-d2ce-11e8-878b-b56fd55b298a.png">

Safari + VoiceOver:
![23361539834883_ pic](https://user-images.githubusercontent.com/206848/47130855-21fb1880-d2ce-11e8-8f83-2150fd086de9.jpg)

Does there any browser or aa tool do the wrong thing? Or is it necessary to define the unique performance of the error case like this?

Thanks.

**Comment by jnurthen** [comment]
https://www.w3.org/TR/core-aam-1.1/#document-handling_author-errors states in (3) that 

>User agents are not responsible for logical validation, such as the following: 
>4 Elements that do not correctly observe required child / parent role relationships or that appear elsewhere than in their required parent.

User agents are not required to handle such author errors in a defined way.

Closing this issue.
