### ISSUE TITLE
Remove the string reflection properties that will be replaced by incompatible element reflection properties

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#834]
Some attribute string reflection properties will likely be replaced by TBD and potentially incompatible object reference properties, so in ARIA 1.2, we should remove the string reflection properties for any attributes referencing IDREF or IDREFS based values.

**Comment by cookiecrook** [comment]
Example: String Element.ariaActiveDescendant may be replaced by Element Element.ariaActiveDescendantElement, which could make it difficult to keep string reflection supported and working as authors expect. 

Note: there would be no change to reflection of attributes that take number, token, or string values.

**Comment by cookiecrook** [comment]
Yes, I'm suggesting we remove these _before_ publishing 1.2.

```
	attribute DOMString? ariaActiveDescendant;
	attribute DOMString? ariaControls;
	attribute DOMString? ariaDescribedBy;
	attribute DOMString? ariaDetails;
	attribute DOMString? ariaErrorMessage;
	attribute DOMString? ariaFlowTo;
	attribute DOMString? ariaLabelledBy;
	attribute DOMString? ariaOwns;
```

**Comment by jnurthen** [comment]
1.2 is still quite a way off. But if these will be removed and not consistently supported then removing them seems like a good idea.

**Comment by cookiecrook** [comment]
Note: The prose of the "disambiguation pattern" section references `ariaDescribedBy` so that could be replaced with another came-cased example such as `ariaHasPopup`.

**Comment by cookiecrook** [comment]
No need to wait. We plan to [unship these from WebKit](https://webkit.org/b/197764). I do not believe any other implementor will ship these, because element reflection is the likely path forward.

**Comment by jnurthen** [comment]
@joanmarie Looks like this hasn't been merged into master. I don't believe there is anything left to do here... Should we merge?

**Comment by joanmarie** [comment]
@jnurthen which PR specifically hasn't been merged? Or is another PR needed?

**Comment by jnurthen** [comment]
@joanmarie I was confused.... There is no PR... forget I said anything....

**Comment by cookiecrook** [comment]
Looks like this has been superseded with later edits by Alice and Aaron. I think this issue can be closed. Do you concur @jnurthen?

**Comment by cookiecrook** [comment]
NM. Ignore that. We'll remove them now and add them back in 1.3.
