### ISSUE TITLE
No ARIA property for "default" or "submit" button

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#842]
In HTML, when a `<button type="submit">` or `<input type="submit">` is encountered, it is exposed with STATE_SYSTEM_DEFAULT or ATK_STATE_DEFAULT. As far as I'm aware, there is no ARIA equivalent.

Thoughts:
- I'm not aware of the default state being used or useful outside of buttons. This suggests it could be implemented as a subtype of button, e.g. role="defaultbutton".
- However, for screen readers, it may be more useful to have a relation pointing to the default from the parent window/dialog that it's the default for. If a relation was present, it could be mapped to both a relation if available on the platform, as well as a state.

**Comment by stes-acc** [comment]
Why not simply use aria-roledescription for special button flavors in the meantime instead of inventing a new role AND a relation to the default?

**Comment by jnurthen** [comment]
related issue https://github.com/w3c/aria/issues/559

**Comment by aleventhal** [comment]
@stes-acc I was suggesting either a role or a relation, not both.

The reason we might want it to be semantic is for feature parity in ATs.
For example, in JAWS, press JawsKey+E in a dialog to read the default button

**Comment by aleventhal** [comment]
@asurkov You should be able to safely remove the MSAA relation (accNavigate). I checked the NVDA source and asked JAWS team. Neither uses it.

**Comment by carmacleod** [comment]
@kosl90 
> Return or Enter always trigger the default button, not the focused button.

That's on Mac. On Windows, the advice is that if a non-default button has focus, Enter should trigger the focused button, as stated in [this WinForms article](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/designate-a-wf-button-as-the-accept-button-using-the-designer):
> Whenever the user presses the ENTER key, the default button is clicked regardless of which other control on the form has the focus. The exceptions to this are when the control with focus is another button — in that case, the button with the focus will be clicked — or a multiline text box, or a custom control that traps the ENTER key.

Personally, I think triggering the default button when another button has focus is dangerous. For example, if the default button is "Delete", and the user tabs to the Cancel button and types Enter, then it is obvious that their intent is to Cancel.

**Comment by kosl90** [comment]
@carmacleod thanks you, it helps a lot. I used to think there might be a consistent behavior in different system and I was going to confirm it today.

BTW, I think triggering the default button when another button has focus is confusing, but it is convenient when you get used to it 🤣 . You can use spacebar to trigger focused button, use Enter to trigger default action, so that you can do two things without tab.

It's fine to keep the current behavior 👍 , it's much more intuitive.

**Comment by asurkov** [comment]
> @asurkov You should be able to safely remove the MSAA relation (accNavigate). I checked the NVDA source and asked JAWS team. Neither uses it.

thanks, filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1559995

**Comment by jnurthen** [comment]
closing - please discuss in #559
