### ISSUE TITLE
Editorial: Change "Default value(s)" in "Handling Author Errors" into more corrective phrase

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#843]
Right now we have the phrase "Default value" and "Default values" in/around the table for what user agents need to expose for missing required attributes. We're also trying to disambiguate "required attributes" from "supported attributes with default values." With this in mind, perhaps we should change "Default value" to something more corrective-sounding. Perhaps:

* Fallback value
* Error correction
* (_your suggestion here_)

**Comment by carmacleod** [comment]
+1 for "Fallback value"
