### ISSUE TITLE
ARIA 1.1 Spec has conflict with use of alert role and aria-atomic attribute

### ISSUE THREAD

**Issue by dmargaretosIBM** [w3c/aria#849]
Problem:  The wai-aria (v1.1) description of aria-atomic does not accommodate the this attribute's implicit value when role="alert".

Details:
The role definition for "alert" says that this role has an implicit aria-atomic value of "true" (i.e., for the case where there is no inclusion of aria-atomic for the element with role="alert").  However, when you read the description of aria-atomic, it says that if the attribute is not explicitly set, the value is "false".  These two statement appear to be in conflict.

Relevant Links:
https://www.w3.org/TR/wai-aria-1.1/#alert
https://www.w3.org/TR/wai-aria-1.1/#aria-atomic

**Comment by jnurthen** [comment]
This is allowed per https://w3c.github.io/aria/#implictValueForRole although the text which specifies how to specify the default value is IMO confusing. Merged change above to clarify.
