### ISSUE TITLE
Using the form’s role attribute

### ISSUE THREAD

**Issue by yatil** [w3c/aria#85]
There has been a [twitter conversation](https://twitter.com/rogerjohansson/status/633986303097442304) that started by an Validator warning:

```html
<form role="search">
```

> Warning: Element form does not need a role attribute

Now I know that it violates the [second rule of ARIA use](http://www.w3.org/TR/aria-in-html/#second-rule-of-aria-use):

> Do not change native semantics, unless you really have to.

Yet the specifications do not facilitate that and there seems to be no indication that this behavior is wrong, for example:

* [WAI-ARIA 1.0 says nothing specific about this](http://www.w3.org/TR/wai-aria/roles#search) which makes sense as it is agnostic to HTML, yet mentions that the `form` role is “related” although the “Superclass Role” is `landmark` and not `form`.

* [WAI-ARIA 1.1 (Draft)](http://www.w3.org/TR/wai-aria-1.1/#form) seems to steer people in the direction of using `search` on forms by noting: <q>For search facilities, authors SHOULD use the search role and not the generic form role.</q>

* [HTML5 says forms can have “any roles”](http://www.w3.org/TR/html/forms.html#the-form-element)

* [WCAG technique ARIA11](http://www.w3.org/TR/WCAG20-TECHS/ARIA11.html#ARIA11-ex4) has `<form role="search">` as an example.

Now, a validator warning is not an error, and developers can chose to ignore it. On the other hand having `<form role="search">` seems to feel natural for many people (including me when I first heard about the search role a few years back).

What one could do:

* Make `search` a subclass of `form` (if even possible) and get rid of the validator warning. (That may have implications in the current implementations of AT.
* Outlaw any roles on form (but `presentation`, I suppose) for HTML5.1 and have the validator display an error.
* (… other ideas welcome …)

At least the WCAG technique should be changed to reflect best practices (see w3c/wcag#113)). There is no indication (but it hasn’t been sufficiently tested) that `<form role="search">` breaks AT support, but it feels like this is a glitch in the ARIA matrix that should be clarified.

Related: See @aardrian’s blog post on this issue: [Where to Put Your Search Role](http://adrianroselli.com/2015/08/where-to-put-your-search-role.html)

(Thanks to the input @rogerjohansson, @aardrian, @LjWatson, @stevefaulkner, @cptvitamin and others.)

**Comment by Volker-E** [comment]
I wonder why you're -- after laying out "On the other hand having <form role="search"> seems to feel natural for many people (including me when I first heard about the search role a few years back)" -- choosing to change to *adding an extra DOM element* `<div role="search">` instead of making `search` a subclass of `form`. There's also people out there assuming it ["as specialized version of `form`"](https://accessibility.oit.ncsu.edu/training/aria/landmarks-xhtml.html#search) publicly. 
Adding roles is already hard to get around for some developers (personally fighting for due to missing mapping to semantic elements by older browsers), but adding extra --otherwise superfluous-- DOM element seems illogical at best to many.

**Comment by yatil** [comment]
Hi @Volker-E – Well, that is exactly what we want to find out here. At the moment specs seem to have no clear indication if `role="search"` can be used on a `form` or not. Currently I, personal, would like to avoid the questions by using `<form><div role="search">` as it provides the best of both worlds and doesn’t throw an error in the validator. I agree that it is an additional superfluous element and probably is illogical, but we won’t know until this issue is resolved.

**Comment by yatil** [comment]
Looks like this is resolved by @stevefaulkner here: w3c/html-aria#18.

**Comment by MichielBijl** [comment]
Can this be closed?

**Comment by yatil** [comment]
I think so, feel free to close it.

**Comment by MichielBijl** [comment]
Well if it's fixed… Let's close it up :)
