### ISSUE TITLE
“Todo” notice still in rec document

### ISSUE THREAD

**Issue by yatil** [w3c/aria#863]
In the [Schemata section of ARIA 1.1](https://www.w3.org/TR/wai-aria/#a_schemata), a note is visible with a red background that says:

> WAI-ARIA roles, states, and properties are available in a number of machine-readable formats to support validation of content using WAI-ARIA attributes. WAI-ARIA is not finalized, however, so these files are subject to change without notice. **Todo: Remove disclaimers about not final at rec.**

I suspect the note should have been removed before publication as Rec.

**Note:** The same note is also present in the [Editor’s Draft of ARIA 1.2](https://w3c.github.io/aria/#a_schemata) but without the red background.

<img width="847" alt="screenshotof the above" src="https://user-images.githubusercontent.com/58862/49541166-450b7700-f8d2-11e8-9114-a168e4db2849.png">

**Comment by jnurthen** [comment]
fixed by https://github.com/w3c/aria/issues/977
