### ISSUE TITLE
DPUB: Consider doc- prefix

### ISSUE THREAD

**Issue by mattgarrish** [w3c/aria#87]
It's been noted at times that the current dpub- prefix may not be easily digestable, especially by a broader audience than the initial publishing community that we're targeting, as it may seem too specialized.

One idea for generalizing would be to use the prefix doc- instead, since these are primarily document structures (even if the documents get wrapped up into publications). It also makes for a better mnemonic, as it more clearly reflects the intended usage domain of the attached roles.

**Comment by iherman** [comment]
I like it. +1 from me.

**Comment by JaninaSajka** [comment]
Matt Garrish writes:
> It's been noted at times that the current dpub- prefix may not be easily digestable, especially by a broader audience than the initial publishing community that we're targeting, as it may seem too specialized.
> 
I guess I haven't been privvy to such conversations. I'm skeptical,
though. I believe there's a good degree of professionalism conveyed by
variants of "publishers." I would prefer to hold to the sense of
"quality" the dpub association offers, imo.

> One idea for generalizing would be to use the prefix doc- instead, since these are primarily document structures (even if the documents get wrapped up into publications). It also makes for a better mnemonic, as it more clearly reflects the intended usage domain of the attached roles.
> 

Yes, that's more generalized. But, is that valuable? Won't it be
confused with Microsoft Word? And, how is it distinct from a typical PDF
found on the web, perhaps from your local tax assessor's office?


> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/aria/issues/87

I'm interested to hear what others think.

Janina

-- 

Janina Sajka,	Phone:	+1.443.300.2200
			sip:janina@asterisk.rednote.net
		Email:	janina@rednote.net

Linux Foundation Fellow
Executive Chair, Accessibility Workgroup:	http://a11y.org

The World Wide Web Consortium (W3C), Web Accessibility Initiative (WAI)
Chair,	Protocols & Formats	http://www.w3.org/wai/pf

**Comment by mattgarrish** [comment]
Issue with the prefix was raised when we presented to the dpub group. See the July 13 minutes.[1] We also considered a number of other prefixes before settling on dpub more because it matched the working group name (e.g., pub, publ, and book). A problem with it is it's a prefix that doesn't mean a lot unless you're participating in dpub.

There are also many facets of document publishing beyond industry fields that I'm certainly hoping could benefit from the roles. Added clarity moving content from word processing software formats to accessibility-enhanced OWP-based content seems like a good thing to me. The more we can avoid any sense of exclusion the better.

[1] http://www.w3.org/2015/07/13-dpub-minutes.html

**Comment by iherman** [comment]
@JaninaSajka :

>  I'm skeptical, though. I believe there's a good degree of professionalism conveyed by variants of "publishers." I would prefer to hold to the sense of "quality" the dpub association offers, imo.

I see the point that the reference to publishers conveys professionalism (at least we hope:-). But isn't it enough if this reference and background is clearly marked (as I believe it is) in the document itself? I do not think the *prefix*, per se, inspires that professional feeling.

>  > One idea for generalizing would be to use the prefix doc- instead, since these are primarily document structures (even if the documents get wrapped up into publications). It also makes for a better mnemonic, as it more clearly reflects the intended usage domain of the attached roles.

> Yes, that's more generalized. But, is that valuable? Won't it be confused with Microsoft Word? And, how is it distinct from a typical PDF found on the web, perhaps from your local tax assessor's office?

I think the point is that many of the DPUB ARIA terms can be used for any kind of "document" on the Web that has a certain level of complexity in its structure. A chapter, or a glossary, is not only useful in a book, after all; I could see a real usage in a, say, scholarly journal paper or an online flight manual. Ie, a more general prefix suggests a wider usability of the term, and I actually think that is a good thing.

Whether ``doc`` is the right term or not, is of course a question but, frankly, I do not know any better. I would hope term ``doc`` is not monopolized by Word…  And if, as a side effect, the DPUB-ARIA terms were picked up in a Word file or in a PDF, would that be so bad?

B.t.w., as a side issue, we currently have a [raging discussion on the DPUB IG right now](http://goo.gl/DZffdq) on defining what we mean by a "Web document" in  general as opposed to a simple Web Page. Without going into this discussion, one of the issue the DPUB community is looking at is how to fill the gap that separates today's Digital Publishing (say, EPUB) from the Web. Clearly, whatever a Web Document is, the DPUB-ARIA terms should be used by that, too…

**Comment by richschwer** [comment]
Microsoft Word is pretty much ubiquitous and we have a Microsoft member in the ARIA task force. 

Is there any reason you would not want pub-?

**Comment by iherman** [comment]
"Document" is a fairly ubiquitous term and I do not believe that it is bound to a particular software. Yes, it is used by Microsoft Word but, to take another example, PDF stands for "Portable *Document* Format", too... Ie, I am not convinced that the existence of Word should be an issue here.

"pub" is, in my mind, associated with an active intention of "publishing", ie, with a specific action and institution. "doc" seems to be a more neutral term; as @mattgarrish said, not strongly associated with the publishing community. And, in this case, I think that is a good thing.

**Comment by TzviyaSiegman** [comment]
This has been addressed in draft and -doc prefix will appear next public draft

**Comment by richschwer** [comment]
you meant the doc- prefix. :-)
