### ISSUE TITLE
"Placeholder for compact list of roles" appears under 5.4 Definition of Roles 

### ISSUE THREAD

**Issue by LukeButters** [w3c/aria#871]
Hi

On https://w3c.github.io/aria/#role_definitions
under section `5.4 Definition of Roles`
I have noticed this string appears to be left over:
```
Placeholder for compact list of roles
```
Is that expected?

**Comment by joanmarie** [comment]
It's not expected of course. It appears that there's some script breakage causing the list to not be generated. Thanks for the report!

**Comment by jnurthen** [comment]
Subclass roles also has "Placeholder" for every role.

Looks like respec is failing. The question is - did we break something in our spec or did respec make a change that breaks ours.

**Comment by jnurthen** [comment]
I think this is due to https://github.com/w3c/respec/issues/1846

**Comment by jnurthen** [comment]
Confirmed that adding ```<script src="https://www.w3.org/scripts/jquery/2.2/jquery.min.js" class="remove"></script>``` before all the other scripts resolves the issue

**Comment by jnurthen** [comment]
@michael-n-cooper @halindrome is this the best way to resolve or should we add this centrally in a referenced script?

**Comment by jnurthen** [comment]
This seems to be resolved. Thanks for the report
