### ISSUE TITLE
Need cite role

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#873]
per [plans for role parity](https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#specific-role) need a role for equivalent to [`<cite>`](https://www.w3.org/TR/html52/textlevel-semantics.html#the-cite-element) in HTML

**Comment by pkra** [comment]
Happy to take this on.

**Comment by pkra** [comment]
Thanks, will do!

**Comment by pkra** [comment]
After a bit of research, it seesm the situation around `cite` hasn't moved much in the last few years, despite hopes to the contrary after reducing its scope in HTML5 (from virtually anything in HTML4 to just "creative work").

* the WHATWG and W3C spec still disagree -- WHATWG only wants creative works as content, W3C still seems to allow author's names as well. 
* for practical purposes, schema.org is probably more relevant and uses a very different approach.

I still find the following quote from an old HTML5doctor article fitting:

<q>The dirty secret of all this is the <cite> element has historically been semantics for the sake of semantics. So far, the only non-site-specific application of <cite> is browser default stylesheets, which format it with font-style: italic;.</q>

I have not found evidence to the contrary, so it seems to me that `role=cite` **should map to the generic role** until HTML clarifies its definition.

Some references:

* [W3C spec entry](https://w3c.github.io/html/textlevel-semantics.html#the-cite-element)
* [WHATWG spec](https://html.spec.whatwg.org/#the-cite-element)
* [WHATWG wiki on history](https://wiki.whatwg.org/wiki/Cite_element)
* [2011 article on ### html5doc](http://html5doctor.com/blockquote-q-cite/)
* [2013 article on htmldoctor](http://html5doctor.com/cite-and-blockquote-reloaded/)
* [Jeremy Keith's 2009 24ways article](https://24ways.org/2009/incite-a-riot]
* [schema.org citation](https://schema.org/citation) (which doesn't make a lot of sense on its own but look at examples in [creaiveWork](https://schema.org/CreativeWork) or [scholarlyArticle](https://schema.org/ScholarlyArticle))

**Comment by joanmarie** [comment]
@pkra will you be around to present your findings at next week's (28 Feb) meeting? If so, could you please add the 'agenda' label to this issue so that it winds up on that agenda? Thanks!

**Comment by pkra** [comment]
Yes, I'll be there. 

I've added the label "Agenda".

**Comment by pkra** [comment]
unassigning myself since the WG agreed that cite will be generic.

**Comment by scottaohara** [comment]
as it was decided that the `cite` element will map to the generic role, there's no work left to do here.  closing.
