### ISSUE TITLE
Clarification does the widget role of tree support name from content

### ISSUE THREAD

**Issue by cpandhi** [w3c/aria#889]
As per the latest editors draft [https://w3c.github.io/aria/#tree](url) tree role supports name from author only. But if you look at Roles supporting name from content list [https://w3c.github.io/aria/#namefromcontent](url) it does include the tree role. Which one is correct?

**Comment by carmacleod** [comment]
Good catch @cpandhi.
Tree role supports name from author only.
@jnurthen's PR removes tree from the name from content list.

**Comment by jnurthen** [comment]
Thanks for the issue. I've merged the change and it should be resolved in the current editor's draft.
