### ISSUE TITLE
dfnTitle() is undefined

### ISSUE THREAD

**Issue by klown** [w3c/aria#90]
@halindrome,

The restrictReferences() function contains two calls to dfn.Title():
https://github.com/w3c/aria/blob/master/common/script/resolveReferences.js#L94
https://github.com/w3c/aria/blob/master/common/script/resolveReferences.js#L117

This results in an error: "call to restrictReferences() failed with TypeError: $t.dfnTitle is not a function".

Where is it defined?

**Comment by halindrome** [comment]
It is defined in respec's core/util.js module.  But it's name changed to getDfnTitles.  And it returns an array of matching titles.  I will undertake to make this work.  Actually, I thought I already had and put in a PR but I guess not.

**Comment by klown** [comment]
That worked.  Thanks for the fix, @halindrome.
