### ISSUE TITLE
Change references from W3C to WHATWG version of HTML spec

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#900]
In response to https://twitter.com/stevefaulkner/status/1095728948443521024 we should probably change our HTML references

**Comment by carmacleod** [comment]
What happened??

**Comment by jnurthen** [comment]
Needs discussion before implementing.

**Comment by carmacleod** [comment]
See this email thread: http://lists.w3.org/Archives/Public/spec-prod/2019AprJun/0003.html
Apparently, just using [HTML] and [DOM] (and _not_ [HTML5] or [HTML51] etc) will make the Respec/Specref magic happen. That should be all we need to do.
