### ISSUE TITLE
Add additional details regarding the new caption role

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#901]
Now that I'm implementing some related support for our new `caption` role in a user agent, I noticed some things we (I) potentially neglected to address in the initial commit:

* There is currently not a "Required Context Role" for `caption`. I don't think we want `caption` instances floating around in unexpected places in the accessibility tree. I think we should add `table` and `figure` as the required context roles.
* HTML states that the `caption` element should appear as the first element. I don't know if we want to do that or not. But even if we address the first point, we don't know where the caption will appear in the accessibility tree (other than it will descend from a `table` or `figure`.

**Comment by joanmarie** [comment]
Setting the milestone to ARIA 1.2 because the `caption` role was added to 1.2 and is being implemented now.

**Comment by carmacleod** [comment]
- Agree with adding Required Context Role: table, figure
- `figcaption` doesn't need to be first element, so we shouldn't restrict where `caption` role should go in table/figure ancestor.

**Comment by joanmarie** [comment]
> * `figcaption` doesn't need to be first element, so we shouldn't restrict where `caption` role should go in table/figure ancestor.

Unless we want to do it just for table. (I'm not saying we do, mind you. Just that HTML does restrict where it should be.)

**Comment by scottaohara** [comment]
having done a review of #1020 (failing to notice its issue 1019 had been bumped to 1.3), it seems there are portions of that PR that could be used to address this issue.
