### ISSUE TITLE
Consider new abstract role "phrase"

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#908]
Consider an abstract role for the ontology which would be used for roles equivalent to HTML phrasing elements. Section doesn't seem correct as a parent role for many of these and there doesn't seem to be any other place to put them... Example would be the new subcript/superscript roles

**Comment by pkra** [comment]
I'm wondering if this could also help with the following problem. If a paragraph contains an inline graphic which represents text (e.g., an icon font, a non-Unicode character/word), then screenreaders will (usually?) interrupt their voicing after the image description is done. I'm not aware of a method to get AT to consider a description to be part of a text flow. Could a role derived from phrase help?

**Comment by aleventhal** [comment]
Wondering if we can think of some alternative names to consider? A phrase
sounds like part of a sentence to me. Although, I just learned that
phrasing element is a thing in HTML. Not sure how many authors will know
that.

Just as an alternative idea, how about "span".

Overall I'm fine if we go with "phrase", just wanted to throw it out there.

Aaron

**Comment by mcking65** [comment]
Also consider using as superclass of insertion and deletion added for issue #526.

**Comment by brennanyoung** [comment]
This seems very similar to the intentions behind role=text (which already has support from many ATs).

Disregarding the (un)suitability of the nomenclature, how is the mooted role=phrase different from the almost-already-implemented role=text?

**Comment by jnurthen** [comment]
take a look to see if this would help to decide whether to close or do in 1.3

**Comment by cookiecrook** [comment]
role=text would be a concrete role, usable by authors. role="phrase_bikeshed" would be an abstract role, not usable by authors, but could be used with inheritance in the role ontology.

**Comment by cookiecrook** [comment]
@aleventhal I think "span" isn't a good choice for an abstract role, as authors will assume they can use it for generic elements

**Comment by jnurthen** [comment]
How about actually using the html term. Either "phrasing" or "phrasingcontent" - the more abstract it is the less likely folks are going to use it accidentally.

**Comment by jnurthen** [comment]
Working group agreed in https://www.w3.org/2022/10/06-aria-minutes#a02 that this has little benefit and closing as wontfix
