### ISSUE TITLE
nested role=tree

### ISSUE THREAD

**Issue by pkra** [w3c/aria#910]
Currently, https://w3c.github.io/aria/#tree lists `group→treeitem` and `treeitem` under Required Owned Elements.

When building tree components that can nest, it is cumbersome that either the parent component needs to add a wrapper with treeitem or the child component needs to check if an ancestor has a role of tree (to decided if role tree or group is needed).

I'm guessing there is a reason why role=group is in the spec instead but I'm wondering if the evolution of the tree role might take another step towards simplifying things for authors.

**Comment by cookiecrook** [comment]
> or the child component needs to check if an ancestor has a role of tree

I don't understand this comment. Could you elaborate? Why would the component need to check its ancestor? I'm assuming the JavaScript would just construct it correctly and not need to do structure checks. Only a validator or a user agent would need to do the checking as I understand it.

**Comment by pkra** [comment]
As I said on the call, I don't completely recall what led me to file this back then.

I think I was primarily misunderstanding Required Owned Elements, but that might be a biased look given recent discussions around that topic.

> > or the child component needs to check if an ancestor has a role of tree
> 
> I don't understand this comment. Could you elaborate? 

I believe I was thinking about nesting web components that have role=tree. I think I was wondering if I'd have to change the role of such web component to group if it ends up a subtree. 

Again, that's a reconstruction. As such, I'll close this from my end - if someone feels like re-opening, I'd suggest a new thread might reduce confusion in the long run.
