### ISSUE TITLE
Aria role for step widget

### ISSUE THREAD

**Issue by flyinhigh** [w3c/aria#917]
I have a case like this

![](https://img.alicdn.com/tfs/TB14YylM4TpK1RjSZFKXXa2wXXa-856-748.png)

this widget  is used to guide user to finish something step by step.

when I use role="progressbar" for it, the VoiceOver will announce the widget as a progress bar with the percentage value other than defined value (for example "66.7%" instead of "2 out of 3").

I set the aria-current="step", but it does'nt work

so, what I can do for this case.

**Comment by jnurthen** [comment]
I've always just used an ordered list for these. Do they need to be more complicated?

**Comment by flyinhigh** [comment]
> I've always just used an ordered list for these. Do they need to be more complicated?

ol is great, thank u , but I need to tell the current step, should  I use aira-current="step" or aria-selected="true" with ol ?

**Comment by youluna** [comment]
I have the same question.
![image](https://user-images.githubusercontent.com/10049465/54667638-cad0cc80-4b27-11e9-8ea0-e3aaea53fa74.png)
I tried this, but VoiceOver  just read the order but did't tell me what's the current step is.
 Is there anything wrong with my usage?

**Comment by jnurthen** [comment]
see support note at https://labs.levelaccess.com/index.php/Aria-current_attribute

**Comment by jnurthen** [comment]
I'm going to close this as there doesn't seem to be anything to do in the aria spec.
