### ISSUE TITLE
aside vs role=note

### ISSUE THREAD

**Issue by pkra** [w3c/aria#918]
This likely belongs elswhere but allow me to start here.

HTML (both W3C and WHATWG) have the following note:

>  It’s not appropriate to use the aside element just for parentheticals, since those are part of the main flow of the document. 

At the same time, role=note is allowed and reads

> A section whose content is parenthetic or ancillary to the main content of the resource.

At the same time, roles similar to note (e.g., doc-dedication - which led me down this rabbit hole) are not allowed on an aside element.

I find this a bit confusing and I'm wondering if I'm missing a difference here.

**Comment by scottaohara** [comment]
Hi @pkra 

The HTML `aside` element maps to `role=complementary` not `role=note`, so I'm unclear of what the issue is here?

**Comment by pkra** [comment]
Thanks @scottaohara, I'd forgotten about this and I can now see that my past self was clearly confused.

Now that I know a bit more of which issues belong where, I think I'll open an issue on aria-in-html. The question is not about role=note vs role=complementary but about aria-in-html not permitting doc-dedication on an aside.
