### ISSUE TITLE
Consider parity with HTML's OL "type" attribute

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#925]
(This is a spin-off issue from issue #667)

@minorninth said in the opening report:

> Similarly, for ARIA lists, there should be a way to indicate the text of an ARIA list marker, for example a list that uses a, b, c instead of 1, 2, 3.

This strikes me as being quite similar to the `type` attribute associated with HTML's `ol` element. ARIA has plans to tackle attribute parity during the 1.3 cycle.

**Comment by scottaohara** [comment]
related to #961 `aria-listtype`

**Comment by scottaohara** [comment]
on the call today we decided this was a duplicate of #961
