### ISSUE TITLE
[Role Parity] What do we do about input (type=color)?

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#930]

**Comment by carmacleod** [comment]
role="color" or role="colorinput"?

We already have "time" role for `<time>` element,
so do we go with "timeinput" role for `<input type="time">`?
If so, then "colorinput" would be consistent with "timeinput", but more verbose than "color"...

Both Chrome and FF on Win7 render `<input type="color">` as a "color well button that pops up a color picker dialog".
So if someone was implementing this today, they might use a [read-only combobox](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Comboboxes/ARIA%20Comboboxes%20(Simulated,%20Readonly)/demo.htm) with aria-haspopup="dialog".

So I think "color/colorinput" should support aria-haspopup (with all of its tokens).

I don't know if any platforms still implement this as a textbox that only takes hex color values, but presumably someone might want to do that. So they might use a combobox with aria-autocomplete. This would likely be similar to using the list="datalist-id" attribute.

So  I think "color/colorinput" should support aria-autocomplete (with all of its tokens).

I don't know how useful the HTML autocomplete attribute is with input type="color", but it is supported. Perhaps one could create colors using autocomplete="postal-code"... :smile:

In case it's helpful, here's a [basic HTML element test page](https://www.html5accessibility.com/html5elements/) for trying out the various inputs (and other elements).

**Comment by carmacleod** [comment]
Regarding naming:
> role="color" or role="colorinput"?
> We already have "time" role for `<time>` element,
> so do we go with "timeinput" role for `<input type="time">`?
> If so, then "colorinput" would be consistent with "timeinput", but more verbose than "color"...

Since we have always had "checkbox", "radio", and "button", I think it makes more sense to go with role="color".

The time element is very different from input type="time", so we do need to resolve that conflict (in https://github.com/w3c/aria/issues/936), but there's no conflict for "color".

(perhaps input type="time" can be role="timebox" for consistency with role="textbox" for input type="text")
:smile:

**Comment by carmacleod** [comment]
See also the discussion starting at [comment 8 in Firefox bug 559767](https://bugzilla.mozilla.org/show_bug.cgi?id=559767#c8) about platform mapping of color input (button, dialog).

**Comment by jnurthen** [comment]
As detailed at https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#no-consensus-yet-will-do-for-1-3 moving to 1.3

**Comment by jnurthen** [comment]
Honestly - I don't see any way this is going to happen until HTML color inputs are more standard. Propose closing this as a wontfix.
