### ISSUE TITLE
[Role Parity] What do we do about object?

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#938]

**Comment by jnurthen** [comment]
As detailed at https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#no-consensus-yet-will-do-for-1-3 moving to 1.3

**Comment by joanmarie** [comment]
Tentative consensus: New embeddedobject role. Largely a generic herebedragons container to preserve exposure via platform accessibility APIs.

**Comment by scottaohara** [comment]
per today's conversation, closing this as a dupe of #929
