### ISSUE TITLE
Proposal to surface the availability of virtualized content

### ISSUE THREAD

**Issue by melanierichards** [w3c/aria#958]
On MS Edge we've been thinking about ways we can better surface the availability of virtualized content to ATs, etc. That is, content that is not yet rendered on the page, but is relevant to the user and may not be triggered by their current navigational method (for example, scroll-initiated content relevant to a user who is currently navigating a page by headings).

We've put together [this Aria Virtual Content explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Accessibility/VirtualContent/explainer.md) to describe the goals a little more in detail (avoiding fingerprinting while keeping authoring overhead low is a key part of this), as well as a proposed solution for an `aria-virtualcontent` property. Would love to discuss this initial proposal with the ARIA WG!

**Comment by jnurthen** [comment]
minuted at https://www.w3.org/2019/04/30-aria-minutes.html#item02
