### ISSUE TITLE
aria-valuenow implicit value is always 50 for separator

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria#959]
https://w3c.github.io/aria/#separator

> The implicit value of aria-valuenow is 50.

Should this be half-way between valuemin and valuemax (like for `slider`)? In particular, if the author sets valuemax to 10 and doesn't specify valuenow, the valuenow will be outside the range.

cc @mcking65

**Comment by zcorpan** [comment]
It's possible that this is addressed by https://github.com/w3c/aria/pull/945

cc @melanierichards

**Comment by melanierichards** [comment]
I think the question would still apply, even though we removed the implicit value from role prose. The fallback table in [Section 9.2 on handling author errors](https://rawgit.com/w3c/aria/master/#document-handling_author-errors_states-properties) doesn't specify for `aria-valuenow` on the `separator` role.

**Comment by zcorpan** [comment]
cc @spectranaut

**Comment by jnurthen** [comment]
Looks like this is addressed
