### ISSUE TITLE
Consider creation of aria-textattribute property for role parity with generic

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#960]
We have quite a few [generic-role candidates](https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#generic-role) related to formatting that is relevant to the user -- not sufficiently relevant to justify a dedicated role, but still something we may wish to preserve and expose to users through their assistive technologies. In order to expose this formatting, we could have an attribute such as `aria-textattribute` (namesmithing welcome :smile: ).

My current thought is that `aria-textattribute` would have the value of `token`. It would only be supported on the to-be-created "generic" role. And it would contain one of the following values:
 * `abbreviation`
 * `address`
 * `bold`
 * `italic`
 * `keyboard`
 * `mark`
 * `preformatted`
 * `quote`
 * `strikethrough`
 * `sample`
 * `small`
 * `underline`
 * `variable`

Thoughts?

**Comment by carmacleod** [comment]
I think it needs to be a space-separated token list, because it is possible to have "bold italic underline", etc.

**Comment by joanmarie** [comment]
So given `<b><i><u>foo</u></i></b>`, we'd just have one generic element?

**Comment by jnurthen** [comment]
> So given `<b><i><u>foo</u></i></b>`, we'd just have one generic element?

Wouldn't that be better?

**Comment by joanmarie** [comment]
Not sure. I'm just asking. :)

**Comment by joanmarie** [comment]
Straw poll 1 of 2: We want an attribute.

**Comment by carmacleod** [comment]
See also @aleventhal's: https://github.com/w3c/aria/issues/651

**Comment by joanmarie** [comment]
Straw poll 2: We want to make it a space-separated token list.

**Comment by brennanyoung** [comment]
Why are `<strong>` and `<em>` missing from the list above? These are true semantic inline tags.

These were introduced as semantic alternatives to overly presentational `<b>` and `<i>` (originally "bold" and "italic"). These elements only survive in HTML5 because some sophist decided that `<b>` is short for "**b**ring to attention" and `<i>` is short for "**i**diomatic". (I don't buy it either).

I'd rather see parity for `<strong>` and `<em>` than `<b>` and `<i>`!

**Comment by jnurthen** [comment]
@brennanyoung ARIA 1.2 already includes the following roles
`strong` , `emphasis`, 'insertion`, `deletion` and `blockquote`
`mark` is already in the editors draft for 1.3 to support the annotations work.

**Comment by jnurthen** [comment]
Are we still considering this or should we close?

**Comment by scottaohara** [comment]
i was under the impression this wasn't really needed anymore with the way that generic has panned out in implementations.
