### ISSUE TITLE
Consider creation of aria-sectiontype property for role parity

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#963]
(Disclaimer: I don't like the name `aria-sectiontype` nor am I sure we even need to solve this problem. But in the spirit of thoroughness....)

`header` and `footer` (when they are NOT scoped to the `body` element) are amongst the elements we're applying our to-be-created "generic" role to. In addition, `thead` and `tfoot` have at least partial parity via the ARIA `rowgroup` role. Question is: Do we need to add an ARIA property to achieve full role-parity?

Assuming we do, and assuming we need to for *all* of the aforementioned elements, then I propose `aria-sectiontype` (propertysmithing encouraged :smile:). The value would be of type `token` and the value could be either:

* `header`
* `footer`

Thoughts?

**Comment by joanmarie** [comment]
Another sectiony type element which is getting the "generic" treatment is `form` (without an accessible name). If we want complete parity for it, I suppose we could add a third token value, namely: `form`.

**Comment by carmacleod** [comment]
Just a small reminder that this is only for `header` and `footer` when they are NOT scoped to the `body` element. We already have role parity for body-level header (role=banner) and body-level footer (role=contentinfo).

**Comment by joanmarie** [comment]
Consensus: We shall not do this.
