### ISSUE TITLE
tabpanel - accessible name required conflicts with prose

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#965]
States

> Authors SHOULD associate a tabpanel element with its tab, either by using the aria-controls attribute on the tab to reference the tab panel, or by using the aria-labelledby attribute on the tab panel to reference the tab.

but Accessible Name is required. This conflicts

**Comment by carmacleod** [comment]
Should the prose simply remove any mention of aria-controls? i.e.:
> Authors SHOULD associate a tabpanel element with its tab using the aria-labelledby attribute.

**Comment by jnurthen** [comment]
Actually thinking about this again I don't think this does conflict. 

I guess someone can label the tabpanel with aria-label and then use aria-controls on the tab to create the relationship with the tabpanel.

I'm going to close this. If someone wants to create an issue to do something about aria-controls and require aria-labelledby they can do so but the original premise of this issue is not true.
