### ISSUE TITLE
propose an text based aria-description based on aria-label

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#992]
There is a way to populate the accessible name with text offscreen using ```aria-label```. How about a corresponding text based attribute that maps to the ```accessible description```?

```aria-description``` OR ```aria-textdescription```

It would allow developers to add helpful notes for screen readers and would help in the following ways:

-   overcomes the burden of creating ids and ensuring the id is not a duplicate, and placing the text somewhere else besides on the element,
-  overcomes double speak which happens when a screen reader user arrows over a node that is referenced with ```aria-describedby``` before encountering the control that references it, where they hear it again.
- will avoid the confusing use of ```display:none``` on an node referenced by ```aria-describedby``` to overcome the issue in the bullet above.
- overcome  accidentally overriding the ```Accessible Name``` when devs mistakenly add an ```aria-label``` when they want to add some helpful hints. This is a common problem, which might be minimized with the addition of this attribute.

**Comment by carmacleod** [comment]
Dup of https://github.com/w3c/aria/issues/891 ?

**Comment by DavidMacDonald** [comment]
Yup, perhaps it could be revisited. It seems to just make sense. @stevefaulkner proposed this, previously.

**Comment by jnurthen** [comment]
Agree - this is a duplicate

**Comment by DavidMacDonald** [comment]
Let's continue the discussion over on  #891
