### ISSUE TITLE
Gridcell has accessible name required

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#993]
If they are empty they don't (and probably shouldn't) have an accessible name.

**Comment by schne324** [comment]
Question from call on 06/13/19:
> Do validators raise violations for each role which has `Accessible Name Required: True` for an element with said role with no accessible name?

Digging into axe-core, it looks like it isn't black and white. For this example, `role=gridcell`, axe will not raise a violation for one with no name (an empty cell).  But it will (obviously) raise a violation given a `role=button` element with no accessible name.

Axe's approach follows wcag so it will enforce `Accessible Name Required` on all *widget* roles for example.

I can dig into other validators if need be 😄 just let me know!
